### ISSUE TITLE
All content of a @Id mapped element are removed from the DOM

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10106]
### Description of the bug / feature
If you have a template / component that modifies its child elements dynamically, you cannot use it with a `LitTemplate` as Flow will remove all the created children.

### Minimal reproducible example

```java
@JsModule("./views/empty/empty-view.ts")
@Tag("empty-view")
public class EmptyView extends LitTemplate {

    @Id
    private Div root;
}
```

```ts
import { customElement, html, LitElement, PropertyValues, query } from "lit-element";

@customElement("empty-view")
export class EmptyView extends LitElement {
  @query("#root")
  private root!: HTMLElement;

  createRenderRoot() {
    // Do not use a shadow root
    return this;
  }
  render() {
    return html`<div id="root"></div>`;
  }

  protected firstUpdated(_changedProperties: PropertyValues) {
    super.firstUpdated(_changedProperties);
    this.root.innerText = "Hello";
  }
}
```

### Expected behavior
You see "Hello" in the view

### Actual behavior
The view is empty. If you remove the `@Id` mapping, then you see "Hello"

### Versions:
    - Vaadin / Flow version: 18

**Comment by Artur-** [comment]
Example at https://github.com/Artur-/test-flow-removes-content

**Comment by Artur-** [comment]
Seems to originate in `IdCollector.collectElementData` / `IdCollector.setText` which for some reason thinks that it should set the inner text for the element when the element has no inner text

**Comment by Artur-** [comment]
So the workaround is to render an extra element just to keep Flow from destroying the DOM
```
  render() {
    return html`<div id="root"><span></span></div>`;
  }
```

**Comment by Artur-** [comment]
Not sure if the problem is
1. Flow does not only set the text on the server but communicates it to the client (overhead for all Id mapped components and also breaks things)
2. Flow thinks that there is a text node when there is none

**Comment by knoobie** [comment]
@mshabarov this looks kinda similar to the issue you are currently investigating https://github.com/vaadin/flow/issues/10086

**Comment by mshabarov** [comment]
This behaviour may be caused by the known limitations described in the feature ticket https://github.com/vaadin/flow/issues/8975.

**Comment by Artur-** [comment]
Which limitations are you referring to? I only see the issue mentioning that the user should be able to replace the text. Not that the server should automatically destroy any contents of the element

**Comment by mshabarov** [comment]
Ok, I messed up the things.
8975 says that setting the component's text on java side would replace any children it has, and how to workaround it.
So I'd mark this ticket as a bug with major severity, because it has a workaround. Otherwise, it would be treated as a blocker.

**Comment by denis-anisimov** [comment]
This is not a bug.
The expectation in the description contradicts the feature which sets the values in the Java template instance based on the attributes/text values in the parsed template.
More explanation is here:
https://github.com/vaadin/flow/pull/10112#pullrequestreview-596269719

**Comment by Artur-** [comment]
If you change the version in the linked project to 17.0.11, you can see that this is actually a regression. Web components that use their light DOM work fine in templates with 17.0.11 but not in 18.0.6

**Comment by denis-anisimov** [comment]
What kind of the argument it is ?

`17` has no https://github.com/vaadin/flow/issues/3735 implementation 
`18` has https://github.com/vaadin/flow/issues/3735 implemented.

This and only this is the cause if the behavior.

I can say that `18` has a regression comparing to `17`  because it works in a different way (because https://github.com/vaadin/flow/issues/3735 is implemented).

It's not a regression, it's a consequence if the requested "feature".
I repeat it in 100th time : let's revert the feature in the https://github.com/vaadin/flow/issues/3735. I will be happy to do that.

**Comment by Legioth** [comment]
I "requested" the "feature" descried in #3735. I'm quite sure it says nowhere in that ticket that use of 3rd party components should be broken.

**Comment by denis-anisimov** [comment]
I gave up.
Useless discussion.

**Comment by Artur-** [comment]
Yes, so #3735 is implemented and has a bug, causing this regression that you cannot use all web components. 

#3735 is about making the initial values available on the server side. At least I see nothing in #3735 saying that the text values should be sent from the server to the client, this is just how it has been implemented and likely this case has not been considered then.

**Comment by Legioth** [comment]
I suspect that what's needed for fixing this regression is to remove some specific entries from `com.vaadin.flow.internal.StateNode.changes` so that they won't be sent as changes to the client. Alternatively, there might be some way of making those changes without having them registered in the `changes` field.

The suggested PR that just ignores a specific case seems quite risky and would only treat the most common case as a special case rather than fixing the full problem.

**Comment by denis-anisimov** [comment]
`setText` to an empty value cases issues with templates which don't use shadow root since it's called 
for the element after it gets the direct DOM structure: https://github.com/vaadin/flow/issues/10821

It doesn't happen for templates with shadow root since `setText`  doesn't destroy the shadow root.

**Comment by pleku** [comment]
>I suggest to remove functionality which reads the text for the template: it works only in corner case anyway (if element has no children).

Ok, lets do this. I think there used to be a note about this behavior in the designer docs as a known limitation, and now it should probably be added back there.

**Comment by Artur-** [comment]
That means `<vaadin-button>OK</vaadin-button>` will lead to `mappedButton.getText().equals("")`? Is there any other case where the text is really relevant?

**Comment by Artur-** [comment]
What I am thinking is can the text support be opt-in for given components?

**Comment by denis-anisimov** [comment]
At the moment <vaadin-button>OK<div/></vaadin-button> leads to mappedButton.getText().equals("").
So the absence of children is quite specific case anyway.
Also text node is hierarchical structure which never works with `@Id` mapped components.

If there is a necessity to make text work with `@Id`  mapped components this should be considered as a separate (serious) feature separately.
For now setting text for the template obviously leads to unexpected behavior which should be reverted.
Implementing text feature quickly leads to regressions because of quite unexpected behavior with `@Id`  mapped component overall: we have a bunch of such issues because of unclear contract.

**Comment by Legioth** [comment]
> If there is a necessity to make text work with @Id mapped components this should be considered as a separate (serious) feature separately.

Sounds like this (serious) ticket https://github.com/vaadin/flow/issues/8975 that we already have.

**Comment by pleku** [comment]
> Sounds like this (serious) ticket #8975 that we already have.

It is now reopened and to be continued there
