### ISSUE TITLE
When opening an application based on Hummingbird I want a subtle but noticeable notification telling me that the application is not in production mode so that I can take needed steps before going into production

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#1029]

**Comment by pleku** [comment]
No

**Comment by Legioth** [comment]
> No

Why

**Comment by web-padawan** [comment]
BTW https://github.com/TryGhost/Casper/issues/286#issuecomment-281907266 🙂

**Comment by pleku** [comment]
>>No

>Why

Deemed not important enough to be considered for now based on: no requests nor feedback about this. Probably not going to do it ever since there are always other things that are more important. Also not sure if this brings more value than potential harm, as I can see how this could be come annoying if it requires some interaction to discard the notification when you _know_ that you're running in development mode. So it would require some logic for being able to discard which will soon lead into complexity.

I think issues that probably should not and are not going to be done should be closed, but yes a good explanation should be given too.
