### ISSUE TITLE
change the default Endpoint access to "deny all"

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#10328]
When adding a Fusion `@Endpoint` to a Vaadin app, as a developer I want the default access level to the new endpoint to be 'deny all' so that the applicaiton is secure by default and I do not accidentially expose access to the backend to unintended users. In order to enable access I want to explicitly use one of the [access control annotations](https://vaadin.com/docs-beta/latest/fusion/security/configuring/#other-security-options): `@RolesAllowed` to allow access to selected roles, `@PermitAll` to allow access to any logged-in (non-anonymous) users, or `@AnonymousAllowed` to allow unrestricted access to _everyone_. As in Vaadin 15-19 I want to set these annotations either on an entire endpoint class or on individual public methods of that class.

**NOTE: this is a breaking change. In Vaadin 15-19 the default endpoint access is "any logged-in (non-anonymous) user"**

**Comment by haijian-vaadin** [comment]
Currently, the logic is that the authenticated requests are permitted unless it's [forbidden](https://github.com/vaadin/flow/blob/master/fusion-endpoint/src/main/java/com/vaadin/flow/server/connect/auth/VaadinConnectAccessChecker.java#L177) otherwise:
- Has an explicitly `@DenyAll`
- Has `@RolesAllowed` and the user role in the request is not allowed
- No `@RolesAllowed` and No `@AnonymousAllowed`

It needs to change to deny all by default unless it's allowed. entityFormbidden -> entityAllowed?
- No `@DenyAll`
and
  -  Has `@RolesAllowed` and the user role in the request is allowed
  -  or 
  -  Has `@PermitAll` 
  -  or
  -  Has `@AnonymousAllowed`
