### ISSUE TITLE
[maven plugin] Cleanup generated client files

### ISSUE THREAD

**Issue by stbischof** [vaadin/flow#10320]
### Description of the bug / feature
maven plugin generates a lot of files into the root of the project. this pollutes the project

### Minimal reproducible example
https://github.com/vaadin/base-starter-flow-osgi/tree/v19/starter
- webpack.generated.js
- webpack.config.js
- types.d.ts
- tsconfig.json
- pnpmfile.js
- pnpm-lock.yaml
- package.json
- .npmrc

### Expected behavior
put these files into a temporary folder. let mvn clean remove these files

### Actual behavior
files exist in root folder ans woill not be removed on clean

### Versions:
    - Vaadin / Flow version: 19++
    - Java version: 8++
    - OS version: every

**Comment by Legioth** [comment]
All those files are there for a reason. It is unfortunate that the root of the project is polluted, but it's not practical to get rid of the files without causing lots of complexity in other cases instead.

Most of the files are furthermore intended to be "owned" by the application project. They are simply initialized with sensible default values if they don't exist but after that the application developer is free to make their own changes. For that reason, it's also recommend to include the files in version control so that everyone developing the application will have consistent configuration.

**Comment by stbischof** [comment]
Good to know,
It's hard to find out why which file is there because of what reasons.
And i am still convinced, that they truly should schuld not be ungrouped in the root folder.

**Comment by pleku** [comment]
Like said, these files should not be cleaned as they serve a purpose. It might be another thing to be able to configure where those files are created and used from - but that would be another ticker.

There is a similar issue for cleaning frontend build related files that are automatically regenerated: https://github.com/vaadin/flow/issues/8885 but I'm closing this one.
