### ISSUE TITLE
TerminalErrorHandler triggered when Upload is cancelled

### ISSUE THREAD

**Issue by Springrbua** [vaadin/flow#10351]
### Description of the bug / feature
In a web application I am currently working on, I am using a terminalErrorHandler (`VaadinSession#setErrorHandler`).
I am also using the `Upload` component as well as a custom upload component based on it.
Now when I cancel the upload on the client side `StreamVaribale#streamingFailed` and the terminalErrorHandler get triggered.
In my opinion, the terminalErrorHandler should not be triggered in this case, as a failed upload is somehow expected and already handled by `StreamVariable#streamingFailed`.

While trying to find the cause, I have seen the the  `StreamReceiverHandler` handles an `UploadInterruptedException` ([here](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java#L524-L536))  and this exception is not propagated to the terminalErrorHandler. However, this exception only occurs, if you cancel the upload from the server.
All other Exceptions, which includes the `EOFException` I get, when the client cancels the upload, are handled by the next `catch` block ([here](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java#L537-L546)) and there the Exceptions is wrapped in an `UploadException` and thrown.

There is even a comment about that `throw new UploadException(e)` but I am not sure if thats the correct behavior, as an Exception is somehow expected in this case.
If in your opinion the exception should propagate to the terminalErrorHandler if it is not cause of an cancelled upload, then the solution might be to add a `if (!streamVariable.isInterrupted())` before the `throw`.
The `Upload` component triggers a `UploadAbort` event, when the client aborts the upload and `StreamVariable#isInterrupted` would then return true in this caseand as I said already handled by `StreamVariable#streamingFailed`.

### Minimal reproducible example
1) Set a terminalErrorHandler like this: `vaadinSession.setErrorHandler(e -> System.out.println("Error"))`
2) Add a Vaadin Upload with a `FailedListener` to your application:
```
Upload u = new Upload();
u.addFailedListener(e -> {
	System.out.println("Upload Failed");
});
u.setReceiver(new MemoryBuffer());
```
3) Start an upload of a file and cancel the upload before it finishes.

The output in the console looks like this:

> Upload Failed
> Error

### Expected behavior
Only the `FailedListener` should be triggered

### Actual behavior
The terminalErrorHandler gets triggered too.

### Versions:
    - Vaadin / Flow version: 18.0.7

**Comment by pleku** [comment]
Thanks for the detailed and clear issue description.

I have to agree that I would expect that in the case when a component has a distinct API for handling some error scenario, the error handling of the component should be used when such handler/listener is set and if not, then the error is passed to the generic error handler. Like in the described case here for `Upload`.

Without looking deeper into the code, I can't say if there is an existing way to make the described behavior happen or if some additional API would be needed. The tricky part might be making it possible to determine whether or not the component actually handled the error or not.

**Comment by Springrbua** [comment]
> The tricky part might be making it possible to determine whether or not the component actually handled the error or not.

I am not sure if thats even needed. The `StreamVariable` itself offers the API for error handling. So one could argue, that if you want to handle the error, use the `StreamVariable` itself and not the generic error handler.
Of course this would introduce a breaking change although it probably won't affect many applications.
But another posibility would be to check `streamVariable.isInterrupted()` before throwing the Exception.
The Vaadin `Upload` already handles that correctly and sets the server side `interrupted` to true, if the client interrupts the upload (see https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java#L81-L82)

**Comment by denis-anisimov** [comment]
>While trying to find the cause, I have seen the the StreamReceiverHandler handles an UploadInterruptedException (here) and this exception is not propagated to the terminalErrorHandler. 

Yes. `streamVariable.streamingFailed(event);` is called: it just fire events and doesn't report anything to `ErrorHandler`.
Then 
`return new Pair<>(startedEvent.isDisposed(),success ? UploadStatus.OK : UploadStatus.ERROR);` just return ERROR and `handleFileUploadValidationAndData`  just returns `false`.

>However, this exception only occurs, if you cancel the upload from the server.

And I didn't get how should I cancel the upload: from the browser or from the server in your steps to reproduce ?

>All other Exceptions, which includes the EOFException I get, when the client cancels the upload, are handled by the next catch block (here) and there the Exceptions is wrapped in an UploadException and thrown.

Other exceptions occurs because of errors (not cancelation) and then `UploadException` is thrown indeed.
It looks correct to me.

So in the end : everything looks correct to me and your steps to reproduce doesn't work.

I may assume that the steps to reproduce can't be used to reproduce.
Most likely you have some example which fails but the steps to reproduce are theoretical extract from the real example without check that it really does anything.
I may assume that the exception is thrown inside your code inside some listener . And this is a custom runtime exception which indeed should be caught by the `ErrorHandler`.
So the problem may be in the application code and not inside Flow/Upload.

To eliminate any assumptions and assure that we are on the same page please :
- use https://github.com/vaadin/skeleton-starter-flow project.
- modify the code so that I may download (or checkout) the resulting project and run it without any single line modifiction
- provide steps to reproduce one by one

**Comment by Springrbua** [comment]
Thank you for your response.
I failed to reproduce it with the Vaadin starter (spring-boot). The exception (`EOFException`) is printed to the console, but it isn't coming from the default error handler in this case.
I have two other projects in which I can reproduce the issue. One is a project created with an older vaadin starter, using Vaadin 18 and Jetty. The other is the real project and it is using Vaadin 19 and an embedded Jetty server.
I tried to debug it again and noticed the following:
- The cause for the issue is always an `org.eclipse.jetty.io.EofException`
- My default error handler always gets the `org.eclipse.jetty.io.EofException`, which comes from `doHandleMultipartFileUpload` ([here](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java#L192))
- The error handler sometimes gets a second exception, which is an `UploadException` with a `org.eclipse.jetty.io.EofException`.
  My guess is, that this is a timing issue. The `upload-abort` event causes `StreamVariable#isInterrupted` to return true.
  If the `EofException` is thrown, before the `isInterrupted` causes an `UploadInterruptedException`, the `UploadException` is thrown, otherwise not. But as I said, thats just a guess.

> how should I cancel the upload

The upload has to be cancelled on the client side. I am not sure if a `Thread.sleep` on the server side is enough. In my case, I had a bigger file and due to the slow upload, I had enough time to cancel it on the client. You may want to reduce the upload speed using the developer tools of the browser.

I hope this information helps you to reproduce the problem, if you need any more information, please let me know.
I'll try to investigate a little more tomorrow and I hope to be able to reproduce it with the vaadin starter.

**Comment by denis-anisimov** [comment]
`EOFException` is not an interruption exception.
Something happens on the server side : some runtime exception is thrown and it's caught by the `ErrorHandler`.
And this is correct.

The problem is not in the `ErrorHandler`  at all. The problem is: some unexpected exception is thrown. And this is not related to the `ErrorHandler`.

Why this exception is thrown needs to be identified.

>I hope this information helps you to reproduce the problem

Unfortunately no.
We need exact steps to reproduce.
The original steps to reproduce are wrong: they don't reproduce the issue.

Please use a starter project and modify it so I may use it as is to reproduce the issue.
I don't see what we can do without proper exact steps to reproduce.

**Comment by Springrbua** [comment]
Ok, I managed to reproduce it with a Vaadin starter without Spring (Vaadin 14 - plain Java):
1) Download the Vaadin starter (https://github.com/vaadin/skeleton-starter-flow/archive/v14.zip)
2) Open project in IDE
3) Replace content in `MainView` with this code:
```
public class MainView extends VerticalLayout {
    public MainView() {
        Upload u = new Upload();
        u.setReceiver(new MemoryBuffer());
        add(u);
    }
    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        attachEvent.getSession().setErrorHandler(e -> System.out.println("ERROR!"));
    }
}
```
4) Run the project with `mvn jetty:run`
5) Start uploading a big file and cancel the upload using the button on the browser:
![image](https://user-images.githubusercontent.com/18258317/113255061-ac316e80-92c7-11eb-82b5-e9eb6922168e.png)
6) Look at the console, "ERROR!" should have been printed once or twice.

I hope you are able to reproduce the issue with this steps.
Thank you for your time!

**Comment by denis-anisimov** [comment]
No, I can't reproduce this with these steps and I've already said that: memory buffer makes download immediate.
I don't know how big the file should be. I don't have such bug files.

Please provide exact steps to reproduce: what should I do to be able to cancel the download.

**Comment by denis-anisimov** [comment]
By the way : 1.4 Mb 10% means your file is 14 Mb.
The file is not that big enough from one point of view and it's big enough from another point of view: `MemoryBuffer`  should be able to accommodate this data.
Do you have such memory for JVM at all ? It might be that using  `MemoryBuffer`  is the reason of the exception.

**Comment by Springrbua** [comment]
It has nothing to do with the `MemoryBuffer`. In fact, the file is only 1.4MB big. In my case the client is my local pc and the server is somewhere else. Due to my slow connection I have enough time to cancel the upload **on the client side**.
However you can easily simulate this using the developer tools in chrome:
![image](https://user-images.githubusercontent.com/18258317/113264388-3501d780-92d3-11eb-96df-db6dc8f7b9b5.png)
So a file of about 1-2MB with the simulation of `slow 3G` should give you enough time to cancel the upload on the client.
Note, that the upload on the client side (see network tab in dev tools) is marked as `canceled`.

**Comment by denis-anisimov** [comment]
OK, now with network which is slow down via developer tools I indeed se the "ERROR!" in the server console.
The message appears in the console twice.

**Comment by Springrbua** [comment]
> with network which is slow down via developer tools I indeed se the "ERROR!"

Great! Sorry for wasting your time, I should have mentioned this earlier.

>The message appears in the console twice

For me thats not always the case, but it shows up at least one time.

**Comment by denis-anisimov** [comment]
The exception cause in the `ErrorHandler`  is :
```
org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1141)
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1129)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:321)
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:999)
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.close(MultipartStream.java:943)
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.close(MultipartStream.java:922)
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl$FileItemStreamImpl.close(FileUploadBase.java:866)
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.findNextItem(FileUploadBase.java:1017)
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.hasNext(FileUploadBase.java:1106)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.handleMultipartFileUploadFromInputStream(StreamReceiverHandler.java:245)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.doHandleMultipartFileUpload(StreamReceiverHandler.java:186)
	at com.vaadin.flow.server.communication.StreamReceiverHandler.handleRequest(StreamReceiverHandler.java:143)
	at com.vaadin.flow.server.communication.StreamRequestHandler.handleRequest(StreamRequestHandler.java:110)
```

So as I said: this is not an interruption exception which we internally throw/handle.
This is `org.eclipse.jetty.io.EofException`  which is generic `IOException`   thrown by Jetty when `InputStream::close` is called.

So generally speaking: during cancel some `IOException`  is thrown.
This exception is reported via  `ErrorHandler`  and this is correct.
I don't see what we can do here.

We may not stop reporting `IOException`  via `ErrorHandler`: this is wrong.
We don't know `org.eclipse.jetty.io.EofException` : it's not a generic exception. This exception won't even exist in other Servlet container.

We have to catch `IOException`  during file upload and report it.

So I don't see why this is a bug: the exception is thrown by Jetty and it's reported via `ErrorHandler`.
Everything looks correct to me.

As I mentioned : the problem is not `ErrorHandler`, the problem is unexpected exception thrown by Jetty.
So you may report an issue in Jetty.

You may handle `ErrorEvent`s in your   `ErrorHandler` implementation : distinguish whether the cause is `org.eclipse.jetty.io.EofException` . In the latter case you may ignore such event.

If you may suggest another better generic solution which we may use in Flow please let me know.

**Comment by Springrbua** [comment]
The point is that this excption occurs during a normal user interaction and I am not able to stop it.
The `StreamVariable` itself has an API for error handling. This API should probably be notified about all kinds of `Exception`s (including `IOException`). So in my opinion there is no need to notify the default `ErrorHandler`, as there is a specific API for error handling, @pleku seems to agree on that (see https://github.com/vaadin/flow/issues/10351#issuecomment-806670020).
As I said earlier, this would introduce a breaking change although it probably won't affect many applications.

Another possible solution would be to check the `isInterrupted` before notifying the `ErrorHandler`. If the upload has been interrupted, I probably don't care about the `Exception` and if I really do, I can still use `SteamVariable#streamingFailed`.

**Comment by denis-anisimov** [comment]
Ah.
You are suggesting to limit stream processing handling to `streamVariable.streamingFailed(event);`   and avoid throwing any other exception which then reported to `ErrorHandler`.

Well.... I'm not familiar with the overall `StreamReceiverHandler` /`StreamVariable`  design but it makes sense for me.
Technically `UploadException` is explicitely thrown to be handled by the  `ErrorHandler` by design.

But on the other hand this happens in `catch (final Exception e)`  block and not in `catch (UploadInterruptedException e)` .

Apparently the exception `EofException`  happens before check `streamVariable.isInterrupted()`  is done.

I'm also confused by the wrong stacktrace of  `EofException` : it has no any call inside `streamToReceiver` . I think the exception is rethrown as is without making the correct stacktrace: the exception happens in totally different place and it's not possible ti identify which call inside `streamToReceiver`  causes the exception.
That's why I'm very confused with this.

>Another possible solution would be to check the isInterrupted before notifying the ErrorHandler. If the upload has been interrupted, I probably don't care about the Exception and if I really do, I can still use SteamVariable#streamingFailed

Kind of yet and no.
In this specific case `EofException`  is indeed tightly related to the fact that the upload is cancelled.
But there may be a bunch of other reasons why generic `IOExcepion`  happens.
It might be that there are two totally unrelated things:
- upload is cancelled
- some exception is thrown

We may not be sure that even `IOException`  happens only because upload was interrupted.
So I wouldn't rely on `isInterrupted`  check in the catch block.

And the block is `catch (final Exception e) {` not `catch (final IOException e) {` : the exception is really quite unexpected since the expected exception should be `UploadInterruptedException` .

So I would even go with avoiding throwing `UploadException`  at all and just  delegate to `streamVariable.streamingFailed`.

May be it makes sense to distinguish `IOException`  and delegate only to `streamVariable.streamingFailed`  and other exceptions and then throw `UploadException`.
I will think about this.

**Comment by Springrbua** [comment]
> Technically UploadException is explicitely thrown to be handled by the ErrorHandler by design.

Yea, I have seen that but I didn't really understand why. This might cause a `Exception` to be handled twice.

> We may not be sure that even IOException happens only because upload was interrupted.

What I meant was, that I am probably not interested in any `Exception`, if the upload has been canceled anyways. But I might be wrong.

**Comment by denis-anisimov** [comment]
The issue is more complicated than I expected.

As I said: I get two "ERROR!" messages.
And this is not same code called twice: this is two different place which throw an exception.
For me it's always double "ERROR!" message and this is expected. I don't know how there can be one message.

The first message is coming from the place which has been already discussed. It's caused by the `catch (final Exception e)` block which rethrow an `UploadException`  and then this exception is handled by the `ErrorHandler` .
As it's been discussed : `StreamVariable`  is notified about this failure and it's reasonable do not notify `ErrorHandler` in addition  to that.

But this exception is thrown by some internal mechanism of Jetty during `InputStream`  processing.
The exception is thrown in a totally different place and it's just re-thrown as is (without stackreace correction/wrapping) inside `streamToReceiver`.

What happens in fact is:
- there are two connections (HttpRequests).
- the first connection renders `Upload` component, listens the progress and reports events (failures, etc.) This connection is handled inside `streamToReceiver` method.
- It really makes sense to avoid exceptions in this first connection since a `StreamVariable`  is notified via events about the upload process
- the second connection handles the upload itself: it receives data from the client to the server. This is totally different connection which doesn't manage the `StreamVariable`  variable anyhow.

The `IOException`  happens in the second connection. And then it's rethrown by some internal Jetty magic via `InputStream`  operations to the another connection. Technically it's an issue in Jetty.

The proposed solution allows to avoid to fire an exception via `ErrorHandler` in the first connection.
But it still happens in the second connection and technically I cannot say for sure that this exception shouldn't be reported via  `ErrorHandler`: Jetty throws an exception and this exception happens in the data receiving connection which is valid to report.

So If I fix the `streamToReceiver` method to avoid rethrowing the exception (using only a `StreamVariable`  notification method) it still doesn't solve the issue which you are trying to get rid of: there still will be an call to `ErrorHandler` with another exception (the root cause) . And you again will be dissatisfied I guess.

So to fix it as you would like to the exception which is thrown in totally different place should not be forwarded to  `ErrorHandler` at all and this is already questionable behavior (comparing to the first agreed one).

I think I will consider I/O errors as a normal upload behavior which should be caught properly by the `StreamVariable`  in the connection which renders the `Upload` . And all `IOException`s will not be forwarded to the `ErrorHandler` but either just logged or fired via the `StreamVariable`  instance.

**Comment by Springrbua** [comment]
> I don't know how there can be one message.

To me this happens sometimes. My guess is, that this is a timing thing. Aborting the error on the client sets the `isInterrupted` of the `StreamVariable` to true. If this is checked before the `EOFException` occurs, the `Upload` stops with an `UploadInterruptedException`, which is not rethrown. If the `EOFException` happens before the check of `isInterrupted` there will be two errors. But this should be irrelevant for this issue.

> there are two connections (HttpRequests)
> the second connection handles the upload itself

But the `StreamVariable` is the one that receives the data from the upload. Doens't that also mean, that it should handle `Exceptions` caused by the upload connection?
As the `Exception` occurs inside `streamToReceiver` it is technically possible to notify the `StreamVariable` about it instead of notifying the `ErrorHandler` right?

Thank you again for taking the time to investigate.

**Comment by bertvermeiren** [comment]
Trying to open up the discussion again after the fix, since it seems there is still an issue.

`    try (InputStream handledStream = inputStream) {
            // Store ui reference so we can do cleanup even if node is
            // detached in some event handler
            Pair<Boolean, UploadStatus> result = streamToReceiver(session,
                    handledStream, streamReceiver, filename, mimeType,
                    contentLength);
            if (result.getFirst()) {
                cleanStreamVariable(session, streamReceiver);
            }
            return result.getSecond() == UploadStatus.OK;
        } catch (Exception e) {
            session.lock();
            try {
                session.getErrorHandler().error(new ErrorEvent(e));
            } finally {
                session.unlock();
            }
        }`

When an upload is interrupted (slow upload with for example 3G throttling in the browser), you get a Failed event with an EofException. That seems all working fine.
Either, in the above code you get up to the return statement but then you get in the Exception catch block again, probably due to the "try-with-resource statement" on the input stream trying to close the input stream. That will raise again an EofException it seems and you get again an error on the error handler. There is no way to disable somehow this behaviour. No plugin, no tweak....

Please advice.

Regards,
