### ISSUE TITLE
Upload of big files: StartedEvent and ProgressUpdateEvent report -1 file size

### ISSUE THREAD

**Issue by roelnoten** [vaadin/flow#10392]
### Description
When uploading large files, eg 2Gb, the StartedEvent and the ProgressUpdateEvent report -1 as contentLength.  When the filesize is small, the contentlength is correct.
Our application needs to accept those huge uploads but must implement a server-side free-space check before accepting the file, so thie -1 is very inconvenient.

### Live Demo

https://glitch.com/edit/#!/vaadin-upload-issue

### Steps to reproduce
```
        Upload upload = new Upload(new Receiver() {
            @Override
            public OutputStream receiveUpload(String s, String s1) {
                return new OutputStream() {
                    @Override
                    public void write(int b) throws IOException {
                        //noop, good enough to demonstrate the issue
                    }
                };
            }
        });
        upload.addProgressListener(new ComponentEventListener<ProgressUpdateEvent>() {
            @Override
            public void onComponentEvent(ProgressUpdateEvent event) {
                System.out.println("ProgressUpdateEvent "+event.getReadBytes() +" / "+event.getContentLength());
            }
        });

        upload.addStartedListener(new ComponentEventListener<StartedEvent>() {
            @Override
            public void onComponentEvent(StartedEvent event) {
                System.out.println("StartedEvent "+event.getFileName() +" of "+event.getContentLength());
            }
        });
        body.add(upload);
```

Note that is noticed that in the the javascript it does know the filesize correctly. Today i have this ugly workaround in place, which works:
```
    private void determineFileSizeThroughJsOfLastFile() {
        try {
            PendingJavaScriptResult jsResult = getElement().executeJs("if (this.files == null || this.files.length ==0) {return -2} else { return this.files[this.files.length-1].size}");
            jsResult.then(result -> {
                long length = Double.valueOf(((JreJsonNumber)result).getNumber()).longValue();
                System.out.println("determineFileSizeThroughJsOfLastFile file size is "+length );
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

### Expected outcome
The actual file size should be there, not -1.

### Actual outcome
-1
### Browsers Affected
Seen on Chrome, not tested further.

### Version
Vaadin Flow 14.4.0

**Comment by tulioag** [comment]
Transferred to Flow.

The issue seems to be in this line:

https://github.com/vaadin/flow/blob/088293ffea44272e2b80487fcfaa8b269da4fa47/flow-server/src/main/java/com/vaadin/flow/server/communication/StreamReceiverHandler.java#L240

It delegates to `ServletRequest.getContentLength`, which returns -1 if the value is greater than `Integer.MAX_VALUE`
https://javaee.github.io/javaee-spec/javadocs/javax/servlet/ServletRequest.html#getContentLength--


Something like this should work:

```java
long contentLength = ((VaadinServletRequest) request).getContentLengthLong();
```

**Comment by knoobie** [comment]
@pleku I was wondering about the issue.. I can talk a look at this but I have two ways of fixing it: 

Option A) as described, simple instance of combined with the long method if applicable, otherwise the current return 
Option B.1) Vaadin has as dependency servlet 3.1 API - this API introduced the new method with getContentLengthLong - meaning I could add this method to VaadinRequest and just use it directly (added API) 
Option B.2) instead of creating a second method with getContentLengthLong, I could change the return typ of the current method (breaking change, but probably better in the long run?)

Option B.1 / B.2 both have a bigger impact because of all the different VaadinRequest implementations.
