### ISSUE TITLE
Impossible to load assets from npm packages in style.css

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#10426]
### Description of the bug / feature
I'm following the documentation to load the assets from npm Package.
https://vaadin.com/docs/v14/flow/styling/custom-theme-configuration/#assets
But I have a 404 error when I'm using it in styles.css.
```
{
  "assets": {
    "@fortawesome/fontawesome-free": {
      "svgs/regular/**": "fontawesome/icons"
    }
  }
}
```
```
.icon-snowflake {
  background-image: url('fontawesome/icons/snowflake.svg');
}
```
It's working if I'm trying to add the image with Java:
```
Image crmImage = new Image(
                "themes/myapp/fontawesome/icons/snowflake.svg",
                "Vaadin Brand");
        add(crmImage);
```
### Minimal reproducible example
Create the view:
```
@NpmPackage(value = "@fortawesome/fontawesome-free", version = "5.15.3")
@Route(value = "about", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div {

    public AboutView() {
        addClassName("about-view");
        addClassName("icon-snowflake");
        add(new Text("Content placeholder"));
        /*Image crmImage = new Image(
                "themes/myapp/fontawesome/icons/snowflake.svg",
                "Vaadin Brand");
        add(crmImage);*/
        add(new Html("<i class=\"fab fa-vaadin\"></i>"));
    }

}
```

Update styles.css:
```
.icon-snowflake {
    background-image: url('fontawesome/icons/snowflake.svg');
}
```
And theme.json:
```
{
  "assets": {
    "@fortawesome/fontawesome-free": {
      "svgs/regular/**": "fontawesome/icons"
    }
  },
  "importCss": [
    "@fortawesome/fontawesome-free/css/all.min.css"
  ]
}
```
### Expected behavior
The icon as a background image should be there.

### Actual behavior
No icon.
In Vaadin 14.6 alpha I have a 404 error.
In Vaadin 19.0.2, the image is redirected by flow: http://localhost:8080/fontawesome/icons/snowflake.svg
### Versions:
    - Vaadin / Flow version: 14.6.0.alpha1 and 19.0.2
    - Java version: 14
    - OS version: Mac
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Tomcat (default Spring boot app)
    - IDE (if applicable): IntelliJ

Here is an example project:
[vaadin_19_theme.zip](https://github.com/vaadin/flow/files/6210512/vaadin_19_theme.zip)

The right path seems to be:
```
.icon-snowflake {
    background-image: url('/themes/myapp/fontawesome/icons/snowflake.svg');
}
```

But it won't work if the application has a context path.
With the example project you can try by adding in application.properties:
```
server.servlet.context-path=/context
```

**Comment by pleku** [comment]
From Java and CSS, it should be fine to use
```css
.icon-snowflake {
    background-image: url('fontawesome/icons/snowflake.svg');
}
```
```java
Image crmImage = new Image(
                "fontawesome/icons/snowflake.svg",
                "Snowflake");
```
since the asset is mapped with 
```json
{
  "assets": {
    "@fortawesome/fontawesome-free": {
      "svgs/regular/**": "fontawesome/icons"
    }
  }
}
```
@Artur- in https://github.com/vaadin/flow/issues/9535#issuecomment-737107336 you said that _it should go like in the prototype_ to be able to use `theme/my-theme/fontawesome/icons/snowflake.svg` and then some changes were made so that it works like that. 
But actually in the story map @rolfsmeds this is specified as using things like above in my comment. So we are now going to fix it to work like above.

But it is a good question that should it also work by using the prefixed `themes/my-theme/` ? From CSS, I would say no. From Java, I would say No to avoid using hard-coded magic strings. In the future we might have support for multiple runtime themes on the application, and as a Java developer you want to specify `new Image("icons/snowflake.svg", "Snowflake");` where a different theme maps different set of resources to be used. And even there, IMO it would make more sense to **be able to drop out the theme name** from the url because that is hard-coded to the theme name. It seems at least easier if one doesn't have to use any code to get the name of the active theme, but to just let the framework redirect the request to the resource to the active theme.

**Comment by Artur-** [comment]
We already support multiple themes through a parent theme. How do you load `images/bg.png` from the parent theme when it exists also in the child theme?

**Comment by rolfsmeds** [comment]
My mental model of this feature is that the path to which an asset is mapped is relative to the root folder of the theme with the `theme.json` that does the mapping, i.e. `: "fontawesome/icons"` in `mytheme/theme.json` maps to `themes/mytheme/fontawesome/icons`, thus you should be able to refer to it within `mytheme/styles.css` as `url("fontawesome/icons/snowflake.svg")`.

Having to prefix the url with `/themes/mytheme` would be weird if the referrer is in that same folder.

As for parent-themes, my mental model of them is that they're available as sibling-folders to the used sub-theme, so `themes/mytheme` can refer to `themes/basetheme` by `../basetheme`.

As for npm-mapping in parent/sub themes, following the above model, mapping to `fontawesome/icons` in `basetheme/theme.json` would mean that the asset is available, for the sub-theme, in `../basetheme/fontawesome/icons`, in which case sure, you have to refer to the parent theme by name, but the same applies if you want to refer to a real path in the parent theme from the child theme, e.g. `basetheme/logo.png` could be referred to from the sub-theme as `url('../basetheme/logo.png')`.

Not sure about the java side. Seems to me that it would be good to have an standard way to point to an asset from the currently applied theme without having to use its name, but I would consider that an enhancement.

So I suggest we start by poking holes in my mental model, and take it from there :)
