### ISSUE TITLE
Hardcoded UI class in JavaScriptBootstrapHandler

### ISSUE THREAD

**Issue by xdenser** [vaadin/flow#10696]
https://github.com/vaadin/flow/blob/dde115adfbcc9484e60a34d603251edf94fae529/flow-server/src/main/java/com/vaadin/flow/server/communication/JavaScriptBootstrapHandler.java#L122

why UI class is fixed here, when it may be taken from parameter and checked for compatibility? It makes big problems to override UI class.

**Comment by Legioth** [comment]
Why do you want to override the UI class?

**Comment by xdenser** [comment]
because I migrate application where I use custom UI class, so now in order to switch to Vaadin15+ bootstrap I have to move everything that depends on my custom UI class to some other place, instead of just overriding IndexHtmlBoostrapHandler to create my UI.

**Comment by xdenser** [comment]
And this may be easily fixed with "if" checking that passed class is assignable to JavaScriptBootstrapUI and only if not then ignore it. I can wait for next release with my switch of boostrap.

**Comment by miguelatvaadin** [comment]
Hi @xdenser,

thanks for your comments.

Could you please provide more details on what is your UI customization about, in order to properly address this issue? 

Please notice that you can easily override the default index.html just by following the instructions you get from the default index.html: 
> If you want to customize the index.html, you can copy this file or create your
> own `index.html` in your frontend directory.
> By default, the `index.html` file should be in `./frontend/` folder.`

Best regards

**Comment by xdenser** [comment]
I do not need to customize index.html. Well I actually need but this is another story. 
UI in our application just holds some server side state which is not related to VaadinSession - as I can have multiple UIs in the same session, but to browser Tab/Window. It was easy to use for such purpose because you can just set UI class in servlet configuratoin with Vaadin 14 bootstrap. And then call UI.getCurrent() and you get your correct UI (in some places casted to MyUI class), or MyUI.getCurrent() - which does the same. If this method from first comment would respect at least uiClass parameter or better method getInitialJson would repsect what UI class is set in ServletConfig - then it will be easer to override.

**Comment by Legioth** [comment]
As a workaround if you only have some limited state, you can use `getData` and `setData` from `ComponenUtil`.

In that way, what was previously like this
```java
String someValue = ((MyUiType) UI.getCurrent()).getSomeValue();
```
would instead become
```java
String someValue = (String) ComponentUtil.getData(UI.getCurrent(), "someValue");
```

**Comment by miguelatvaadin** [comment]
Yes. You could also use the UI id (`UI.getCurrent().getUIId()`) as part of a key to store your UI related values in the session.

Please let us know if that works for you.

**Comment by xdenser** [comment]
I know I can move this state from UI somewhere, but this means also some bigger re-work that I wanted to avoid. If this problem with hardcoded class will be solved in some of the next releases I will wait. If not - I have to plan some bigger refactoring or just give up upgrade from Vaadin14 boostrap.

**Comment by miguelatvaadin** [comment]
Hi @xdenser,

thanks for your help and patience. We are just trying to understand the problem before adressing it.

Please note that overriding the UI is not the way to go with Vaadin Flow. It was with Vaadin 8, but now you are supposed to override any other component (e.g. a div) and annotate it with `@Route`. As https://vaadin.com/docs/v10/flow/migration/3-general-differences says:

> A subcass of UI is not needed in Vaadin Flow applications. It is still there, but it is not the starting point of the application anymore, and you don’t need to define your custom UI.

and 

> Most things you have previously done in the UI class, can be achieved in alternative, better ways.

That said, before taking any action we need to verify that there is a real need for modifying the current UI behavior, and that's why we are asking you to provide more details so we can fully understand your use case.

From your messages I understand that your true problem is to access your custom UI instance (which now should not be a `UI` anymore) from wherever as you were using the `UI.getCurrent()` method for that purpose. Is that right?

**Comment by xdenser** [comment]
Yes right.

**Comment by miguelatvaadin** [comment]
Hi @xdenser,

thanks for your answer. If that's the point, then I think Leif's suggested solution should be the way to go. Just register you custom view instance (let's call it MainView) inside the constructor like this:

`ComponentUtil.setData(UI.getCurrent(), MainView.class, this);`

and get the instance from wherever with:

`
MainViewLocator.get()
`

where MainViewLocator is something like this:

```java
public class MainViewLocator {

    public static MainView get() {
        return ComponentUtil.getData(UI.getCurrent(), MainView.class);
    }
    
}
```


If you are using Springboot then you can obviously use the `@UIScope` annotation to inject your own logic at the UI level.

Could you please confirm if any of those solutions address your need?

Best regards,

**Comment by Legioth** [comment]
Using a custom UI class has been deprecated but still functioning since Vaadin 10. We would like to encourage application developers to move away from that pattern so that we could eventually simplify the internal implementation. Not supporting custom UI classes with the new bootstrapping mode that is set as the default in Vaadin 15 seems like a good nudge in that direction, even though it might have been introduced by accident.

I'm wondering whether it would indeed make sense for us to keep that nudge in place even though it also looks like it would be rather trivial to fix the "bug"?

**Comment by xdenser** [comment]
As said I can find solution how to get rid of custom UI. Thanks for hints. If custom UI is definitely will not be supported  - ok I will plan some more time on switch to Vaadin 15 bootstrap.

**Comment by miguelatvaadin** [comment]
Thanks to you for sharing your use case details and letting us know about your problem, @xdenser.

I will close this issue.

Best regards

**Comment by mvysny** [comment]
> We would like to encourage application developers to move away from that pattern so that we could eventually simplify the internal implementation.

I read that as "Taking away features in order to simplify Vaadin internals". I do hope the cleanup benefit is HUGE.

I have a 700-line Vaadin 8 UI that needs to be migrated to Vaadin 20. Vaadin 8 example:

```java
class MyUI {
  private ExecutorService es;
  public void init() {
    es = ... build the executor;
  }
  public void detach() {
    es.shutdown();
  }
}
```

Everything is nicely wrapped in the UI class which has a clear responsibility for creating the executor, providing its instance and then clearing it up. In Vaadin 10+, I have to register VaadinService.addUIListener() in one place, then add detach listener to the UI in another, then call `ComponentUtil.getData(UI.getCurrent(), ExecutorService.class);` to retrieve the executor service. Sure, I can create a class that hosts all of this functionality, but why should I when there is the UI class already available?

**Comment by mvysny** [comment]
Regardless. The Docs says that "it actually is possible to use a custom UI": https://vaadin.com/docs/v14/flow/integrations/cdi/tutorial-cdi-instantiated-beans#using-a-custom-ui

Which sounds totally to be not true. It would be good to finally decide on this, then fix the documentation.

**Comment by enver-haase** [comment]
Can we reopen this one then.

**Comment by Legioth** [comment]
Why? It works as designed.

**Comment by enver-haase** [comment]
https://github.com/vaadin/flow/blob/main/flow-server/src/main/java/com/vaadin/flow/server/InitParameters.java#L38  
"The name of the parameter that is by default used in e.g. web.xml to define the name of the default UI class."
gives away that it shall not be hard-coded and the overridable default shall be used, right?

The implementation violates this documented intent by ignoring the configuration in JavaScriptBootstrapHandler.

**Comment by Legioth** [comment]
Right. So we need to update the documentation to be aligned with the design and the implementation. That might be more appropriate as a separate ticket.
