### ISSUE TITLE
When the WebComponentExporter constructor fails with an exception, Maven will print a non-informative "Could not write exported web component module!" error message

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#10766]
### Description of the bug / feature

The Maven Vaadin plugin needs to create instances of `WebComponentExporter`s in order to obtain the tag name and the default parameter values for the webcomponent/component being exported. This is highly unusual since this causes customer code to be instantiated **at build time** (where the necessary runtime environment is not available), which could cause the customer-specific WebComponentExporter classes to fail with an exception. If this happens, Maven will print a non-informative "Could not write exported web component module!" error message.

We've spent hours trying to figure out what's wrong, and it took inside Vaadin knowledge to learn the origin of the issue.

Since creating customer classes in compile time is unusual, this needs to be clearly documented in WebComponentExporter's javadoc. Also, the error message must be made much more informative.

Excerpt from the stacktrace:
```
Caused by: java.lang.NoClassDefFoundError: java/sql/SQLException
    at be.kava.tarifering.vaadin.views.exporter.QueriesExporter.<init> (QueriesExporter.java:23)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:490)
    at com.vaadin.flow.internal.ReflectTools.createProxyInstance (ReflectTools.java:483)
    at com.vaadin.flow.internal.ReflectTools.createInstance (ReflectTools.java:451)
    at com.vaadin.flow.component.WebComponentExporterFactory$DefaultWebComponentExporterFactory.create (WebComponentExporterFactory.java:108)
    at com.vaadin.flow.server.webcomponent.WebComponentExporterTagExtractor.apply (WebComponentExporterTagExtractor.java:38)
    at com.vaadin.flow.server.webcomponent.WebComponentModulesWriter.getTag (WebComponentModulesWriter.java:142)
    at com.vaadin.flow.server.webcomponent.WebComponentModulesWriter.writeWebComponentToDirectory (WebComponentModulesWriter.java:114)
    at com.vaadin.flow.server.webcomponent.WebComponentModulesWriter.lambda$writeWebComponentsToDirectory$0 (WebComponentModulesWriter.java:94)
```

### Minimal reproducible example

Create a WebComponentExporter class which throws in the constructor.

### Expected behavior

Maven should fail with an informative error message, such as "Failed to create instances of MyCustomExporter because of NoClassDefFoundError: java/sql/SQLException. Please read WebComponentExporter's javadoc for more information on this. Please run Maven with the -e switch (or Gradle with the --stacktrace switch), to learn the full stack trace.

Also, this needs to be clearly documented in WebComponentExporter's javadoc.

### Actual behavior

"Could not write exported web component module!" is printed. When maven is run with `-e`, the exception stack trace is printed which still doesn't suggest as to why the error happened.

### Versions:
    - Vaadin / Flow version: 14.5.3, 19.0.5

**Comment by denis-anisimov** [comment]
There are a lot of problems which are not obvious from the simple usage and they make quite hard or impossible the suggested simple solution.

`java.lang.NoClassDefFoundError` (which is not an exception by the way) is thrown during exporter instantiation via Reflection. This code has no any relation to the `WebComponentModulesWriter` code : it's in a totally different place.
So it's not clear what  exactly causes the exception in the `WebComponentModulesWriter`: the exporter instantiation or something else.
`WebComponentModulesWriter` calls itself via Reflection to be able to allow this code works in Maven because of different classloader issues.
So the exception which is caught at the moment of the call is just a generic `InvocationTargetException` which doesn't give the information about the cause semantic.

`java.lang.NoClassDefFoundError` is not an exception. It's a `Throwable` and it's quite rare situation that you have to catch `Throwable`: it's too easy to miss the `catch`  for this and you normally doesn't catch it at all. 
The fact that `java.lang.NoClassDefFoundError` is not an exception is most likely the reason why it was that hard to find the cause : it's always hard to catch the linkage errors.

The same code is called differently depending whether this s a production mode or dev mode.
In dev mode the code is called inside the web app runtime directly and the exception which is thrown because of inability to instantiate the exporter may not mention Maven at all.

In production mode the code is called during project build and it means that it's required to catch one more exception inside Maven module code to be able to provide some additional info about maven.


Now,  `WebComponentExporter's javadoc` : I don't even know what you suggest to write there.
As I said: the same code is called depending on the mode: dev or production. And it's not possible to mention Maven specifics in this javadocs.
So nothing exact can be written there. May be something about calling the `WebComponentExporter `code during build time.
But I don't see how it helps. I would say this doesn't help anyhow.

**Comment by denis-anisimov** [comment]
I will try to put more `catch`  in various places and handle somehow exceptions better.
But I may not be sure that that will solve all the possible issues: this is my point.

And I don't see how may I improve `WebComponentExporter`  javadocs at all.

**Comment by mvysny** [comment]
> And it's not possible to mention Maven specifics in this javadocs.

I'd say it depends whether we want to pursue the purity of javadoc, or be helpful to the users.

> java.lang.NoClassDefFoundError is not an exception. It's a Throwable and it's quite rare situation that you have to catch Throwable: it's too easy to miss the catch for this and you normally doesn't catch it at all.

True. But then again, depends on whether we try to achieve purity of code or be helpful to the users. In case of the latter, we can catch Throwable in a code that clearly belong to a plugin - I think catching Throwable in a plugin is okay-ish.

**Comment by denis-anisimov** [comment]
The problem is : `catch(Throwable) `  should be done not in the Maven specific code but is some place where you don't expect such Throwable at all.

I don't say we should not do it.
I'm talking that it's quite hard to detect all such places and it's hard to expect all such cases: it's complicated from the implementation point of view.

Again: javadocs. If you see good meaningful messages (considering the fact that the exported is called not only from Maven but also in runtime) please let  me know. I will add it.
