### ISSUE TITLE
V14.5.x - API Element.setAttribute("href", "value") not working

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#10947]
### Versions:
    - Vaadin / Flow version: 14.5.4
    - Java version: 11
    - OS version: Windows
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Tomcat 9.45

The Java API: `Element.setAttribute("href", "https://vaadin.com/")` is not working. The URL still remain the previous setting "https://github.com/"

Below is html on view setting (.js)

```
<div >
	<a id="mylink" href="https://github.com/" target="_self" ></a>
</div>

```

**Comment by letrthang** [comment]
remove **href**="https://github.com/" on html will work:

```
<div >
	<a id="mylink"  target="_self" ></a>
</div>
```

**Comment by letrthang** [comment]
Hi @miguelatvaadin 

We create a file:
**view.js**

`
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';
import '@webcomponents/webcomponentsjs/webcomponents-loader.js';
import '@polymer/iron-icon/iron-icon.js';
import '@vaadin/vaadin-button/vaadin-button.js';
import '@vaadin/vaadin-text-field/vaadin-text-field.js';
import '@vaadin/vaadin-combo-box/vaadin-combo-box.js';
import '@vaadin/vaadin-text-field/vaadin-password-field.js';
import '@vaadin/vaadin-ordered-layout/vaadin-horizontal-layout.js';
import '@vaadin/vaadin-ordered-layout/vaadin-vertical-layout.js';
import { sharedStyles } from './view-all.js';

class StaffCompanyView extends PolymerElement {
	static get template() {
		 return html`
		 	${sharedStyles}

			<div class="main-layout main-div-layout">
				
			 	<vaadin-vertical-layout class="main-screen-large" id="mainLayout">
			 	
			 		<vaadin-horizontal-layout class="staff-info-label">
				 		<div class="div-staff-info">
			     			<label id="lbWelcome" class="color-black">Last check-in </label>
			     		</div>
			     		<div class="div-staff-info-link">
				    		<a id="**mylink**" href="https://github.com/" target="_self" class="staff-info-label-link"></a>
				    	</div>
			   		</vaadin-horizontal-layout>
			   		
			   		<vaadin-vertical-layout class="main-screen-vert-layout-row padding5">
					   	<hr class="main-screen-vert-layout-button divHR">
				    </vaadin-vertical-layout>
		
				 	<vaadin-vertical-layout class="main-screen-vert-layout padding5">
				 		<label id="lbGrid" class="color-blue main-screen-vert-layout-row-label">List of Organizations</label>
				      	<vaadin-grid id="gridOrganizations" theme="mobile" class="main-screen-grid"></vaadin-grid>
				   	</vaadin-vertical-layout>
				    
				    <vaadin-vertical-layout class="main-screen-vert-layout-row padding5">
		 				<label id="lbNoticeMessage" class="color-blue-notify main-screen-vert-layout-row-label "></label>
	 				</vaadin-vertical-layout>

			  		<vaadin-vertical-layout id="verLayoutButton"> </vaadin-vertical-layout>
			  		<vaadin-vertical-layout id="verLayoutTimer"> </vaadin-vertical-layout> 
			 	</vaadin-vertical-layout>
			</div>
		 `;
	}
	static get is() {
        return 'staff-company-view';
    }

    static get properties() {
        return {
            // Declare your properties here.
        };
    }
}
customElements.define(StaffCompanyView.is, StaffCompanyView);

`

**Java code:**

```
@Route(value = "StaffInformation", layout = MainView.class)
@PageTitle("Staff Information")
@Tag("staff-information-view")
@JsModule("./src/view/staff-information-view.js")
public class StaffInformationView extends PolymerTemplate<StaffInformationView.StaffInformationViewModel> {

@Id("linkLecompany")
	private Element **mylink**;
//....

mylink.setAttribute("href", "https://vaadin.com/") **is not working**

}

```

**Comment by denis-anisimov** [comment]
It's very important to provide at least this information in every ticket report:
- steps to reproduce (which anyone can use)
- expected result
- actual result

This is a perfect example why it's so important:

steps to reproduce: `StaffCompanyView.js` code snippet contains a lot of irrelevant information .
There a lot of `import`s (they are not related to the issue) there is `sharedStyles` import whose content is not known from the report and what's worse it's used in the body of the template. So it's impossible to say whether it matters or not.

There is no expected result ( even though it's kind of implicit : negation of real result)

The actual result is not clear : there is only a DOM snippet.

Since a lot of things are missed I have to make my own steps to reproduce to guess what the issue in fact is:

- take starter https://github.com/vaadin/skeleton-starter-flow
- Use this code instead of `MainView` :
```
@Route("")
@Tag("my-some")
@JsModule("./src/some.js")
public class MainView extends PolymerTemplate<TemplateModel> {

    @Id("mylink")
    private Element mylink;

    public MainView() {
        mylink.setAttribute("href", "https://vaadin.com/");
    }
}
```
- use this template as some.js
```
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';

class Some extends PolymerElement {
  static get is() {
    return 'my-some';
  }

  static get template() {
    return html`
        <div class="div-staff-info-link">
            <a id="mylink" href="https://github.com/" target="_self" class="staff-info-label-link"></a>
        </div>
    `;
  }
}
customElements.define(Some.is, Some);
```

The expected result: the DOM snippet looks  this way:
```
<div class="div-staff-info-link">
            <a id="mylink" href="https://vaadin.com/" target="_self" class="staff-info-label-link"></a>
        </div>
```

The actual result : the DOM snippet looks this way:
```
<div class="div-staff-info-link">
            <a id="mylink" href="https://github.com/" target="_self" class="staff-info-label-link"></a>
        </div>
```

**Comment by denis-anisimov** [comment]
With these steps to reproduce and the expected result I can say:
the expected result is wrong.

to get the expected result the code `mylink.setProperty("href", "https://vaadin.com/");` must be used.
You can do exactly the same via the Chrome inspector: select the element and call for it `$0.setAttribute("href", "https://vaadin.com/");`
Nothing will be changed in the DOM.
But if you set a property `$0.setProperty("href", "https://vaadin.com/");` then you will get what you expect.

The attributes are not the same as properties, please read e.g. this: https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html?answertab=active#tab-top

**Comment by miguelatvaadin** [comment]
In fact, `$0.setAttribute("href", "https://vaadin.com/");` works. Also, `href` is an attribute (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a). 

Am I missing something?

**Comment by denis-anisimov** [comment]
Yes, it works.
Yes, it's an attribute ALSO.

Yeas you are missing that `setAttribute` doesn't update the DOM. It set's the attribute.
And you can check that `getAttribute` returns the value which has been set.

But the DOM shows the _property_ `href`. And the property is not updated via `setAttribute` .

**Comment by miguelatvaadin** [comment]
Thanks for your comment, @denis-anisimov .

I understand the difference between attribute and property but, shouldn't it work as expected by @letrthang . To be honest, I expected exactly the same bahavior as he did.

If we have a `setAttribute` method in our `Element` class, shouldn't it just update the attribute in the client side as expected? And, if not, shouldn't there be something to warn the user? At least in the javadoc or somewhere?

**Comment by miguelatvaadin** [comment]
> And the property is not updated via setAttribute .

In fact, I think it is updated. It's just that they do not hold the same value

```
$0.setAttribute("href","a");
$0.href; // returns http://localhost:8080/a
```

**Comment by denis-anisimov** [comment]
This is how JS works.

Flow Element API just replicate the JS HTML API.
There is nothing to complain abut Flow.

The whole JS is confusing for me personally.
But I don't see any point to complain how HTML works since it's given and we have to deal with this. 
Feel free to complain to HTML/JS spec for impl.

**Comment by miguelatvaadin** [comment]
Well, I'm still worried about our side of all this. I would say we are publishing an api which is not working as expected. Also, if it only does not work when the `href` has formerly been set in the html, I would say it points out to a bug. 

Anyway, let's see if @letrthang is happy with using `setProperty` instead of `setAttribute`. 

Thanks a lot for your patience and the discussion, Denis ;)

**Comment by letrthang** [comment]
because this is JS spec, we have no choice :))
