### ISSUE TITLE
 Add ability to add devDependency with NpmPackage annotation

### ISSUE THREAD

**Issue by niiyeboah** [vaadin/flow#11032]
I would like to add an NPM package as a `devDependency`  from the Java side in order to exclude it from the frontend build.

### Example API:
`@NpmPackage(value="@types/d3", version = "6.2.0", devDependency = true)`

**Comment by pleku** [comment]
The API seems simple enough. The implementation needs to change `FrontendDependencies` and `FullDependenciesScanner` so that it would separate the dev dependencies to another API declared in `FrontendDependencies` or then change the return type for `getPackages()` to include the dev-dependency information for each package. Then this logic should be taken into account when writing things to package.json.

**Comment by michael-newsrx** [comment]
Is there any work around for this that doesn't involve editing the rather touchy packages.json file?

**Comment by jsalts** [comment]
We would also like to see this added. It seems like Vaadin would like us to managing package.json with this annotation but is not providing all the tools to do so. Maybe manual edits are fine but it feels a bit anti-pattern.

**Comment by oliveryasuna** [comment]
I am going to open a PR for this.
