### ISSUE TITLE
ResponseWriter.writeResponseContent writes incorrect Content-Length if resourceUrl points to a file system directory

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#11046]
`ResponseWriter.writeResponseContent` uses `connection.getContentLengthLong()` (see https://github.com/vaadin/flow/blob/83ebf7b7a920ce098b9048d10a7d32813d2719e4/flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java#L166-L171). When `resourceUrl` points to a file system directory, this internally translates to a call to `File.length()`, which has the following in the JavaDoc:

> The return value is unspecified if this pathname denotes a directory.

Steps to reproduce it locally:
1. Create SVC app
2. Run `mvn package` (to put some stuff to `/target/classes/META-INF/VAADIN/webapp/VAADIN/build`)
2. Run applicatoin in development mode in a normal manner
3. Run `curl -i "http://localhost:8080/VAADIN/build/." --path-as-is`
4. Observe that content-length in HTTP response doesn't match to the actual amount of text
5. Observe that CURL "hangs" (it waits for more data)

**Comment by miguelatvaadin** [comment]
Hi @fluorumlabs ,

could you please provide versions?

Thanks

**Comment by fluorumlabs** [comment]
I think all versions of Flow are affected, but I tested only in LTS and V20

**Comment by miguelatvaadin** [comment]
Great. Thanks, @fluorumlabs

**Comment by denis-anisimov** [comment]
There is indeed weird behavior of URLConnection for file (FileURLConnection) for a directory.
See e.g. here https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/sun/net/www/protocol/file/FileURLConnection.java
The length is set inside the `initializeHeaders` method.

I see this is as a bug inside `FileURLConnection`: I'm not aware of its impl and should not be aware of it.
There is a contract of `URLConnection::getContentLengthLong` and it should just work.
If it's not able to give a length for the directory URL then it shouldn't either handle the directory at all or throw an exception on calling `getContentLengthLong`. 
Since it gives the directory listing it's the responsibility of the implementation to give the correct length (since it's not the length of the `File` as a directory).

But this is a bit offtopic. The bug is there and we have to handle this somehow.
In fact I would do here only one thing : add a javadocs for the `ResponseWriter` that it doesn't work for the URL which is directory.
Vaadin should not just list the files in the directory at all.
There is already a ticket for that : https://github.com/vaadin/flow/issues/11047
It's going to be fixed soon.
The only place which uses `ResponseWriter` is the `StaticFileServer`.  Since there is no way to invoke `ResponseWriter`  except via  `StaticFileServer` it will be fixed along with #11047.

We may add a check whether the URL is a directory or not similar to #11047 but that will be excessive double-check and I don't think it's worth to do it.

So : I'm going to add just a javadoc warning to the `ResponseWriter` and that's it. `ResponseWriter` is an internal class and it should be enough.

**Comment by fluorumlabs** [comment]
The proposed solution of adding JavaDoc comment sounds good.
