### ISSUE TITLE
SPIKE: investigate enabling @PreserveOnRefresh on UIs

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#11045]
Related to https://github.com/vaadin/flow/issues/6395.

The target is to figure out if it is possible to just enable users to have their `MyCustomUI extends UI` or `MyCustomUI extends JavaScriptBootstrapUI` and apply `@PreserveOnRefresh` on that, to be able to achieve the same behavior as in Vaadin 7 or 8, to be able to migrate "more easily" and to be able to preserve any `@UIScope(d)` beans for Spring and CDI.

It should be still possible to retain the existing code - there is no need to have a custom UI and the `@PreserveOnRefresh` can be still applied to the root layout.

**Comment by denis-anisimov** [comment]
It is possible to specify the custom `UI` via init parameter _IF_ old V14 bootstrap mode is used.
E.g. skeleton starter project may be used to do this, just add a custom servlet and a custom UI class:

```
@WebServlet(value = "/*", initParams = {
        @WebInitParam(name = InitParameters.UI_PARAMETER, value = "org.vaadin.example.MyUI"),
        @WebInitParam(name = SERVLET_PARAMETER_USE_V14_BOOTSTRAP, value = "true") })
public class MyServlet extends VaadinServlet {

}
public class MyUI extends UI {

    public MyUI() {
        System.out.println("custom UI is created");
    }
}
```

That works.
So if we attach the `@PreserveOnRefresh` annotation for the custom `UI` class then we can apply preserve on refresh functionality which preserves the `UI` instance  (instead of some component).

That's theoretically since Flow `@PreserveOnRefresh` is much simpler than its implementation in V8 which allows to preserve the `UI` instance. `@PreserveOnRefresh` in Flow is a part of routing which just preserves the navigation chain.
`@PreserveOnRefresh` in V8 requires 2 steps bootstrap to be able to get the window name first and than using the window name use the proper `UI` instance if it exists.

See the https://github.com/vaadin/framework/blob/e30226a19564c6ee77064e5178a7665554d57466/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L127 which initializes the `UI` (and is a replacement for Flow `BootstrapHandler`).
and https://github.com/vaadin/framework/blob/e30226a19564c6ee77064e5178a7665554d57466/server/src/main/java/com/vaadin/server/BootstrapHandler.java which is the first response step on the very initial client request.

So to be able to support `@PreserveOnRefresh` on `UI` level we need dramatically redesign the bootstrap in Flow which I consider as quite dangerous change. So there should be essential reasons why we need this: the price is quite high.

Another issue is : without V14 bootstrap mode it's not possible to override the UI at all.
`JavaScriptBootstrapHandler` (and `IndexHtmlRequestHandler` which doesn't override the behavior anyhow) passes hardcoded `JavaScriptBootstrapUI.class` as a `UI` class and it doesn't read it from the deployment config anyhow.
We may change this : via reading the deployment configuration (and check whether the class is subclass of `JavaScriptBootstrapHandler`) but this is needs to be discussed: do we need this at all (do we want to support `@PreserveOnRefresh` for non V14 bootstrap and complicate the choice of `UI` class to extend).

So there are only technical details to support `@PreserveOnRefresh` on `UI`. level. It's possible to use it from the user's point of view: everything is already there.
The challenge is only the implementation.
