### ISSUE TITLE
PolymerTemplate converts properties from number to string.

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#11175]
In Vaadin 14.6.1, the type of a number-typed property that had been initialized from an attribute in the JS template, will be converted to `string` when the component is bound with `@Id` in a PolymerTemplate. In Vaadin 14.4.10 the type of the property was not modified.

Observed behavior: (Vaadin 14.6.1) 
- The property `min` of `field1` has type `string`
- The property `min` of `field2` has type `number`

Expected behavior: (Vaadin 14.4.10) 
- The property `min` of `field1` has type `number`
- The property `min` of `field2` has type `number`

```
class TestElement extends PolymerElement {
static get template() {
	return html`
		<vaadin-number-field id="field1" step="0.2" min="0" max="10" has-controls></vaadin-number-field>
		<vaadin-button on-click="test1">Test me</vaadin-button>
		<br>
		
		<vaadin-number-field id="field2" step="0.2" min="0" max="10" has-controls></vaadin-number-field>
		<vaadin-button on-click="test2">Test me</vaadin-button>
		<br>		
	`;
	}
	
	static get is() { return 'test-element'; }
	
	test1() { alert(typeof this.$.field1.min); }
	test2() { alert(typeof this.$.field2.min); }	

}
```

```
@Tag("test-element")
@JsModule("./test-element.js")
@Route("test")
public class TestTemplate extends PolymerTemplate<TemplateModel> {

  @Id("field1")
  private NumberField field1;

  public TestOne() {}
}
```

The actual effects on a component depends on its implementation. It doesn't seem to cause issues with `vaadin-number-field` itself, but other components such as `paper-slider` present incorrect behavior because of this issue:

```
<!-- bound as @Id("slider"), doesn't work because step is "1" (string) -->
<paper-slider id="slider" min="0" max="100" step="1" editable snaps></paper-slider>

<!-- not bound with @Id, work as expected because step is 1 (number)-->
<paper-slider min="0" max="100" step="1" editable snaps></paper-slider>
```

**Comment by denis-anisimov** [comment]
This is technically not a regression : the same can be seen in any version with different steps to reproduce (see below).
This specific issue is just one more aspect of https://github.com/vaadin/flow/issues/3735.

The template object become immediately "broken" just because the property values are set from the server side as String values because of #3735.
In previous versions there was no automatic initial properties set so it "worked" as expected.
In fact I don't see why things are broken at all since it's a JS with dynamic types and anything can be casted to anything.
So `"0"` has the same value `0` and it should not cause the problems.
Apparently it's a JS component which for some reasons have an explicit check for type.

Anyway, I will make a workaround for this specific case on the client side engine.

But as I said: there is another way to do the same thing manually in any version.

The correct template is :
```
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {html} from '@polymer/polymer/lib/utils/html-tag.js';

class TestElement extends PolymerElement {
static get template() {
    return html`
        <vaadin-number-field id="field1" step="0.2" min="0" max="10" has-controls></vaadin-number-field>
        <vaadin-button on-click="test1">Test me</vaadin-button>
        <br>
        
        <vaadin-number-field id="field2" step="0.2" min="0" max="10" has-controls></vaadin-number-field>
        <vaadin-button on-click="test2">Test me</vaadin-button>
        <br> 
        <slot>       
    `;
    }
    
    static get is() { return 'test-element'; }
    
    test1() { alert(typeof this.$.field1.min); }
    test2() { alert(typeof this.$.field2.min); }    

}

customElements.define(TestElement.is, TestElement);
```

The java class is:
```
@Tag("test-element")
@JsModule("./test-element.js")
@Route("test")
public class TestTemplate extends PolymerTemplate<TemplateModel>
        implements HasComponents {

    @Id("field1")
    private NumberField field1;

    public TestTemplate() {
        NativeButton button = new NativeButton("Set min value",
                event -> field1.getElement().setProperty("min", "0"));
        add(button);
    }
}
```

Now after the "Set min value" button click the type of the value on the client side will be "String" in any version.

**Comment by javier-godoy** [comment]
Thanks for the fix. I wasn't aware the behavior I considerd "expected" was actually undefined.

> In fact I don't see why things are broken at all since it's a JS with dynamic types and anything can be casted to anything.
So "0" has the same value 0 and it should not cause the problems. 
> Apparently it's a JS component which for some reasons have an explicit check for type.

Not only that case. Type coercion to number doesn't take place when the operand is `+` , thus `"0" + 0` is `"00"` while `"0" + 0` is `0` (and of course `"0" + "0"` is `"00"` too, but `"0"-"0"` isn't). Those scenarios seem more plausible than explicit checks.
