### ISSUE TITLE
More and more Spring applications started in parallel

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11215]
```
vaadin init --pre v21-test
cd v21-test
mvn
```

Wait until server is started and do
```
touch target/classes/banner.txt
```

Server restarts (expected) and recompiles the frontend (unexpected).

Do the same again
```
touch target/classes/banner.txt
```

The application is started two times as shown by the message appearing twice
```
 [  restartedMain] com.example.application.Application      : Starting Application using Java 16 
```
Frontend recompilation messages are output 4 times.

Do the same again
```
touch target/classes/banner.txt
```

The application is started three times as shown by the message appearing three times
```
 [  restartedMain] com.example.application.Application      : Starting Application using Java 16
```
Frontend recompilation messages are output 6 times.

Vaadin 21 alpha 4

**Comment by pleku** [comment]
I'm not able to reproduce the same behavior on Windows 10 running AdoptOpenJDK 11.0.11.

What I see is basically #11214 instead, with two startups and two frontend complition happening every time even when changing Java file.

**Comment by mshabarov** [comment]
I wasn't able to reproduce this issue with the following configuration:
Vaadin 21.0.0.alpha4
Mac OS
AdoptOpenJDK 8

**Comment by denis-anisimov** [comment]
Spring tries to start the application again and again indeed.
But frontend recompilation is done every time on `touch` _once_.

So it's only about starting several instances of Spring.

**Comment by denis-anisimov** [comment]
Update: 
when I run the project exactly as it's described in the steps to reproduce I get some `ClassNotFoundException` for some dev mode class.

But application is still able to run and works somehow. Then I can see that Spring indeed tries to load the application several times (from scratch, meaning that spring dev tools don't reload the app but it's instead initialized and tries to occupy a port).

Since I don't want to see the exception and it may cause some side effects I did:
- remove extra dependency from the pom file:
```
<dependency>
            <groupId>org.vaadin.artur</groupId>
            <artifactId>a-vaadin-helper</artifactId>
            <version>1.6.2</version>
        </dependency>
```
- remove the code which uses this dependency from the `Application`: `LaunchUtil.launchBrowserInDevelopmentMode` and its related import.

Now start the application in the same way via `mvn` command.

The result is:
- I'm not able to reproduce the issue anymore.
- There is frontend compilation every time on `touch` and may be this is unexpected but this is not a blocker and it's a different issue if any.
- There is an app restart but this restart is a Spring dev tools restart (without an attempt to start the app from scratch with occupying the port).

Based on attempts from others I assume that they cannot reproduce this issue because they use plain normal starter project without extra `LaunchUtil` class. That may be the cause why everything works as it should.

So I suggest:
- someone else should try the same steps to reproduce and remove irrelevant `LaunchUtil` class usage.
- in case everything is fine the reason of the behavior is extra `a-vaadin-helper` dependency which is broken.
- I don't know whether this dependency is completely initially broken or it's broken because of the exception which I get but I'm pretty sure it's the cause of the issue.
- in case this is confirmed the ticket should be closed as invalid.

**Comment by Artur-** [comment]
Interesting find. Does this mean that if you throw an exception from `main` then Spring will start a new instance in addition to the one already running?

**Comment by Artur-** [comment]
It does indeed mean that, example here https://github.com/Artur-/springboot-main-exception/blob/master/src/main/java/com/example/demo/DemoApplication.java

It is not an issue in Flow

**Comment by Artur-** [comment]
Created https://github.com/spring-projects/spring-boot/issues/26894
