### ISSUE TITLE
Package.json is being modified by TaskCreatePackageJson even though no changes are needed

### ISSUE THREAD

**Issue by lladnik** [vaadin/flow#11259]
I'm using package.json with "\r\n" newline characters. After maven vaadin:prepare-frontend step is run, newline characters are changed to "\n". That's the only change applied to package.json. It seems unnecessary.

It seems, that this code is responsible for this:
![image](https://user-images.githubusercontent.com/26218463/122260173-3ce51700-ced3-11eb-9dc1-d4bcc33a3675.png)

- Vaadin / Flow version: 14.6.3
- OS version: Windows 10

**Comment by caalador** [comment]
#10081 fixed an issue with FW defaults not getting actually written to the package.json making the dependencies out of sync and not updating correctly.

`\n`  is used by the used libraries instead of `\r\n`  is there a specific need to actually use the windows End Of Line when the file is system managed?

**Comment by lladnik** [comment]
This change of EOL signs is treated by git as a package.json change. That's confusing when somebody is using "autocrlf = true" setting in git.
