### ISSUE TITLE
Navigating via Javascript/window.location.href doesn't work

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow#11268]
Take any starter from https://vaadin.com/start, in the HelloWorldView add the code below for a simple button to do a navigation on click as described in the [documentation](https://vaadin.com/docs/v14/flow/advanced/tutorial-application-lifecycle#application.lifecycle.session-closing).

```
        Button button = new Button("Logout", event -> {
            UI.getCurrent().getPage().executeJs("window.location.href='http://www.myurl.foo'");
            UI.getCurrent().getSession().close();
        });
        add(button);
```

Now, on clicking an attempt at navigation happens but fails with NS_BINDING_ABORTED in the browser's network tab and the original page gets reloaded.
Executing the above script in the console works as expected.

Workaround: Use `UI.getCurrent().getPage().setLocation("http://www.myurl.foo");` instead.

Tested with Oracle Java 1.8.0_131, Vaadin 14.6.3 and 20.0.3, Chrome 91.0.4472.106, Firefox 89.0 on MacOS 10.14.6

**Comment by caalador** [comment]
To have it work the JavaScript should now be `UI.getCurrent().getPage().executeJs("this.stopApplication(); window.location.href='http://www.myurl.foo';");`

Also it would work without the getSession().close(), but then you can return to the old session with the back button.

**Comment by denis-anisimov** [comment]
This is a known issue and we can't do anything with that: the client application should be stopped before location is set.
As @caalador mentioned the correct way is either call `this.stopApplication();` before setting the location in your JS or use
ready made API `Page::setLocation` which  does this for you.

So I'm closing the ticket since we can't do anything with that: just use the proposed workarounds.
