### ISSUE TITLE
Do not sort main keys in package.json

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11294]
### Description of the bug / feature
Please do not touch the main keys of `package.json`. The order that `npm init` creates the keys is just fine, you should not sort those alphabetically. `npm install` also only sorts the dependencies, I have never seen it change the other parts of `package.json`

This has apparently been introduced as a side effect of #7431 

### Minimal reproducible example
```
vaadin init --pre packagejson
cd packagejson
mvn
```

### Expected behavior
The `name` field should still be first in `package.json`

### Actual behavior
The `name` field is moved below `dependencies` and `devDependencies`

### Versions:
    - Vaadin / Flow version: 21 alpha 7

**Comment by pleku** [comment]
So apparently any top level keys should be left unsorted, only the objects that contain the dependencies should be sorted by #7431 https://docs.npmjs.com/cli/v7/configuring-npm/package-json

**Comment by denis-anisimov** [comment]
>So apparently any top level keys should be left unsorted, only the objects that contain the dependencies should be sorted by

I don't understand this comment

Does it mean that `dependencies` can be at any place ? Does it mean that `devDependencies` can be at any place ?

**Comment by denis-anisimov** [comment]
This is again is not description of the task.
This is an example.

The `package.json` can be  created in many ways: I can create it manually, I can generate it using `npm` , Flow generates it.

In every such case the order will be different , different keys will be in the file.

The ticket #7431 complains that `vaadin` key sometimes may be before `dependencies` .

The main problem for some reason with the tasks is not a technical solution but the absence of the exact description what should be done. Apparently I have to write the exact task description instead of the reporter:

- don't sort any key inside the main/root Json object except: `vaadin` should be _last one_.
- sort keys inside `dependencies`, `devDependencies`, `vaadin` objects

is this the expected behavior which we can agree on ?

I strongly dislike the situation when the developer has to write the exact description of the task instead of the reporter but apparently this needs to be done now for every ticket.

**Comment by pleku** [comment]
> is this the expected behavior which we can agree on ?

Otherwise seems OK, but in case the `vaadin` key is already present, and the developer adds another top level key after it, I think flow should not move the `vaadin` key to be after it as this is again an unnecessary change.

> I strongly dislike the situation when the developer has to write the exact description of the task instead of the reporter but apparently this needs to be done now for every ticket from now on.

It is the responsibility of the developer who makes the fix to understand what he is fixing and how it should be fixed. This is regardless of what the reported has written or has not written. Also the reviewer of the code needs to double check this when making the review code - not just look at the code. In case there is no clarity on the fix or report is too obscure, we take the time to discuss or ask for details.

**Comment by denis-anisimov** [comment]
>It is the responsibility of the developer who makes the fix to understand what he is fixing and how it should be fixed. 

yes, and this is a responsibility of the reporter to make description so that the fix is done according to the expectation.
The fix for #7431 is done based on the description in the ticket.

>Also the reviewer of the code needs to double check this when making the review code - not just look at the code. In case there is no clarity on the fix or report is too obscure, we take the time to discuss or ask for more details.

Apparently this is failing and I would say this is impossible. The reality is incompatible with this wish.

Several hours spent on clarifying the ticket: that's the reality.
