### ISSUE TITLE
NullPointerException in LookupServletContainerInitializer 

### ISSUE THREAD

**Issue by mariokoehler** [vaadin/flow#11398]
### Description of the bug / feature

I'm using Arquillian for Unit Tests that require CDI. When the Payara embedded container boots up in Arquillian, apparently some Vaadin classes (namely com.vaadin.flow.server.startup.LookupServletContainerInitializer) are activated, because they are on the classpath, allthough the Arquillian tests themselves do not test any Vaadin components. We do use Vaadin for our UI, thats why the classes are on the classpath, but again, we don't do any unit tests on any Vaadin classes or components.

This then leads to a null pointer exception:

Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.process(LookupServletContainerInitializer.java:64)

That is this line of code:

        if (!classSet.contains(LookupInitializer.class)) {

apparently the "classSet" variable here is null (verified via debugger) and causes this.

I'm not familiar enough with the inner workings of all of this, but I have a hunch that this is an oversight, because the rest of the process() method seems to be fine with a null value for classSet. It even checks explicitly for null and handles it (e.g. inside of collectSubclasses()->filterSubClasses() that is called as part of the process() method)

### Minimal reproducible example
have Vaadin on the classpath, boot up Arquillian with an Payara embedded container

### Expected behavior
I suspect if the null value would be handled correctly, the rest of the method would be fine and the container would boot up. 

### Actual behavior
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.startup.LookupServletContainerInitializer.process(LookupServletContainerInitializer.java:64)

### Versions:
    - Vaadin / Flow version: 20.0.3
    - Java version: 11
    - OS version: Windows 10
    - Browser version (if applicable): n/a
    - Application Server (if applicable): Payara 5.2021.4 Embedded within Arquillian
    - IDE (if applicable): Eclipse 2021-03 (4.19.0)

**Comment by denis-anisimov** [comment]
>I'm not familiar enough with the inner workings of all of this, but I have a hunch that this is an oversight, because the rest of the process() method seems to be fine with a null value for classSet. 

It's possible that the `LookupServletContainerInitializer` class is able to deal with the `null`  `classSet` .
The problem is : the will break the whole application completely even though there will be no NPE inside `LookupServletContainerInitializer`.

`LookupServletContainerInitializer` is `ServletContainerInitializer` . The latter interface is a part if Servlet 3.0 specification which is REQUIRED to use Vaadin. Vaadin Flow framework doesn't work if Servlet container doesn't support Servlet 3.0 specification .

`ServletContainerInitializer` declares a number of classes via `@HandlesTypes` annotation and (at least) their subclasses from the classpath has to be passed via `onStartup` (or `process` which is called from `onStartup` directly)  .
This is a part of  Servlet 3.0 specification .

It might be that `classSet` may be `null` indeed : ONLY if there are no eligible classes.
BUT `AbstractLookupInitializer` is one of the interface declared in `@HandlesTypes` for `LookupServletContainerInitializer`.
And `LookupInitializer` is the class that implements `AbstractLookupInitializer` and  it's in the classpath of the application since it's inside `flow-server` module.

So : 
- IF servlet container supports Servlet 3.0 specification then `classSet` may not ever be `null` .
- If it doesn't support Servlet 3.0 then `LookupServletContainerInitializer` shouldn't be called at all

We have some cases when  Servlet 3.0  is not completely supported. In these cases we have something else which does job of  `LookupServletContainerInitializer` or it's called in other way.

But if `LookupServletContainerInitializer` is called but it gets `null` then something is totally broken in the application setup or it's deployed into Servlet 3.0 incompatible container.

`LookupServletContainerInitializer`  logic has to be executed: it initializes a `Lookup` application instance which is vital part of the framework: everything will be broken without the `Lookup` .

We have tests for CDI in CDI repository which uses Arquillian : https://github.com/vaadin/cdi/ and they work fine.

**Comment by mariokoehler** [comment]
Thank you for the explanation. I'll investigate the Arquillian setup then.

**Comment by markusweisssiemens** [comment]
Hi @mariokoehler , did you find a solution in the end because we face the same problem with Vaadin 23 now also?

**Comment by markusweisssiemens** [comment]
I also have to admit that for me this is still a bug, because only by adding one Vaadin dependency to my project all of my Arquillian Tests for my business logic immediately fail with:

> Caused by: javax.servlet.ServletException: ServletContainerInitializer is called but the provided set of classes is 'null'. class com.vaadin.flow.di.LookupInitializer should always be present and has to be passed to the 'onStartup' method as an argument in the set of classes if the servlet container supports Servlet 3.0 specification

**Comment by markusweisssiemens** [comment]
[skeleton-starter-flow-cdi-23.zip](https://github.com/vaadin/flow/files/11596862/skeleton-starter-flow-cdi-23.zip)
Hello @mcollovati ,

sure. Attached you find a very small test project based on the current starter project from the Vaadin page.

Thank you 
Markus

**Comment by mcollovati** [comment]
Hi @markusweisssiemens, I would say the problem may be in arquillian or the payara module or the test configuration because when the test starts the servlet container, it finds the `LookupServletContainerInitializer` in the classpath, but then it does not find the and cannot scan the jars for types expected by the initializer.
