### ISSUE TITLE
Vaadin depends on Apache FileUtils which is not supplied with TomCat

### ISSUE THREAD

**Issue by michael-newsrx** [vaadin/flow#11413]
### Description of the bug / feature
Unable to use Tomcat as servlet container with gretty

It looks like the Vaadin component is depending on the 3rd party dependency Apache FileUtils which only appears to be available when using Jetty. Either a) Vaadin needs to declare this dependency in it's module or whatever, or b) create the directory structure needed with out using a 3rd party lib

### Minimal reproducible example
Create a flow/fusion project version 20.0.4
Add a gretty block similar to:

```gradle
gretty {
	servletContainer = "tomcat9"
	
	consoleLogEnabled = true
	fileLogEnabled = true
	loggingLevel = "ALL"
	logDir="$projectDir/log"
}
```
 
### Expected behavior
Servlet should serve content.

### Actual behavior
Vaadin fails to start with a no such method error.

```bash
2021-07-13 14:18:17.163 ERROR 327129 --- [nio-8080-exec-5] c.v.flow.server.DefaultErrorHandler      : 

java.lang.IllegalStateException: java.lang.NoSuchMethodError: 'void org.apache.commons.io.FileUtils.forceMkdirParent(java.io.File)'
        at com.vaadin.flow.server.DevModeHandler.getCause(DevModeHandler.java:273) ~[flow-server-7.0.4.jar:7.0.4]

```
### Versions:
    - Vaadin / Flow version: 20.0.4
    - Java version: 11
    - OS version: 20.10
    - Browser version (if applicable):
    - Application Server: Tomcat 9 via Gretty 3.0.4
    - IDE: Eclipse

**Comment by knoobie** [comment]
Related to https://github.com/vaadin/flow/pull/11224

**Comment by denis-anisimov** [comment]
>Create a flow/fusion project version 20.0.4
>Add a gretty block similar to:

Where this block should be added ?

Here is example Flow project : https://github.com/vaadin/skeleton-starter-flow
I don't see where should I add the block .

I may assume that this issue is related to gradle plugin.
But anyway : the steps to reproduce should not assume any implicit context. 
Please describe how I can make a project and run it.

Flow server declares explicit dependency to `commons-io` library :  https://github.com/vaadin/flow/blob/master/flow-server/pom.xml#L101 (this library has `FileUtils` class)

So you have either a version collision or something else which may not be identified with the exact project.

**Comment by michael-newsrx** [comment]
This appears to be some sort of conflict in our setup between gretty and spring boot. We've dropped gretty and are just using spring boot run for now.
