### ISSUE TITLE
Implement Vaadin Externalized Session (HA) with Spring Session and Redis

### ISSUE THREAD

**Issue by SomboChea** [vaadin/flow#11470]
### Description of the bug / feature
Components that using: @Push, @PreserveOnRefresh and AppLayout always reload after session was created and refresh again the page view always auto reload never end.

### Minimal reproducible example
```kotlin
@Push
@PreserveOnRefresh
@Route("/", layout = AppLayout::class)
class HomeView : Div() {
    init {
        add("Home View")
    }
}
```

```gradle
implementation("org.springframework.boot:spring-boot-starter-data-redis")
implementation("org.springframework.session:spring-session-data-redis")
```

### Expected behavior
Implement Vaddin High Availability with Spring Session and Redis as Externalized

### Actual behavior
Externalized session work with other components without session, but not work with @Push, @PreserveOnRefresh and AppLayout and relates to UI Session. And UI's components that including @Push, @PreserveOnRefresh and AppLayout always reload after session was created (Need to refresh browser after session created).

### Versions:
    - Vaadin / Flow version: 14.6.5
    - Java version: 11
    - OS version: Ubuntu 20.04.2 LTS (5.8.0-63-generic)
    - Browser version (if applicable): Google Chrome 91+
    - Application Server (if applicable): Spring Boot 2.5.3
    - IDE (if applicable): IDEA 2021

### References
- Previous issue: https://github.com/vaadin/flow/issues/7462
- Vaadin Microservices HA: https://vaadin.com/blog/microservices-high-availability

**Comment by denis-anisimov** [comment]
Sorry, I don't understand the issue.

First of all : I'm not familiar with Kotlin.
Please use https://github.com/vaadin/skeleton-starter-flow or https://github.com/vaadin/skeleton-starter-flow-spring as a project base.

`Expected behavior` may not be an action like "Implement something". It should be a short description of what I can see _as a result of action_. And the action should be described in the steps to reproduce.

`Actual behavior` should be also a result of action. Short description of what I can see in the result of steps to reproduce.
In your case it's "Externalized session work" (and then a lot of text which doesn't relate to the behavior but it's an explanation).

So please follow the ticket template: 
- detailed steps to reproduce as actions
- expected behavior which I can see in the case when everything works as expected
- actual behavior which I can see as a result of steps to reproduce.

Other issues: 
- it mentions Spring. So is it a Spring add-on related issue ? This is the repo for Spring add-on: https://github.com/vaadin/spring
- it mentions `ApplicationLayout`. Is this an important detail? Can you reproduce this without `ApplicationLayout` , e.g. `Div`. is a simplest HTML container which can be used as a layout. Can you reproduce it with Div (or something which extends `Div`)? If you can't reproduce it with `Div` then it's `ApplicationLayout` issue . Here is the repo for  it: https://github.com/vaadin/flow-components/tree/master/vaadin-app-layout-flow-parent

So it might be that this is a wrong repo for the issue: please use a correct one.

You can find a very good ticket description here: https://github.com/vaadin/flow/issues/11260 . Please use it as an example.

**Comment by SomboChea** [comment]
Thank you @denis-anisimov!

**Comment by Legioth** [comment]
The core issue here is most likely that the whole idea of using Spring Session and Redis with Vaadin has turned out to be a fragile approach. It might appear to work at first but it doesn't hold up for actual usage since there isn't anything that prevents multiple concurrent requests from making conflicting changes to the session state.
