### ISSUE TITLE
Build info on classpath overrides parameters set in web.xml

### ISSUE THREAD

**Issue by rudiejd** [vaadin/flow#11479]
### Description of the bug / feature
When using DevModeInitializer to get classes from annotations, a flow-build-info.json found on the classpath will override parameters set in web.xml.

Here's the code in question (DeploymentConfigurationFactory.java): 

```
  protected static Properties createInitParameters(
              Class<?> systemPropertyBaseClass, VaadinConfig vaadinConfig)
              throws VaadinConfigurationException {
          Properties initParameters = new Properties();
          readUiFromEnclosingClass(systemPropertyBaseClass, initParameters);
          readConfigurationAnnotation(systemPropertyBaseClass, initParameters);
  
          // Read default parameters from server.xml
          final VaadinContext context = vaadinConfig.getVaadinContext();
          for (final Enumeration<String> e = context.getContextParameterNames(); e
                  .hasMoreElements();) {
              final String name = e.nextElement();
              initParameters.setProperty(name, context.getContextParameter(name));
          }
  
          // Override with application config from web.xml
          for (final Enumeration<String> e = vaadinConfig
                  .getConfigParameterNames(); e.hasMoreElements();) {
              final String name = e.nextElement();
              initParameters.setProperty(name,
                      vaadinConfig.getConfigParameter(name));
          }
  
          readBuildInfo(systemPropertyBaseClass, initParameters,
                  vaadinConfig.getVaadinContext());  // this overrides config from web.xml, for example the frontend folder setting
          return initParameters;
      }

```

### Minimal reproducible example

Create two dependent projects in eclipse, build one then try to build the other. DevModeInitializer will override parameters in the second project if the flow-build-info.json for the first one is on the classpath. 

### Expected behavior

web.xml parameters should override any existing flow-build-info.json on the classpath

### Actual behavior
parameters from an existing flow-build-info.json on the classpath override those set in web.xml

If this is intended behavior, feel free to close. Otherwise, I can submit a PR changing the order, because I think that might make more intuitive sense for users. Right now, we have to delete the flow-build-info.json for our dependent, standalone Vaadin project so that we can compile a second project that uses the first as a dependency. 

### Versions:
    - Vaadin / Flow version: 14.6.5
    - Java version: OpenJDK 8
    - OS version: Manjaro
    - Browser version (if applicable): N/A
    - Application Server (if applicable): Jetty
    - IDE (if applicable): Eclipse

**Comment by denis-anisimov** [comment]
There are two notes here:
- not all the properties are overridden. Most of properties are from  the token file if they are available there. E.g. dev mode properties are set from the token file only if they are not yet set as init parameters. See `setDevModePropertiesUsingTokenData` method.
- To be able to read the token file `PARAM_TOKEN_FILE` init property should be read first ( see `getTokenFileContents` : the token file may be specified via init parameter).

I don't know whether this is an intentional behavior or not since I'm not the author of the token file reading.
But I think you are right that the init parameters should take precedence over token file.
So the "order" should be : 
- set properties based on token file
- set properties based on init parameters
This can be done either via reading the token file first (but again: token file may be specified via init parameter) and then read init parameters.
Or it can be done via checking property availability inside `setInitParametersUsingTokenData` as it's done inside `setDevModePropertiesUsingTokenData` .

Please feel free to make a PR. I think it will be valuable definitely .

**Comment by rudiejd** [comment]
@denis-anisimov Submitted the PR. I just checked whether the property was already set in the private `readBuildInfo` helper, and that was enough for my specific case. I added a unit test to capture this behavior as well.
