### ISSUE TITLE
BrowserDetails.isIPhone() is false for Firefox on iPhone

### ISSUE THREAD

**Issue by kyberorg** [vaadin/flow#11514]
### Description of the bug / feature
If I visit my website from Firefox on iPhone 7 `isIPhone()` method of `BrowserDetails` gives false. For Chrome and Safari on the same iPhone7 it gives `true` as should be.

It reports following User-Agent string:
```
mozilla/5.0 (macintosh; intel mac os x 10_15_4) applewebkit/605.1.15 (khtml, like gecko) version/13.1 safari/605.1.15
```

### Minimal reproducible example
```
public static boolean isIPhone(final WebBrowser webBrowser) {
        return webBrowser.isIPhone();
}
```
### Expected behavior
I except that `isIPhone()` method of `BrowserDetails` gives true, even when I visit from Firefox on iPhone.

### Actual behavior
Currently it return `false`

### Versions:
    - Vaadin / Flow version: Vaadin version: 14.5.3 (Flow: 2.5.3)
    - Java version: 11 (openJ9)
    - OS version: ArchLinux (Server)/iPhone 7 (client)
    - Browser version (if applicable): Firefox 35.0 for iOS
    - Application Server (if applicable): Undertow
    - IDE (if applicable): IDEA

**Comment by denis-anisimov** [comment]
Do you have any idea how to identify IPhone from the user agent string which you mentioned ?
`
mozilla/5.0 (macintosh; intel mac os x 10_15_4) applewebkit/605.1.15 (khtml, like gecko) version/13.1 safari/605.1.15
`
This string looks like a regular Desktop computer identifier rather than mobile device browser.
May be it's just a bug in the browser ?

Anyway: I don't see how we may say that this User Agent belongs to a browser running on IPhone.

**Comment by kyberorg** [comment]
No idea honestly. 
I checked that Firefox at MacOS User-Agent haven't "applewebkit", but Firefox on iPhone has. Maybe this helps

**Comment by kyberorg** [comment]
Anyhow, this is Firefox's bug. I reported it https://github.com/mozilla-mobile/firefox-ios/issues/8946. So this one can be closed.

**Comment by denis-anisimov** [comment]
Thank you for proper report and reporting it to the Firefox 
:+1:
