### ISSUE TITLE
Java 16 | Vaadin 20.0.5 | Linux (e.g. Ubuntu 21.04) - production build fails at build-frontend goal

### ISSUE THREAD

**Issue by loadi-dev** [vaadin/flow#11524]
### Description of the bug / feature
When running the production build of a clean flow application a downstream js library fails to build the frontend on linux environments including CI environments using lnux based docker images to build.

Hints: 
* The build is working perfectly fine on my Windows 10 environment when using the same settings.
* The build started to fail on my CI environment yesterday (05.08.2021) in the afternoon. An earlier build was working fine. Due to some caching of artifacts the issue could have been caused earlier.

### Minimal reproducible example
Download a Vaadin starter from start.vaadin.com with the following settings:
* Vaadin 20
* Java 16
* Everything else default
Build the application on a linux environment using java 16 using the production profile (e.g. "mvn package -Pproduction")
### Expected behavior
The build should be successful.
### Actual behavior
Getting an exception during build-frontend:

> 
> [ERROR] Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'
> [ERROR]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
> [ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
> [ERROR]     at Module.require (internal/modules/cjs/loader.js:637:17)
> [ERROR]     at require (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
> [ERROR]     at Object.<anonymous> (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/generate-sw.js:20:33)
> [ERROR]     at Module._compile (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
> [ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> [ERROR]     at Module.load (internal/modules/cjs/loader.js:600:32)
> [ERROR]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> [ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> [ERROR]     at Module.require (internal/modules/cjs/loader.js:637:17)
> [ERROR]     at require (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
> [ERROR]     at Object.<anonymous> (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/index.js:10:20)
> [ERROR]     at Module._compile (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
> [ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> [ERROR]     at Module.load (internal/modules/cjs/loader.js:600:32)
> [ERROR]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> [ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> [ERROR]     at Module.require (internal/modules/cjs/loader.js:637:17)
> [ERROR]     at require (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
> [ERROR]     at Object.<anonymous> (/home/steven.ladewig/Downloads/my-app/webpack.generated.js:10:28)
> [ERROR]     at Module._compile (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
> [ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> [ERROR]     at Module.load (internal/modules/cjs/loader.js:600:32)
> [ERROR]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> [ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> [ERROR]     at Module.require (internal/modules/cjs/loader.js:637:17)
> [ERROR]     at require (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
> [ERROR]     at Object.<anonymous> (/home/steven.ladewig/Downloads/my-app/webpack.config.js:10:22)
> [ERROR]     at Module._compile (/home/steven.ladewig/Downloads/my-app/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
> [ERROR] -> [Help 1]

### Versions:
    - Vaadin / Flow version: 20.0.5
    - Java version: openjdk 16.0.1 | adoptopenjdk 16
    - OS version: Ubuntu 21.04 OR Docker image: maven:3-openjdk-16-slim or maven:3-openjdk-16 or maven:3-adoptopenjdk-16

**Comment by denis-anisimov** [comment]
This is not related to a Linux or any other environment. 
We are working on this: this is an issue in the frontend dependencies.

**Comment by crowstudios** [comment]
We are currently experiencing the same issue.  It might have something to do with a recent update to https://www.npmjs.com/package/workbox-webpack-plugin (6.2.0).

If we use a copy of pnpm-lock.yaml built before workbox-webpack-plugin 6.2.0 was released, Vaadin webpack works.  But new projects or rebuilding after a "vaadinClean" results in failure.

**Comment by skiedrowski** [comment]
this also affects many other environments
here: Vaadin 20+, gradle build, JDK11, macOS/Linux/Windows

**Comment by skiedrowski** [comment]
This issue triggered several concerns regarding the reproducability of our Vaadin builds. Since we've just started using Vaadin there might also be a misunderstanding on our side. 

Lets assume our build currently uses Vaadin 20.0.5 and we have built a release candidate for internal testing. There are no bugs found during internal testing so the next day we're building the final release.
Our assumption so far was that the only change between release candidate and final build is the version number and maybe a build timestamp.

Now this issue shows us that there are changes which seem to be out of our control :-(.
In this case someone created a new release of `workbox-webpack-plugin` and that affected our build quite badly. The problem was easily identified during the build. It would have caused a release delay and it affects developer productivity badly.

How comes that the new release of `workbox-webpack-plugin` failed our build?
Why has this new release been pulled into the project?
What do we need to do to make the build reproducible?

We're currently running `gradle vaadinClean vaadinBuildFrontend` during the build. Would it be advisable to stop using `vaadinClean` except for "we want the latest"? The #issuecomment-894062761 indicates that `pnpm-lock.yaml` could be used to lock the versions.

The Vaadin documentation could use some enhancements regarding generated files, what is generated by which build task and which should be versioned in which cases and why (not). 
One the one hand, Vaadin tries to abstract npm/JavaScript/... but I've got the feeling these questions cannot be ignored.

**Comment by knoobie** [comment]
@skiedrowski the problem comes from gradle's vaadinClean because it clears files (pnpm lock) an other files it shouldn't. That was already discussed today in discord.

**Comment by skiedrowski** [comment]
Workaround mentioned on Stackoverflow (https://stackoverflow.com/questions/68681211):

The recommended workaround until the fix is out is to bump webpack-cli to 3.3.12 and workbox-xxx dependencies to 6.2.0 in the project's package.json.
