### ISSUE TITLE
Do not override custom .npmrc config file

### ISSUE THREAD

**Issue by JustinVoitel** [vaadin/flow#11545]
Currently when importing packages from the `GitHub Packages Registry (GPR)` pnpm is not able to fetch them, because it assumes to find the package under `https://registry.npmjs.org/<PACKAGE>`.
For npm (or pnpm) to find the Package in GPR you need to provide a `.npmrc` file inside of the project with the content of the package registry (e.g `@OWNER:registry=https://npm.pkg.github.com/`). 
Unfortunately Vaadin generates and overrides the content of the file when the dev server starts. Is it somehow possible to stop the autogeneration of the .npmrc file ?

- Vaadin Framework version: 21.0.0.alpha10

**Comment by web-padawan** [comment]
Thanks for the issue. I have moved it to the correct repository and renamed according to the described use case.

**Comment by denis-anisimov** [comment]
Please provide exact steps to reproduce since I'm not able to reproduce this.

There is code which specifically checks the file presence and doesn't override it if it exists: https://github.com/vaadin/flow/blob/8.0/flow-server/src/main/java/com/vaadin/flow/server/frontend/TaskRunNpmInstall.java#L440 

When I run the build with a custom ".npmrc" file which is empty I get 
```
[INFO] Custom .npmrc file (/Users/denis/workspace/skeleton-starter-flow/.npmrc) found in project; pnpm package installation may require passing the --shamefully-hoist flag
```

This is exactly what I expected from the code.

**Comment by JustinVoitel** [comment]
@denis-anisimov Hey thanks for the answer! 
Yea the first time I edited the file I left the auto generated lines at the top, leading to a override. 
I tested it without the lines and it now works as expected :) Might be considerable to document it or add a line something like 
```
#Delete these comments to use your own .npmrc file
```
