### ISSUE TITLE
Webpack compilation fails because of missing 'mkdirp' with latest npm

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11621]
```
2021-08-23 14:57:52.239  INFO 85514 --- [nPool-worker-19] c.v.base.devserver.DevModeHandlerImpl    : Running webpack to compile frontend resources. This may take a moment, please stand by...
node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module 'mkdirp'
```

npm version 7.20.6

Looks like `target/plugins/stats-plugin/stats-plugin.js` depends on `mkdirp` but the project has no dependency for it

**Comment by pleku** [comment]
As `npm` 7.20.6 is not yet even included to any node.js version, it doesn't seem like a big issue.

**Comment by pleku** [comment]
I did `npm i npm@7.20.6` and I got `+  npm: 7.21.0` and I'm not able to reproduce this. I see inside package.json
```json
  /npm/7.21.0:
    bundledDependencies:
...
      - mkdirp
```
It would be trivial to include the dependency as a default devDependency but it seems like it is probably unnecessary @Artur- ?

**Comment by Artur-** [comment]
As a rule of thumb, you should not use anything you do not depend on

**Comment by pleku** [comment]
> As a rule of thumb, you should not use anything you do not depend on

Sure, but as the platform still seems to depend on it (mkdirp) itself, it seems like a bad idea to declare a specific version that we use instead of using the one that is compatible with the platform. Lets see if the tests pass. If yes and we merge it, then it is another question that should it be picked to any existing version or not. There is a potential risk of regressions
