### ISSUE TITLE
Vaadin Starter App not run propaly in IE11 (development and production mode)

### ISSUE THREAD

**Issue by rhonibaer** [vaadin/flow#11713]
### Description of the bug / feature
Downloaded a fresh starter-app, with mostly all demo pages.
only started with "mvnw" and container runs up.
open now localhost:8080 in IE11

### Minimal reproducible example
simple open the app  localhost:8080 in IE11

### Expected behavior
Mostly all components are not rendered correctly. see attachments

### Actual behavior
![screen-1-ie11](https://user-images.githubusercontent.com/26479653/131649637-b9b3b0a3-fc82-477d-9322-18163ca27d8f.PNG)
![screen-2-ie11](https://user-images.githubusercontent.com/26479653/131649652-4e9a050c-8bc8-43a2-abc7-1c9e029d1d28.PNG)

### Versions:
    - Vaadin / Flow version: 14.6.8
    - Java version: Corretto 8
    - OS version: windows 10
    - Browser version (if applicable): IE11
    - Application Server (if applicable): 
    - IDE (if applicable): IntelliJ ultimate

**Comment by mshabarov** [comment]
Judging by the errors in the console, the grid connector (`gridConnector.js`) wasn't initialised/loaded at all.
Is this observed only in IE11?

**Comment by mshabarov** [comment]
I'm able to reproduce it as well. For Card List view, I don't see any type errors, but the components are not rendered at all.
Tried with `mvn -Dproduction` and `mvn -Dvaadin.devmode.transpile=true`.

**Comment by caalador** [comment]
A quick test would say that the new theme feature is not working with IE11.
So a suggestion would be to use `@CssImport` and `@StyleSheet` when targeting IE11

**Comment by caalador** [comment]
I noted that as soon as I added the map view using LeafletMap then no components rendered anymore and the console gets a `SCRIPT1002: Syntax error`.

With the new theme feature there is the console exceptions:
`message"Unable to get property 'appendChild' of undefined or null reference"`, `Could not find style data in module named lumo-spacing` and `SCRIPT5007: Unable to get property 'querySelectorAll' of undefined or null reference`

One issue that comes up with the map is that it is a .ts file which actually is not transpiled, but I can't get a configuration for transpilation of the `@customElement` in the ts file. Else without the theme the components work as they should.

For the ticket view selection I can see that ImageList and CheckoutForm utilise .ts files

So to fix the usage with no theme we should find a way to get the ts files transpiled

**Comment by caalador** [comment]
At the moment to get forward with IE11 development you shouldn't use TypeScript templates and you should theme the application using `@CssImport` and `@StyleSheet` instead of the new CustomTheme feature (as for some reason the polyfill fails to work as it should in IE11).

**Comment by caalador** [comment]
After #11792 is released TypeScript templates should be usable in IE11

**Comment by caalador** [comment]
So the issue with the CustomTheme breaking the application on IE11 is due to `construct-style-sheets-polyfill` doing something which breaks the `webcomponentsjs` polyfills `$0.attachShadow({ mode: "open" })` so that it only returns `$0` when it should return `$0.shadowRoot` meaning that it doesn't create the shadowroot making the polymer execution fail due to a `null`/`undefined` when it calls `$0.shadowRoot.appendChild(...)`

**Comment by caalador** [comment]
There is a fix for using the Custom Theme with IE11, but as it breaks another browser the fix is waiting for a fix to the polyfill.

But at the moment to get IE11 working one can update in package.json the `construct-style-sheets-polyfill` to version `3.0.0` (note. only update it in `dependencies`, but not in `vaadin { dependencies { } }`)
