### ISSUE TITLE
Lumo Utility Classes are not applied in production mode for LitElement "views"

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#11877]
### Description of the bug

Lumo utility classes are not applied in `production` mode in a `flow` project that has a `lit element` as view.

This does NOT happen with `flow` components as view NOR in development mode. In development `lit element` views look good as well.

### Minimal reproducible example

 - Download given [example.zip](https://github.com/vaadin/flow/files/7178334/vaadin-bug.zip); created with start.vaadin.com

 - Build in production mode
 - Open localhost:8080 -> see black heading

### Expected behavior

Lumo utility classes work in `production` mode. (like in development mode)

![image](https://user-images.githubusercontent.com/3968629/133625435-76f81de7-19df-4541-8133-f979f3e820de.png)

### Actual behavior

Lumo utility classes are not loaded / do not work.

![image](https://user-images.githubusercontent.com/3968629/133625526-88c30fc0-ae1c-42a2-bbe2-33eeb75fbfb5.png)

### Versions:
    - Vaadin / Flow version: 21.0.1
    - Java version: ---
    - OS version: ---
    - Browser version (if applicable): Only Tested with Firefox
    - Application Server (if applicable): ---
    - IDE (if applicable): ---

**Comment by Artur-** [comment]
Tried the app with `mvn -Pproduction`. The text is blue as expected.

**Comment by knoobie** [comment]
I just tried again with the example and for me it doesn't work in chrome (93) and firefox (93) on Ubuntu (if that matters)

**Comment by Artur-** [comment]
Ok, it is broken in Firefox (mac)

**Comment by Artur-** [comment]
If you manually call `window.ShadyCSS.CustomStyleInterface.processStyles()`, then it works

**Comment by caalador** [comment]
On windows I at least can replicate with all installed browsers.

**Comment by denis-anisimov** [comment]
I'm not sure whether this is a Flow bug or theming issue (either Flow Lumo integration in https://github.com/vaadin/flow-components repository https://github.com/vaadin/flow-components/tree/master/vaadin-lumo-theme-flow-parent) or even just a lumo client side issue in https://github.com/vaadin/vaadin-lumo-styles.
I spent some time just to understand what "**Lumo Utility Classes**" are.

As I understood this is about `@vaadin/vaadin-lumo-styles/utility.js` module which I cannot even find in the https://github.com/vaadin/vaadin-lumo-styles. But I see it's available in the `node_modules/\@vaadin/vaadin-lumo-styles/utility.js` locally,

I see its import in the `theme-myapp.generated.js`.
Also I see this code there:
```
const shadowRoot = (target instanceof ShadowRoot);
if (shadowRoot) {
injectGlobalCss(getStyleModule("lumo-typography"), target, true);
injectGlobalCss(getStyleModule("lumo-color"), target, true);
injectGlobalCss(getStyleModule("lumo-spacing"), target, true);
injectGlobalCss(getStyleModule("lumo-badge"), target, true);
injectGlobalCss(getStyleModule("lumo-utility"), target, true);
} else if (!document['_vaadinthemelumoimports_']) {
addStyleInclude("lumo-typography", target);
addStyleInclude("lumo-color", target);
addStyleInclude("lumo-spacing", target);
addStyleInclude("lumo-badge", target);
addStyleInclude("lumo-utility", target);
document['_vaadinthemelumoimports_'] = true;
}
```
Apparently the latter block is executed since I see `document['_vaadinthemelumoimports_']` value `true` in the browser.
And it looks like everything is working as coded.
The `addStyleInclude` just adds the `include` block:
```
const addStyleInclude = (module, target) => {
  addCssBlock(`<custom-style><style include="${module}"></style></custom-style>`, true);
};
```

And it really adds it. Once the page is loaded in the very first time I see: 
<img width="418" alt="Screen Shot 2021-09-21 at 9 16 37 AM" src="https://user-images.githubusercontent.com/11425472/134121763-a8e037fd-4a18-4791-bebb-330cf9c3ae32.png">

And the styles are not applied as described in the ticket.
But then if I reload the page then styles become applied but the document header looks differently: the same `include` is "expanded":
<img width="445" alt="Screen Shot 2021-09-21 at 9 16 46 AM" src="https://user-images.githubusercontent.com/11425472/134121952-806138f8-b6b0-4dc5-ad2f-38233d2eae83.png">

I don't know why it happens: is it expected that it should be expanded ?
If it's not expanded from the very beginning then this is a bug in Flow theming.
If the expansion should happen out of the box then this is a bug on the client side theming.
I see a call `registerStyles` internal function inside `utility.js` and might be this is the source of the bug.

Anyway this is an theming issue it's not my are of expertise, so I transfer this to someone who has some knowledge there.

**Comment by knoobie** [comment]
@denis-anisimov Thanks for looking into this! I try to add more context next time; so you don't have to dig through it all. 

FYI: the utility package and the "latest" lumo is available in https://github.com/vaadin/web-components/tree/master/packages/vaadin-lumo-styles

**Comment by denis-anisimov** [comment]
@jouni , could you please take a look at this and give any idea why it may happen ?

**Comment by jouni** [comment]
I’m pretty clueless about these types of issues. I can comment on things in the CSS, but I don't really know where it might go wrong when the style sheet is imported and included on the page.

**Comment by Artur-** [comment]
The cause seems to be really simple here: 

Nobody calls `window.ShadyCSS.CustomStyleInterface.processStyles()` which is the one responsible for expanding `<custom-style>` tags into real style tags.

In development mode it happens to be called through the dev mode detector.
If you e.g. wrap the `<h1>` with `<vaadin-vertical-layout>` then the vertical layout will call it, also in production mode.

Seems like the theme support would need to call it.

**Comment by knoobie** [comment]
Thanks for the help - successfully tested with 21.0.2 :)
