### ISSUE TITLE
Cookies doesn't set to Vaadin Web App from my API (But in Postman it works)

### ISSUE THREAD

**Issue by juferdinand** [vaadin/flow#11977]
### Description of the bug / feature
Cookies doesn't set in Vaadin Web App via API. Postman get my httpOnly Cookie and I can use it in my next request but in Vaadin I get this Cookie not, in my API comes the Error "webReq.request.cookies must not be null"
### Minimal reproducible example
You need an API which set after request was send to API an httpOnly Cookie, in Postman you will see the Cookie and in Vaadin will be this not set. This can you see if you try in next Request to read this httpOnly Cookie
### Expected behavior
Cookie should be set in Vaadin also
### Actual behavior
Error comes from API because the API have the cookie not.
### Versions:
    - Vaadin / Flow version: 14 LTS
    - Java version: 17 (kotlin 1.6)
    - OS version: Windows 10
    - Browser version (if applicable): idk
    - Application Server (if applicable): My PC and I use GraphQL API
    - IDE (if applicable): IntelliJ Ultimate

**Comment by denis-anisimov** [comment]
Hello, thanks for the report. Can you please provide an example project based on https://github.com/vaadin/skeleton-starter-flow that reproduces the issue ? Otherwise there is not much what we can do with this.

**Comment by juferdinand** [comment]
Why you can't do much?

I explained how to error is occured and how it can be reproduced. Problem is it is not Vaadin only, an API based on Spring Boot send an Cookie (if httpOnly or not it don't happend in both). And in Postman I see the cookie and Vaadin the cookie won't be set. I use this for saving my refreshToken of JWT and if it won't be saved in Vaadin it would bad but I think it exists already an solution but in the documentation I don't find anything about this. I can do it also in other way but this is not so easy like this way, this is way I opend the issue.

**Comment by denis-anisimov** [comment]
The issue has to be proven and this is necessary to provide the exact steps to reproduce when you make an issue in the open source project.

If it's a Spring issue please use correct repository : https://github.com/vaadin/spring.
In any case the steps to reproduce are required: we are getting too many incorrect issues which are caused by the user errors and also if/when the issue is fixed the steps to reproduce verifies that the issue can't be reproduced anymore. How otherwise we can be sure that it's fixed?

When you make a ticket there is a placeholder which you should have been read: https://github.com/vaadin/flow/issues/new

It says: 
```
Good quality bug report increases the likelihood to get the bug fixed. A bad quality one will likely be just closed. Please use the following template to report bugs.
```

This ticket doesn't follow the template since it doesn't contain any example but instead some explanation of your point of view.

If you are absolutely sure that there is an issue then you know the code and can just point the place in the code which causes the problem or just can provide the PR by yourself. If so please do it.
Otherwise we need a proof that there is bug.

The reality is : I don't even understand what the issue is about at the moment. Cookies is HTTP Servlet 3.0 spec feature and Vaadin doesn't affect this feature anyhow. So the example is required at least to understand what the ticket is about at all.

**Comment by denis-anisimov** [comment]
Sorry, but until you can provide the code that reproduces the issue, there is nothing that we can do. Until that we consider this an issue specific to your application. Please reopen the issue if you discover a root cause not dependent on your application and can provide the code to reproduce the issue.
