### ISSUE TITLE
@CssImport(themeFor="whatever") is broken in v22

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#12106]
### Description of the bug / feature
This code https://github.com/vaadin/flow/blob/9fa4ed549eae0fac269d593b261a1c65fbe1ac6b/flow-server/src/main/java/com/vaadin/flow/server/frontend/AbstractUpdateImports.java#L74-L82 uses `<custom-style>` and is probably broken with the latest changes. The code does not include the legacy style adapter but still relies on those features. It is strange that no test is failing.

The code should be rewritten to use `registerStyles`

**Comment by miguelatvaadin** [comment]
It's actually working, so I change the severity label. This issue is currently under work

**Comment by miguelatvaadin** [comment]
I have asked the components guys for advise to know which exact client side code should be written from flow.

As soon as we have an answer this class and the associated test could be updated.

I would also add an integration test to verify (by screenshot comparison) that styles are effectively applied.

**Comment by joheriks** [comment]
Looking at the code logic, `<custom-style>` is only used when the `themeFor` parameter is *absent* (when it is present, a `<dom-module>` element is instead created and this works at the moment, but would be better replaced with a `registerStyles` invocation). If the `<custom-style>` wrapper been added originally for [IE11 compatibility](https://cdn-origin.vaadin.com/vaadin-themes/0.2.0/demo/compatibility.html#applying-custom-properties), with [current CSS custom property state](https://caniuse.com/?search=css%20custom%20properties) in supported browsers, it could just be dropped (i.e., instead of adding `<custom-style><style%s>${$css_%d}</style></custom-style>` to `<head>`  we would just add `<style%s>${$css_%d}</style>`).

**Comment by joheriks** [comment]
So are we fine with adding a dependency on `@vaadin/vaadin-themable-mixin` (for `registerStyles`) to Flow?

**Comment by Artur-** [comment]
`registerStyles` is already used in Flow: https://github.com/vaadin/flow/search?q=registerStyles
