### ISSUE TITLE
Weird behavior of VaadinSession.getCurrent().getLocale()

### ISSUE THREAD

**Issue by fgrazi** [vaadin/flow#12203]
I am making localization tests. I moved Portuguese on top of my browser (Chrome) preferences, so that I now have:

1. pt
2. en_US
3. en
4. it

I would expect Vaadin return pt as preferred locale, but Vaadin returns en_US. Well, not always, from time to time (but I am unable, or better have no time) to check when. Sample code to test:
```
private static void checkLocales() {
    List<Locale> locales = new ArrayList<>();
    Iterator<Locale> iter = VaadinService.getCurrentRequest().getLocales().asIterator();
    while (iter.hasNext())
      locales.add(iter.next());
    String myLocales = locales.stream().map(Locale::toString).collect(Collectors.joining(", "));
    log.info("*** Vaadin locale: " + VaadinSession.getCurrent().getLocale() + ". My locales: " + myLocales +
        ". Preferred: " + VaadinService.getCurrentRequest().getLocale());
  }
```

Result in the message:
```
*** Vaadin locale: en_US. My locales: pt, en_US, en, it. Preferred: pt
```

Same result if I use `UI.getCurrent().getLocale()`.

I even suspected that Vaadin used some kind of weight like [Locale lookup](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html) but that wouldn't justify why sometimes return the correct one (pt) and other times the wrong one (em).

Will stick with Request#getLocale for now. Just reporting the issue.

I also see the following message:

The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior

Maybe related? Shall I implement a I18NProvider? If so why not use the request default when no provider is given?

**Comment by caalador** [comment]
Having a quick look at the locale feature as it is now it would seem that it should ALWAYS be `Locale` default `Gets the current value of the default locale for this instance of the Java Virtual Machine.` if no I18NProvider exists that would define provided locales for use.

So with a provider providing the locales the first locale in the request that matches a value in the provided locales list should be picked.
```
    final Locale PORTUGESE= new Locale("pt", "PT");

    @Override
    public List<Locale> getProvidedLocales() {
        return Arrays.asList(Locale.ENGLISH, Locale.ITALIAN, PORTUGESE);
    }
```

**Comment by fgrazi** [comment]
Thanks Caalador. I also noticed and read a [post](https://vaadin.com/learn/tutorials/i18n/i18nprovider) on localization in Vaadin flow. I understand that you can provide a fixed sequences of locales, but this is not how things are expected on the web. What is usual is to query **the preferences defined by client browser**. And this was exactly what Vaadin 7 did. 

Since this is the stardard method to make localization I would expect getLocale would follow it (even because to get the server locale I do not need an UI method).

I also see Vaadin Flow added the I18NProvider. But introduced a second method (`getTranslation`) whose usage not very clear: does Vaadin itself relies on it? For example, I would be tempted to define this bean:

```
  @Bean
  public I18NProvider myLocaleProvider() {

    return new I18NProvider() {
      @Override
      public List<Locale> getProvidedLocales() {
        return Collections.list(VaadinService.getCurrentRequest().getLocales());
      }

      @Override
      public String getTranslation(String key, Locale locale, Object... params) {
        return MessageFormat.format(ResourceBundle.getBundle("app_i18n", 
            locale).getString(key), params);
      }
    };

  }
```

But at this point wouldn't Vaadin try to read its own localization strings from `app_i18n_xx.properties` file?

**Comment by pleku** [comment]
> But introduced a second method (`getTranslation`) whose usage not very clear: does Vaadin itself relies on it?

Vaadin doesn't use it directly for anything. Like described in the tutorial you mentioned @fgrazi, you can choose the implementation behavior yourself (e.g. what to do if key or locale is missing) and it shows how to use it from the code for localizing the components.

> I understand that you can provide a fixed sequences of locales, but this is not how things are expected on the web. What is usual is to query the preferences defined by client browser. And this was exactly what Vaadin 7 did.
Since this is the stardard method to make localization I would expect `getLocale` would follow it (even because to get the server locale I do not need an UI method).

I'm not sure I follow what you're after here. Si when the user opens the UI for the first time, the session is created and Vaadin sets the locale for the session with the code in https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L951 and this locale is used for all opened `UI`s unless set to something else (to session or to `UI`) . In Flow (Vaadin 10+) **the locale is set only if an `I18NProvider` exists** . It matches the locale from the request to the available locales based on the logic here https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L963 and in `LocaleUtil`.

The corresponding code in Vaadin 8 (and probably 7) just always sets the locale to what the request provided https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/server/VaadinService.java#L868

So I guess you're referring to this difference of behavior ? At this point, I cannot recall anymore why we went with this default behavior or using JVM locale instead of request one when there is no `I18NProvider` present. Do you remember @caalador ?

I would be up for changing it for next version so that it work same as Vaadin 8 when there is no `I18NProvider` present.

At the moment @fgrazi you can customize the behavior for any version with e.g. https://vaadin.com/docs/latest/flow/advanced/application-lifecycle/#application.lifecycle.session.init.

**Comment by caalador** [comment]
It has been made according to #2791
But I can't remember any extra details

**Comment by pleku** [comment]
From #2791:
> Automatically choosing the locale based on the request is dangerous in cases when the application has translations for some specific languages, but no defaults.
> We should clean up this to make it always use Locale.getDefault() by default, and then provide a way for application developers to select a locale to use so that they can use something based on the browser's settings if any of those locales are actually supported by the application (or hardcode it to some specific value, or read a cookie, or whatever).

So the reason for the current behavior is that the old behavior was _dangerous_. @Legioth can you please clarify what you meant with that ?
Though now the case is that _request based locale_ is not used even when there are no application translations at all.

**Comment by Legioth** [comment]
"Dangerous" is probably not the right word, sorry about that. A better choice might have been "confusing" or "potentially difficult to use".

The situation I had in mind was for a "typical" application without any translations and all the texts hardcoded in English. If I open that application on my own computer (which only sends English in the request header), then everything would look as expected. If I would instead be on vacation in Mexico and use the same application to quickly check something from a public computer in a hotel lobby, then I would suddenly be faced with date pickers and other automatically localized content in Spanish, which I would have trouble understanding.

If the application would be designed to support both English and Spanish, then it makes sense that it automatically shows a fully Spanish UI if the browser asks for it. In that case the application would most likely also have a language selector that would allow me to switch back to English in case that's what I prefer. An application that isn't designed to support multiple languages would on the other hand not have any language selector and a user that doesn't know how to configure their browser would be stuck with whatever is chosen automatically for them.

**Comment by fgrazi** [comment]
I fully agree that disposing an I18NProvider is a good choice, this way everybody can decide how to rule the language, on the other side I **suggested** to also leave a default implementation that uses the browser setup to decide. This is how Vaadin 7/8 and most Java applications usually work. It is a matter of productivity: you use a framework mecause most things work in the usual way. You can always inject in Spring your provider if you decide so.

Again, just a suggestion. I already wrote my I18NProvider.

The Mexico example is a little unrealistic or dated. First of all, again, it is always possible to inject your provider. Second, do you really think that today with spread usage of tablets and mobile phones somebody will rely on a public computer to access an application? Probably an enterprise-level application (Java/Vaadin) that will require some kind of authentication? Would somebody authenticate on a third party hardware? By the way who says that system administrator will not change, one day, server locale and affect the whole application, or deploy a second, third ... instance in a computer with a different locale for load balance purposes?
