### ISSUE TITLE
Click shortcut of a Button in a Dialog is not triggered

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#13205]
### Description of the bug

Click shortcut of a Button in a Dialog is not triggering the click event of the button. 

Tested in Vaadin 23.0.0

Works in Vaadin 22.0.7

### Expected behavior

Shortcut triggers the Button click event (Notification shown in the attached example)

### Minimal reproducible example

```
@PageTitle("Dialog")
@Route(value = "dialog", layout = MainLayout.class)
public class DialogView extends VerticalLayout {

	public DialogView() {
		Dialog dialog = new Dialog();
		Button button = new Button("Click me");
		button.addClickListener(event -> {
			Notification.show("Hello");
		});
		button.addClickShortcut(Key.ENTER);
		dialog.add(button);
		dialog.open();		
	}
}
```

### Versions

- Vaadin / Flow version: 23.0.0
- Java version: 11
- OS version: Wind

**Comment by joheriks** [comment]
The issue is because the state node root which handles the key events is inert (and hence [discards the event](https://github.com/vaadin/flow/blob/7ca947a658fe681766d3458e34a91460df4e7473/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L64-L69)). This will need some special handling to not block these. When fixing this, remember to test with key shortcut both behind the server-side modality (listener should not be triggered) and on top of it (the above case).
