### ISSUE TITLE
Page.setTitle() is not working

### ISSUE THREAD

**Issue by ImOlli** [vaadin/flow#13396]
### Description of the bug

When i try to call ``UI.getCurrent().getPage().setTitle("Test");`` nothing happens.

### Expected behavior

The method should change the title of the page.

### Minimal reproducible example

Create a Route and call ``UI.getCurrent().getPage().setTitle("Test");`` in the constructor or while clicking on a button.

### Versions

- Vaadin / Flow version: 23.0.3
- Java version: 17.0.1
- OS version: Windows 10 64 Bit
- Browser version (if applicable): Chrome 99.0.4844.84
- Application Server (if applicable): Spring Boot 2.6.5
- IDE (if applicable): Intellij Ultimate

**Comment by mcollovati** [comment]
Using `UI.getCurrent().getPage().setTitle("...");` in a button click listener works for me.
Doing the same in the component constructor has no effects because page title is rewritten during navigation process.
Based on your need you may either use a @PageTitle annotation or implement `HasDynamicTitle`
See [documentation](https://vaadin.com/docs/latest/flow/routing/page-titles) for further details and examples.

**Comment by ImOlli** [comment]
Thank you, ``HasDynamicTitle`` worked for me
