### ISSUE TITLE
SPIKE: Servlet 5.0 spec (aka Jakarta) migration

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#13428]
### Describe your motivation

Spring Boot 3 will come with Servlet 5.0 (https://jakarta.ee/specifications/servlet/5.0/).
This is an initial step for making https://github.com/vaadin/flow/issues/10366 happen.

#### Acceptance Criteria
- [x] Estimate impact on namespaces/imports
- [x] Test Atmosphere 3.0.1 against Flow (https://github.com/Atmosphere/atmosphere/issues/2467). Need to patch 3.0.1 for Vaadin?
- [x] Investigate the ways to separate Servlet 3.0 and Servlet 5.0 in Flow: a good way for that would be to change the code during build time (?)
- [x] Investigate Jetty websocket support has changed in Jetty 10 so it needs some refactoring, e.g. the websocket-server does not exist in Jetty 11
- [x] Investigate Apache commons file upload is for Servlet 3: https://issues.apache.org/jira/browse/FILEUPLOAD-345.
- [x] Propose a design for maintaining both specs in Flow.

**Comment by Artur-** [comment]
https://github.com/vaadin/flow/tree/feature/servlet5

**Comment by knoobie** [comment]
Awesome to see this going forward! Thanks a lot! One of the last missing pieces for our Spring Boot 3 Migration later this year. 

Probably something of interest / to checkout: https://github.com/apache/tomcat-jakartaee-migration

**Comment by Artur-** [comment]
The interesting part here is 
> Propose a design for maintaining both specs in Flow


All the other parts have been tested in the feature branch. 


Apache commons file upload is a problem as they have not released any version except for a snapshot

**Comment by knoobie** [comment]
> Apache commons file upload is a problem as they have not released any version except for a snapshot

I'm not sure how deeply it's integrated but it could probably be released by Vaadin until it's official supported like other libs you guys ha e forked? 

But yeah the hardest part would probably the design to support both specs at the same time; e.g. with different artefacts or classifier or a new major version 24? And letting 23 fade out

**Comment by mshabarov** [comment]
> All the other parts have been tested in the feature branch.

Awesome, thanks Artur. Then we can tick those as done, but before review your POC and understand how it works first.

> Apache commons file upload is a problem as they have not released any version except for a snapshot

We can contact them somehow and check the plans about release version, meanwhile test the snapshot.

**Comment by Artur-** [comment]
This is an incomplete hacky script for doing the upgrade https://gist.github.com/Artur-/b5aaf27e71599a1bc52ef91199b94c13

**Comment by Artur-** [comment]
> ~Probably something of interest / to checkout: https://github.com/apache/tomcat-jakartaee-migration~

In addition to this there is https://github.com/eclipse/transformer

**Comment by Artur-** [comment]
Some thoughts that just came to my mind and I did not really think through:
1. Are we talking about only `javax.servlet` changes here and are `javax.validation` namespace changes completely separate? In other words, can we upgrade to `jakarta.validation` first while keeping `javax.servlet` in use? Can we do that today?
2. Which parts do `javax.servlet` leak outside tests and the servlet definition itself? Is it possible to cut any other dependencies to `javax.servlet` so we could have two separate modules for servlet3 and servlet5 much like we have a portlet module?

**Comment by knoobie** [comment]
> Can we do that today?

Depends if you mean Jakarta Validation 2.0 or 3.0 - Spring Boot already replaced all Javax Artefacts to their Jakarta Validation 2.0 Equivalent. So that change would be painless. The change to Jakarta Validation 3.0 with the real namespace change is probably technical possible.. but I would recommend not to do it.. because it's possible that this could confuse users and or is problematic with "older" deployment container like jboss and so on. 

> Which parts do javax.servlet leak outside tests and the servlet definition itself?

Most of it is inside flow-server so having an additional flow-server-impl could theoretically be possible.. problematic could be that some API e.g. Cookies leak through the end user if I remember correctly. (VaadinRequest / -reponse)

**Comment by mshabarov** [comment]
> Can we do that today?

Not sure, we are wrapping up the remaining tasks from pervious iterations and hopefully can start dig into this spike tomorrow or next week.

**Comment by mcollovati** [comment]
Deltaspike published artifact with `jakarta` classifiers since version 1.9.6

https://issues.apache.org/jira/browse/DELTASPIKE-1434
https://search.maven.org/remotecontent?filepath=org/apache/deltaspike/core/deltaspike-core-api/1.9.6/deltaspike-core-api-1.9.6-jakarta.jar
https://search.maven.org/remotecontent?filepath=org/apache/deltaspike/core/deltaspike-core-impl/1.9.6/deltaspike-core-impl-1.9.6-jakarta.jar

**Comment by mcollovati** [comment]
Quarkus is also working on Jakarta 9 migration

* https://github.com/quarkusio/quarkus/issues/21574#issuecomment-1079733970
* https://github.com/quarkusio/quarkus/pulls?q=is%3Apr+label%3Aarea%2Fjakarta

**Comment by knoobie** [comment]
> Investigate Apache commons file upload is for Servlet 3: https://issues.apache.org/jira/browse/FILEUPLOAD-345.

I'm wondering if it would be feasible to remove the old dependency all together to move forward. Currently flow already depends on Servlet 3.1 in which the upload API got [improved](https://docs.oracle.com/javaee/7/api/javax/servlet/http/Part.html#getSubmittedFileName--)  and could probably be used natively instead of this legacy external dependency.
