### ISSUE TITLE
SPIKE: Estimate impact of using Servlet 5.0 on namespaces/imports in Flow

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#13431]
Subtask for the https://github.com/vaadin/flow/issues/13428.

### Acceptance Criteria
- [x] Look into migration tools given here https://github.com/vaadin/flow/issues/10366#issuecomment-804698911 and POC from Artur https://github.com/vaadin/flow/tree/feature/servlet5 and decide whether it's sufficient for Flow.
- [x] Create a POC in Flow and make tests compile and pass.

**Comment by mcollovati** [comment]
Some notes on making Artur's branch work after rebase on master:

- some conflicts on pom files to be resolved
- `fusion-endpoints` needs Java 17 to compile after spring upgrade
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project fusion-endpoint: Compilation failure: Compilation failure: 
[ERROR] /home/marco/projects/vaadin/flow/flow/fusion-endpoint/src/main/java/dev/hilla/EndpointProperties.java:[18,52] cannot access org.springframework.beans.factory.annotation.Value
[ERROR]   bad class file: /home/marco/.m2/repository/org/springframework/spring-beans/6.0.0-M2/spring-beans-6.0.0-M2.jar(/org/springframework/beans/factory/annotation/Value.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
   ```
- `test-spring-common` has an explicit dependency to `spring-security-oauth2-authorization-server:0.2.2` that references `javax.servlet` classes. Dependency has been introduced with vaadin/flow#13259 at the same time as the removal of `spring-security-oauth2` (`NoClassDefFoundError: javax/servlet/http/HttpServletRequest` on `OAuth2AuthorizationServerConfigurer.<init>`)
- There are some exceptions logged during `flow-server` tests, on Atmosphere initialization (`NoClassDefFoundError: jakarta/annotation/PostConstruct`). Tests pass but perhaps dependencies should be checked

**Comment by Artur-** [comment]
https://github.com/spring-projects/spring-authorization-server/issues/598#issuecomment-1020103822

**Comment by mcollovati** [comment]
Did a test with Eclipse Transformer and more specifically adding the `transformer-maven-plugin` to the project. It produced a companion jar for all modules with needed replacements (only bytecode, not sources). After replacing original jars in local maven repo with the transformed version I was able to run the plain Java starter on Jetty 11 (manually fixing atmosphere version on starter pom).
Interesting thing, but not yet tested, is that the transformer should be also able to do the opposite work, from `jakarta` to `javax`.

So having an automated binary migration seems to be easy, perhaps attaching artifacts to the build with specific classifiers, but the downside is that additional work would be needed to handle dependency management between modules correctly.
Also the transformer works on binary artifact, so we cannot replace the produced jar during the build, otherwise dependent modules will fail during compile phase.
