### ISSUE TITLE
SPIKE: Isolate Servlet 3 API usage from a common logic

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#13569]
Refactor current Flow master to extract java servlet API usages into separate module/classes in (at least):
- flow-server
- flow-data
- vaadin-dev-server
- fusion-endpoint
That makes it easer to proceed the migration to Servlet 5 in a feature branch and keep it up-to-date with master.

**Comment by mcollovati** [comment]
After a first investigation on `flow-server` and `vaadin-dev-server` modules it seems we have different kinds of servlet API usages:
* references on Javadocs
* usage of constants (mostly HttpSerlvetResponse status codes)
* usage in internals
* usage in public APIs
* container hooks (ServletContainerInitializer, `@WebListener`, HttpSessionBindingListener, ...)

For the first two points we can maybe open separated tickets and work on them immediately, without having breaking changes. For the rest, design is needed.

Below a list of components that may be refactored

### flow-server

#### Javadocs only

Classes referencing servlet APIs only on Javadocs 

* HasErrorParameter: HttpServletResponse only in Javadocs
* ApplicationConfiguration: Servlet only in javadocs
* OneTimeInitializerPredicate:	 ServletContainerInitializer only in Javadocs

#### Constants

Classes using only  HttpServletResponse for HTTP status code; we can maybe introduce our own constants

* JavaScriptNavigationStateRenderer
* InternalServerError
* AbstractNavigationStateRenderer
* LocationChangeEvent
* Router
* StreamRequestHandler
* HeartbeatHandler
* WebComponentProvider

#### Existing abstractions using servelt APIs

* VaadinSession: HttpSession, HttpSessionBindingEvent, HttpSessionBindingListener
* VaadinResponse: Cookie (see #4613), HttpServletResponse and ServletResponse used in javadocs
* VaadinRequest: Cookie (see #4613), HttpServletRequest and ServletRequest used in javadocs
* WrappedHttpSession: HttpSession

#### Highly coupled components

The following component should perhaps be duplicated to support `jakarta.servlet`

* VaadinServletContext
* VaadinServletRequest
* VaadinServletResponse
* VaadinServletService

#### Servlet types in public API

For the following we need more investigation and design, because perhaps we may also introduce breaking changes

* ResponseWriter: HttpServletRequest and HttpServletResponse in public API, ServletRequest in internal methods, ServletOutputStream in internal methods, (can be replaced with OutputStream?)
* PwaRegistry: ServletContext in public API and constructor
* StaticFileHandler: HttpServletRequest and HttpServletResponse in public API
* SpringCsrfTokenUtil: ServletRequest in public API
* DevModeHandler: HttpServletRequest, HttpServletResponse in public API
* ContentTypeResolver: ServletContext in public API
* VaadinApplicationInitializationBootstrap: throws ServletException
* StreamReceiverHandler: HttpServletResponse only status code, HttpServletRequest, Part, **commons-fileupload**
* StreamResourceHandler: HttpServletResponse only status code, ServletContext for ContentTypeResolver
* FaviconHandler: explict cast to VaadinServletRequest, HttpServletResponse used only for HTTP status code
* HandlerHelper: HttpServletRequestin public API
* ViewAccessChecker, AccessAnnotationChecker: explict cast to VaadinServletRequest, HttpServletRequest in public API to get Principal and to check roles
* PushRequestHandler: ServletConfig and ServletException, needed and thrown by **Atmoshpere**
* BeanUtil: uses Class.forName("javax.validation.Validation") to check JSR-303 availability; used by flow-data module

#### Initialization stuff

Components that directly extends Servlet hook (e.g. `ServletContainerInitializer`)

* ServletContextListeners < ServletContextListener: annotated with `@WebListener`
* ServletDeployer: not `@WebListener`, handled by ServletContextListeners
* SR356WebsocketInitializer: not `@WebListener`, handled by ServletContextListeners

ClassLoaderAwareServletContainerInitializer < ServletContainerInitializer: most of the following are annotated with `@WebListener` and `@HandleTypes`
* LookupServletContainerInitializer
* AnnotationValidator < VaadinServletContextStartupInitializer
* DevModeStartupListener < VaadinServletContextStartupInitializer
* ErrorNavigationTargetInitializer < VaadinServletContextStartupInitializer 
* RouteRegistryInitializer < VaadinServletContextStartupInitializer
* ServletVerifier < VaadinServletContextStartupInitializer
* VaadinAppShellInitializer < VaadinServletContextStartupInitializer
* VaadinServletContextStartupInitializer
* WebComponentConfigurationRegistryInitializer < VaadinServletContextStartupInitializer
* WebComponentExporterAwareValidator < VaadinServletContextStartupInitializer

For the above components we can maybe try to make them completely independent from servlet api (and they partially are designed in this way as they implement `VaadinContextStartupInitializer`) and perhaps have a single `ServletContainerInitializer` that handles `VaadinContextStartupInitializer`s and creates and registers a listener for each of them (ServletContext.addListener) or directly invokes their `initialize` method; this way we could also define an initialization order (e.g. sorting based on `@Priority` annotation). We could maybe add our own `@HandlesTypes` annotation.
Another possibility is to make classes abstract so we can have different implementation for `javax.servlet` and `jakarta.servlet` but sharing the same logic.
Perhaps we will have breaking changes, but above component are marked as `For internal use only` in javadocs.

	
### vaadin-dev-server

* DevModeHandlerManagerImpl: annotated with `@HandlesTypes`
* AbstractDevServerRunner: HttpServletRequest and HttpServletResponse in public API and javadocs, ServletOutputStream in internal method but can be replaced with OutputStream
* DevModeStartupListener < ServletContextListener & VaadinServletContextStartupInitializer: uses ServletContextEvent in initialized and destroyed hooks, it is annotated with `@WebListener` and `@HandleTypes`
* DevModeInitializer: annotated with `@HandlesTypes`



### fusion-endpoint and vaadin-spring

To be further investigated. Many components has injection of servlet stuff or use them in public APIs.
Maybe we can have both implementations on the same code base, marking dependencies as `optional` and use some spring magic to load the correct one for the runtime (e.g. `@ConditionalOnClass`), but we should check if this can work well with both Spring 5 and 6.

**Comment by mcollovati** [comment]
### flow-data

In flow-data module there's a chance that we can support both `javax.validation` and `jakarta.validation` at the same time, without having separate modules or different code on different branches.

#### Components that references `javax.validation` api 

RequiredFieldConfigurator: uses annotation `.class`
RequiredFieldConfiguratorUtil: `@Size` used only on javadocs
BeanValidator: exposes javax.validation APIs  on public and protected APIs; used by BeanValidationBinder
BeanValidationBinder: javax.validation APIs used only on private method configureRequired

The following steps may allow us to support both dependencies at same time, hopefully without breaking changes (just a quick investigation, may be better analyzed)

* Extract common logic from `BeanValidator` into an abstract class (e.g. `AbstractBeanValidator`) and then have `BeanValidator` and `JakartaBeanValidator` subclasses
* Add a static initialized factory in `BeanValidationBinder` to get a new `BeanValidator` instance (e.g. `BiFunction<Class<?>, String, AbstractBeanValidator>`); it will return a `BeanValidator` if **javax.validation** classes are available otherwise a `JakartaBeanValidator`. We can invert the check when we will ship **jakarta.validation** as default.
* Add a `abstract Annotation extractContrainst(PropertyDefinition)` method in `AbstractBeanValidator`; subclasses will implement it as it is currently coded in `configureRequired(...)` method
* Refactor `BeanUtil.LazyValidationAvailability` to check for presence of both **javax.validation** and **jakarta.validation** (or move it elsewhere)


Probably tests and/or annotated test classes should be duplicated.
