### ISSUE TITLE
Define default dependencies using a package.json file

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#13640]
### Describe your motivation

The dependencies currently defined in [NodeUpdater.java](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java#L366) and the development dependencies defined in https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdater.java#L384 need manually updating and are often forgotten. For example https://github.com/vaadin/flow/pull/13638 looks like it updates Lit but in practice it only changes one test package lock file and lit remains the old version

### Describe the solution you'd like

The dependencies should instead be defined in a `package.json` file in e.g. 
- https://github.com/vaadin/flow/tree/master/flow-server/src/main/resources/com/vaadin/flow/server/dependencies/webpack - for webpack
- https://github.com/vaadin/flow/tree/master/flow-server/src/main/resources/com/vaadin/flow/server/dependencies/vite - for Vite

By using a package.json file it is easy to see what dependencies are but also it allows tools like dependabot or snyk to upgrade the versions.

**Comment by knoobie** [comment]
This could be extended, that you read/parse the `package.json` provided by some vaadin artifact on customer projects instead of looking at `NodeUpdater.java` what has to be updated.

**Comment by Artur-** [comment]
Not sure I follow what you mean, care to expand a bit?

**Comment by knoobie** [comment]
Currently the `NodeUpdater.java` defines the `getDefaultDependencies` and `getDefaultDevDependencies` a user project is created with. 

Once you create the needed dependencies inside a package.json in  `flow-server/src/main/resources/com/vaadin/flow/server/dependencies/webpack` or `flow-server/src/main/resources/com/vaadin/flow/server/dependencies/vite` the flow build plugin could use those files to calculate the current frontend dependency tree instead of relying on the `NodeUpdater.java` allowing for a more up-to-date end-user project if dependabot, renovate or snyk update your dependencies -> a customer (project) can have the same benefit.

**Comment by knoobie** [comment]
Thanks @Artur-! Just realized/was notified you were fixing this ticket 🙇‍♂️
