### ISSUE TITLE
Can license-checker be excluded by spring boot fat jar without breaking anything?

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#13922]
Title says it all. Can the license checker (a 4mb jar) be removed from production builds? Is it needed at runtime?

Additionally the license-checker jar contains jna, jna-platform and oshi-core. Those are already present within a spring boot fat jar and are probably the reason why this jar is so big.

Example based on the latest 23.1.0.beta1 with license checker 1.4.1

![image](https://user-images.githubusercontent.com/3968629/166936101-5c24478f-06cf-4c2e-bdf8-eb3917589798.png)

**Comment by Artur-** [comment]
To be clear: the checker can be excluded from the final jar/war. If that causes an issue there is something broken.

**Comment by bwolff** [comment]
I'm using Vaadin with Spring Boot + Gradle + Spring Boot Gradle plugin + Vaadin Gradle plugin.

It turns out that the `license-checker` dep is pulled in as a transitive dependency of the `vaadin-dev-server`. Both deps are present by default in the runnable jar produced by `bootJar`. Of course, the production jar file should not contain dev stuff and therefore not the `license-checker`.

I solved the problem by excluding the `vaadin-dev-server` dep and include it under a different dependency scope (`developmentOnly`) that makes it available when running the app with `bootRun`, but will not be ncluded it in the `bootJar`.

`build.gradle`

```
dependencies {
    implementation('com.vaadin:vaadin-spring-boot-starter') {
        exclude group: 'com.vaadin', module: 'vaadin-dev-server'
    }

    developmentOnly 'com.vaadin:vaadin-dev-server'
}
```

However, it would be much better if the Vaadin setup would not bundle these dev-dependencies in the `bootJar` by default.

HTH,
Ben

**Comment by Artur-** [comment]
Created #15749 for automatiacally excluding vaadin-dev-server from production builds
