### ISSUE TITLE
Application restarts immediately on startup when using Vite

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#14022]
### Description of the bug

When starting a 23.1 application using Vite, the startup sequence ends in
```
2022-06-22 10:55:56.268 DEBUG 4669 --- [   File Watcher] o.s.boot.devtools.restart.Restarter      : Application restart required due to the following changes: [/.../target/classes [/.../target/classes/META-INF/VAADIN/webapp/sw.js.map (ADD), /.../target/classes/META-INF/VAADIN/webapp/sw.js (ADD)]]
```

This causes two problems:
1. Longer startup time as the Spring Boot application is restarted before it is available
2. The browser shows a white page instead of the application because of 
![image](https://user-images.githubusercontent.com/260340/174975675-d2e7ee08-3470-45af-b6ba-d8f5ff9e929c.png)

Apparently the browser reloads when the Vite server is ready but this is exactly when the Spring Boot server is restarting. 

Because of this it all looks broken

### Expected behavior

The application should not restart on startup. The service worker should not be written to that directory in development mode

### Minimal reproducible example

```
vaadin init hello
cd hello
echo "com.vaadin.experimental.viteForFrontendBuild=true" > src/main/resources/vaadin-featureflags.properties
mvn
```

### Versions

Vaadin: 23.1.1
Flow: 23.1.1
Java: Homebrew 17.0.1
OS: aarch64 Mac OS X 12.4
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Comment by vursen** [comment]
I remember I’ve encountered this while adding dev mode offline support for the service worker. This is exactly caused by the fact that the output `sw.js` is written in a physical folder as a result of the build rather than stored in memory. Flow watches that folder and restarts the server whenever a change occurs.

A solution that we might try is to build the service worker on request like other modules. This way Vite will serve it from memory.

1. Configure Flow to proxy `sw.js` to `VAADIN/sw.js`.
2. Rewrite the current SW plugin to only build `sw.js` on request in dev mode.

**Comment by vursen** [comment]
> Is this the same as https://github.com/vaadin/flow/issues/13123?

Hah, yes, turns out that I have already reported this and there is actually a prototype.
