### ISSUE TITLE
Enable polling cause "Ignoring Poll RPC for UI that does not have polling enabled." log

### ISSUE THREAD

**Issue by davidef** [vaadin/flow#14136]
### Description of the bug

Enable polling without adding a custom PollListener cause "Ignoring Poll RPC for UI that does not have polling enabled." warning log.

### Expected behavior

No warning log written because polling is enable on the specific UI. We just haven't registered a custom PollListener

### Minimal reproducible example

```
@PageTitle("Main")
@Route(value = "")
public class MainView extends HorizontalLayout {
	private static final long serialVersionUID = 1L;

	private Button testPool;

	public MainView() {
		testPool = new Button("Test pool");
		testPool.addClickListener(e -> {
			getUI().get().setPollInterval(1000);
			UI ui = getUI().get();
			new Thread(()->{
				try {Thread.sleep(5000);} catch (InterruptedException e1) {}
				ui.access(()->{
					Notification.show("Test");
					ui.setPollInterval(-1);
				});
			}).start();
		});

		add(testPool);
	}
}
```

### Versions

- Vaadin / Flow version: 23.1.2

**Comment by mshabarov** [comment]
Poll listener is checked [here](https://github.com/vaadin/flow/blob/e44a7eb959cc1cf9b8ce1413af842c4d1b7c3a81/flow-server/src/main/java/com/vaadin/flow/server/communication/rpc/AbstractRpcInvocationHandler.java#L118). Seems like the second condition is not needed 
```java
ComponentUtil.hasEventListener(ui, PollEvent.class)
```
since the polling is considered enabled if `UI::setPollInterval` gives a meaningful and non `-1` value to it.
