### ISSUE TITLE
Browser history navigation fails silently in v23 with v14 bootstrapping enabled

### ISSUE THREAD

**Issue by SoylentBob** [vaadin/flow#14323]
### Description of the bug

When using [server side navigation](https://vaadin.com/docs/latest/routing/navigation/#server-side-navigation) (e.g. `UI.getCurrent().navigate("some-link")`) in a Vaadin v23.1.6 Application built with gradle and v14 bootstrapping enabled, the browser navigation history is displayed correctly, but going back via the browsers history does not open the previously opened pages, even though the URL in the browser is updated correctly.

Other links such as HTML Anchors or Router Links seem to not be affected by this issue.

### Expected behavior

Going through the browsers history should work even with server-side navigation and v14 bootstrapping enabled.

### Minimal reproducible example

Clone https://github.com/SoylentBob/vaadin-navigation-bug (the project is based on https://github.com/vaadin/base-starter-gradle)

1. Start the application with the command `./gradlew jettyRun`
2. Open `http://localhost:8080` in your browser.

![Result of Step 2](https://user-images.githubusercontent.com/9849919/184111251-e18caf63-2fed-48c7-a392-dcc89ba9daf6.png)

3. Click on the "Open second view", you should be on the URL `http://localhost:8080/second` now

![Result of Step 3](https://user-images.githubusercontent.com/9849919/184111312-4437a85f-fa4a-4cba-a0fe-38b750a94e37.png)

4. Click on the browsers back button, your browsers URL should have changed to `http://localhost:8080`, without actually displaying the "Main" view.

![Result of Step 4](https://user-images.githubusercontent.com/9849919/184111338-35f1e50a-d638-4235-9299-88a14b652d62.png)

_Setting the `useDeprecatedV14Bootstrapping` flag in the `build.gradle` file to `false` seems to fix the bug in the attached test project, but is not feasible at the moment for the project that we noticed the bug in._

### Versions

- Vaadin / Flow version: 23.1.6 (v14 Bootstrapping enabled)
- Java version: 17
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mshabarov** [comment]
Might be related to https://github.com/vaadin/multiplatform-runtime/issues/115#issuecomment-1216864719

**Comment by mcollovati** [comment]
When performing a server-side navigation, the client receives a JavaScript `history.pushState` instruction to update the history
```
setTimeout(() => window.history.pushState($0, '', $1))
```
On flow client, in `PopStateHandler` we register a `ResponseHandlingEndedHandler` to catch the current `window.location` path and query string.
In addition, a `popstate` listener is registered, to react to browser back and forward navigation buttons (events are not fired for `history.pushState`). This listener compares stored location information with the current value; if they are different, the server is notified of the change; otherwise there is no server roundtrip.

The issue here seems to be that the `ResponseHandlingEndedHandler` is running before the execution of `history.pushState` (probably because of `setTimeout`), so when the back button is pressed and the `popstate` listener is executed, the current `window.location` is the same as the one we stored in `ResponseHandlingEndedHandler`
