### ISSUE TITLE
Migrate Vaadin Portlet add-on to Jakarta Servlet 5

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#14386]
Should be checked that the Apache Pluto and Liferay have Servlet 5 compatible versions.

**Comment by mshabarov** [comment]
Since Liferay has no plans to support Jakarta EE 9 / Servlet 5.0 and since Portlet spec compatible with Servlet 5.0 doesn't exist, this migration is not possible.

**Comment by mshabarov** [comment]
This is a comment from Liferay expert https://issues.liferay.com/browse/LPS-161259?focusedCommentId=2752279&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2752279

**Comment by johnplatts** [comment]
Update: There is a proposal underway to migrate JSR 362 API over to the `jakarta.portlet` package in order to allow Liferay Portal and Apache Pluto to run on Jakarta EE 10 servers, and this effort is described over at https://liferay.dev/blogs/-/blogs/liferay-s-java-roadmap-for-2025, https://liferay.dev/blogs/-/blogs/preparing-for-jakarta, https://projects.eclipse.org/proposals/jakarta-portlet, and https://liferay.atlassian.net/browse/LPD-49394.

**Comment by mshabarov** [comment]
@johnplatts thanks for the comment and links!

I've made a new ticket here to follow https://github.com/vaadin/platform/issues/7498.

Though I have no ideas about priorities for this.
Do you by the way use Vaadin with Liferay?
