### ISSUE TITLE
setVisible(false) does not work in production mode

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#14453]
### Description of the bug

I have created a component `Composite<Div>`. (here is the code: https://github.com/jcgueriaud1/googlemap-v23-issue/blob/visibility/src/main/java/com/example/application/components/XPanel.java)
`setVisible(false)` set correctly the attribute hidden on the div.
It's not visible in development mode.
In production mode, it's visible.
I can reproduce it when I'm using a subset of Vaadin components so I suppose the css rule is added by one of the component I'm not using. Apparently it's coming from this component: https://github.com/PolymerElements/iron-flex-layout/blob/a8b8e91b261ca835aa8b457cc571d55ac4973fdc/iron-flex-layout.html#L62-L72

### Expected behavior

A component not visible should be hidden.

### Minimal reproducible example

https://github.com/jcgueriaud1/googlemap-v23-issue/tree/visibility
Start the application and go http://localhost:9080/visibility
In development mode, 
![image](https://user-images.githubusercontent.com/51313578/187902754-ec11826d-212a-4c01-936b-2e59294c7866.png)

In production mode:
![image](https://user-images.githubusercontent.com/51313578/187901061-1f3d7721-a80a-47db-83c0-5e6d5706c798.png)

### Versions

- Vaadin / Flow version: 23.2.0.rc1
- Java version: 11 and 17
- OS version: Mac
- Browser version (if applicable): Chrome (probably not relevant)

**Comment by jcgueriaud1** [comment]
As a workaround, you can apply this css rule in your global css:
```
[hidden] {
    display: none !important;
}
```

**Comment by Legioth** [comment]
There has been some discussion about whether this issue has security implications since `setVisible(false)` may be used for hiding content that a user is not authorized to see. I want to make it clear that this issue is purely completely cosmetic and doesn't have any direct security implications.

`setVisible(false)` is implemented to always keep an element in the DOM, but hiding it using CSS. For an initially hidden element, all that is sent to the client is an empty placeholder element. For an element that was previously shown and subsequently hidden, the element's contents will remain as they were before hiding. Subsequent content changes (e.g. children, properties or attributes other than `hidden`) are enqueued on the server and sent to the client only if the element is again set as visible. The purpose of this functionality is to enable fast toggling e.g. in association with a tab sheet. This can potentially have security implications in the quite special case of changing the current user's permissions on-the-fly without also rebuilding the UI since they could in that situation still access the content that they were previously allowed to access. This is how `setVisible(false)` has worked since Vaadin 10 and nothing has changed in that regard in Vaadin 23.2.

The suggested workaround with adding CSS to not show elements with a `hidden` attribute is 100% valid since the root cause of this regression is that a Polymer feature that was injecting that CSS rule is no longer used by default. Our fix will thus only be to explicitly include that CSS snippet so that it's in effect even without that Polymer feature.

This is still an embarrassing regression that we will fix as quickly as possible now when we have realized that it's highly disruptive regardless of the non-issue with security. From an optimist's point of view, I can even see this as a happy accident since it may have helped developers become more aware of the dangers of hiding sensitive content only using CSS 😄.
