### ISSUE TITLE
PiT 23.3: implement a mechanism for updating `tsconfig.json`

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#15238]
### Description of the bug

Any upgrade of an app having `tsconfig.json` file in git, will fail with an error.

#### Workaround

Remove the file manually

### Expected behavior

User does not have to do any action, flow updates the file appropriatelly

### Minimal reproducible example

Checkout any project with the `tsconfig.json` and run it. 

### Versions

- Vaadin / Flow version:  23.3.0.alpha3 / 23.3.0.beta1

**Comment by Artur-** [comment]
Would this work?

1. If tsconfig.json matches a "known" old version, we replace it with the new one without asking. We must match all variants back to V14 as somebody might still have an old tsconfig that has happened to work with newer versions, or she is upgrading from V14
2. Otherwise tsconfig.json has presumably been customized. We overwrite tsconfig.json anyway (if you have customized it, it is in the repository) and then throw an exception saying that the user should verify the changes as we just overwrote it. If the user just starts the app again, the new one will be used and no exception is thrown as it now matches the 23.3 version
