### ISSUE TITLE
Add html table component et al

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#15475]
### Describe your motivation

Using html table (et al) would sometimes make more sense than to use e.g. Grid component. For example much more flexible when styling. As we support raw html table as well like we do support UnorderedList, H1 etc.

### Describe the solution you'd like

There should be Table,Tr,Td,THead and TBody components in flow-html-components. Names of the components should probably be something more meaningful than in html (e.g. `TableCell` instead of `Td`);

### Describe alternatives you've considered

Keep using add-ons.

### Additional context

The [Html Table add-on ](https://vaadin.com/directory/component/html-table) by @stefanuebe could be the basis for official components. See also [BeanTable](https://vaadin.com/directory/component/beantable) by @TatuLund that use <table> element to render DTOs.

**Comment by mstahv** [comment]
I think Table would be great name, but yeah, there is still history in the old Table component from older Vaadin versions. Maybe `HtmlTable`🤔

**Comment by stefanuebe** [comment]
Some issues I see with the current implementation: 

* the usage of "Has(Ordered)Components" for parts like the table, row or the head can in theory produce illegal html, since for instance `tr` only must have `td` or `th` as children. In this scenario the dev can set components directly as children of `tr`
* another similar problematic constellation is, where the table may have a `tbody` element and have direct `tr` children
* colgroup or cols are not implemented
* header cells have no col- or rowspan

Additionally to that I want to add, that I cannot really comprehend why the "wheel was reinvented" here. Other tickets / issues are filtered out through triage / not enough time and here existing things have been written again. Please don't get me wrong, I don't want to sound salty and its not meant as a personal offense in any way, but I have to explain customers very often, that we cannot fix issues they reported, because of missing time.

In the end it's up to you guys, just wanted to share my thoughts on that for future to-integrate-components, where already mature addons exist (and are free to integrate). And regarding the mentioned points: as said before - feel free to reuse stuff from the addon. It has basically all the work done already. :)

**Comment by stefanuebe** [comment]
@sosa-vaadin / @tepi 

Some issues I see with the current implementation: 

* the usage of "Has(Ordered)Components" for parts like the table, row or the head can in theory produce illegal html, since for instance `tr` only must have `td` or `th` as children. In this scenario the dev can set components directly as children of `tr`
* another similar problematic constellation is, where the table may have a `tbody` element and have direct `tr` children
* colgroup or cols are not implemented
* header cells have no col- or rowspan

Additionally to that I want to add, that I cannot really comprehend why the "wheel was reinvented" here. Other tickets / issues are filtered out through triage / not enough time and here existing things have been written again. Please don't get me wrong, I don't want to sound salty and its not meant as a personal offense in any way, but I have to explain customers very often, that we cannot fix issues they reported, because of missing time.

In the end it's up to you guys, just wanted to share my thoughts on that for future to-integrate-components, where already mature addons exist (and are free to integrate). And regarding the mentioned points: as said before - feel free to reuse stuff from the addon. It has basically all the work done already. :)
