### ISSUE TITLE
Vaadin only sets Locale in VaadinSession if an I18nProvider Bean exists

### ISSUE THREAD

**Issue by ImOlli** [vaadin/flow#15693]
### Description of the bug

We want to use the Locale of the current client for internal I18n stuff. Back in Vaadin 8 we could use the Locale in der VaadinSession for that. 

Now in the current Vaadin version it will only be set if an I18nProvider Bean exists.

### Expected behavior

The Locale should always be set in the session or atleast it should be toggeable via properties.

### Minimal reproducible example

Create a new Vaadin-App and try to use `VaadinSession.getLocale()`. The Locale will always be the system locale.

### Versions

- Vaadin / Flow version: 23.2.8
- Java version: 17
- OS version: Windows 10
- Application Server (if applicable): Spring Boot 2.7.6

**Comment by Legioth** [comment]
It's a conscious design decision to not automatically use user-supplied locales unless the application has explicitly opted in to support a specific locale. This is because some components automatically adapt to the locale which leads to a sometimes annoying situation that e.g. the date picker uses a different language than the rest of the application.

As a workaround in case you still want to offer an inconsistently localized UI, you can either define a simple `I18nProvider` or add a session init listener that does `session.setLocale(event.getRequest().getLocale());`.
