### ISSUE TITLE
Vaadin 24.0.0.beta2: Frontend bundle not rebuilt when changing .ts file

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow#15970]
### Description of the bug

In a pure Flow application (straight from https://start.vaadin.com/) I'm using the template approach for one component: so I have a Java Component (extends LitTemplate) and a corresponding .ts file. In the latest Vaadin **release**, changes to the .ts file are automatically picked up and the page is reloaded. So far so good.
After upgrading to a Vaadin 24 pre-release this no longer works. Changes are no longer detected immediately, but - even worse - even after a restart of the whole application it still doesn't pick up the previously made changes.
The first one (hot deploy) is caused by `vaadin.frontend.hotdeploy` which is now `false` by default. When I turn this on, everything works. But even when this is turned off, the cold deploy (picking up the changes after restarting the server) should work, but doesn't. The `Building front-end development bundle` isn't shown.
Changes to .ts files in an add-on that I develop side-by-side with the application are picked up after a restart.

### Expected behavior

Even with `vaadin.frontend.hotdeploy=false` (the default) restarting the server should pick up changes to .ts files in the application project.

### Minimal reproducible example

Use https://start.vaadin.com/app to create a new `Vaadin 24 (pre)` project and drop in the two files below into the appropriate locations. Alternatively just download the attached project which should be exactly the same.
Then start the application and open http://localhost:8080/lit-view
Observe the background color and then change it in lit-view.ts. The new color isn't used, even after restarting the server.

```java
// LitView.java

package com.example.application.views;


import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.littemplate.LitTemplate;
import com.vaadin.flow.router.Route;


@Route("lit-view")
@Tag("lit-view")
@JsModule("./views/lit-view.ts")
public class LitView
  extends
    LitTemplate
{

}
```

```typescript
// lit-view.ts

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

import '@vaadin/checkbox';


@customElement('lit-view')
export class LitView
  extends LitElement
{

  static styles = css`
    :host {
      display: block;
      width: 100%;
      height: 100%;
      background-color: red;
    }
  `;
[my-app.zip](https://github.com/vaadin/flow/files/10790850/my-app.zip)


  render() {
    return html`
      <div></div>
    `;
  }
}
```

### Versions

Vaadin: 24.0.0.beta2
Flow: 24.0.0.beta2
Java: Eclipse Adoptium 17.0.2
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
IDE: Eclipse

**Comment by mshabarov** [comment]
@Frettman thank you for the issue! Indeed, restarting the server should trigger a bundle rebuild if the template has been changed. As a workaround, while this issue is being fixed, you can try to remove `src/main/dev-bundle` which should trigger a new bundle. Also, setting `vaadin.frontend.hotdeploy=true` is recommended if one uses templates, but the behaviour above still looks like a bug.

**Comment by Frettman** [comment]
On related notes:
1. Is there a reason, why `vaadin.frontend.hotdeploy=false` is the default for Flow? Does that actually save anything? It's especially confusing as the Vaadin debug widget still says that live reload is active for the frontend.
![image](https://user-images.githubusercontent.com/24453813/220837161-2282a947-aa11-4958-af7f-7ed176ad3ab6.png)
2. Does your fix also help to hot deploy resources from add-ons that are being developed in the same workspace?

**Comment by mshabarov** [comment]
@Frettman thanks for question!
1. Vaadin 24.0 includes a new development mode with pre-compiled frontend bundle (aka Express Build mode), see docs https://vaadin.com/docs/next/configuration/development-mode/#pre-compiled-front-end-bundle-for-faster-start-up . In this mode the Vite dev server is not running, so the hot deploy is not available, but from the other side, this mode doesn't require Node.js, Vite and npm installation if no frontend customisations used in the project (only Flow views and components). This gives a significant profit in application startup time. We decided to make it a default development mode  for Flow applications, because it gives a better productivity there, and also this is better to do in a major release rather than in further minor releases. If one makes an often frontend development, we recommend to use Vite dev server (which was a default in V23.3) and set `vaadin.frontend.hotdeploy=true`.
Live-reload for the custom theme files is still available in this new mode, that's why it is shown in the dev tool window.
2. No, hot deploy (i.e. for frontend files) is not going to be added, at least in Vaadin 24.0. My fix will be covering detecting modifications in JS/TS files in `frontend` folder, so on the next cold restart the bundle will be re-generated.

**Comment by Frettman** [comment]
Thank you for taking the time to answer my questions. I still feel like there could be an additional `auto` mode for `vaadin.frontend.hotdeploy`. If there are frontend customizations detected (and my *.ts files are built into the frontend bundle, so they must somehow already be detected), the Vite dev server could automatically be started. For that extra little bit of "it just works".
But having to set `vaadin.frontend.hotdeploy=true` isn't so bad once you know it exists :)
