### ISSUE TITLE
Vulnerability in nimbus-jose-jwt : 9.23

### ISSUE THREAD

**Issue by craigwebb-xft** [vaadin/flow#16298]
### Description of the bug

nimbus-jose-jwt : 9.23 has a vulnerability - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-1370

This is used in the license-checker:
vaadin-core 23.3.7 -> vaadin-dev-server 23.3.4 -> license-checker 1.12.0 -> nimbus-jose-jwt 9.23

### Expected behavior

n/a

### Minimal reproducible example

n/a

### Versions

- Vaadin / Flow version: 23.3.7
- Java version: 11
- OS version: Windows 10
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Legioth** [comment]
This issue is most likely not affecting Vaadin through the license-checker module since JWT support is only used for reading offline license files. Those files are part of the application itself rather than being received from the outside.

We should still definitely make sure this issue is fixed since there's also a possibility that an application developer discovers that they already have `nimbus-jose-jwt` on their classpath and go on to also use it for other purposes.

**Comment by Artur-** [comment]
How is nimbus-jose-jwt related to json-smart mentioned in the CVE?

**Comment by knoobie** [comment]
Nimbus ist using it as transitive dependency. 

Even tho it's no issue per-se because normally people should have already excluded dev-server from production builds.

**Comment by craigwebb-xft** [comment]
nimbus-jose-jwt-9.23.jar is using net.minidev:json-smart:2.4.8

**Comment by Artur-** [comment]
Ok so not a dependency but bundled into the jar

**Comment by knoobie** [comment]
Yes they shaded it https://www.connect2id.com/blog/nimbus-jose-jwt-9 ... Soo not much Vaadin can do atm.

**Comment by Artur-** [comment]
9.31 does not have it anymore

**Comment by Artur-** [comment]
version 9.24 (2022-08-16)
    * Replaces JSON Smart 2.4.8 (shaded) with GSon 2.9.1 (also shaded) (iss
      #448, #483).

**Comment by craigwebb-xft** [comment]
Can the nimbus-jose-jwt version in license-checker be updated to at least 9.24 then or the latest version?

**Comment by craigwebb-xft** [comment]
@knoobie Thanks!

**Comment by craigwebb-xft** [comment]
@Artur- Brilliant, thanks.
