### ISSUE TITLE
Add license checking to Vaadin Servlet for Flow 9.1 (Vaadin 22.1.0)

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#16319]
Upcoming Vaadin 22.1.0 (Flow 9.1.0) will be under commercial license. Thus Flow needs a license checking in a runtime during initialising `VaadinServlet`.

**Comment by jhult** [comment]
@mshabarov, does this mean Flow is no longer open source? Has there been an announcement about this?

**Comment by jhult** [comment]
Related: #16301

**Comment by knoobie** [comment]
Flow 9.1 is  the release targeted for Vaadin 22.0 which is EoL since March. Like with V8, they  change the license for the old version for commercial customer support if those need this EoL Version longer. Flow 9.1 == Vaadin 22.1 

This does not change anything for people using already not EoL versions.

**Comment by mshabarov** [comment]
@jhult thanks for asking!
This ticket only affects Flow 9.1 (targets Vaadin 22.1). Vaadin 22.0 is end of life in March 2023 and Vaadin 22.1 has an extended maintenance for Prime+ customers, thus we are adding a license into it.
See https://vaadin.com/releases
```
Vaadin 22 is the latest stable version to support Java 8, and will be exceptionally maintained for an extra year, until March 2023, to help transition to Java 11. Prime customers will get support until Match 2024.
```
Also thanks @knoobie for fast reply and explanations!
