### ISSUE TITLE
Vaadin 23.2.17 - Build for production fails

### ISSUE THREAD

**Issue by giusdiluca** [vaadin/flow#16577]
### Description of the bug

Hello,

my application runs fine in development mode, but when I try to run it in production mode (-Pproduction) build-frontend task fails.
Please look at the log attached.

[vaadin_compile.log](https://github.com/vaadin/flow/files/11221986/vaadin_compile.log)

### Expected behavior

Build for production should not fail 

### Minimal reproducible example

mvn -Pproduction spring-boot:run

### Versions

- Vaadin / Flow version: 23.2.17
- Java version: 11
- OS version: RedHat 7
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):
- Maven: 3.8.4

**Comment by giusdiluca** [comment]
Hello Marco, no I didn't use JDK17 neither the IDE compile with Java 17 nor have any dependency compiled with that java verion.
I've just tried with the simple spring-boot:run as suggested and the errore is the same.

**Comment by mcollovati** [comment]
In the log I can see at lest a dependency to `org.vaadin.olli:file-download-wrapper` at version 7.0.0, that is for Vaadin 24 and compiled with JDK 17, and the add-on has a class annotated with `@JsModule`

`org.vaadin.olli:file-download-wrapper:jar:7.0.0:compile`

I don't know if this one is the cause, but you should change version, as you are on Vaadin 23.2

Based on the [add-on page](https://vaadin.com/directory/component/file-download-wrapper) on directory, I suppose you should use version 4.0.0, as 5.0.0 is for Vaadin 23.3+ and 6.0.0 for Vaadin 24.

**Comment by giusdiluca** [comment]
Thanks Marco, actually the addon was not used in the project, maybe added from someone else in the team to the pom.xml
During the development phase that did not caused issue, but while trying to build for production it crashed the build.
Removing the dependency from the pom.xml the issue was solved, thanks a lot.

**Comment by Artur-** [comment]
As this seems to be an issue that pops up every now and then, is there anything we can do to improve the situation? For instance an error message that would hint at a Java version problem, or a missing `--enable-preview` flag as it was in another case

**Comment by mcollovati** [comment]
For this particular issue, a quick and dirty way to have additional information about the class compiled with an unsupported JDK may be to overwrite the `loadClass` for the `URLClassLoader` instance we provide to `Reflections`.

We can surround the super execution in a try/catch, log the offending class and propagate the exception.
Another solution would be to subclass `Reflections` and override the `forClass` method to intercept the exception, or just log the type name if the result of the super call is null.
However, modifying the exception handing is not ideal as it may require copy/paste the original method, and adding log messages may produce a verbose console output as `forClass` is used by many methods.
Perhaps the log message can be enabled and disabled with a flag, so we can enable it only on some code paths.

**Comment by diversit** [comment]
Ran into this issue also this morning. Code compiled just fine. Only the vaadin-maven-plugin failed.
So I had to figure out how and where to add the missing `--enable-preview` flag, mentioned by @Artur- , since the compiler clearly had that setting already and the vaadin plugin has no way to add it.
So I figured that the Maven java process should be started with the `--enable-preview` setting.
There are, of course, multiple ways to do this.
- setting JAVA_OPTS does not work
- setting JAVA_TOOL_OPTIONS does work, but not easy to persist with the project.

Eventually settled on adding a `.mvn/jvm.config` with `--enable-preview` to the project. This gets picked up by Maven, see [configurating Maven](https://maven.apache.org/configure.html#mvn-jvm-config-file) and is easy to check in Git so everyone has it.

With this we're able to use Java (21) preview features in Vaadin page classes.
