### ISSUE TITLE
Vaadin abnormal memory consumption - PendingJavaScriptInvocation

### ISSUE THREAD

**Issue by giusdiluca** [vaadin/flow#16572]
### Description of the bug

for a project I'm working on (Spring Boot 2.7.9 + Vaadin 14.9.7) I'm experiencing a strange heap memory usage. Attached to this post you can find the first objects by top memory usage in my application. I see there is a big usage from PendingJavaScriptInvocation and UIInternals$JavaScriptInvocation. The application is accessed by 500 users but only 30-40 concurrently, and I've put some ClientCallable functions to accomplish ARIA accessibility (on row grid buttons) as per the tutorial that can be found here https://cookbook.vaadin.com/aria-label-to-components.

Could you please give some advise on what to put the eye on to understand a so big heap usage ?
![VisualVM](https://user-images.githubusercontent.com/20367954/231511946-5ebcdef0-00b9-4f7b-8e58-6de1869223e5.png)

### Expected behavior

Not so big heap usage by PendingJavascriptInvocation

### Minimal reproducible example

Just analyzing the heap dump

### Versions

- Vaadin / Flow version: 14.9.7
- Java version: 11
- OS version: RedHat 8
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by bwajtr** [comment]
This bug reminds me of a [similar issue](https://github.com/vaadin/flow/issues/14435), however, in that issue, the large number of PendingJavaScriptInvocations caused the server to crash eventually (in a matter of minutes). Also, the root cause of the issue was fixed in 14.8.19... so this is probably something else.

7,5 million instances of PendingJavaScriptInvocations does not seem ok - however, I'm afraid that not much can be said from your screenshot. Any chance to share the dump? If not, then I'm afraid that you'll have to analyse those invocations yourself: 
1. The content of the invocations -> maybe you'll find some reference there which will give you a clue where these PendingJavaScriptInvocations are coming from. This is a screenshot from Eclipse Memory Analyzer - analysing "objects with outgoing references", where you can look up which Vaadin component the invocation is related to (the full component name is pixelated to protect the customer):
![image](https://user-images.githubusercontent.com/1890879/231674370-112e0147-b46d-48dd-8e11-96bea8b0cfc5.png)
2. In a similar way, you can analyse "objects with incoming references" for PendingJavaScriptInvocations to see which objects are holding the reference to the invocation, preventing it from being garbage collected.

**Comment by mcollovati** [comment]
@giusdiluca did you have a chance to analyze a heap dump to detect what components are keeping references to the JS invocation objects, as suggested by @bwajtr?

**Comment by giusdiluca** [comment]
@mcollovati I tried to analyze the heap dump but was not able to detect the components causing the issue. I've recently updated to platform version 14.10.1 and the issue didn't happen again. I don't know if I was lucky or any fix was released... Many thanks again for the support

**Comment by mcollovati** [comment]
There have been a couple of fixes on PendingJavaScriptInvocation since 14.9.7.
I suggest you to upgrade to 14.10.3, that contains some additional fixes.

**Comment by giusdiluca** [comment]
I will do, many thanks for the suggestion

**Comment by mcollovati** [comment]
I'll close the issue.
Please comment here or create a new ticket if you still experience similar problems.
