### ISSUE TITLE
CSS import with ?inline query -> Invalid import

### ISSUE THREAD

**Issue by Silicat-git** [vaadin/flow#16731]
### Description of the bug
In one of our components we imported a Stylesheet like this:
import * as css from "./my-styles.css";

Upon starting the application Vite warns that this use of importing Stylesheets is deprecated and gives us an example to use instead:
Default and named imports from CSS files are deprecated. Use the ?inline query instead. For example: import * as css from "./my-styles.css?inline"

So as suggested we changed the line to:
import * as css from "./my-styles.css?inline"

Now after running the application again Vaadin shows an ERROR about a failed Import.

com.vaadin.flow.server.frontend.AbstractUpdateImports::resolve does not consider the "?inline" of the filename and fails to resolve a path and as such enters the InvalidPathException exception block.

The File loads fine since the styles are applied, but I dont know if it impacts something internally. 

### Minimal reproducible example
Simply import a style in your component like this:
import * as css from "./my-styles.css?inline"

### Expected behavior
No Exception should occur and the path should be properly resolved
### Actual behavior
Path resolution fails and an Exception is thrown (handled by logging)
### Versions:
    - Vaadin / Flow version: 24.0.5
    - Java version: 17
    - OS version: Windows 11
    - Browser version (if applicable): Chrome
    - IDE (if applicable): IntelliJ
    - Development or production mode: Development
    - Project from start.vaadin.com or activated in application: own application, nothing from start.vaadin.com

**Comment by Artur-** [comment]
It is typescript that does not understand the `?inline` style import I suspect

Adding something like
```
declare module '*.css?inline' {
  import { CSSResultGroup } from 'lit';
  const content: CSSResultGroup;
  export default content;
}
```
to `types.d.ts` might resolve it

**Comment by Silicat-git** [comment]
> Ok, missed the part about `InvalidPathException` and `AbstractUpdateImports`. Then it is probably something else

It doesnt exclude the "?inline" after the filename in its search so it will never find a file named my-styles.css?inline

**Comment by Artur-** [comment]
If I 
"Simply import a style in your component like this:
import * as css from "./my-styles.css?inline""

then I get no error

**Comment by gert-dubois** [comment]
In Vaadin 24.0.5 we have the same issue, all our LitElements where we use `import style from './some-style-sheet.css?inline'` give the same error.
Changing to `import * as style from './some-style-sheet.css?inline'` give the same error message.

As well in our case it does not seem to break anything, CSS seems to be applied correctly, but we are still worried this might break something in the Vaadin Build process.

**Comment by gert-dubois** [comment]
> ```js
> import css from "./my-styles.css";
> ```
If you import stylesheets like this Vite will give a warning that importing stylesheets in this way is deprecated (just like the original reporter mentioned).
The suggested solution from Vite is to transform the import statement to:
`import css from "./my-styles.css?inline"`

But when we do this we get a bunch of errors during the Vaadin build on invalid imports. Could you verify again with appending "?inline"

**Comment by gert-dubois** [comment]
@mshabarov I made some small changes to your example to illustrate the issue on Vaadin 24.1.0
[style-lit-element-updated.zip](https://github.com/vaadin/flow/files/11772239/style-lit-element-updated.zip)

I added `vaadin.frontend.hotdeploy=true` to ensure Vite is used when running the application.
When you run the updated example you will see that the entire body of the page is colored green, this is because stylesheets imported like `import css from "./my-styles.css";` are put into the light dom by Vite. 
You will also receive a warning from Vite that CSS should be imported using the `?inline` suffix.

When you append `?inline` you will see that the CSS is now no longer included in the light dom (as intended) but only applied to the shadow dom of the component, but during application start-up you will now get the `c.v.f.server.frontend.TaskUpdateImports  : Invalid import './my-styles.css?inline'` log message.

So while on first sight nothing seems broken, the fact that we get this error message worries us somewhat

**Comment by Artur-** [comment]
This is likely a Windows only issue because on Mac
```
Path.of("foo").resolve("bar?inline")
```

does not throw an `InvalidPathException`, instead it returns `sun.nio.fs.UnixPath@118 "foo/bar?inline"`

**Comment by gert-dubois** [comment]
That would make sense, in our case it would limit the impact since our CI/CD server runs on Linux.
What would be the impact on the Windows dev stations? Because at first glance nothing seemed to break, but I'm also not sure what the TaskUpdateImports code exactly does.
