### ISSUE TITLE
Combine the generated files of the dev bundle

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow#16874]
### Describe your motivation

When a javascript file is updated in the project the dev-bundle is regenerated and a lot of files are removed and recreated (with a different unique name).
So the git status contains multiple updated files and 26 files added and 26 files removed.
That also happen when the Vaadin version is updated.

### Describe the solution you'd like

I'd propose to also combine the generated files into one, so that it wouldn't look so massive change now whenever one updates a Vaadin version or fixes a typo in a javascript file.

See here also: https://github.com/vaadin/flow/issues/16028#issuecomment-1459690490

**Comment by Artur-** [comment]
Does it matter in any way how they are combined or just that it would be one file that always has the same name?

**Comment by jcgueriaud1** [comment]
It doesn't matter to me. I'm not planning to check what's in the file (if I need to debug I will use the frontend hotdeploy).

Maybe @mstahv has another opinion.

**Comment by mstahv** [comment]
I have exactly the same opinion. So far I haven't looked into those files either.

But a perfect solution would be that the file is not stored in source code management system at all. It is a generated file, so kind of against the best practices. If only there was a cloud service that would store the bundles and share them with other who have the same front-end resources 🤪

**Comment by Artur-** [comment]
This could probably be done so that instead of using a dev bundle from `src/main/dev-bundle` (and storing a new one in the same place) we would use `target/dev-bundle` for that. When creating a new bundle we would also compress it (e.g. tar or whatever is fast) as `src/main/dev-bundle/dev.bundle`. When using the bundle  and `target/dev-bundle` does not exist, we would decompress `src/main/dev-bundle/dev.bundle`, if it exists.

There is probably no need to change how we handle the default dev bundle as compressing it inside a jar sounds unnecessary

**Comment by mshabarov** [comment]
**Acceptance Criteria:**
- When building a new custom dev bundle for project, Flow compresses bundle files into `src/main/dev-bundle/dev.bundle` single file, so it would be easier to commit it to the VCS
- Flow decompresses bundle files into `target/dev-bundle` (Maven) or `build/dev-bundle` (Gradle) and uses them in runtime
- Platform should build the default dev bundle as previously without compression
- This approach should be applied to the production bundle for consistency, if no significant obstacles would be found.
