### ISSUE TITLE
Vaadin 24 w/ Push + Embedded Jetty 12 - Multiple Issues

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#16908]
### Description of the bug

This all started when we upgraded to Vaadin 24 on our base project. We use embedded Jetty, so we had to upgrade to Jetty 12 to support Servlet 6.

1. The static file server fails to serve `/VAADIN/static/push/vaadinPush.js`.
2. `@PWA` is not present, yet the generated frontend sources expect `sw.js` and `sw-runtime-resources-precache.js`.

As far as I tested, the issues only occur when push is enabled.

![image](https://github.com/vaadin/flow/assets/17092333/ba01ab08-bafc-4338-8cc2-88007844628b)

### Expected behavior

Self-explanatory.

### Minimal reproducible example

https://github.com/oliveryasuna/vaadin24-embedded-jetty12-bug

Run `main` and navigate to http://localhost:8080. Some errors are demonstrated on first page load; more on refresh.

### Versions

- Vaadin version: 24.0.5
- Java version: 17
- OS version: macOS
- Browser version (if applicable): Chrome or Firefox
- Application Server (if applicable): Embedded Jetty
- IDE (if applicable): IntelliJ IDEA

**Comment by mcollovati** [comment]
I suppose this is related to the Resource API refactoring in Jetty 12.
It seems like that Jetty at boot creates a new `java.nio.file.FileSystems` for every JAR in class path, and then relies on `Paths.get(uri)` to get the resource.

When starting the example application, the first request succeeds and the `/VAADIN/static/push/vaadinPush.js` is served correctly. All subsequent requests, however, fail with a `FileSystemNotFoundException` error.
This happens because `StaticFileServer` also uses the FileSystem APIs to check that a requested resource in a JAR is not a directory, but once the check is done, the file system gets closed.

**Comment by oliveryasuna** [comment]
@mcollovati I had a similar hunch and just realized my tired brain last night forgot to include the detail that it loads on first attempt. That would have saved you some time. Thank you for looking into this. Do you see an official fix around the corner? I am a Prime subscriber.

**Comment by oliveryasuna** [comment]
You're right, it was caching. Thank you.

Am I allowed to fork and open a PR for the fix?

**Comment by mcollovati** [comment]
Sure, contributions are more than welcome
