### ISSUE TITLE
Improve Theme Editor components coverage

### ISSUE THREAD

**Issue by MarcinVaadin** [vaadin/flow#17042]
Goal of this issue is to analyze and extend support for components in Theme Editor.

Vaadin components based on https://vaadin.com/docs/latest/components

Components coverage analysis done by @danielsarkwa-vaadiner https://docs.google.com/spreadsheets/d/1gFAxfpKOntJVXXN9DKTa2_71a2KCRE2NDBOiP3ezRUA/edit#gid=0

### Supported components

Component | Metadata | Comments
-- | -- | --
Accordion | ✅ | 
App Layout | ✅ |
Avatar | ✅ |
Badge | - | span with theme attribute (variant), no variant support for the moment
Board | ✅ | 
Button | ✅ | 
CRUD | ✅ | styling editor dialog not possible due to missing `overlayClassName` API in `vaadin-card` 
Charts | ✅ | basic block properties and data series colors 
Checkbox | ✅ | 
Combo Box | ✅ |
Confirm Dialog | ✅ |
Context Menu | - | mostly as given component feature, should be styled globally
Cookie Consent | ✅ | 
Custom Field | ✅ | 
Date Picker | ✅ | 
Date Time Picker | ✅ | confusing while picking date and time fields
Details | ✅ | 
Dialog | ✅ |
Email Field | ✅ |
Form Layout | ✅ | 
Grid | ✅ | 
Grid Pro | ✅ | cannot style Select editor overlay as it does not have classname
Horizontal Layout | ✅ |
Icon | ✅ | 
List Box | ✅ | 
Login | ✅ |
Login Overlay | ✅ | 
Map | ✅ | basic shape properties only 
Menu Bar | ✅ |
Message Input | ✅ | 
Message List | ✅ | 
Multi-Select Combo Box | ✅ |  
Notification | ✅ | 
Number Field | ✅ |
Password Field | ✅ |
Progress Bar | ✅ |
Radio Button | ✅ |
Rich Text Editor | ✅ |  
Scroller | ✅ |
Select | ✅ |
Side Navigation | ✅ | 
Split Layout | ✅ |
Spreadsheet | ✅ | basic shape properties only 
Tab, Tabs, TabSheet | ✅ | 
Text Area | ✅ |
Text Field | ✅ |
Time Picker | ✅ | overlay is closed on theming due to nested combobox events
Tooltip | - | mostly as input fields feature, should be styled globally
Tree Grid | ✅ | 
Upload | ✅ | 
Vertical Layout | ✅ |
Virtual List | ✅ |

### Summary of findings

- There should be simple way to see states preview and modify styles
- There should be a possibility to apply variant
- Some default values are not present after picking (overlays, some ::parts)
- Styling child items directly on parent editor (tabsheet and tabs, accordion and panels, etc) is not so convenient
- There are CSS properties that should be styled as single property (background-position, -repeat, -size, -image)

**Comment by danielsarkwa-vaadiner** [comment]
Components I've started working on;

1. Date picker
2. Date time picker
3. Accordion
4. Details
5. List box
6. Login
7. Tabs

# Findings

### Findings working on Date picker meta data

1. The editor doesn't show the component default style values for overlay contents on selecting the Date picker component until a change is made.

8. To set the background color for calendar month scroller will need to use `background-image: linear-gradient(#, #);` with other properties but there isn't support for linear-gradient as EditorType.

9. **There isn’t support for multiple css properties and value** - Some simple styling requires more than just one CSS property and value from the editor. For example, when setting the background color for the calendar month scroller, additional properties such as height, width, background-image, background-size, background-position, background-repeat, and position are needed. To simplify this process for the user, the editor can provide a method to set the other properties and values and the user can set the color value without needing to concern themselves with the other properties.

10. There isn't support for styling states. eg: if you want to change the color for selected day or active year, and this also applies for the selected option of combo box and select components. By default they all use `lumo-primary-color`, so perhaps change those should change the `lumo-primary-color` but with a clear indication of it's effect.

### Findings working on Date time picker meta data

1. There isn't support to for group or multiple child component styling. Date picker and time picker has to be styled together from the DateTimePicker component to ensure consistency in style. This also applies for Accordion panels, a single style for one panel should be the style for each panel.

### Findings working on Accordion meta data

1. There is support for theme variant specific styling. eg: If the Accordion not filled, there should be the need to change the background-color, border-radius.

2. There isn't support to for group or multiple child component styling. According panels needs to have a consistent style, but the editor uses classnames to isolate each accordion panel and styles are not applied to the other sibling panels.

3. CSS properties like border-bottom-width is not covered for the accordion panel. Adding border-bottom-width as a style property will allow users to edit the width of the panel divider instead of applying border width around the entire panel.

4. There is a need for `margin-left` style property for specifying the gap between the toggle icon and the summary text.

11. Default variant will need `padding-top` and `padding-bottom` style for specifying the space around the panel. Currently spacing padding applies spacing around the entire panel.

12. Filled variant will need `margin-bottom` to specify the spacing between panels.

### Findings working on List Box meta data

1. `vaadin-item` cannot be selected for styling by the editor because it can't be declared as a variable component. Vaadin list box only accept a string variable.

2. Using child combinator as selector to style list box divider and list items doesn't show the default css values of these two elements.

### Findings working on Login meta data

1. Editor is not able to detect login form when rendered as an [overlay](https://vaadin.com/docs/latest/components/login#modal-overlay)

2. Editor is not able to detect the child components in Login component

**Comment by MarcinVaadin** [comment]
### Findings on Upload:
1. Selectors with child selector are being saved properly but after picking element they are not matched with Theme Editor property making it going back to default:

https://github.com/vaadin/flow/assets/106965834/667e38c3-7514-44de-b420-ec6d70601162

**Comment by MarcinVaadin** [comment]
@danielsarkwa-vaadiner observations from https://github.com/vaadin/flow/pull/17301

### Findings working on Tabs
1. There isn’t support for box-shadow as editor property, the divider on Tabs uses box-shadows

2. There isn’t a way to specify style properties for variants, the divider on Tabs uses box-shadows but vertical variant needs a different sets value to style the width and the horizontal variant also needs a different set of values.

3. There isn't a way to set the width, and color of the Tab divider because the values are defined together as a single CSS property - box-shadow: inset 0 -1px 0 0 var(--lumo-contrast-10pct);. It will need some method to expose only the width and color to user in the editor for styling while it adds the other values and assign it to the box-shadow.

4. There isn’t support for multiple css selectors. To style the selected tab indicator, you will need to use :host::before, :host::after to apply styles.

5. There isn’t support to style multiple tab items together using multiple selectors.

6. Using CSS child selector vaadin-tabs vaadin-tab, editor doesn’t show the default css values but only shows new values set by editor.

7. There isn’t support to set style for states, changing the inactive color for tab item overrides the color for the tab item when selected

8. Editor cannot select disabled tab item

9. Style properties for Tab item has been moved to the vaadin-tabs, leaving vaadin-tab empty when selected for styling. It needs a custom message to inform the user to style from the parent component or disable select for child component.

10. When a tab item has a vaadin-icon, changing it's color overrides the color because it has higher specificity.

**Comment by MarcinVaadin** [comment]
@danielsarkwa-vaadiner findings from https://github.com/vaadin/flow/pull/17316

### Finding on Message input

1. It will be more helpful to be able to set border-bottom for the message item other that border around the entire message item. shapeProperties only have border-width, would be helpful to have border-bottom-width

2. The default style values for vaadin-message, ::part(name), ::part(title) and ::part(message) are empty until you update the style with a new value

3. Avatar component vaadin-message > vaadin-avatar cannot be styled as a child component and vaadin avatar cannot be selected to be styled individually since it’s a slot not a child element to vaadin-message-list.

**Comment by MarcinVaadin** [comment]
### Finding on Spreadsheet

While dynamically creating `vaadin-spreadsheet` element using `document.createElement('vaadin-spreadsheet')`  I end up with:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertRule')
    at bT (spreadsheet-export.js:1478:33)
    at HV (spreadsheet-export.js:2369:288)
    at v_ (spreadsheet-export.js:377:18)
    at GP (spreadsheet-export.js:2279:132)
    at new d7 (spreadsheet-export.js:2053:124)
    at VaadinSpreadsheet.updated (vaadin-spreadsheet.js:179:18)
    at VaadinSpreadsheet._$didUpdate (reactive-element.js:868:1)
    at VaadinSpreadsheet.performUpdate (reactive-element.js:834:1)
    at VaadinSpreadsheet.scheduleUpdate (reactive-element.js:753:1)
    at VaadinSpreadsheet.__enqueueUpdate (reactive-element.js:726:1)
```

**Comment by MarcinVaadin** [comment]
### Finding on Side Nav (by @danielsarkwa-vaadiner on https://github.com/vaadin/flow/pull/17340)

1. There isn’t support for border-width-right or border-width-left, it will be more helpful to set the border style on just one side of the vaadin-side-nav or it's parent wrapper.

2. To ensure consistent styles for multiple vaadin-side-nav and vaadin-side-nav-item elements within a single wrapper, you need to apply global styles. This may not be very helpful when there are multiple side nav (as sub navigation).

3. To make styles consistent for all vaadin-side-nav-item, selectors have been moved to the parent component but styles applied on the vaadin-side-nav-item has flow specificity and can't override parent style.

4. Some style properties on vaadin-side-nav-item label ends up affecting suffix content if it’s a text, eg: badge gets italic style, and leading icon gets the font size style.
