### ISSUE TITLE
When calling a function defined in a webcomponent, I want to be able to receive the return value of the call, so I can build server-side logic that uses the returned value

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#1724]
Using a concrete example: `<vaadin-combo-box>` has a `validate()` method, that returns a `boolean`. Currently it's possible to call this function by using `element.callFunction("validate')` or by using `ui.getPage().executeJavascript(...)`.

But here's no way of getting the return of the function. The function is invoked at the client-side, but the returned value is lost.

Since it's not possible to get the returned value synchronously, a callback on the server side would be needed to invoke the function. Something like: `element.callFunction("validate", Consumer<JsonObject> callback)`.

**Comment by amahdy** [comment]
I'm trying to implement a server-side API for a web component. If I use the WC from JS, I would write a code similar to:

`this.show().then( console.log("success") );`

But right now, the Java implementation of `show()` using `callFunction` has no single way to receive the returned value and confirm the success of the operation on the server side.

Modifying the client-side code is not an option.

**Comment by pleku** [comment]
>But right now, the Java implementation of show() using callFunction has no single way to receive the returned value and confirm the success of the operation on the server side.

Can you elaborate on the specific use case - what is the value that you actually need get back to server side ? Or is there any ? Do you just _need to know_ the method call finished without exceptions ? What issues does it cause you to just _trust_ that the operation was executed on the client side?

I understand that the web component don't fire DOM events for operations that have been triggered in JS, but rather use promises like you described. Would just want to know _why_ and in _what type of cases_ those are used, we haven't run into those that much but that doesn't mean that there isn't any cases.

**Comment by Legioth** [comment]
The case of waiting for a client-side Promise and relaying that to the server can be implemented in this way:

```
@Tag("some-component")
public class SomeComponent extends Component {
  private int nextReturnId = 0;
  private Map<Integer, CompletableFuture<String>> returnHandlers = new HashMap<>();
  
  public CompletableFuture<String> doSomething(String input) {
    int returnId = nextReturnId++;
    CompletableFuture<String> result = new CompletableFuture<>();
    returnHandlers.put(returnId, result);

    getElement().executeJavaScript("this.doSomething($1).then(result => this.$server.handleResult($0, result)", returnId, input)
    return result;
  }

  @ClientCallable void handleReturn(int returnId, String value) {
    returnHandlers.remove(returnId).complete(value);
  }
}
```
This example goes slightly further than the case with `show()` since it also allows the resolved promise value to be passed back.

The same approach can also be used for client-side methods that immediately return a value instead of a Promise. The value is still passed back to the server asynchronously, so `CompletableFeature` is still necessary even though there isn't any corresponding client-side Promise. For this use case, the `executeJavaScript` snippet would be changed to something like `this.$server.handleResult($0, this.doSomething($1));`.

Handling a rejected promise or synchronous exception from the called method is left as an exercise to the reader.

This example uses the `Element::executeJavaScript` shorthand that was introduced in Vaadin 12 / Flow 1.2. With older versions, some additional bookkeeping would be needed to instead use `Page::executeJavaScript`.

**Comment by amahdy** [comment]
@pleku to answer your questions, I will give you the exact scenario:

The web component has a function `show()` that when called, asks the browser to show a native pop-up window to collect some data (credit card data natively). Once the data has been collected, the browser notifies the web component about the status. Such as: "canceled", "timed out", or "JSON with the collected data from the form".

From Java, I need to call `show()` and then get notified when the operation has finished (the return value of `show`). But right now this is not possible, and from servers-side, there is no single way to tell when the operation has finished and what values has returned from the form filling.

I'm not trying to develop a specific tailored component to add to the Vaadin collection, I'm trying to purely act as a developer who wants to integrate a WC into Vaadin. This developer does not want to get into deep details on how the WC is written, he does not want to modify the source code of WC, and he does not want to waste time into calculating possible scenarios on how the server-side will handle the component and work nicely or not.

So things like getting a signal that a function has terminated the execution, finished successfully, didn't finish, are all needed cases as well, as a very simple case like:

```js
let foo = function(a,b) { return a+b; }
```

where I want to be able to:

```java
var foo = wc.callFunction("foo", a, b);
```

**Comment by Legioth** [comment]
I just want to make one thing clear: `var foo = wc.callFunction("foo", a, b);` will not be practical unless someone finds a way of communicating faster than the speed of light or the Java language gets support for transparent asynchronous calling.

What is doable in the scope of this ticket would be something along the lines of `wc.callFunction("foo", a, b).thenAccept(foo -> ...);`. Until then, the workaround from my previous comment can be used as a workaround.

If a future Java version would introduce something similar to `await` that has been in JavaScript for some time now, then it would also be possible to write something like `var foo = await wc.callFunction("foo", a, b);`.

**Comment by Legioth** [comment]
I'm trying to come up with an API for this kind of functionality. So far, I've identified three different alternatives that each has it's own set of pros and cons.
1) Define separate a method with similar arguments as the current method, but returning something like `CompletableFuture<JsonValue>` instead of `void`. To make the Java compiler happy, the method would have to have a separate name, e.g. `executeJavaScriptReturn` or something completely different such as `getJavaScriptResult`.
2) Update the existing method to return `CompletableFuture<JsonValue>`. The challenge here is to know whether someone is actually waiting for a return value. Sending back results for all invocations would not be an option because of the performance overhead.
This basically means that the decision would have to be made right after `beforeClientResponse` depending on whether any listeners have been registered for the result. Furthermore, registering a listener after `beforeClientResponse` would have to be disallowed since the client would then already have received instructions to discard the result.
Knowing whether any listener has been registered is not practical if returning `CompletableFuture` since it has almost 40 different methods for registering dependencies. One alternative could be to return a simpler type that the most basic methods for registering listeners along with a `toCompletableFuture()` method that can be used for composing and that would also explicitly registers that a result should be sent back to the server.
3) Instead of returning a value that can be subscribed to, the result value handler would be passed as an argument to the `executeJavaScript` method. In this way, the used method overload would also indicate whether a result should be passed back, while still allowing to use the same method name. This approach has two problems. First, the distinction between listening to successful versus failed invocations would either require passing two separate callbacks, or alternatively one callback with separate parameters for the value and an error. The second problem is that the varargs of the original method leaves no good place for a callback parameter - it would either have to come before the expression to call or between the expression and the parameters to pass to that expression.

I'm currently leaning towards option 2 with a custom return type. This custom type could also provide a helper for converting the raw json value into some specific type along with shorthands for accepting values and handling errors.

```
public interface JavaScriptResult<T> {
  void then(Consumer<T> resultConsumer);
  void then(Consumer<T> resultConsumer, Consumer<String> errorConsumer);

  <U> void then(Class<U> targetType, Consumer<U> resultConsumer);
  <U> void then(Consumer<U> resultConsumer, Consumer<String> errorConsumer);

  void then(Runnable successHandler);
  void then(Runnable successHandler, Consumer<String> errorConsumer);

  CompletableFuture<JsonValue> toCompletableFuture();
  <U> CompletableFuture<U> toCompletableFuture(Class<U> targetType);
}
```

With this API, the basic example with `function add(a,b) { return a+b; }` could be expressed in these ways:
```
// Works as before. Client-side is not instructed to pass back the result
element.callFunction("add",  2 , 3);

// Manually unpack JSON
element.callFunction("add",  2 , 3)
  .then(jsonValue -> System.out.println(jsonValue.asNumber() + 4));

// Automatic conversion to Integer
element.callFunction("add", 2, 3)
  .then(Integer.class, intValue -> System.out.println(intValue + 4));

// Using CompletableFuture and manual JSON unpacking for more elaborate chaining
element.callFunction("add", 2, 3)
  .toCompletableFuture()
  .thenApply(JsonValue::asNumber())
  .thenApply(number -> number + 4)
  .thenAccept(System.out::println);

// CompletableFuture with automatic JSON conversion
element.callFunction("add", 2, 3)
  .toCompletableFuture(Integer.class)
  .thenApply(number -> number + 4)
  .thenAccept(System.out::println);
```

**Comment by pleku** [comment]
I agree that 2) seems like the best option: it gives us more control over the API and makes it easier to customize it further if required.

**Comment by Legioth** [comment]
For the record, this couldn't be done by changing the return type of the existing methods because of the way it would break binary compatibility for lots of add-ons.

Instead, the new return types are introduced as separately named methods. At the same time, the old methods are deprecated so that we wouldn't have multiple almost identical methods to choose from.
