### ISSUE TITLE
Chart component is not displayed in production mode

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#17694]
### Description of the bug

If a Vaadin application that uses Chart and high tech called inheritance, Chart components are not rendered in production mode.

### Expected behavior

Chart is shown

### Minimal reproducible example

```

package org.example;

import com.vaadin.flow.component.charts.Chart;
import com.vaadin.flow.component.charts.model.ChartType;
import com.vaadin.flow.component.charts.model.ListSeries;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route
public class MainView extends VerticalLayout {

    public static class MyComponent extends Chart {
        public MyComponent() {
            super(ChartType.LINE);
            getConfiguration().addSeries(new ListSeries(1, 2, 3, 4, 5));
        }
    }

    public MainView() {
        add(new MyComponent());
    }
}

```

Compile App in production mode and open the view.

### Versions

Vaadin: 24.1.10
Flow: 24.1.12
Java: Eclipse Adoptium 17.0.2
OS: aarch64 Mac OS X 13.6
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Live reload: Java unavailable: Front end active

**Comment by mshabarov** [comment]
From internal discussion:

> We have a problem with the new `FontIcon` and `SvgIcon` components in production built Vaadin apps. If you have an app with a view that only contains these icons, they are not shown because `<vaadin-icon>` Web Component never gets defined.
As soon as you add an `Icon` to the view, then all the icons show fine. All three icon types extend `AbstractIcon` which has the `AtNpmPackage` and `AtJsModule` for the web component.
The difference between Icon and the other components is that Icon also has:
`AtNpmPackage(value = "@vaadin/icons", version = "24.2.0-alpha16")`
`AtJsModule("@vaadin/icons/vaadin-iconset.js")`
...but it doesn’t seem to be related because even adding the same annotations to the other icons doesn’t fix the issue.
I think it has to do with pre-built bundles. If I add an empty js file to /frontend and import it in the view with `AtJsModule`, then the icons show fine.
Related issue: https://github.com/vaadin/flow-components/issues/5448

**Comment by mshabarov** [comment]
Workaround is to force the production build in Vaadin plugin configuration:
```xml
<configuration>
    <forceProductionBuild>true</forceProductionBuild>
</configuration>
```

**Comment by Artur-** [comment]
Likely this code in UIInternals
```
        if (mightHaveChunk(componentClass, dependencies)) {
            triggerChunkLoading(componentClass);
        }
```

need to check super classes also

**Comment by Artur-** [comment]
which sounds a bit odd because that should already happen as loading of dependencies for the parent class works

**Comment by mcollovati** [comment]
The problem here is that parent dependencies are found, and the chunk loading instruction is added.
However, it tries to load the chunk for the subclass (e.g. `MyComponent`) that is of course not present in the default production bundle.
So probably, as Artur said, we need to call `triggerChunkLoading` for all component ancestors.

Otherwise, we should force a bundle creation for that kind of situation, that however seems not an adequate solution because the default bundle already contains the needed chunk.
