### ISSUE TITLE
Regression after the recent change in runWhenAttached

### ISSUE THREAD

**Issue by vursen** [vaadin/flow#18123]
### Description of the bug

The recent https://github.com/vaadin/flow/pull/18078 has resulted in [various IT failures](https://bender.vaadin.com/buildConfiguration/FlowComponents_Snapshot/466363?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true) in the Flow components, so apparently there is a regression. In particular, one of the components that has broken is ContextMenu. It no longer opens after you detach and reattach the target element. I made an effort to debug this but wasn't successful in pinpointing the specific code fragment that behaves differently.

### Expected behavior

The ContextMenu should work after the target element has been detached and reattached.

### Minimal reproducible example

```java
@Route("context-menu")
public class ContextMenuView extends Div {

    public ContextMenuView() {
        Button target = new Button("Target");

        ContextMenu contextMenu = new ContextMenu();
        contextMenu.setTarget(target);
        contextMenu.addItem("Item 1");
        contextMenu.addItem("Item 2");

        Button detachAttachButton = new Button("Detach/Attach target", event -> {
            remove(target);
            add(target);
        });

        add(target, detachAttachButton, contextMenu);
    }
}
```

### Versions

- Vaadin / Flow version: 24.3
- Java version: 17

**Comment by mshabarov** [comment]
One of the failed cases was for `ComboBox` being detached and attached.
Then after that, once the dropdown is being opened, `ComboBox` tries to refresh all the items and `DataCommunicator` calls `runWhenAttached` for flush request.
But since the `ComboBox` has been attached and detached already, the execution ends up in `StateNode` here
```java
if (isAttached() && (!wasAttached || !hasBeenDetached)) {
            command.accept(getUI());
        } else { ... }
``` 
having `wasAttached`=true and `hasBeenDetached`=true, which skips immediate refresh, but postpones it, however `onAttach` listeners are not fired anymore (because the combobox was already attached before openning the dropdown).

This lead to a spinner and no items in the list.

My conclusion is that the `StateNode` have to call the command immediately in this case and we have to find another solution for issue https://github.com/vaadin/flow-components/issues/1434.

**Comment by mshabarov** [comment]
Patch #18078 has been reverted in https://github.com/vaadin/flow/pull/18131.
