### ISSUE TITLE
Cannot move element to a different UI: can't change id once it has been assigned

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#18390]
### Description of the bug

Cannot move element to a different UI after `removeFromTree()`.

`removeFromTree()` succeeds, but after the removed element is added to a different UI (in the same session) it fails with IllegalStateException: Can't change id once it has been assigned
```
 ~[flow-server-24.2.5.jar:24.2.5]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:459) ~[flow-server-24.2.5.jar:24.2.5]
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$2(ServerRpcHandler.java:440) ~[flow-server-24.2.5.jar:24.2.5]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:440) ~[flow-server-24.2.5.jar:24.2.5]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:323) ~[flow-server-24.2.5.jar:24.2.5]
```
https://github.com/vaadin/flow/blob/47b643689be3d198b8b1a30e163077da9d9f1e0b/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L836-L837 

This issue seems to be related to https://github.com/vaadin/flow/pull/17695, see also https://vaadin.slack.com/archives/C6X43FE8M/p1695724670429019

As a workaround, `removeFromTree(false)` seems to work, but that method is "meant for internal use only".

### Expected behavior

After `removeFromTree()` I should be able to add the element to a different UI.

### Minimal reproducible example

1. Open two tabs of the application
2. In the first tab click "Set target"
3. In the second tab click "Send"

Expected behavior: div should be removed from the second tab and added to the first tab
Observed behavior (Vaadin 24.2): an exception is thrown

The same code works as expected in 23.3.21
```
public class HelloWorldView extends VerticalLayout {
 private static VerticalLayout targetView;

  private Div div = new Div();

  public HelloWorldView() {

    add(div);
    addAttachListener(ev -> {
      div.setText("" + UI.getCurrent().getUIId());
    });

    add(new Button("Set target", ev -> targetView = this));

    add(new Button("Send", ev -> {
      if (targetView != null && targetView != this) {
        div.getElement().removeFromTree(false);
        targetView.add(div);
        targetView.getUI().get().push();
        return;
      }
    }));
  }
 }
 ```

### Versions

- Vaadin / Flow version: 24.2.6

**Comment by tepi** [comment]
> As a workaround, `removeFromTree(false)` seems to work, but that method is "meant for internal use only".

This seems a bit weird considering implementation of `removeFromTree()`:
```
public void removeFromTree() {
    removeFromTree(false);
}
```

**Comment by javier-godoy** [comment]
@tepi 
https://github.com/vaadin/flow/blob/9a593fc243c19095f02a7eb67cbde1849d9f9543/flow-server/src/main/java/com/vaadin/flow/dom/Element.java#L525-L527

**Comment by enver-haase** [comment]
I remember having played with moving a component from one UI in one session to another UI in another session, that was with Vaadin 8 IIRC. I found this quite useful, given that the idea was (and still is) that all state is known by the server and entirely reproducible onto the client side, including a fresh new one in another session. Could even make for a great test case for Vaadin components (we had bugs in the past in the Grid where state was in the client side with no or broken bookkeeping on the server side).

**Comment by knoobie** [comment]
I personally would vote against this. Allowing users to move components between different UIs / browser tabs feels utterly wrong imho. I can understand the need from e.g. chats that should only be visible on the active tab in a multi tab situation but I would say it's better to re-create the components in that case and just restore the session-wide available data to the other tab. This complexity doesn't seem worth the potential downsides this could cause especially when the session should shrink and components *should* have less instead of more session affinity.. shamelessly tagging @Legioth

**Comment by Legioth** [comment]
> I would say it's better to re-create the components in that case

We rely on the ability to explicitly detach a node from one UI and attach it to another UI for implementing `@PreserveOnRefresh`. If someone else wants to build their own variant of `@PreserverOnRefresh` as an add-on, then they should also have that possibility. I don't think we should require them to do it with a less convenient DX that would require the application developer to provide a callback that re-creates the components.

If we look at things through a really wide perspective, then all UI should preferably be declared as a function of state so that the same state (which shouldn't be directly attached to any UI instance) can be used to create identical components for multiple UIs. But that's not how Flow works today.

> Looking at this comment https://github.com/vaadin/flow/issues/9376#issuecomment-1807618311 makes me think the current behavior is intentional.

We don't want to make it possible to move elements by accident - it must be an explicit action specifically for this particular purpose rather than something that happens automatically when you just do `layout.add(child)`. So it's intentional that you must use `removeFromTree()` but it's not intentional that you get an `IllegalStateException` after using `removeFromTree()`.

What is it that makes `removeFromTree` work as expected with `@PreserveOnRefresh` but not with the case reported in this ticket?

**Comment by tepi** [comment]
> What is it that makes `removeFromTree` work as expected with `@PreserveOnRefresh` but not with the case reported in this ticket?

With `@PreserveOnRefresh`, `com.vaadin.flow.dom.Element#removeFromTree(boolean)` is called instead of the one with no parameters. Calling this was mentioned as a workaround in the original description, but seen a suspicious since its javadoc states `This method is meant for internal use only.`

**Comment by mshabarov** [comment]
This makes sense to me to fix this behaviour, and here are pros that I see:
- This worked in Vaadin 23, so looks like a regression. However, that might work accidentally in 23.
- The way how Flow reacts to this use case is wrong. It doesn't say any human readable message, nor it gives any instructions. I'd want to improve that.
- Moving a component from one UI to another requires non-trivial codes: removing from one UI, storing a reference to another UI and adding it into that UI. Flow's API does not encourage devs to access another UI rather than the UI to which the current request belongs to. So I think that the chance to shoot in the leg by accidentally moving the component is very low. The example above shows it.

Thus, I agree to fix it.
But has no clear use case still. If the intension is to have a "pinned" tab in browser with only one component (e.g. some live dashboard) and not have it in the other tabs, this IMO is a bad UI design. Would be better to extract the component into a separate view, probably a protected one if one doesn't want to show it to all.

**Comment by subITCSS** [comment]
The use case we have is that a user want for example extract a grid into another tab to have a wider view on it. The original UI shows a placeholder which is smaller and the new tab which shows this component (and has a much bigger size) can be used and has all the references to the "old" ui. So the user can have multiple tabs which appears in use like one in interaction. When the user close the tab the component which was extracted is placed to the originally place and replaces the placeholder with its grid for example.
