### ISSUE TITLE
Detaching Listeners on resync

### ISSUE THREAD

**Issue by mbrunenieks-proofit** [vaadin/flow#18414]
### Description of the bug

There is an issue we encounter when dealing with RPC resynchronizing event. When this event happens, prepareForResync internal method is called
```
    protected void prepareForResync() {
        visitNodeTreeBottomUp(StateNode::fireDetachListeners);
        visitNodeTree(stateNode -> {
            getOwner().markAsDirty(stateNode);
            stateNode.wasAttached = false;
            stateNode.isInitialChanges = true;
            stateNode.hasBeenAttached = false;
            stateNode.hasBeenDetached = false;
        });
        visitNodeTreeBottomUp(sn -> sn.fireAttachListeners(true));
    }
```
The problem for us is that in our solution on component detach event we unregister a bunch of listeners but we do not recreate them on component attach (we do it on component creation - attaching them to the UI could happen sometime later).

This causes an issue when resync happens - our UI becomes unresponsive (all listeners are gone).

Reimplementing the solution to recreate listeners on AttachEvent would be quite challenging.

### Expected behavior

There could be some flag either in the DetachEvent or StateNode class that would indicate that detaching happens because of resync.
We would not remove our listeners in that case. Our initial testing with such patched solution looks promising.

### Minimal reproducible example

It was reported on some other issue that resync event happens more often on Mac computers.

### Versions

- Vaadin / Flow version: 23
- Java version: 17
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by tepi** [comment]
> on component detach event we unregister a bunch of listeners but we do not recreate them on component attach

In addition to failing on resync, this approach also means that once you attach your components somewhere in the component tree, you can't move them anywhere else anymore since that will also cause a detach-attach cycle.

I'd advice for either changing the logic so that the listeners are added in attach, or so that they are not removed on detach at all. This should be ok since once the component is disgarded (removed from component tree for good) the listeners will be eventually garbage collected along with the component itself.

**Comment by mshabarov** [comment]
Closed as a duplicate
