### ISSUE TITLE
[Spike] Make sure that IDE auto-completion works well for React and Web-components

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18638]
### Describe your motivation

This is a spike issue aiming to test the IDE (mainly IDEA and VS Code) auto-completion for Vaadin React and Web-components in Hilla/Hybrid apps with Vaadin 24.4, i.e. if IDE suggest a proper tag/component when you develop component/view with React/Web-components.
Based on the found anomalies, further issue can be created.

### Additional context

Vaadin 24.4.

**Comment by tarekoraby** [comment]
Tested React autocomplete using https://github.com/vaadin/flow-hilla-hybrid-example/tree/v24.4.

## On VSCode: autocomplete is NOT working 👎 

![image](https://github.com/vaadin/flow/assets/42799254/db8743b4-49a3-4619-9351-8ecdabb2a5fc)

![image](https://github.com/vaadin/flow/assets/42799254/609e4fdc-24d2-4c2b-b966-da67e7e3e914)

## On IDEA: autocomplete works fine

![image](https://github.com/vaadin/flow/assets/42799254/f599e800-3987-4fad-81ec-f756fa8e5d59)

![image](https://github.com/vaadin/flow/assets/42799254/bfa5c34d-a010-48f6-9620-3b52ebc17e2b)

**Comment by tarekoraby** [comment]
The issue in VS Code could be due to `package.json` including both web components and React components. But even if I remove `@vaadin/combo-box` from `package.json` while the app is running, autocomplete isn't still working on VS Code.

I will wait to test autocomplete in web components until we figure out this issue with React components first.

**Comment by mshabarov** [comment]
Auto-completion has been fixed in Flow 24.4.0.alpha12.
