### ISSUE TITLE
JS error: "Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission."

### ISSUE THREAD

**Issue by Haprog** [vaadin/flow#1864]
When using our internal webpage project in the current deployed environment (using Flow 0.1.10-SNAPSHOT) I don't want to see errors in the JS console so that it doesn't feel like something is broken.

Error in JS console:
> Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission.

The error doesn't show up when running the project locally.

**Comment by kolle1986** [comment]
Deployed to AWS and same issue happens. Any progress with this?

**Comment by Legioth** [comment]
@kolle1986 A fix for this issue was merged almost two years ago. If you're seeing something similar, then it's probably a different issue. Could you please create a new issue with instructions on how to reproduce.

**Comment by kolle1986** [comment]
@Legioth Not sure, but after decreasing heartbeat interval to 45 seconds, this is not happening anymore. I see now same repeating reconnects, dough: "Scheduling heartbeat in 45 seconds" and after that "Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent). - wasClean: false" "Push connection closed" "Reopening push connection". 

I know this isn't maybe related to this issue because it is possible that aws server (configuration) disconnecting opened websocket connections...
