### ISSUE TITLE
Exclude react components from package.json if not needed

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#18676]
### Description of the bug

When I develop a flow application without any usage of react components, I expect no react components to be added to my package.json - this includes the free and the commercial components. Even tho it's possible to disable react completely by using reactEnabled=false, this would result in some kind of legacy mode which is not wanted in the long run. 

### Expected behavior

When I exclude hilla and only use flow's default, no react components should be present in the application's package.json for compliance reasons. 

Suggestions: 
- add the react components annotation to a flow- react package which I can exclude 
- add the react components to the hilla-react spring boot starter which I can exclude 

### Minimal reproducible example

Any 24.4 version. 

### Versions

- Vaadin / Flow version: 24.4+

**Comment by caalador** [comment]
ReactComponentAdapter and parts will be mvoed to its own module in #18699 after that the idea would be that if this module is not available in the project then we would not add the `react` packages (at the moment this is only `react-components`) from versins.json

**Comment by knoobie** [comment]
Thanks! This sounds like a good solution for me and easy to add to the migration guide.

**Comment by knoobie** [comment]
@Legioth / @mshabarov I tried update a shared lib of mine to the latest beta (from 24.9). I was hoping to get rid of all my custom excludes (hilla etc.) and I was hoping to get also rid of my exclusion for `flow-react` because it was only needed to be excluded so that the `package.json` is not polluted with `react-components`. 

With 25.x and the default Hilla exclusion, I'm wondering where are you even needing the `react-components` if it's only for hilla.. should the linked PR be changed so that Hilla is pulling in the react-components instead of `flow-react`? or does `flow-react` require `vaadin-button` and all other components as react instead of web-component?

**Comment by mshabarov** [comment]
`flow-react` artifact acts as a marker in Vaadin Flow for adding `react-components` into `package.json` besides it's main goal - [React/Flow integration](https://vaadin.com/docs/latest/flow/integrations/react), i.e. API for wrapping a third-party react component into Java component. `react-components` may be used in this integration (e.g. if you want to wrap the third-party component into layout or decorate it with other Vaadin components), so they are not only for Hilla apps.

At some point, when we discussed artifact optimizations, we decided to not touch `flow-react` artifact, because we want to keep the seamless integration between Flow and React. Also React Router is the default routing tool, whereas we deprecated `vaadin-router`, better to use same routing and components altogether by default. From these two perspectives, it seems more logical for us to keep `flow-react` included and give a way to opt-it out, if needed.
