### ISSUE TITLE
PiT 24.4: when migrating a project to 24.4 modifications to tsconfig.json and types.d.ts should throw once

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#18984]
### Description of the bug

When frontend configuration files require updating, Flow does not perform these updates in a batch. Instead, it executes separate modifications and throws errors, necessitating the user to run the application multiple times after the migration.

NOTE: it makes several projects run with the PiT script fail because it only considers one extra run

### Expected behavior

It should throw just once

### Minimal reproducible example

The attached project is a 24.3 project with the needed modifications to run in 24.4, but types.d.ts, tsconfig.json and package.json have not been modified.
Unzip the project and run mvn, you need to run 3 times

[latest-lit-top.zip](https://github.com/vaadin/flow/files/14647570/latest-lit-top.zip)

### Versions

- Vaadin / Flow version: 24.4.0.alpha15

**Comment by Legioth** [comment]
> It should throw just once

My expectation is that it wouldn't throw at all but instead just update everything and then work without requiring the user to re-run anything.

**Comment by Legioth** [comment]
If I understand it correctly, what happens is that Flow creates a backup of the file in the project and then puts a new file with the default content in its place. The throwing happens only if the backup cannot be created because an old backup is in the way.

It might be enough to just clarify the error to inform that it's caused by leaving old backups behind. A more laborious approach would be to resolve the naming conflict by optionally adding a unique postfix to the name of the new backup file.

**Comment by cromoteca** [comment]
This could be solved by using [createTempFile(String prefix, String suffix, File directory)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#createTempFile(java.lang.String,java.lang.String,java.io.File)) to create the backup file.

**Comment by mshabarov** [comment]
> The throwing happens only if the backup cannot be created because an old backup is in the way.

Back-ups are not created for `tsconfig.json`.

Sounds to me like `tsconfig.json` and `types.d.ts` need more unification and better DX.
Here is a draft of requirement that we might want to apply to both `types.d.ts` and `tsconfig.json` to address this issue:
- [ ] Flow creates back-up files always when it want to modify the content, for `tsconfig.json` at least I couldn't find back-up login in `TaskGenerateTsConfig` 
- [ ] File auto-update creates a back-up file in a unified format with a timestamp or other unique postfix that avoid copy conflicts if file already exists.
- [ ] Flow doesn't throw nor doesn't it log a warning if files have one of the default contents from known templates.
- [ ] Flow collects all the warning messages to user during build time and only shows them once in the end. This addresses the issue above and also should address an issue when you got tons of exceptions in the log, preventing you even read the message, because any page refresh request triggers this exception.
- [ ] Flow doesn't log a stacktraces, only messages/banners.

Also, probably it's better to log a warning, rather than throw, but I have no strong opinion regarding it.
