### ISSUE TITLE
static resources can not be imported from parent theme

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/flow#19045]
### Description of the bug

When I import a theme from another jar via `"parent": "parent-theme"` in theme.json, I'm getting a 404 in the browser.

NPM Dependencies are loaded via Dependency class in jar module and svg sources are imported via theme.json and assets notation.

### Expected behavior

the keyboard icon in Hello World View should be visible.

### Minimal reproducible example

See https://github.com/SebastianKuehnau/demo-theme-app

import to IntelliJ and run Demo Spring Application

### Versions

- Vaadin / Flow version: 24.3.8
- Java version: 21
- OS version: MacOS 14.4.1
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
It could be related to `CssBundler` not rewriting URLs if a physical file cannot be detected under the theme folder.
For imported assets URLs this does not hold, but, being relative path they probably should be rewritten as `VAADIN/themes/<resolved-asset-path>`.

Also, I'm not completely sure the URL in `src/main/resources/META-INF/resources/themes/components-lib/components/keyboard-icon.css` is correct, since it references a resource in the same folder (`url('./fontawesome/icons/keyboard.svg')`), but the assets URLs should be relative to the theme folder, so it should perhaps be `url('../fontawesome/icons/keyboard.svg')`

**Comment by SebastianKuehnau** [comment]
Thank you for your answer and the suggested workaround.

Unfortunately this doesn't work and the icon is still not loaded.

**Comment by mcollovati** [comment]
Actually it was not a workaround, just a doubt I had 😁

**Comment by mcollovati** [comment]
The issue in production build is `vaadin:theme` Vite plugin not considering themes from jar, so computing wrong theme name paths when rewriting URLs

```ts
    async transform(raw, id, options) {
      // rewrite urls for the application theme css files
      const [bareId, query] = id.split('?');
      if (
        (!bareId?.startsWith(themeFolder) && !bareId?.startsWith(themeOptions.themeResourceFolder)) ||
        !bareId?.endsWith('.css')
      ) {
        return;
      }
      const [themeName] = bareId.substring(themeFolder.length + 1).split('/');
      return rewriteCssUrls(raw, path.dirname(bareId), path.resolve(themeFolder, themeName), console, opts);
    }
```

The function accepts CSS from both `frontend/themes` (`themeFolder`) and `jar-resources/themes` folders (`themeOptions.themeResourceFolder`), but then it computes `themeName` only considering `themeFolder`, resulting in a wrong value for JAR resources. This causes it to provide the wrong theme folder to `rewriteCssUrls` that is then unable to find the resources referenced in CSSs and to correctly rewrite them.

**Comment by mcollovati** [comment]
So, I can see two changes to be applied to fix this issue:

- make CSSBundler rewrite relative URLs prepending `VAADIN/themes/` even if the resolved file does not exist (because it is probably an asset). This should fix DEV mode
- Change the `vaadin:theme`  `transform` function in `vite.generated.ts` so that theme name and folder are computed correctly. This should fix production build
   ```ts
      const resourceThemeFolder = bareId.startsWith(themeFolder) ? themeFolder : themeOptions.themeResourceFolder;
      const [themeName] =  bareId.substring(resourceThemeFolder.length + 1).split('/');
      return rewriteCssUrls(raw, path.dirname(bareId), path.resolve(resourceThemeFolder, themeName), console, opts);
   ```
