### ISSUE TITLE
PiT 24.4: error in dev-mode when IDE recompiles the hybrid project 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#19450]
### Description of the bug

When application is running in dev-mode, and there are changes in sources that require compilation, dev-mode reloads and there is client-compilation error

![error](https://github.com/vaadin/flow/assets/161853/f0421285-7b8e-4f10-9553-d25c88be2370)

### Expected behavior

no error when recompiling

### Minimal reproducible example

- unpack attached project and run `./mvn`
- check that project works by visiting http://localhost:8080/
- open separated terminal and run `./mvn` compile
- check that the app reloads, and there are errors in the other terminal and in browser
[hackathon-24-4.zip](https://github.com/vaadin/flow/files/15434260/hackathon-24-4.zip)

### Versions

- Vaadin / Flow version: 24.4.0.beta5
- Java version: 21
- OS version: mac / windows
- IDE: Eclipse

**Comment by mcollovati** [comment]
The issues is similar to https://github.com/vaadin/flow/issues/18907, fixed by https://github.com/vaadin/flow/pull/19037.

Basically, when starting in dev-mode, `TaskGenerateReactFiles` that creates `routes.tsx` file is called by `DevModeInitializer`.
However, when you compile with maven, the prepare-frontend goal does not run that task, so the `routes.tsx` is not tracked as generated file and removed by `TaskRemoveOldFrontendGeneratedFiles` as last step of the goal.

We should probably add `routes.tsx` as *knownUnhandledFile* in `TaskRemoveOldFrontendGeneratedFiles`

**Comment by mcollovati** [comment]
And similar problems also happen with other Hilla generated files that are not created during prepare-frontend.

**Comment by mcollovati** [comment]
Actually, I don't know how we can detect Hilla generated files without recursively parsing all imports, starting from `endpoints.ts`

**Comment by mcollovati** [comment]
I just noticed that there's a `generated-file-list.txt` that can probably be used

**Comment by manolo** [comment]
@mcollovati @mshabarov this also happens in a 24.3 Hybrid application, you can check by using flow-hilla-hybrid-example branch v24. 
Shouldn't this be cherry picked or issue being re-opened?

**Comment by mshabarov** [comment]
Let's cherry pick it.
