### ISSUE TITLE
Add note to @Layout that Hilla needs ts file changes

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#19904]
Update the `@Layout` javaDoc to mention that for Hilla
usage you need to also enable the feature in the ts file.

**Comment by Legioth** [comment]
Could it instead be automatically enabled? The problem is that we cannot later on change it to be automatically enabled without at that time introducing a breaking change.

**Comment by caalador** [comment]
So you would suggest that hilla views would be opt-out instead of opt-in?

**Comment by Legioth** [comment]
Why not as long as we can do it without performance impact in the cases where there are no candidate layouts?

**Comment by caalador** [comment]
So that would mean 
 - flowLayout -> noAutoLayout
 - having a `@layout.tsx` would auto opt-out all under that layout, 
 - we need to propagate `@Layout` data to `RouterConfigurationBuilder` so we get the correct routes setup. (does this mean sending layout paths to the client?)

**Comment by Legioth** [comment]
> flowLayout -> noAutoLayout

I don't think that's necessary. This is not a HTML attribute which means that it's fine to have `true` as the default value (though the implementation would have to make a distinction between actual `false` and the falsey `undefined` value). Negations in property names are often problematic since special cases lead to weird double negations like `noAutoLayout: false`.

> having a `@layout.tsx` would auto opt-out all under that layout

Yes

> we need to propagate `@Layout` data to `RouterConfigurationBuilder` so we get the correct routes setup. (does this mean sending layout paths to the client?)

Yes. And the layout paths that are sent to the client have to be filtered by access control. And preferably also filtered by whether there are actual client-side views that would use the Flow layout to avoid sending a long list of layout paths that cannot be used.

**Comment by caalador** [comment]
Actually was thinking that as a simplification Flow could generate a layouts.json on into the generated folder that would then be taken into account when generating the file routes as there we have better visibility on layouts and by referencing the layouts we would automatically add the flowLayout flag for all applicable routes if no flag has been set.

.layouts.json
```
{
 {
  "path": "/"
  },
  {
   "path": "/user"
  }
}
```
Then we wouldn't meet any problems and extra filtering on the security either.
