### ISSUE TITLE
Implement a possibility to optimize development environment for Vaadin/Hilla dev without components

### ISSUE THREAD

**Issue by johannest** [vaadin/flow#19948]
### Describe your motivation

Use case: an application development where no Vaadin components are used, but only Vaadin/Hilla TypeScript generation and middleware are utilized. 

For production builds unused Vaadin/React component will be removed more or less automatically. But, to be able to speed up the development environment it would be good to have a possibility to exclude all Vaadin components from the package.json.

### Describe the solution you'd like

A setting or a documented dependency exclusion for excluding Vaadin components from the package.json.

**Comment by Legioth** [comment]
To clarify, this means that neither `@vaadin/react-components` nor any WebComponent like `@vaadin/button` should be included in the application's `package.json` while still including framework parts like `@vaadin/hilla-frontend` and `react-router-dom`.

**Comment by mshabarov** [comment]
**Acceptance Criteria**
- [ ] Vaadin provides an opt out option that during build time excludes Vaadin web-components packages from `package.json`, so these packages are not installed which makes build and development faster
- [ ] In conjunction with `react.enable=false` and excluding `flow-react` dependency, this opt-out option should result in excluding Vaadin React and Web components from project, e.g. neither `@vaadin/react-components` nor any `@vaadin/button` installed
- [ ] Even after these exclusions, `package.json` includes npm packages that are needed for Hilla and Flow frameworks to set up routing, code generation, theming and other core features, e.g. `@vaadin/hilla-frontend`, `react-router-dom`, `@vaadin/router` and etc.

Proposed solution and implementation details: 
- The implementation can be placed into `TaskUpdatePackages::updatePackageJsonDependencies` that has a filter for React already.
- Platform needs a meta data for web-components, so that Flow would know what exactly to exclude.

**Comment by mshabarov** [comment]
Closed, as all three related PR are in.
