### ISSUE TITLE
`writeBean` no longer works with `record`s

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#20552]
### Description of the bug

We just upgraded from 24.4.12 to 24.5.5 and whenever we call `Binder#writeBean`, where the argument is a instance of a `reocrd`, it throws with the message: `writeBean methods can't be used with records, call writeRecord instead`. However, the `writeRecord` method does not accept any parameters.

### Expected behavior

Should work as it used to.

### Minimal reproducible example

Easy to reproduce.

### Versions

- Vaadin / Flow version: 24.5.5
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
Binder in Vaadin 24.4 does not support records.
Being records immutable, Binder cannot "update" a given instance, so `writeBean` would not work since it has void as return type.
`writeRecord` has been introduced to allow Binder to return a record instance based on the data on the fields.
Of course, record support can be further improved, for example by adding a `R writeRecord(R)` method. See #20318 to follow the discussion.

Here's the relevant documentation https://vaadin.com/docs/latest/flow/binding-data/components-binder-load#using-java-records-with-binder

**Comment by oliveryasuna** [comment]
Understood. I was in a rush to push out a hotfix and didn't think about that. It's very obvious. I think it's appropriate to close this isuse.
