### ISSUE TITLE
HTML and BODY height defaults to 100% makes no sense for normal web sites

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#2344]
`BootstrapHandler` have implicit `styles.appendText("html, body {height:100%;margin:0;}");` in `setupCss` method. While this might make sense for desktop-like apps, it is not true for normal web sites, since it restricts the height of html and body to the height of the viewport instead of the height of the page content.

**Comment by jouni** [comment]
If a user wants to build a layout that covers the entire viewport, I would use `100vw` and `100vh` instead, no need to mess with the height of the `html` and `body` elements.

Setting the margin/padding of the viewport still probably needs some API.

**Comment by pleku** [comment]
So @jouni should we instead remove the default style that we have completely for `<html>` `<body>` ? Then we would probably just have to documentation on what you should, probably (?), put to your main layout (`height: 100vh; width: 100vw;`)

Otherwise we would have to add similar feature as with `@Viewport("<meta name=\"viewport\" content=\"width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes\">")` and `@ViewportGenerator(MyGenerator.class)` where the user can statically or dynamically define the body styles... So I think removing those completely could be nice.

**Comment by pleku** [comment]
Recapping after f2f discussion with Jouni:

### Acceptance Criteria

- We should not set any default styles for `<html>`, but remove this from `BootstrapHandler`
- We should not set any `height` for `<body>` element in `BootstrapHandler`
  - We still want to override the default `margin: 8px` for `<body>`(?)
- We should have documentation on how to customize the styles for the `<body>` for the initial page response, using e.g. what #3010 will provide
- We should have documentation that recommend setting `height: 100vh; width: 100vw` for the Apps main layout / template.

**Comment by pleku** [comment]
After this is done, we should update our starters to use a `PageConfigurator` to apply the `height: 100vh; width: 100vw` for the app.

**Comment by Legioth** [comment]
I'd suggest also introducing a shorthand annotation for making the configuration without having to define a configurator, but this can be done as a separate ticket.

The API could be something like this.
```
@BodySize(height = "100vh", width = "100vw")
public class MainLayout extends Div implements RouterLayout {
  [...]
}
```

**Comment by caalador** [comment]
@Legioth Can you make a separate ticket on the possible wanted shorthand.
