### ISSUE TITLE
Improved keyboard shortcuts API

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#2449]
For instance, if i want to have a search field with a search button, pressing the enter key should also perform the search. in V8 i could use a click shortcut, but couldn't find anything similar for Flow.

I'm sure it can be done with JS, but it would be really, really good if there was a Java API for it.

**Comment by heruan** [comment]
IIRC in Framework 8 one should set the shortcut on the button itself, i.e. `button.setClickShortcut`, and many would set the `Key.ENTER` to trigger the button, even if outside related form elements, whereas a *shortcut* should be more a <kbd>CTRL</kbd>+<kbd>H</kbd> and similar.

To approach the more common "trigger button when user presses enter on certain fields", I see this use case better:

```java
TextField field = new TextFied("Search");
field.addKeyboardListener(Key.ENTER, event -> button.click());
```

**Comment by heruan** [comment]
I think this is not completely fixed, since there are two use case of shortcuts:

1. add a key listener to a field to shortcut an action;
2. add a key listener to the whole document to shortcut focus on some element.

Also, keyboard event introduced in #3110 aren't used yet anywhere.

**Comment by SomeoneToIgnore** [comment]
GitHub autoclosed this, thanks for noticing.

**Comment by pleku** [comment]
### Acceptance Criteria
Make it possible to achieve the following things with new keyboard shortcuts API:

_When building a form, I want to add a keyboard shortcut to for the save button, so that I don't have to do it for every single field in the form separately (and save time) and I can perfect the UX for my App_

_When building an app, I want to add a keyboard shortcut for focusing search field or some other  action, so that I can have good UX in the app as the user can access certain features of the app easily from anywhere_

There is a tutorial for the API and it is taken into use in the starters.

**Comment by pleku** [comment]
Sorry, I was intentionally lazy about _some other action_ as I didn't want to list all the things here as those have already been listed elsewhere, but sure lets add what we identified e.g. in the bookstore starter:
- logout
- apply login input with enter
- navigate to some view
- focusing the search field
- creating a new book entry
- saving the edited form
- closing/canceling the form

From these we ended up into the following more detailed use cases:
- focus shortcut (inputs)
- click shortcut (buttons)
- generic shortcut (execute certain method on server)
