### ISSUE TITLE
Layouts or Component API needs click listeners

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#2465]
sometimes you need an action to happen when clicking on an area with several components in it, se e.g. double-clicking individual items in TodoMCV; http://todomvc.com/examples/angularjs/#/

Adding the listener to Label is not enough in this case, as e.g. the area around a button also needs to trigger the action.

**Comment by pleku** [comment]
Probably would not make sense to apply `ClickNotifier<T extends Component>` to all components that implement [`HasComponent`](https://vaadin.com/api/platform/13.0.0/com/vaadin/flow/component/HasComponents.html) or  components based on [`HtmlContainer`](https://vaadin.com/api/platform/13.0.0/com/vaadin/flow/component/HtmlContainer.html), but at least
- `VerticalLayout`, `HorizontalLayout` and `FlexLayout` in vaadin/vaadin-ordered-layout-flow
- `FormLayout` in vaadin/vaadin-form-layout-flow

### Acceptance Criteria
- Add the `ClickNotifier` to the layouts mentioned above in their repositories
- Add a unit test that uses the API so that it cannot be that easily accidentally removed
