### ISSUE TITLE
Migrate Vertical/HorizontalLayout to use the corresponding Vaadin webcomponents

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2475]
The elements team just released https://github.com/vaadin/vaadin-ordered-layout , which contains the base webcomponents to build Vertical and Horizontal layouts in Flow.

**Comment by pleku** [comment]
Should only require changing `FlexLayout` to use `Tag(Tag.DIV)` instead of ´super(new Element("div"));` and then override that in `VerticalLayout` and `HorizontalLayout´ with `Tag("vaadin-horizontal-layout")` and `Tag("vaadin-vertical-layout")`.

No need to switch repository for this ticket, or use WebJars.

**Comment by pekam** [comment]
Shouldn't this still include adding the WebJar to `demo-flow-components` at least? How to otherwise make sure that the `HtmlImport` works since the bower-stuff is already removed from the demo?
