### ISSUE TITLE
Make Flow Spring starter module

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2585]
See https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-custom-starter-module-starter.

So it should work as Vaadin 8 FW Spring integration: it should work out of the box without 
need to create extra classes and extra functionality (no special Servlet or extra config).
Only presence of Flow and Flow Spring add-on should be enough to use Flow in the project.

In case if additional config is needed then it should be possible via `@Configuration` , properties and other Spring mechanisms.

**Comment by pleku** [comment]
When this is done and released as a part of some Vaadin 10 release, we should inform our friend at Pivotal so that we can get this to start.spring.io

I think we should probably separate FW and V10. Now it lists _Vaadin_, should we override that or add another option, e.g. _Vaadin Flow_. ping @Legioth @mstahv

**Comment by mstahv** [comment]
I'll discuss with Stephane about this in Devoxx. One option is that it could go out maybe as "Vaadin 10 beta/alpha" until the final is out. Then get back to just having Vaadin there when we are confident with V10.

**Comment by pleku** [comment]
@mstahv we have hopefully completed everything needed for this, just waiting until there is a flow release (1.0.0.alpha7) and another V10 platform release. If there is a way to verify that we have everything needed, please let us know.
