### ISSUE TITLE
Allow to obtain the browser's timezone info server-side

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#2592]
It would be great if Flow provided the browser info, exactly as provided by the `WebBrowser` class in Vaadin 8. However, it would be great if the browser's time zone was provided as well, exactly as stated in https://github.com/vaadin/framework/issues/7911

**Comment by Legioth** [comment]
Will be included by default when we migrate changes from 8.2. I'll close this ticket so that it won't remain open by accident.

**Comment by Legioth** [comment]
This feature should have been picked by https://github.com/vaadin/flow/issues/2885 that ported all changes that went into Framework 8.2, but it, along with potentially some other enhancements have accidentally been omitted. See https://github.com/vaadin/flow/issues/3592 for more details.

**Comment by Legioth** [comment]
It seems like migrating vaadin/framework#7911 wouldn't be enough since there is no code for collecting any similar parameters from the client and sending them to the server, even though the server-side code for accessing the values is still present. I created https://github.com/vaadin/flow/issues/3657 for restoring that functionality.
