### ISSUE TITLE
Flow silently won't fill in final properties of a model item when being transmitted from client to server

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#2636]
I have a Kotlin-based model item being transmitted to the client and then back to the server (in BeverageBuddy this `ReviewsList.edit` method is called, with the `Review` class). In Kotlin, by default all properties (that is, getters and setters methods) are final. Flow won't complain, but the Review class will appear in the `edit` method with all fields being `null`.

The coder may find this behavior surprising; also it is not clear what course of action should be taken to remedy this. There should be at least a warning in the console that some fields are not final for field BlahBlah and won't be transferred by Flow.

Flow could perhaps go even further, consider that an error and fail with an exception, since final getters and setters are rare in Java world. After all, if the class itself is final, Flow will throw an exception.

**Comment by Legioth** [comment]
I think throwing would be the best approach here

**Comment by denis-anisimov** [comment]
It's funny that this ticket looks quite simple at the first glance.
In reality I don't even see a way to fix it properly.

The number of facts are:
- we don't care whether the property is `final` or not. The bean is proxied. So its getter and setters don't update/return the property value. They deal with our own internal classes which stores the value. This internally stored value is updated/returned. The property value is totally ignored.
- as mentioned above: we proxy the class so that its methods are proxied and our internal method is invoked when the getter/setter is invoked on the proxy.
- final methods can't be proxied and it means that our logic is never invoked in this case
- it's totally fine to have final accessors. E.g. the `Object` class has `getClass` `final` getter. Which means that the developer may extend some existing binary class with `final` getter/setter and use it as a bean.

The result is: 
- we can't do anything when final getter/setter is called at any time sine we just don't know when it happens. And those methods are not proxied. So we cannot throw at all when final accessor is called.
- we can't throw if the bean has final getter/setter. As I mentioned every class has at least one final getter `getClass`. We of course can hardcode this specific method and exclude its check in our code. But I don't see why we should exclude this specific method from our checks and check any other final accessor.
- The only thing we can do: introspect all accessors of the bean when the model is created and somehow warn via the logger that the bean has final accessors which may cause problems (the important thing is: they _MAY_ cause the problem. Because it might be that those accessors won't ever be called assuming they are proxied). Here we can hardcode and exclude `getClass` from those warnings to avoid spam with obvious methods. But a warning is almost invisible. And I don't think it's a good solution in the end.

So it's not easy issue at all.

**Comment by denis-anisimov** [comment]
Technically, one should prefer interfaces (not classes) as a model type which has no such issues at all.

An option could be : deny classes as model type. But I think it's not a good solution either.

What we can do: log (with a level more severe than WARNING) that class is used as a model type instead of interface (always log it). And say there that we recommend to use interfaces. And list all properties in the class which can cause an issues (e.g. they have `final` accessors).

This can be a compromise.

**Comment by Legioth** [comment]
Even if we recommend using an interface for defining the model, the same issue also applies for sub models that are more often reusing some predefined type (e.g. a JPA entity).

I actually think it might be best to throw for custom setters and getters that are `final` (i.e. whitelisting methods defined in `Object`) since there is no case where it could work as expected. The developer can avoid the exception for reused typed by selectively using `@Exclude` for properties that are not supported.

**Comment by mvysny** [comment]
I like Leif's proposal: it will work by default in Java world, it will fail with an informative error message in Kotlin and there is means to resolve this, either by marking setters non-final or excluding them.

**Comment by denis-anisimov** [comment]
Well, I still don't see why we should emphasize `Object`'s methods (and exclude them by default).

But I don't see any other good solution here. And it's true that normally accessor methods aren't `final` so we may just throw if it happens.

In the end here is what should be done:
- `PolymerTemplate` should introspect model properties in its CTOR.
- Most likely this should be done on the very first `getModel()` method call (which is done in the `PolymerTemplate` CTOR anyway).
- Find all accessors which are `final`.
- Filter `Object`'s accessors (like `getClass()`).
- All other accessor should not be `final`.
- Throw an exception ( `IllegalStateException`) with informative message (list all final accessors) if there are `final`  accessors and a recommendation how to fix this (use `@Exclude` annotation).

**Comment by mvysny** [comment]
Thank you, the new Flow works awesomely and indeed fails with an exception which lists all of those fields. A minor bug: every property is listed two times:
```
...
java.lang.IllegalStateException: Bean type 'class com.vaadin.starter.beveragebuddy.backend.Review' cannot be used in the template model because it has accessors which cannot be proxied:
property 'date' has final getter 'getDate'
property 'score' has final getter 'getScore'
property 'count' has final getter 'getCount'
property 'name' has final getter 'getName'
property 'category' has final getter 'getCategory'
property 'date' has final setter 'setDate'
property 'score' has final setter 'setScore'
property 'name' has final setter 'setName'
property 'count' has final setter 'setCount'
property 'category' has final setter 'setCategory'
Use @Exclude or @Include annotations to limit properties to use in the model so that all properties with final accessors are excluded from the model
...
```

**Comment by denis-anisimov** [comment]
Well, the reason is simple: every property is printed out with the method which is `final`.
If you have only one `final` accessor then there will be only one line with its name.
You have both getter and setter final so every property is printed twice but the message it not the same.

As I understand you suggest to combine accessors in one line and print one line per property which contains all final accessors instead of splitting them into two lines.
That makes sense though it's so minor issue that I don't even know when we will have time to fix it (even though it's easy to express this in words it will require some not trivial efforts to implement this): technically the lines are different.

Anyway, please create another ticket with this issue. This one considered as closed.

**Comment by mvysny** [comment]
Oh hell, I have totally missed that :( Sorry about that. It makes sense now, no need to fix anything.
