### ISSUE TITLE
add support for Long arguments in @ClientDelegate methods

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#2681]
As a developer I want to use arguments of type `long` in my `@ClientDelegate` methods (in the same way as I can use `int`, `String` or `boolean`).

`Long` is commonly used for entity IDs, so a typical use case would be having a `LongToStringConverter` to convert longs into strings to pass IDs to the client side, and then passing them back to the server with `@ClientDeligate` methods.

Currently I would have to do a conversion manually (which means, I would also need to take care of possible conversion errors -- and that is easy to forget):

```java
@ClientDelegate
private void addComment(String orderId, String message) {
	presenter.addComment(Long.parseLong(orderId), message);
}
```

Whereas it should be:
```java
@ClientDelegate
private void addComment(String orderId, String message) {
	try {
		presenter.addComment(Long.parseLong(orderId), message);
	} catch (NumberFormatException e) {
		// In this case we need a descriptive diagnostic error message
		// to help identifying and fixing the cause of the wrong parameter type.
		// It would be best if Flow handles this for me.
	}
}
```

**Comment by Legioth** [comment]
One small gotcha here is that the full 64 bit range cannot be represented as a JS number since the  native numeric type in JS is double-precision IEEE 754, thus only preserving 52 bits of precision when mapped to an integer type. To see this in practice, try logging `Long.MAX_VALUE` in a JS console.
```
> console.log(9223372036854775807)
9223372036854776000
```


On one hand, it would be convenient to support `Long` in this context. On the other hand, there's a risk of WTF moments in cases when the numbers would be truncated.

**Comment by vlukashov** [comment]
From my perspective it would be totally OK to convert Java longs into JS strings, not into JS numbers (as long as it's clearly stated in the documentation along with the underlying reason you've just mentioned). That would eliminate the JS `number` overflow concern.

It can be as well a developer choice: use one conversion strategy by default (I argue that should be Long to String) and allow developers to overwrite it with another one if they need it.

**Comment by pleku** [comment]
We concluded that we could add the support for `Long`, `Double` and  `Enum` at the same time. 

The documentation should contain information on the supported types.

**Comment by denis-anisimov** [comment]
I don't think I understand the initial issue and further discussion here.

1. `Long` argument in `@ClientDelegate`method.
You can declare a method with `long` as a type on Java side.
But how do you get `long` value on the client side ?
It's not possible since JS doesn't support `long`.
So what type of value you want to pass into the @ClientDelegate`method on the client side?
It's not clear for me.

2. You are talking about conversation.
Conversation on the server side. 
Does it mean that you want to pass e.g. a `String` argument on the client side and get `Long` on the server side?
That looks like a completely new feature which requires design: of course it's not only about those two types. It's quite generic feature which means that we should be able to know which types are "compatible" (which type can be converted and how to another type).
Also it will require SPI so that the conversation becomes extendable.

3. `Long`, `Double` and `Enum`.
`Long` - is discussed above.
`Double` may be implemented right now. No need to invent any converters.
`Enum` is kind of the same as `Long`. There is no such thing as enum on the client side.
How do you get the `Enum`  value on the client side ?
Do you get it from the server side and expect that it's a JsonValue received as a result of communication ?
Or you have e.g. a `String` that represents `Enum` and you want to get it on the server side as an `Enum`  ?
It's again the question of generic converters feature on the server side.

The converters feature requires some discussion since it may be done in a generic way (keeping in mind extendable approach with possibility to allow users to register custom converters) or it may be done via hardcoding.

So it looks like the description of the ticket "add support for Long arguments in @ClientDelegate methods" has quite far relation to the feature which is requested in reality.

At least the ticket should be clarified. And as I said: it requires some discussion and design.

**Comment by vlukashov** [comment]
I am following the discussion in this ticket, and, as the original ticket author, I can confirm that the proposed changes meet my expectations well. If the ticket title is ambiguous, please change it to something that is more clear.

Once again, the original use case was that there are `Long` IDs (originating from the JVM on the server side). These IDs are passed to the client side (_automatically_ converted to strings) and are kept there unchanged with the sole purpose of passing them back to the server. Then they are passed back to the server in a `@ClientDelegate` method, but on the way back the automatic conversion is missing.

**Comment by denis-anisimov** [comment]
OK , so your usecase is:
- `String` on the client side and you pass it on the `@ClientDelegate`.
- You want to declare `@ClientDelegate` method on the server side which accepts `Long` ( not a `String`).

I'm pretty sure that I understood you correctly but please correct me if not.

So it's actually about possibility to have automatic converters on the server side for `@ClientDelegate` method arguments.
Quite generic feature.

**Comment by Legioth** [comment]
Hardcoded support for converting String from the into a `Long` or some enum type based on the declared type of the parameter would be a very useful feature on its own. Adding some kind of SPI for making it possible to support even more types should imho be a separate issue that we might consider after hardcoding the suggested simple shorthands.
