### ISSUE TITLE
It is not possible to configure all necessary properties for Flow when using Spring Boot

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2766]
Compare [Spring Boot add-on for Vaadin Framework](https://github.com/vaadin/spring/blob/master/vaadin-spring-boot/src/main/java/com/vaadin/spring/boot/internal/VaadinServletConfigurationProperties.java) to [Spring Boot add-on for Flow](https://github.com/vaadin/flow/blob/master/flow-spring-addon/src/main/java/com/vaadin/spring/VaadinConfigurationProperties.java). I think we should have the same properties configurable (if they still exist in Flow).

**Comment by denis-anisimov** [comment]
This is kind of invalid bug.
The link for Flow properties class is wrong.
But you are comparing two properties classes in FW8 add-on and Flow add-on.
Those properties classes are Spring Boot properties.
It means that they can't be used with Spring MVC application.

So in Flow add-on only two properties because they are used before Servlet is created.
All other properties are init parameter properties and since they should work for both Spring Boot and Spring MVC they are done in a different way in the common `SpringServlet` class: https://github.com/vaadin/flow/blob/master/flow-spring-addon/src/main/java/com/vaadin/spring/SpringServlet.java.

All FW8 properties are there and even more.

So either the bug should be closed as invalid or it should be about `VaadinConfigurationProperties` class which should contain all those properties. Though I cannot even imagine why (they either will never be used or we will need a lot of duplication code to allow those properties outside of Spring Boot).

**Comment by pleku** [comment]
Alright, my bad. The [documentation](https://github.com/vaadin/flow/blob/master/flow-documentation/spring/tutorial-spring-configuration.asciidoc) makes no distinction about which configuration properties are configurable with the `vaadin` namespace, it kind of just says _all properties_, so I thus looked only at the configuration class.
