### ISSUE TITLE
Port the DataGenerator concept from FW8 to Flow

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2787]
With the implementation of `ComponentRenderers`, some problems emerged - for example, how to revalidate the renderered components when the internal data changes (when data is updated or removed for example).

Also currently there's no plugable mechanism on the Flow's Grid to detect when a subset of items is being sent to the client. That set of items is needed to determine which components should be created/rendered.

DataGenerators in FW8: https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/provider/DataGenerator.java

Related to #2720

**Comment by Legioth** [comment]
I would suggest two changes compared to the design of `DataGenerator` in FW8:

1. Simplify `DataCommunicator` implementation to only have one `DataGenerator` instance. It's instead the responsibility of the component implementation to delegate handling into e.g. separate columns.
2. Make `generateData` return `JsonObject` instead of receiving a precreated instance that might already contain some fields.
