### ISSUE TITLE
Feature: Use slf4j-api as a logging frontend

### ISSUE THREAD

**Issue by jreznot** [vaadin/flow#2799]
Now, slf4j-api is an industry standard for Java frameworks and libraries. It would be great if we have SLF4J logging in Flow from the start, so we will not need to change logging principles later.

The Simple Logging Facade for Java (SLF4J) serves as a simple facade or abstraction for various logging frameworks (e.g. java.util.logging, logback, log4j) allowing the end user to plug in the desired logging framework at deployment time.

SLF4J is just API, so libraries can use it safely, app servers will not conflict with it.

**Comment by Legioth** [comment]
One thing to keep in mind here is that Flow itself should only depend on the API, but all our starters and demos would need to have an actual implementation in their `pom.xml` so that messages would actually be logged.

Another factor here is that changing the logging API is a breaking change, it would thus be preferable to get this done this before the first stable version (it would otherwise have to wait for the next release train).

One last remark is that once this is done, we should also configure the validation builds for all modules to fail if the JDK logging API is accidentally used.

**Comment by SomeoneToIgnore** [comment]
Breaking change: need to warn users that they need to provide an implementation in their projects.
We might also consider falling back to jul, if no implementation found.

**Comment by SomeoneToIgnore** [comment]
Now we don't log a thing by default.
