### ISSUE TITLE
Investigate a workaround for https://github.com/vaadin/flow/pull/2845

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#2862]
The fix is reverted in https://github.com/vaadin/flow/pull/2861.

Investigate whether it's possible to workaround the issue.

As a suggestion:
- use non-default CTOR of `WebJarAssetLocator`
- implement a custom strategy to get the path index similar to `getFullPathIndex` (which is used in default CTOR).
- the implementation may be the same except that it should catch the exception and ignore it
- or it may be another implementation

May be totally different way could be used to workaround this.

May be it shouldn't be fixed at all.

**Comment by Legioth** [comment]
Another alternative could be to make an upstream PR to extract the parts that reference thrid party classes into a separate class that is never referenced until actually encountering a `vfs://` resource URL.

**Comment by heruan** [comment]
I'm not sure how this is really failing. The class from the provided repository is already never referenced until `accepts("vfs")` returns `true`, i.e. when encountering a `vfs://` resource URL.

So why it was failing on `flow.app.fi`? I investigated this further, and I suppose `flow.app.fi` uses Tomcat, which might use Apache VFS which is different from JBoss VFS: in this case the locator would trigger the wrong handler for the same protocol, and fail.

**Comment by denis-anisimov** [comment]
That explains at least why it works on Jetty so that it passes the validation.

**Comment by heruan** [comment]
Mine's just a hunch, I didn't find references about Tomcat using VFS and I'm not experienced with it to it so I can't tell for sure. Indeed, I just tried Tomcat 9.0.1 and it didn't provide any `vfs://` URLs.

It *seems* like `flow.app.fi` is providing `vfs://` URLs, otherwise I can't explain why the exception gets thrown… But I do not have access to the server configuration, so I can't investigate any further.
