### ISSUE TITLE
Scrollable interface

### ISSUE THREAD

**Issue by haiwan** [vaadin/flow#2905]
Will it make sense to add an interface to easily enable a component to scroll? For example, after implementing the Scrollable interface, user can say div.enableScrollVertically(), div.enableScrollHorizontally() or div.enableScroll(). So that user can easily make the component scrollable without having to deal with CSS.

**Comment by Legioth** [comment]
In practice, the needed CSS is nothing else than setting `overflow` (or `overflowX`/ `overflowY`) to `auto`. Even though it's a really small CSS addition, it's still something that Java-centered developers might not be familiar with. Getting the API as an auto complete suggestion in the IDE also beats any "manual" approach.

**Comment by rolfsmeds** [comment]
There's a separate issue for creating a separate scroll container component: https://github.com/vaadin/vaadin-core/issues/217
Which I think is a better idea since simply adding overflow:auto to a flexbox-based layout is not enough (in a vertical layout, flex-shrink:0 also need to be set, and in a horizontal layout the component alignment may need to be adjusted, so, TL;DR, it quickly becomes complicated and can have unexpected side effects)

**Comment by mshabarov** [comment]
Closed, because Vaadin includes `Scroller` component in latest versions.
