### ISSUE TITLE
Difference between RouterInterface::navigate and UI::navigateTo

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#2918]
I'd expect to do this to navigate programmatically:

```java
String url = router.getUrl(MyDestination.class);
router.navigate(ui, new Location(url), NavigationTrigger.PROGRAMMATIC);
```

This effectively loads `MyDestination`, but it does not update the browser location which still shows the previous one.

**Comment by pleku** [comment]
Looks like a bug to me, I'd expect it to push a new history state entry in the browser. Another thing is, that would one want to have an option to replace the current entry instead of replacing ?

**Comment by heruan** [comment]
I've just discovered that in `UI.navigateTo` the state push is done before calling `Router.navigate`, so using `UI.navigateTo` works as expected. So, I understand the proper method to navigate programmatically is via `UI.navigateTo` and not `Router.navigate` (which can be still used if I don't want the browser location to change).

**Comment by pleku** [comment]
At least the javadocs for `RouterInterface::navigate` could be fixed to cover the difference between `UI::navigateTo`. Another thing is that why is the methods named differently...

**Comment by heruan** [comment]
Plus, `UI::navigateTo` right now takes only strings; overloads taking `Component`/`HasUrlParamenter` would be very useful.

**Comment by denis-anisimov** [comment]
What I'm going to do:
- rename `UI::navigateTo` to `UI::navigate`.
- don't change the behavior of `Router::navigate` (still won't update the URL).
- add javadoc explaining the behavior.
- won't add overloads for `UI::navigate` taking `Component/HasUrlParamenter` for now.

The reason for the last item is: we still use `RouterInterface` as abstraction for routing because the old routing is not removed yet. But `HasUrlParamenter` belongs to new `Router` only. And there is no methods which allows to translate `Component/HasUrlParamenter` to URL (via `RouterInterface`) like this `String url = router.getUrl(MyDestination.class);` (here you are using new `Router`).
Ot means that overloaded methods in `UI` will work _ONLY_ if new routing is enabled. But it's confusing since we are defining the API.

So this request makes sense but it should be made as a separate ticket. And it won't be done right now. It should be done once old routing is removed.
