### ISSUE TITLE
ComponentRenderer makes Grid irresponsive

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/flow#2935]
Grid with ComponentRenderer freezes whole page when scrolling (or filtering).
example with pretty light Component:
http://flow.app.fi/components/vaadin-grid/using-components

-try to scroll several wheels down. Page is freezed this time
-try to scroll dragging the scrollholder. It is completely not responsive

Same happens for filtering: after call dataprovider.setFilter - it freezes page. Freeze time depends on the result size.

 It takes much more time to render, when more complex Components are used.

**Comment by Legioth** [comment]
There might be two different steps to this that can be done independently:
1) Try to see if there's any avoidable overhead that can be optimized. At least https://github.com/vaadin/flow/issues/2826 could help here.
2) Make the processing done by the renderer asynchronous so that the browser doesn't freeze for long times even if there are complex components.

**Comment by pekam** [comment]
Issue moved to [vaadin/vaadin-grid-flow #3](https://github.com/vaadin/vaadin-grid-flow/issues/3) via [**ZenHub**](https://www.zenhub.com/)
