### ISSUE TITLE
Support for creating multiple bundles based on the input file

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#2944]
For now, this means that you're able to modify the generated input file after it has been generated with all the dependencies from the classpath.

### Acceptance Criteria
I want to be able to create multiple bundles, by defining some hierarchy some way (input file or multiple files ?) for the bundling. As a result I will get multiple bundles that the dependency filter from #2943 knows how to serve. 

There needs to be example of the input file in the documentation.

**Comment by SomeoneToIgnore** [comment]
Now `flow-maven-plugin` generates html file that serves as an input for gulp task: it puts this file into `PolymerProject` and it gets it transpiled and bundled.

What we need to do is the ability for the user to specify a directory with multiple html flies like these in the plugin config.
Then we need to be able to run the bundling multiple times for each of the files (now we run it only once)
After that, we need to merge manifest files generated by the gulpfile into one so that the filter can pick up the manifest and bundles.

**Comment by Legioth** [comment]
How are shared dependencies taken into account if the bundling is run multiple times? Wouldn't there be a risk that the same source file ends up in multiple bundles?

**Comment by SomeoneToIgnore** [comment]
If a user specifies them manually, there will always be a risk.

**Comment by Legioth** [comment]
What can the user do to avoid getting e.g. `vaadin-grid/vaadin-grid.html` included in multiple files if there are multiple views in the application that use Grid, and each view is specified manually?

**Comment by SomeoneToIgnore** [comment]
First of all, move this discussion to the different ticket, this is not related to this problem.

**Comment by SomeoneToIgnore** [comment]
After discussion, have agreed on: `bundle` in our case is something that is close to `fragment` term from polymer-cli: a collection of files that may depend on each other, but have no duplicates inside themselves.
For instance, if there's `index.html` with `vaadin-grid.html` import and `custom-view.html` with `vaadin-grid.html` import and the Flow user wants to have separate bundles for `index.html` and `custom-view.html`, the tool must produce three bundles: one with `index.html` and its dependencies that are not in `custom-view.html` dependencies, one with `custom-view.html` and its dependencies that are not in `index.html` dependencies and a third bundle with shared dependencies that include `vaadin-grid.html`.

**Comment by Legioth** [comment]
There are two different features that are important from the application developer's point of view.

One is to manually define some fragments instead of relying on the not-yet-implemented automatic fragment creation system. This should preferably be designed to work so that the application developer defines some fragments, and then fragments for the rest of the application are supplemented by the automatic creation.

The other feature is some way of controlling the outcome when multiple fragments have a shared dependency. In the Bakery login case, it's desirable that anything used by the login page fragment is directly included in that fragment instead of being split out to a "shared" or "leftovers" fragment. All the other fragments would then depend on the login page fragment if they need anything that is shared with the login page. In the terminology of the Polymer CLI, this is a "bundling strategy". That mechanism is in itself probably too low level for regular application developer use, so it should instead somehow be possible to give indirect input to a strategy provided by us.
