### ISSUE TITLE
Initial Page Settings

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3011]
This is an Epic consisting of, but not limited to, adding the following features to make customizing the bootstrap page response more easier
- Viewport parameters with annotation #3008
- Introduce page configurator #3036
- Html / Body styles #2344
  - the defaults should be sensible and overriding the default should be easy
- Inlining things easily to head & body #3010
  - Favicon
  - Arbitrary meta tags for e.g. OpenGraph integration
- Setting the `lang` attribute for `<html>` in the initial base based on user defined locale #2956
- (Theme, though this is also a separate feature and NOT part of this Epic)

**Comment by Legioth** [comment]
Here's my idea on how these could be configured. I'll use the viewport tag as an example here, but the same approach can also be used for all the other things that we expose as configurable.

One general observation is that these are almost always the same for all parts of the same application, and they are almost always the same for all users, browsers and any other similar variables. I'd thus propose a simple high level API with fully static configuration, and then a compatible low level API that allows defining things dynamically.

The most simple application consists of a single `.java` file that defines a navigation target class. The minimalistic way of configuring the viewport definition for this application is to simply add a `@Viewport` annotation to that class.

```
@Route("")
@Viewport("width=device-width")
public class MyApp extends Div {
  public MyApp() {
    setText("Hello world");
  }
}
```

The next typical step in the evolution of your application is that you introduce additional views and a router layout in which the different views are displayed. To keep the common viewport setting in only one place, the available simple options are either to move the definition to the router layout class or to move the definition to a super class that is extended by all navigation targets. Out of these, the router layout approach is more flexible, easier to maintain and makes it easier to avoid mistakes.

```
@Route(value = "", layout = MyLayout.class)
public class MyView extends Div {
  public MyView() {
    setText("Hello world");
  }
}

@Viewport("width=device-width")
public class MyLayout extends Div {
}
```

If a navigation target or router layout is assigned to a parent router layout, it's seen as a programming error (i.e. a deployment time exception) if it also has a `@Viewport` definition, regardless of whether the parent has one. This effectively forces the configuration to only be on the topmost level, which is typically shared by all navigation targets of the same application. You will not accidentally have an overriding definition on some lower level because that would prevent your application from deploying.

A separate mechanism is provided for the rare cases when it's desirable to have different settings for different sections or navigation targets, as well as for cases when the setting varies based on external factors.

This is achieved by implementing the `PageConfigurator` interface as a replacement or supplement to the declarative configuration annotation. This is again only allowed in a class that doesn't have a parent layout for the same reasons as with the annotations.

```
@Route("")
@Viewport("width=device-width")
public class MyApp extends Div implements PageConfigurator {
  public MyApp() {
    setText("Hello world");
  }

  @Override
  public void configurePage(InitialPageSettings s) {
    if (s.getBrowser().isAndroid()) {
      s.setViewport("width=960");
    } // else, the @Viewport value is used
  }
}
```

`InitialPageSettings` contains setters for anything that can be configurd, getters for declaratively configured settings and various additional data such as `VaadinRequest`, `UI`, and `AfterNavigationEvent`.

The currently implemented SPI for determining the UI's Locale would also be replaced with this mechanism.

**Comment by Artur-** [comment]
This is nice and all but why can't I just supply my own `index.html` and Flow would add whatever internal stuff it needs?

**Comment by Legioth** [comment]
@Artur- That's an interesting approach that might be more suitable for developers embracing front-end technologies, whereas the currently suggested design is more focused on developers that want to stick to Java as much as possible.

Would this happen automatically whenever there's an `index.html` file in some specific location, or would there still be some Java API for explicitly enabling the feature and optionally also selecting which file to use?

**Comment by Legioth** [comment]
A Java API can also offer helpers that are not directly available with a custom `index.html` file.

Some examples:
* Read image metadata to set the `sizes` attribute for icons.
* Built-in constants for typical viewport definitions.
* Generate and refer to strongly cacheable URLs for resources.

**Comment by Artur-** [comment]
Both approaches would probably be useful. When you want to add static content, it's much more convenient to use an HTML editor and write tags. When you want something dynamic, you could then tune that from Java.

How about some convention like "If there is an index.html in `src/main/webapp`, then that it used". Can be combined with some servlet parameter to change the default if needed.

You can then use the available Java methods to further customize, or customize from scratch if you use the autogenerated `index.html

**Comment by Legioth** [comment]
I'm slightly weary of automatically importing an `index.html` since it makes the it quite hard to understand what happens and might cause some surprises. Requiring an explicit declaration from Java, e.g. `@BootstrapPage("index.html")`, might be preferable.

I'd also consider reading the file from the classpath instead of from the servlet context since it's not intended to be served as-is. On the other hand, it might be easier to work with the file if it's in the same location as the resources that it references so that relative URLs would work also without running through Flow. From that point of view, it's still unclear whether `src/main/webapp` or `src/main/webapp/frontend` would be more appropriate.

**Comment by pleku** [comment]
I would not take the route of automatically adding some file, until based on feedback.
Thus on part of this _Epic_ we would provide a way to 
- inline all the things
  - can do what `index.html` would do, but split into several files
- use the `PageConfigurator`
  - can do dynamically what index.html would do, but using these both could cause conflict

**Comment by Legioth** [comment]
I'v extracted the `index.html` idea into a separate ticket: https://github.com/vaadin/flow/issues/3041

**Comment by samie** [comment]
Sounds like `PageConfigurator` API is the dynamic low-level architecture needed in applications, and static (annotations and/or files) are just simplifying (pre-)configuration and thus can be introduced iteratively later? 

The API Leif suggested looks feasible and callback architecture should work ok with modular (eg Spring injected) views. But to be safe here, it should some way expose 'everything' on the page for customisation: 
```
@Override
  public void configurePage(InitialPageSettings s) {
    if (s.getBrowser().isAndroid()) {
      s.setViewport("width=960");
    } // else, the @Viewport value is used
  }
```

**Comment by Legioth** [comment]
Two more tickets that could be taken into account: https://github.com/vaadin/flow/issues/3248 & https://github.com/vaadin/flow/issues/480
