### ISSUE TITLE
As a developer I want to inspect registerred routes

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#3061]
In my use case I would like to create a navigation bar that displays all (first level) views of my application.

The `RouteRegistry` already provides `getRoutes()` but that method is private.

*Denis Anisimov*
> I don't think there is a public API for this.
> `RouteRegistry` contains this info. But its `getRoutes()` method is private. (edited)

*Leif Åstrand*
> Would it make sense to make that method public

*Denis Anisimov*
> Internally it's not needed as `public` for us. But it can be made `public` . Though there are two things:
> - I'm not sure that this class should be considered as public API at all (for external developer usage). May be we need a facade class for this which will expose API
> - `getRoutes()` method cannot be exposed `public` as is. It should be modified to protect internal state from modification.

**Comment by caalador** [comment]
I what format would you expect to get the routes?
`List<String>` or navigation target classes `List<Class<? extends Component>>` or as a Map.
How would you want to know about the optional and wildcard parameters?

**Comment by paulroemer** [comment]
*Denis Anisimov*
> I don't think there is a public API for this.
> `RouteRegistry` contains this info. But its `getRoutes()` method is private. (edited)

*Leif Åstrand*
> Would it make sense to make that method public

*Denis Anisimov*
> Internally it's not needed as `public` for us. But it can be made `public` . Though there are two things:
> - I'm not sure that this class should be considered as public API at all (for external developer usage). May be we need a facade class for this which will expose API
> - `getRoutes()` method cannot be exposed `public` as is. It should be modified to protect internal state from modification.

**Comment by paulroemer** [comment]
For my use case a map `route -> navigation target` is what I need. And I _think_ that this is enough for others, too. 

Exposing too much details will also give others the possibility to implement there own router stuff besides the Flow router (as many customers also implement there own navigator instead of using the provided one by the framework). I guess that is something you do not want.

**Comment by caalador** [comment]
But what do you expect to get for the routes. 
I would expect that you have more need for the `targetRoutes` map instead of the `routes` map.

The `routes` map gives base path + 1-4 targets, where as `targetRoutes` gives all the navigation targets with their corresponding base path.

For both the developer would need to check for parameters and if they are required, optional or wildcard.

What I was asking for was more in line with would you need to have for instance a method `Router::getBaseRoutes` that would return all routes that have a navigation target that is given for the base path (could be the base target or a optional/wildcard e.g. according to the best match algorithm) and ignore the required parameter one.

**Comment by paulroemer** [comment]
Can you give me some examples of what is the base path in this case?
```
[...]
@Route(value = "dashboard", layout = MainApp.class)
public class DashboardView extends PolymerTemplate<ExampleModel> {
```
In this simple case I would expect there one navigation target with route "dashboard".

> The routes map gives base path + 1-4 targets
Can you eleborate that?

**Comment by caalador** [comment]
If the MainApp doesn't define a `@RoutePrefix` then the base path is "dashboard".
The `routes` map would return a object with navigationTargets for the path "dashboard" that could also contain for instance another navigation target:
```
@Route("dashboard")
public class MyWildBoard extends Div implements HasUrlParameter<String> {
    @Override
    public void setParameter(BeforeNavigationEvent event, 
        @WildcardParameter String parameter) {
```
Which would match to "dashboard/*" or we could also have a 3rd target:
```
@Route("dashboard")
public class MyParameterBoard extends Div implements HasUrlParameter<String> {
    @Override
    public void setParameter(BeforeNavigationEvent event, String parameter) {
```
Then for the base path "dashboard" we would have 3 "distinct" navigationTargets for paths "dashboard","dashboard/{string}" and "dashboard/*" that would be resolved in this order.

Also for a setup where we only have one parameter route:
```
@Route("base")
public class MyBase extends Div implements HasUrlParameter<String> {
    @Override
    public void setParameter(BeforeNavigationEvent event, String parameter)
 {
```
Then looking for a route for "base" would still return a Route set, but there would only be available a route that can be reached by "base/{string}". Also the return on this will become more complex when we add more parameter features.

**Comment by Legioth** [comment]
The discussion here indicates that there's a semantic mismatch between the format Flow internally uses for resolving routes and the format that would be natural for application developers to use. I therefore think that the suggestion of creating dedicated API for this is more appropriate than simply exposing the current internal API.

**Comment by caalador** [comment]
Yes. 
The internals should not be exposed, but we would need to have a vision on what users would want to have from the API e.g. "base" routes (routes that match the path perhaps with optional/wildcard parameters), parametrised routes ... what.

**Comment by denis-anisimov** [comment]
This is exactly what I meant by facade.

**Comment by pleku** [comment]
We will want this too for be a basis for our automatic bundling in `flow-maven-plugin`.

**Comment by pleku** [comment]
`When creating an application, I want to get all the registered route-data for my app, so that I can get automatically build a menu, that stays up to date when adding or removing new navigation targets`

The returned `List` should not have error navigation targets. It should have all the registered data available for each navigation target: parent layout, url, parameters, route aliases.
Note that `RouteAlias` can cause the same navigation target to have multiple different parent layouts (or not any).

### Acceptance Criteria
- I can fetch all the navigation targets from somewhere, and it is mentioned in the documentation for `Router`

**Comment by paulroemer** [comment]
Sounds good to me!
