### ISSUE TITLE
Attaching to a polymer template element by @Id fails if there is a truthy dom-if before the element in the template

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3131]
After updating the Flow version from alpha11 to alpha13 I've started getting the following error on the page load: `Element addressed by the path='1,1,0' has the wrong tag name 'TEMPLATE', the requested tag name is 'order-details-brief'`.

Java
```java
@Id("order-details-brief")
private OrderDetailsBrief orderDetailsBrief;
```

The Polymer template:
```html
<iron-media-query query="(min-width: 600px)" query-matches="{{desktopView}}"></iron-media-query>

<div class="content" selected$="[[selected]]">
  <template is="dom-if" if="[[displayHeader]]">
    <div class="group-heading" opened$="[[_showDetailsDesktop(selected, desktopView)]]">
      <span class="main" theme$="[[_getMainFontSize(desktopView)]]">[[header.main]]</span>
      <span class="secondary" theme$="[[_getSecondaryFontSize(desktopView)]]">[[header.secondary]]</span>
    </div>
  </template>

  <div id="wrapper">
    <order-details-brief id="order-details-brief" hidden$="[[showDetail]]"></order-details-brief>
    <slot name="order-details-full"></slot>
  </div>
</div>
```

Apparently, at the run time `<template is="dom-if">...</template>` transforms the DOM _before_ Flow client attaches a server-side instance to a DOM element. At the point when the Flow attachment code runs the DOM in the browser looks different from the source code:

```html
<iron-media-query query="(min-width: 600px)" style="display: none;"></iron-media-query>

<div class="content">
  
  <div class="group-heading">
    <span class="main" theme="l-text">Today</span>
    <span class="secondary" theme="m-text">Mon, Dec 11</span>
  </div>
  <dom-if style="display: none;"><template></template></dom-if>

  <div id="wrapper">
    <order-details-brief id="order-details-brief"></order-details-brief>
    <slot name="order-details-full"></slot>
  </div>
</div>
```

**Comment by denis-anisimov** [comment]
This is because `@Id` collides with template-in-template functionality.
When this happens the implementation chooses template-in-template instead of `@Id` way to report a client side about this.
But template-in-template has a lot of limitation ( this is one of them) and doesn't work in any case.
On the other hand, `@Id` is able to address element in any case.

So we need to correct our implementation so that if the template-in-template is addressed by id then `@Id`machinery should be used instead of addressing element by the indices path.
