### ISSUE TITLE
Stack traces of the exceptions thrown during navigation are lost

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3216]
To reproduce the problem:

1) Create a Component annotated with `@Route`
2) Throw a `RuntimeException` from the constructor of the Component
3) Run the application and navigate to the route

Result: a message is shown in the browser window, but the stack trace is nowhere to be found (not on the client console, not on the server logs).

Example code:

```java
@Route("")
public class ErrorExample extends Div {
    public ErrorExample() {
        throw new RuntimeException("Error here!");
    }
}
```

**Comment by denis-anisimov** [comment]
That happened after change from JUL to SJF4J.
The problem is: we use only logging Facade (SLF4J) which is API.
But there is no SPI implementation (binding) available in the classpath (actually there is one: no op logging).

So it's supposed that you add into the classpath of your project some specific binding which you want to use. Otherwise no-op binding is used which doesn't do anything.

If we add some predefined binding as a dependency to the flow-server then it may cause issues if user specifies its own binding.
So it's not a good solution I think.

But at the moment we definitely have a usability problem: there is exception and it's eaten and invisible. That's very bad and we need a solution for this.

So the options are:
- use some specific SLF4J binding which will log the exception (issues with this approach are described above).
- don't do anything and relies on the user setup (and add a specific binding to all our examples/starters/tutorials). It's a usability problem.
- Some another approach for this specific case (or general).

E.g. we may check that there is no specific binding for SLF4J (via `LoggerFactory.getILoggerFactory()`) at the startup time. By default we will throw a runtime exception with detailed explanation what user need to do. If he doesn't want to use any SLF4J binding then a deployment configuration parameter can be set explicitly to ignore this notification (via the exception).
So if user knows what he is doing then he should explicitly set a parameter which says that no-op logging is fine.

Another approach can be:
- Output the exception stacktrace on the page in `InternalServerError` (that's the class which handles the mentioned exception).
- Again check the binding presence and if it's no-op then output the recommendations how to add binding for SLF4J to get the stacktrace in the console in addition to the browser page (e.g. use slf4j-simple-1.8.0-beta0.jar).

Anyway this requires a design decision.

**Comment by Legioth** [comment]
`flow-server` itself should not depend on any SLF4J logging implementation, but all starters, demos and such should have that dependency (preferably the simplest possible, e.g. `slf4j-simple`).

Doesn't SLF4J already print a message to the console about not doing any logging? In that case, I don't see very much value in us replicating the same logic.

Refusing to deploy (unless explicitly configured otherwise) feels like a quite aggressive solution that I wouldn't suggest based on only one incidence.

Showing a stacktrace on the default error page could be an option as long as production mode is not in use. The error message that is shown on the page could maybe also either say that the stacktrace is logged, or alternatively say that it couldn't be logged because no logger has been configured.

**Comment by Legioth** [comment]
Related: https://github.com/vaadin/flow/issues/3193

**Comment by denis-anisimov** [comment]
>Doesn't SLF4J already print a message to the console about not doing any logging? In that case, I don't see very much value in us replicating the same logic.

It does.
But: this specific issue doesn't strictly relate to the logging (it's actually a consequence of absence of the logging binding but it's absolutely not obvious when you don't get any stracktrace on an exception like here in this issue).

The problem is that : there is underlying issue which is totally not obvious for the end user which hides the exception stactrace. And it's tricky to understand that the reason of stacktrace absence is the absence of the logging binding.
It's a serious usability issue.

>Showing a stacktrace on the default error page could be an option as long as production mode is not in use. The error message that is shown on the page could maybe also either say that the stacktrace is logged, or alternatively say that it couldn't be logged because no logger has been configured.

That looks acceptable solution for me.
So let's go in this way:
- Print the stacktrace on the page _ONLY_ in production mode.
- Check the active logging binding.
- If there is no-op logger then print an additional info message that the stacktrace is not logged because SLF4J is "not configured" (doesn't have binding) and recommendation how to configure it.

**Comment by Legioth** [comment]
I think you meant that the stacktrace should only be printed when production mode is *NOT* active. Otherwise I agree on the summary.

**Comment by denis-anisimov** [comment]
Right, I meant development mode instead. Will correct. Thanks.

**Comment by SomeoneToIgnore** [comment]
What if we fallback to JUL if no implementation found?
