### ISSUE TITLE
Component.getUI() should return UI

### ISSUE THREAD

**Issue by henrikerola** [vaadin/flow#3220]
I think that `Component.getUI()` should return `UI` instead of `Optional<UI>`.

Having `getUI()` to return `Optional` just leads to this kind of code:

`getUI().get().navigateTo("home");`

which doesn't solve any problem, it just adds one extra `.get()` there. Of course, the idea is that developers would use it this way:

`getUI().ifPresent(ui -> ui.navigateTo("home"));`

But I would be more happy to get a NPE during development time, than silently ignore the `navigateTo` call because of an empty `Optional`.

In practice, nobody is going to check if `Optional` is empty or not. I also think that because `UI.getCurrent()` returns `UI`, developers end up using that even I think they should use `getUI()` always when possible.

**Comment by knoobie** [comment]
I would prefer to see it changed to `Result<UI>` to use it like this:

`getUI().ifOk(ui ->...)`
`getUI().handle(ui -> ..., error -> ...)`
`getUI().getOrThrow(NPE::new)`

Or just wait for the Java 9 Feature `Optional#ifPresentOrElse`

**Comment by pleku** [comment]
I've seen this also repeat in some of the demos we have and it doesn't look that nice either (in addition to writing the code).

If the users are not going to do any `null` checks anyway, then the whole point of returning `Optional` is just annoying: it is supposed to make it safer to the users.

A `Result<UI>` or similar is another option, but it also kind of has the same issues that Henri describes. One option I recall we have considered with this or similar cases is to have it both ways:
```java
UI getUI() {...}
Optional<UI> getUiOptional() {...}
```
Which should (hopefully) be easily discoverable and allow you to choose whichever suits the case best.

**Comment by knoobie** [comment]
Sounds reasonable! 

Just my two cents: 
Please name it like you did in `HasValue` - so it's `getOptionalUI` to allow easier discoverability.

**Comment by pleku** [comment]
Yeah right, we should be consistently using the same naming everywhere, thus `getOptionalUI` instead of `getUIOptional`.

**Comment by Legioth** [comment]
I see very little value in a separate `getOptionalUI` method if the return type of `getUI` is changed. `HasValue.getOptionalValue` which was used as an example has the additional benefit of also checking `isEmpty()` in additional to the regular `null` check.

Another question is whether `getUI().get().navigateTo("home")` (regardless of `get()`)  is a good pattern. It has been suggested that there should be static shorthand methods for typical navigation tasks, similarly to how e.g. `Notification` and `JavaScript` are typically used in FW8.

I do in general believe that we should try to provide alternatives to anything that is based on the UI class since its role has been significantly diminished in Flow.

**Comment by heruan** [comment]
Out of the choir, I would rather have `Optional`s for any nullable value instead of null-checking.

> But I would be more happy to get a NPE during development time, than silently ignore the `navigateTo` call because of an empty `Optional`.

@henrikerola in which cases you may want to call `navigateTo` with an empty `Optional`?

**Comment by henrikerola** [comment]
I agree with @Legioth that there is no really use for `getOptionalUI`.

My point is that if `getUI()` returns `null` (or `Optional.empty()`), it's typically a developer mistake:

- trying to call it inside a constructor or
- having an external thread holding a reference to a detached component

And in those cases, as a developer, I just wanna get a NPE.

I don't really see any common use cases for checking if getUI is null (or empty). If the developer has that kind of use case and they want to use Optional, this works always `Optional.ofNullable(getUI())`.

**Comment by Legioth** [comment]
@henrikerola The purpose of returning `Optional<UI>` instead of `UI` is to remind the developer about the potential for those types of mistakes already while writing the code instead of only during runtime. At the same time, there's a risk that developers would quite quickly learn to just put that additional `get()` there without any further thought.

**Comment by ayash** [comment]
Can I know what the reason is to not present the UI?

**Comment by pleku** [comment]
Since the `Optional<UI>` has not created an uproar, I'm closing this one as _won't fix_.
