### ISSUE TITLE
`getModel()` in Template might be public

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3232]
I don't see any strong reason for not being `getModel()` a public method, so as you can set those element properties using type-safe mechanism `myWebComponent.getModel().setFoo(bar)` instead of having to use low-level method `myWebComponent.getElement().setProperty("foo", "bar")`

**Comment by Legioth** [comment]
The model of a `PolymerTemplate` subclass is intended as an implementation detail of that component. Some model properties might be suitable for external use, but other properties might be intended only for internal use (e.g. to preserve invariants).

If the implementation wants to give convenient access to a `foo` property in the model, then the proper solution is to provide a `setFoo` method in the component's own API. This method can then trivially delegate to the model, or alternatively do some additional checks and updates.

An implementation can also choose to make it's own `getModel()` method `public`, but that is something that should be opt-in since Java doesn't provide any means of opting out.
