### ISSUE TITLE
Regression: Critical performance problem in client side when injecting `Id`

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3264]
When upgrading BFF from vaadin 10.0.0.alpha9 to 10.0.0.alpha10, storefront view becomes unresponsive, needing to kill browser process. Server side otherwise seems to be ok.
You can reproduce the issue by changing `<vaadin.version>10.0.0.alpha9</vaadin.version>` with `alpha10` in `pom.xml`

Debugging, I found that commenting that when `OrderDetailsBrief.java` is injected it makes the UI unresponsive

It's not a problem in the grid side, because replacing the `ComponentTemplateRenderer` column definition with normal renderers works as expected. 
 
Note that upgrading to the latest alpha11 does not fix the issue.

**Comment by manolo** [comment]
Checked again, and seems that commenting out the TemplateModel does not fix the problem. The only way to avoid the performance problem seems commenting out the usage of the `<order-details-brief>`, but still need to investigate a little bit more.

```
--- a/src/main/java/com/vaadin/starter/bakery/ui/view/storefront/StorefrontOrderCard.java
+++ b/src/main/java/com/vaadin/starter/bakery/ui/view/storefront/StorefrontOrderCard.java
@@ -13,7 +13,6 @@ import com.vaadin.starter.bakery.ui.view.storefront.event.EditEvent;
 import com.vaadin.ui.Tag;
 import com.vaadin.ui.common.HtmlImport;
 import com.vaadin.ui.event.ComponentEventListener;
-import com.vaadin.ui.polymertemplate.Id;
 import com.vaadin.ui.polymertemplate.PolymerTemplate;

 /**
@@ -39,8 +38,8 @@ public class StorefrontOrderCard extends PolymerTemplate<StorefrontOrderCard.Mod

        private OrderSummary order;

-       @Id("order-details-brief")
-       private OrderDetailsBrief orderDetailsBrief;
+       // @Id("order-details-brief")
+       // private OrderDetailsBrief orderDetailsBrief;

        private OrderDetailsFull orderDetailsFull;

@@ -51,7 +50,7 @@ public class StorefrontOrderCard extends PolymerTemplate<StorefrontOrderCard.Mod

        public void setOrder(OrderSummary order) {
                this.order = order;
-               orderDetailsBrief.setOrder(order);
+               // orderDetailsBrief.setOrder(order);
        }

        public void updateOrder(Order fullOrder) {
diff --git a/src/main/webapp/frontend/src/storefront/storefront-order-card.html b/src/main/webapp/frontend/src/storefront/storefront-order-card.html
index 1756cd6..e98ea34 100644
--- a/src/main/webapp/frontend/src/storefront/storefront-order-card.html
+++ b/src/main/webapp/frontend/src/storefront/storefront-order-card.html
@@ -74,7 +74,7 @@
       </div>

       <div id="wrapper">
-        <order-details-brief id="order-details-brief" hidden$="[[showDetail]]"></order-details-brief>
+<!--         <order-details-brief id="order-details-brief" hidden$="[[showDetail]]"></order-details-brief> -->
         <slot name="order-details-full"></slot>
       </div>
     </div>
```

**Comment by manolo** [comment]
So finally seems that the problem is in the moment that flow parses the template and pick ups components with `id` to inject the child instance in the server component.

In this branch you can see that it does not matter what component you have `order-details-brief` or a simpler `foo-bar`, when flow injects it client side gets frozen. 

https://github.com/vaadin/bakery-app-starter-flow-spring/commit/fe9ab230fa82860d08c8e660d6c53dbc74256686

**Comment by Legioth** [comment]
After some investigation, my conclusion is that the problem is that `SimpleElementBindingStrategy` row 703 assumes that the target element has no shadow root because the element has not yet been attached, even though the reason in this case is that the element belongs to a "virtual child" managed by `<flow-component-renderer>` and has not been attached to the DOM. This causes an infinite loop because `PolymerUtils.invokeWhenDefined` is resolved immediately (but still asynchronously since the API is based on promises) but the element is still not attached to the DOM.

**Comment by denis-anisimov** [comment]
Looks like Leif is right.
At least it's true that there is no shadow root if the element is not attached to the DOM tree.

And in this case I have no idea how to find the element addressed via `@Id` in the element if it has no shadow root.........

**Comment by denis-anisimov** [comment]
So the issue is : 
- grid uses renderer which uses plain virtual children
- so the renderer creates a virtual child to render a cell
- the cell is represented by a component which injects another component
- the cell is not added to the DOM so it doesn't have a shadow root
- `@Id` cannot find the element in the shadow root because there  is no shadow root
- the logic which tries to find an element in the shadow root suggests that every custom element has a shadow root. If it doesn't have it then the element is not defined. And it adds a listener to wait until the element becomes defined and there is the shadow root. But element is actually defined but it has no shadow root because it's not attached.

It's a fundamental problem: it's not possible to find anything in the shadow root if there is no shadow root.

I don't see how to workaround this directly.

What I suggest is:
- every plain virtual children _needs to be added to the DOM tree_ somehow so that it gets its shadow root.
- once it gets its shadow root it should be removed.

So : virtual child should be created, made  hidden, added to the DOM tree, removed when it becomes defined (via `PolymerUtils.invokeWhenDefined`) and made not hidden. Only after this it should be bound.
So that every bound element has shadow root.

**Comment by Legioth** [comment]
Another potential approach might be to hook in to the `ready` or `connectedCallback` functions of the element itself since those will be called at appropriate times. See https://www.polymer-project.org/2.0/docs/devguide/custom-elements#element-lifecycle for more details.

**Comment by denis-anisimov** [comment]
Another proposition is (copied from the Slack discussion):

Replace `ready` with our own function which internally calls the original one plus informs us that we may now execute our logic which relies on shadow root presence.

The `ready` function will be called when the element is attached and it will give us a chance to know when we may execute our own logic.

**Comment by denis-anisimov** [comment]
Blocked by #3276.

This should be doe once there is a way to add a listener available which notifies when the element gets its shadow root .

TODO: 
- identify all places where the check against `null` is done for shadow root.
- replace `whenDefined` listener with listener mentioned above.
- rewrite all GWT tests that uses `whenDefined` (there should be quite many of them) to be notified that there a shadow root.
