### ISSUE TITLE
Performance with fist load

### ISSUE THREAD

**Issue by haiwan** [vaadin/flow#3386]
For a very simple hello world application, it takes about 9 seconds to be loaded. Did the first investigation with XRebel, seems the VaadinServlet.traverseResourcePaths is doing many recursions and took most of the time. See the attached screenshots.

<img width="1317" alt="screen shot 2018-01-24 at 12 55 51" src="https://user-images.githubusercontent.com/3388675/35328933-b1281b92-0106-11e8-806e-51e257c271fb.png">
<img width="899" alt="screen shot 2018-01-24 at 8 50 06" src="https://user-images.githubusercontent.com/3388675/35328938-b46b310e-0106-11e8-955f-dc7520537d63.png">

**Comment by gilberto-torrezan** [comment]
Is it the pure https://github.com/vaadin/skeleton-starter-flow project, or some fork of it with extra stuff?

**Comment by haiwan** [comment]
It's based on skeleton-starter-flow, and even more simple than that.
The difference is that I'm using the Theme(Lumo.class) annotation, but from what I saw, this seems doesn't really make much differences.

**Comment by haiwan** [comment]
Just tried with the latest version of https://github.com/vaadin/skeleton-starter-flow, the same problem, so you can use that one for investigation.

**Comment by caalador** [comment]
Using or not using the Theme doesn't change this in any significant way.
But having production time bundling will affect this a lot, Performance of 48% goes to 86% in production mode for the HelloWorlds demo.

**Comment by OlliTietavainenVaadin** [comment]
This is quite bad for initial developer experience if you're using the standard jetty:run target - it restarts whenever you make a change, meaning most loads are "first".

**Comment by caalador** [comment]
Still the lighthouse is apparently running with the settings
```
Device Emulation Nexus 5X: Enabled
Network Throttling 562.5ms RTT, 1.4Mbps down, 0.7Mbps up: Enabled
CPU Throttling 4x slowdown: Enabled
```

**Comment by johannest** [comment]
Related view from Bakery Flow's testing with JProfiler in the attached screenshot.
<img width="2126" alt="screen shot 2018-01-25 at 13 10 00" src="https://user-images.githubusercontent.com/2297689/35385527-46e061f6-01d1-11e8-8ccc-b37889128c37.png">

**Comment by caalador** [comment]
The idea would be to move the `traverseResourcePaths("/")` from `VaadinServlet` to `ServletVerifier` (name should be changed as then it won't only verify) so that the resources are collected on deployment.

Also remember to add functionality to the spring add-on `VaadinServletContextInitializer` so that the classes get collected when running in boot also.

**Comment by Legioth** [comment]
Slow deployment is just as bad for DX as slow initial request since they are both slowing down the overall development cycle. Why is `traverseResourcePaths` needed in the first place?

**Comment by caalador** [comment]
It's to not eff up theme imports any more than necessary.
We won't rewrite a HtmlImport if we can't find a theme replacement file for it.
The collection is done so we don't try to find the file for each user, but only once.

**Comment by Legioth** [comment]
What about doing each lookup on demand and caching the result instead of doing everything up-front even though most of the results would never be used?

**Comment by caalador** [comment]
The issue with that is that the cache is then for each UI (or we need to create a new one) and we would have to start actually using a URI resolver to handle for instance `frontend://components/login-view.html` so that we would get the base servlet resource path that we should get for this. 
(for that example the path we should check would just be "/frontend/components/" in dev mode, but if it's in a web_jar then we would check wrong and need to add the webjar translation to the check also)

Right now we don't need to know any of this as we do the translation e.g. `frontend://button/src/button.html` -> `frontend://button/theme/lumo/button.html` and then we check if there exists a resource ending with `theme/lumo/button.html`

**Comment by Legioth** [comment]
I don't follow.
* Aren't we already using the URI resolver on the server for figuring out what to look for inside `VaadinServlet.resourcePaths`?
* What else needs to be done than doing the theme translation and then checking if the resulting URL exists in any of these locations?
  * The regular servlet context location.
  * The webjar location that can be looked up in the same way as when serving files from webjars
* Why would the cache have to be UI specific in this case whereas the current solution shares data within the servlet? Is a cache even needed if we only check whether any of those two file locations exist?
