### ISSUE TITLE
Client update allowance for two-way binding property concept is weird

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3495]
`AllowClientUpdates`
`ClientUpdateMode`

There is `ClientUpdateMode.IF_TWO_WAY_BINDING`.

What is two way binding property ?
From the implemented logic I see that the parser checks whether the property is used somewhere in template via `{{property}}`.
That's currently considered as a two way binding property.
Based on the presence or absence the property used in this way the implementation makes a decision whether to allow or deny property update from the client side.

It's not really clear why only properties that are used in the template via `{{property}}` may be allowed via introduced mechanism.
I don't have to use property which I expect to notify the server side via notation like this: `{{property}}`.

I may have a definition :
```
static get properties(){
                return {
                   value: {
                     type: String,
                     value: '',
                     notify: true
                   }
                }
              }
```
I would say that the property `value` defined in the way above is the two way property binding property. And it doesn't matter whether it's used via `{{property}}` notation or not.

**Comment by Legioth** [comment]
First a little background: The idea here is to avoid security issues that would happen if the developer expects model properties to be trusted while the values could be updated from arbitrary JavaScript. To deal with this, model properties are by default only allowing updates to properties in cases when there is something in the template that indicates that updates are expected. It should then also be possible to manually whitelist updates for properties that the default cannot handle.

Detecting `notify: true` is not as clear indication that updates are expected, and is also much harder to detect.

Based on this ticket, I also realized that there's one bug in the current implementation. It should be possible to whitelist updates simply by adding a basic annotation without any value, so that the enum is only needed in special cases. #3497 fixes this case.

**Comment by denis-anisimov** [comment]
The ticket is still sort of valid.
The feature is not entirely clear.

I think that the Javadoc should be improved describing what is written here in all details.
Also it needs to be documented in details in the tutorial (is it documented at all? the documentation is in a different repository nowadays, it's not easy to check it).

**Comment by denis-anisimov** [comment]
See also #3557.

**Comment by pleku** [comment]
I don't understand anymore why we would do anything to this at this point, so closing the issue. Please reopen Denis / Leif if you disagree.
