### ISSUE TITLE
PolymerTemplate parsing is not thread safe in production mode

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3573]
Prerequisite: 
* run in production mode

If two threads enter https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java#L120 simultaneously when the template is not yet cached, the end result is unpredictable.

Both threads will get `useCache=false` and a reference to the same `ParserData` instance. Both threads will then proceed to parse the template and this will fail at some point because of race conditions as nothing inside `ParserData` is synchronized or otherwise designed to be thread safe.

In Bakery tests, you can see this as failures to map fields in templates, e.g.
```
Caused by: java.lang.IllegalStateException: There is no element with id='search' in the template file. Cannot map it using @Id
```
This happens only right after you start the server as the cache is later on populated and used correctly.

The problems appear to be:
* You can't make a cache so that you first check if there is a value, and if not, you populate it with a new value. The operation should be atomic, i.e. `ReflectionCache.contains` should probably not exist at all
* Populating the cache value must happen only once. With the current architecture it would have to happen at https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java#L65
* A `TemplateInitializer` is constructed with a template and a parser. The given parser is not used as a cached version of the parsed template can be used instead. This makes little sense.

Looks like the whole architecture of the class needs to be refactored

Cc @alexberazouski

**Comment by denis-anisimov** [comment]
>The problems appear to be:
>* You can't make a cache so that you first check if there is a value, and if not, you populate it with a new value. The operation should be atomic, i.e. `ReflectionCache.contains` should probably not exist at all

Yes and not exactly.
It's true that it should be atomic. It's true that there should be atomic method which checks whether the value exists and if not then create it (like `computeIfAbsent`). It should be done in this way in the perfectly correct design.
In reality the `ReflectionCache` design doesn't allow to use it for static variable since the value provider passed as an argument cannot be static to be able to calculate absent value.
Also it's possible to have not atomic operations like `contains`. The value still may be calculated if `contains` returns `false` even though after the calculation `contains` returns `true`. The important thing here is the instance which is stored in the cache should be immutable. In the worst case there will be unnecessary computation (which won't happen in most cases at all or will be quite rare).
So technically it's possible to modify the existing code so that it's thread safe at least (and in some cases there will be unnecessary computation).

>* Populating the cache value must happen only once. With the current architecture it would have to happen at https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/TemplateInitializer.java#L65

Doesn't have to be as explained above. It may happen several times (in the worst case). The absolutely necessary thing: the stored value is effectively immutable (cannot be changed after it's stored in the cache). In this sense yes, it should happen only once.

>* A `TemplateInitializer` is constructed with a template and a parser. The given parser is not used as a cached version of the parsed template can be used instead. This makes little sense.

That's true. The current design allows to use different parsers for the same template class but if cache is enabled then in reality only first parser data will be used in the logic. 
Even though there are no other parsers except the default one the logic should take into account the possibility to have another parser and work properly.

>Looks like the whole architecture of the class needs to be refactored

Well, the architecture is the very strong word here but yes, the implementation should take into account the design of the class even though it's totally internal and not supposed to be used externally.
