### ISSUE TITLE
Make flow-server and flow-html-components dependencies in components provided

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/flow#3630]
Currently Flow components (e.g vaadin-icons-flow) have `compile` dependencies on `flow-server` and `flow-html-components`. This makes it hard for Flow application developers to upgrade their flow versions without manually making exlusions.

Example: https://github.com/vaadin/vaadin-icons-flow/blob/master/pom.xml#L36-L45
Replacing "icons" in the URL above with any other component (e.g "checkbox") yields the same result.

Proposal: The component projects should declare a single provided dependency
```
<dependency>
  <groupId>com.vaadin</groupId>
  <artifactId>flow</artifactId>
  <version>${flow.version}</version>
  <scope>provided</scope>
</dependency>
```

[Context](https://vaadin.slack.com/archives/C6X43FE8M/p1519913592000275)

**Comment by pekam** [comment]
I can't make this work because of Jetty. It uses parameter `<useTestScope>` to access the demo files, so I think it should also get the `provided` dependencies, since those are available for `compile` and `test`. So I found another parameter, `<useProvidedScope>` for Jetty, and tried using that, but it doesn't work either. The jetty starts but when opening the demo the browser just shows `404`. No errors or anything.
