### ISSUE TITLE
Div constructor should accept content

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#3662]
When I write  `new Div()`, I want to be able to pass in text content the same way I can when I call `new Span()`.

**Comment by pleku** [comment]
Adding this had been debated for quite some time and many occasions, since some (am I the only one?) have argued that when doing layouting, using `new Div("my-class-name")` would be needed much more instead of `new Div("my text content").

You can do `new Div(new Text("such verbose API"))` for now as a workaround.

I think the HTML components are the first thing I would want to apply a fluent API to. Like `new Div().text("Foobar").className("text-block")`.

**Comment by marcushellberg** [comment]
Yes. Ideally, I would like a fluent API. Especially when creating layouts, it's common to want to create divs with class names. 

My initial ticket was because I felt that it was inconsistent that a Span took in text content in its constructor, but a Div didn't. Both as similar as neither has any specific semantic meaning in HTML. One is just a block and the other is inline.

**Comment by Legioth** [comment]
What about two different static factory methods: `Div.withText(String)` and `Div.withClass(String ...)`? If we're really eager, we could even do `Div.withHtml(String)` as well as icing on the cake.

**Comment by Peppe** [comment]
I ran into an related issue. I had a bunch of HTML snippets in the backend that I wanted to show on in my UI. I wrote `add(new Html(message.getHtml());` where message is the bean from the backend.

I got the problems because some of the backend stuff was just text without root nodes like `lorem <i>ipsum</i>`, some had multiple nodes like `<div>lorem</div><div>ipsum</div>. Doing that caused my app to explode with exceptions on my screen, sayin that I either have 0 or multiple root nodes. I ended up changing my code to `add(new Html("<div>" + message.getHtml() + "</div>"));` to be able to get it working.

I know Html() is another element but it is related. I would hope it to automatically wrap my content to a div if I have zero or multiple roots with an exception in console, pointing me to another method where I can explicitely wrap it and get rid of the warning.

As with the original post, what I would have most wanted to do would have been write  `add(new Div(message.getHtml());` without me having to worry about this. And that's the same constructor @marcushellberg is talking about. Except it would render html :)

**Comment by pleku** [comment]
Shortlist of strings I want to stuff into my divs in the constructor:
- plain text as block content (like the old label component)
- plain text as inline content (could wrap to newline if necessary)
- any safe HTML (like the old label component with html content)
- any unsafe HTML (because I'm bad-ass)
- class name (well, that is apparently that is only me 😢 )

Something else ?

To support all these cases, three options have been presented:
1) Fluent API
2) static factory methods
3) constructors

Unfortunately 1) and 2) are odd in the sense that one would expect to find those as part of the API for all the (html) components then. I would prefer 1) over 2).
3) is closest to what we have now, and could be considered as:
  - `Div(String text)` -> `new Div("this is text");` for plain text content
  - `Div(String content, ContentMode contentMode`) -> `new Div("hello <span>html content</span>", ContentMode.HTML);` with content mode for safe or un-safe html and mayhaps also `ContentMode.PREFORMATTED`
    - I wonder if it is such a bad thing to have to specify the content mode there, it has worked out fine in the framework previously

And as a bonus (?):
  - `Div(String className, Supplier<HasElement[])` -> `new Div("my-css-layout", () -> button1, button2, button3)` // this is quite fugly but cannot use varargs for component since it clashes with the plain text constructor
- `Div(String text, String style)` -> `new Div("my funny label that is inline or wraps if necessary", "display: inline-block;");`

**Comment by tltv** [comment]
Just to summarize what has changed since the ticket was created. Fluent API has not progressed, none of the other similar elements has class-name parameter or content mode parameter in a constructor, and none use static factory methods.

New constructor for text content looks like a winner in the end after all these years.
