### ISSUE TITLE
Properly fix synchronizing JSON objects with cyclic references from client to server  

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3725]
It was fixed earlier for eg. `Tabs` component by removing the object since it was unnecessary.
Here is another fix from @Artur- for handling these cases in TB:
- https://github.com/vaadin/testbench/pull/1022/files

One place where this reproduces is #3356.

Further details:
- https://github.com/w3c/webdriver/issues/1241
- https://github.com/webcomponents/shadydom/issues/217

Please report in this issue if you see this issue reproducing, so we know to prioritize it.

**Comment by Legioth** [comment]
What's the use case for sending raw elements as JSON to or from the server? The receiving end won't have any way of associating the JSON back to an element even though we would "fix" things so that serialization doesn't throw.

**Comment by pleku** [comment]
Synchronizing a property of type `Object` or `Array` to server for any web component.
For `vaadin-tabs` it was because https://github.com/vaadin/vaadin-tabs-flow/issues/25:
```
The problem payload is a rpc array making amSync for items where the items array contains multiple vaadin-tab elements from which we get cyclic exceptions as FireFox parses also __shady, __CE_state etc that should not be parsed for the object.
```

**Comment by Legioth** [comment]
Artur's "actual fix" only relates to how to "serialize" elements as JSON, but they're still serialized in a way that it's not possible to distinguish the element it belongs to without further additions (`JSON.stringify(document.createElement("div"))` returns `"{}"`). This means that a "fix" would make it possible to send useless nonsense information to the server. What's the value of that?

Generic sending of data with cyclic references requires some kind of extension to the JSON format itself, which is a much larger task than the trivial cycle breaking that is necessary for that particular case with Selenium.

**Comment by pleku** [comment]
>This means that a "fix" would make it possible to send useless nonsense information to the server. What's the value of that?

What ? I don't know why we would fix it but making that happen or why do you think I'm suggesting so. I reworded the description.

The point of this issue is about making it possible to pick any objects to synchronize and have as event data from the client side, without getting fireworks because of cyclic object references. The fix should make it possible to achieve use cases like #3356.

**Comment by Legioth** [comment]
1) The "fix" by Artur only fixes some specific cases when the cause of the cyclic reference is a DOM element.
2) Encoding a DOM element as JSON and sending it to the server doesn't make any sense since the server has no way of connecting the JSON back to a corresponding server-side element instance (assuming that the element is even tracked on the server).

Until someone describes a specific case when it would be desirable to send an unaccountable "element" back to the server as JSON, I will keep claiming that it's better to immediately make the developer aware of the weirdness of what they're trying to do through some magnificent firework.

**Comment by Artur-** [comment]
Like #3356?

**Comment by Legioth** [comment]
#3356 wouldn't work even if the cyclic reference would be broken, since the JSON for `event.target` would simply be `{}`.

It sounds like the title of this issue should be something along the lines of "Make it possible to send element references back to the server". This in turn begets the question of how to deal with references to any elements that are not tracked on the server.

**Comment by Artur-** [comment]
I don't think there is anything to do here
