### ISSUE TITLE
Apply full size to body element by default

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#3749]
``` When building a Java app with Vaadin, I want to get relative sizing for UI components to work immediately, without having know and remember to apply full size to the UI/body always```

Currently there is no sizing applied to the `UI`/`body` element by default. Unlike in V8. Most applications want to however use `@BodySize(width="100vw", height="100vh")`. If this gets forgotten, then any relative sizing, eg. using `setSizeFull()` or `setWidth("100%")` will not work because 100% of 0px is 0px, and this is difficult to realize. This is at least partially causing two separate issues reported: https://github.com/vaadin/flow/issues/3709 https://github.com/vaadin/flow/issues/3731

### Acceptance Criteria
- If no `@BodySize` is applied for the route hierarchy, the `height = "100vh; width = "100vw;"` is applied automatically
- All starters are updated for this (either remove the annotation or add it to override)
- Documentation is updated for this, need to highlight 
  - what is the default UI size now
  - that **adding an empty annotation** `@BodySize` is required for canceling the default sizing, even when you apply the body sizing with css

**Comment by Legioth** [comment]
What is the "most applications" assumption based on? I think this mostly depends on what kind of applications you're thinking of. Just taking a couple of applications I have open in my browser into account:
* Undefined size: GitHub, Reviewable, Medium
* 100% size: Slack, Google Docs, Google Inbox, Trello, Gitter

**Comment by pleku** [comment]
>What is the "most applications" assumption based on?
It derived using the scientifically proven Harrison-Stetson method.

It when starting to create a Flow app, quite many users will run into this if not almost all who use the layouts that we provide and eg. a Grid that should expand to occupy as much space as possible.

My gut feeling (based on thinking with my guts), is that it will be more of an issue for understanding _why do I need to know and add this_, than _oh there is this size applied by default, how can I remove it_. I base this on the feedback received thus far and what our previous Framework version users are used to.

**Comment by Legioth** [comment]
I would suggest only applying the default in cases when there is at least one server-side child element of `UI` that has a relative `height` style defined on the server.

I would also suggest some way of supporting the case when the body size is set from CSS. With the currently suggested functionality, the only way of preventing a CSS setting from being overridden by the default setting would be to define a `@BodySize` annotation, which would just override the CSS setting with a different value instead. This could be done with a new annotation, e.g. `@BodySizeFromCss`, or some special constant value in the current annotation, e.g. `@BodySize(height = "css", width = "css")`.

I was originally considering that we'd check the computed style to detect that kind of situation, but it turns out this wouldn't work since the computed style is always resolved to a pixel value.

**Comment by pleku** [comment]
Decided to do it as described in description.

**Comment by Legioth** [comment]
Please also ensure there is a test that verifies that CSS values are in effect when using `@BodySize` without either value.

**Comment by pekam** [comment]
I tried setting the body size with css, by editing the `shared-styles.html` in `skeleton-starter-flow`.

The css values override the `BodySize` values. This is different behavior from what is discussed in this ticket. So you don't need to apply an empty `BodySize` annotation to allow setting the size in css.

So which way should it work?

**Comment by pleku** [comment]
>The css values override the BodySize values

If this happens consistently all browsers with applying the values using css/html file, then I think it is fine not mention that you'd need an empty bodystyle annotation for applying the rules from elsewhere.
