### ISSUE TITLE
You are offline notification for Flow

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#3778]
In Bakery there is some code to show an offline message when network is down. It should be nice that this feature is provided by Flow out-of-the-box.

Flow already shows a reconnect message when server is unavailable, but that happens when the user interacts with the UI o when a heartbeat fails (5 min).

The JS implementation might be something like:
```
        !window.navigator.onLine && offline();
        window.addEventListener('online', e => online());
        window.addEventListener('offline', e => offline());
```

The HTML content might reuse the `v-reconnect-dialog` but changing message
```
<div class="v-reconnect-dialog active" style="visibility: visible;">
  <div class="spinner">
  </div><span class="text">Network is unavailable</span>
</div>
```

Additionally, flow might have an annotation for offline view

```
@HtmlImport("src/offline-view.html")
@OfflineContent("<offline-view></offline-view>")
```

**Comment by pleku** [comment]
When building an app with Flow, I want to be able to react to connectivity drop, so I can perfect the UX for going offline

The offline view is handled separately in #45

### Acceptance Criteria
- There is a dialog similar to reconnect dialog / session expired, that is shown to the user when the network connection is dropped
- The dialog message & delay to shown can be configured from the server side dynamically (because of localization)

**Comment by manolo** [comment]
@pleku can you confirm that there is a offline dialog similar to reconnect?

**Comment by manolo** [comment]
Yep, but I mean what happens when once the entire app is loaded in `online` mode, the terminal goes `offline`, it should show a modal dialog informing about the issue and preventing the user interact with the UI until the network is available

**Comment by manolo** [comment]
I think because the Acceptance Criteria in the @pleku  comment above was not moved to the ticket #4275, the solution was implemented partially
