### ISSUE TITLE
HasValue should not be coupled to element properties

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3834]
HasValue is according to the javaodc "A generic interface for field components and other user interface objects that have a user-editable value." however the API contains methods such as `getClientValuePropertyName` and `getClientPropertyChangeEventName` which prevents it from being very generic and instead couples it directly to client side elements. It feels like the interface should be split into two so that `HasValue` would be only about what `Binder` needs and another interface or abstract class should extend `HasValue` and provide helpers for integrating with properties in the client side element

**Comment by gilberto-torrezan** [comment]
The main reason the interface is the way it is, is to provide a way to just plug it a forget about the implementation details. That is specially important for the code generator: when it identifies that a given webcomponent contains a `value`  property that is notifiable, the generator can just plug the `HasValue` interface to the generated code, and the behavior is automagically implemented.

Splitting it into two interfaces would make all classes to implement the second interface (that contains the full behavior) instead. The practical implication would be that component developers would need to discover this new interface - because `HasValue` alone would be incomplete - or implement the full behavior by hand, which would defeat the purpose of the mixin interface.

What would be the practical benefit of having two interfaces for `HasValue`?

**Comment by Artur-** [comment]
The problem is that it is not a "plug and forget" interface as described in #3835. Today you can't understand how to implement `HasValue` at least based on the javadoc so even if you discover it, it does not really help. 

Another interface might indeed make little sense unless there are cases where you want to use a server side abstraction as HasValue, something which has no `Element`. This is fine for `HasValue` right now as it does not extends `HasElement`, but still `HasValue` in reality assumes that you do extend `HasElement`. It's just confusing. An abstract class might make much sense, as described in #3835

I would forget about the code generator, that can be modified as needed. API is created for users.

**Comment by gilberto-torrezan** [comment]
Replace the `code generator`  by  `developer wanting to integrate a new webcomponent` and you have the same workflow.

The problem of being an abstract class is that it makes it harder to be reusable if you already follow a class hierarchy in your component. For example, suppose you want to create a Composite component that has two components inside, and you want to implement `HasValue` and delegate the `setValue`  and `getValue` to one of the inner components. That's easily doable with the interface that already contains all the bolts and nuts, but not with the abstract class, since you are already extending `Composite`.

So maybe it's a javadoc issue? Would it be enough just to clarify the docs about the usage of the class?

**Comment by Artur-** [comment]
Composite is a good example: if you do a Composite for entering a date, containing three TextFields, which client side property should you define in your `HasValue`?

**Comment by gilberto-torrezan** [comment]
It gets more interesting if you had a checkbox alongside the the text fields, because then one use `checked`  while the others would use `value`.

For Composite, there's nothing sensible to return for `getClientValuePropertyName`, so you don't implement it (you are not going to use it anyway, since you are delegating the call to the inner components).

There's also the `HasValueChangeMode` interface with more fun stuff related to the properties and events. Breaking `HasValue` into different classes would also impact how this interface works.

**Comment by Legioth** [comment]
Why should my component class have `getClientValuePropertyName()` or `getClientPropertyChangeEventName()` methods in its public API when those method has no meaning at all to the users of the component? Even less so for the `Composite` case where the methods doesn't even make any sense for internal use, and anyone implementing `HasValue` would have to know that they also need to override `addValueChangeListener()` to do something different.

**Comment by gilberto-torrezan** [comment]
It all started with the check-box, which uses `checked` as property and `checked-changed` as event (instead of `value` and `value-changed`). Since interfaces don't support protected methods, and to avoid duplicating the logic of the `HasValue` inside components that use different properties for the value itself, the `getClientValuePropertyName()` and `getClientPropertyChangeEventName()` were created.

**Comment by Legioth** [comment]
The purpose of `HasValue` is to provide everything that is needed by `Binder` when doing form binding.
* Setting and getting the value
  * Special support for empty values
* Receiving events when the value changes
* Toggling whether the user is allowed to change the value (readonly)
* Showing to the user that a value is required

I'd propose extracting everything not related to that from `HasValue` into a new `HasElementValue` interface that extends `HasValue`.
* `default` implementations for `addValueChangeListener()`
* `getClientValuePropertyName()`
* `getClientPropertyChangeEventName()` (unless already handled through #3846).

`HasValueChangeMode` and the Component API generator should be changed to use `HasElementValue` instead of `HasValue`.

**Comment by Legioth** [comment]
As a further step, the `getClientValuePropertyName()` and `getClientPropertyChangeEventName()` methods could be removed from the set of `public` methods exposed by any class implementing `HasElementValue`. This could be done by instead using annotations for declaring the values (or alternatively https://github.com/vaadin/flow/issues/3835 which would allow those methods to be `protected` instead).

**Comment by Legioth** [comment]
I'd suggest removing everything related to `Component` and `Element` from the `HasValue` interface, as well as changing `ValueChangeEvent` to be an interface that isn't bound to `ComponentEvent`. The `<C>` type parameter is replaced with an `<E>` parameter that defines the event type (if this is even necessary?). The only `default` implementations that remain in `HasValue` would be `getOptionalValue()`, `isEmpty()` and `clear()`. It is in general not expected that implementations directly use this interface, but instead the `AbstractField` (or `AbstractHasValue`?) abstract class which is also . 

`AbstractField` extends `Component` and has native support for all necessary features except:
* Applying a new value to the component
* Extracting a value from the compnent
* Listening to events

`AbstractField` would still implement all methods from `HasValue`- the missing features would be expressed through dedicated API.
* `setValue` and `getValue` is mapped to an internal instance field. This is not absolutely necessary for the simplest cases, but most cases with a composite value would have problems with finding an old value for the value change event without this buffering.
* Value change listeners are registered directly to the component's event bus. There is a `ComponentValueChangeEvent` that implements the `ValueChangeEvent` interface.
* Readonly and required indicators are implemented based on the corresponding element properties. The readonly status is also used internally to block automatic updates to the `value` instance field.
* Helper methods are extracted from `AbstractField` in FW8: `isDifferentValue` and `createValueChange` and used where appropriate.
* There is an `protected writeValue(V value)` method that must be overridden to define how to write the high level value into the component's implementation details.
* There is an abstract `protected V readValue()` method that must be overridden to define how to read the high level value from the component's implementation details, e.g. by reading an element property or combining values from several sources.
* There is a `protected boolean canReadValue()` method that can be overridden to prevent `readValue()` from being run (and thus values from being changed through the client) while the internal value is not valid (e.g. because one of the internally required fields are empty). Returns `true` by default.
* There are various `bindXyz` methods that bind the field to e.g. an `Element` property or an internal `HasValue` instance. Binding in this way makes events from the bound source trigger a high level value change event (if `canReadValue()` returns `true` and `readValue()` return something for which `isDifferentValue` returns `true`). Also, the `writeValue` uses a callback passed to the `bindXyz` method for automatically writing the value to the designated internal source. If no such binding has been done, `writeValue` throws with a message instructing to either call at least one `bindXyz` method or override `writeValue`.

For the very common case of binding to exactly one Element property of a supported type, it is also possible to automatically do everything needed in `readValue()` as long as an "empty value" has also been defined. I'm not certain whether it would be better to have dedicated subtype (e.g. `HasSinglePropertyField`) for this purpose, or if `readValue()` is left non-abstract in `AbstractField` and implemented to throw with a helpful message unless configured to bind directly to a single element property.

Example cases:
```
@Tag("vaadin-input")
public class TextField extends AbstractField<TextField, String> {
    public TextField() {
        /*
         * Binds the value directly to a DOM property with the given name,
         * synchronizes that property on the given DOM event, and uses a given
         * default/empty value.
         *
         * There are separate methods for each type that can be set as
         * an element property, and each has an overload for converting to/from
         * some other type.
         */
        bindSingleElementProperty("value", "value-changed", ""));
    }
}

@Tag("google-map")
public class LatLonField extends AbstractField<LatLonField, LatLon> {
    public LatLonField() {
        /*
         * Synchronizes property on the event name-changed and triggers
         * element.setProperty(name, getter.apply(value)) when the value is
         * changed through setValue(T)
         */
        // There's also an overload for giving a separate element instead of
        // using this.getElement();
        bindDoubleProperty("latitude", LatLon::getLatitude);
        bindDoubleProperty("longitude", LatLon::getLongitude);

        /*
         * Alternatively, the implementation doesn't explicitly bind anything,
         * but is instead responsible for adding its own low-level listener that
         * triggers refreshValue() and also overriding another method triggered
         * from setValue(T) for applying the value to the component's internals
         */
    }

    @Override
    // Called by AbstractField when receiving event that value might have
    // changed
    protected LatLon createValue() {
        Element element = getElement();
        return new LatLon(element.getProperty("latitude", 0d),
                element.getProperty("longitude", 0d));
    }
}

@Tag("vaadin-horizontal-layout")
public class DatePicker extends AbstractField<DatePicker, LocalDate> {
    private HasValue<Component, String> dayInput = ...;
    private HasValue<Component, String> monthInput = ...;
    private HasValue<Component, String> yearInput = ...;

    public DatePicker() {
        /*
         * Listens to events from the HasValue and sets its triggers
         * hasValue.setValue(getter.apply(value)) when the value is changed
         * through setValue(T)
         */
        bindValue(dayInput, value -> String.valueOf(value.getDayOfMonth()));
        // Alternative way of doing the above with converter and value getter
        // bindValue(dayInput, String::valueOf, LocalDate::getDayOfMonth);
        
        attachComponents();
    }

    @Override
    protected boolean hasValidValue() {
        // checks whether to run createValue after event from bound HasValue
        return hasIntegerString(dayInput) && hasIntegerString(monthInput)
                && hasIntegerString(yearInput);
    }

    @Override
    protected LocalDate createValue() {
        return LocalDate.of(Integer.parseInt(yearInput.getValue()),
                Integer.parseInt(monthInput.getValue()),
                Integer.parseInt(dayInput.getValue()));
    }
}

**Comment by gilberto-torrezan** [comment]
Worth mentioning that this design will require some changes on the code generator. For example,  `GeneratedVaadinTextField` should extend `AbstractField` instead of `Component`.

**Comment by pleku** [comment]
>Worth mentioning that this design will require some changes on the code generator. For example, GeneratedVaadinTextField should extend AbstractField instead of Component.

That is a given, and no public `setValue` or `getValue` methods should be ever created by the generator for those components. Also any value change events and listeners should be opt out (if have not already).

**Comment by gilberto-torrezan** [comment]
Silly question - suppose I have a `PolymerTemplate` component that contains a property called `value`, and I want it to make it work with `Binder`.

With the previous implementation it was just a matter of adding `HasValue`  as a mixin interface to the class, and not implement a single method. Now the developer will have to implement how to get/set the property and how to fire the events. Is that correct?
