### ISSUE TITLE
Extend grids addColumn signature and/or add a setRenderer() method for grid column

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#3840]
The current way of adding a column with a custom renderer is a little strange of handling. When I want to add such a column I have to use addColumn(Renderer) and setId(String) in a second line afterwards. IMO normal workflow is creating a column with a specific key (property / id) and adding additional information (like header, renderer, etc.) afterwards.

Request is to add a grid method addColumn(String property, Renderer renderer) and / or a setRenderer(...) method on Grid column. Changing the renderer after the grid has been send to the UI should invoke a refresh.

**Comment by Legioth** [comment]
This is not feasible without compromising type safety since the `addColumn(String)` method doesn't convey any information about the value type of that column. For more thorough discussion on this topic, please see e.g. https://github.com/vaadin/framework/issues/10277 or https://stackoverflow.com/a/49689882/2376954 (but please note that `Column.setId` in V8 corresponds to `Column.setKey` in V10 because of the way `setId` is a DOM-level feature).

Also, why are do you want to set the `id` of columns?

**Comment by stefanuebe** [comment]
Ok, I was wondering about this since the V8 grid supported this. 
At your question why I want to set Id: I was simply not aware of this: 

> but please note that Column.setId in V8 corresponds to Column.setKey in V10 because of the way setId is a DOM-level feature.

:)

**Comment by Legioth** [comment]
> Ok, I was wondering about this since the V8 grid supported this.

What did the V8 Grid support that is missing here?
