### ISSUE TITLE
Move HasValue.getClientPropertyChangeEventName() to HasValueChangeMode

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3846]
`getClientPropertyChangeEventName()` is defined in `HasValue`, but it has no meaning at all there: it's only used by `HasValueChangeMode`. Therefore, it would also be logical that it's only defined in the cases when it's actually needed.

**Comment by pleku** [comment]
This would be a good first step, but there is quite much more that could be done for `HasValue`to make it easier to use.

Instead of moving it to `HasValueChangeMode`, it there should be another level between `HasValue` and that, which has most of the current default implementations from `HasValue`, leaving it to be a more bare-boned version that applies much better to any field component.

Keeping this issue for now, will try to open another for the refactoring soon.
