### ISSUE TITLE
Apply box-sizing: border-box by default

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#3847]
With the default `box-sizing` (which is `content-box`), components with 100% width and padding, end up having 100% width +padding width, which can lead to unexpected scroll bars and broken layouts.

When using `box-sizing: border-box`, the padding and borders are considered part of the sizing, so a component with 100% width and padding would still occupy 100% of the available space, without creating scroll bars.

Here is the CSS snippet that should be injected by default in the `head`:
```
html {
  box-sizing: border-box;
}
*, *::before, *::after {
  box-sizing: inherit;
}
```

More about it here: https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

**Comment by jouni** [comment]
Personally, I view Flow like any other web app framework, and IMO they should keep styling untouched as much as possible. Alternatively, we should consider if we want to bring in more CSS framework features as a whole, like a full CSS reset/normalize by default, and some other utility CSS (like a CSS grid for example).

**Comment by jouni** [comment]
Sure. The margin & padding APIs are part of the layouts, though, right? Or can you apply those for any component? If you can apply those to any component, then it sounds more like the beginnings of a CSS framework, and we should define that better what it actually means to have that bundled.

If it’s just for layouts, then the layouts should handle this. That’s at least how I feel at the moment.

**Comment by pleku** [comment]
I think for any component, we should consider what is best for the default use cases of that component, and thus best for the users, instead of following what others are doing or coming up with academical reasons for not making it easy for the users.

>Personally, I view Flow like any other web app framework, and IMO they should keep styling untouched as much as possible.

I think in any web app framework, easy thing should be easy. @jouni can you give an example of another Java framework that does what we do and doesn't touch styling at all ?

**Comment by pleku** [comment]
I do feel however that we should apply this default change for those layouts that have the `setPadding` API. Don't know how we would fit it into Flow.

**Comment by jouni** [comment]
> I do feel however that we should apply this default change for those layouts that have the setPadding API. Don't know how we would fit it into Flow.

This was my point exactly. I’m all for making common things easy – but without mixing the sprinkling implementation “randomly all over”.

> I think in any web app framework, easy thing should be easy. @jouni can you give an example of another Java framework that does what we do and doesn't touch styling at all ?

I didn’t even mean a *Java*  framework in particular. Just any web app framework, like Vue, Angular or React. I’m not 100% sure, but I don’t think they add any styles to a page by default. That’s my expectation, that the framework doesn’t do too much ”magic” without asking.

But, since the main target audience for Flow doesn’t want to think about CSS, I’m probably the wrong person to argue about this. I think I would be happy if I can just easily opt-out of any extra boilerplate Flow wants to offer by default.

**Comment by Legioth** [comment]
Another option would be to discourage Java developers from using CSS `padding`?

**Comment by gilberto-torrezan** [comment]
> Another option would be to discourage Java developers from using CSS padding?

And what other option the developer would have to achieve the same result?

**Comment by heruan** [comment]
My 2¢ perspective from outside the team.

With Flow there is now an inversion of control in styling: it is no more a monolithic framework providing core components with particular style conventions (e.g. `v-*` classes) to be used to build a theme, but it embraces Web Component which by design have self-contained styles which do not pollute the whole DOM but are scoped to the element itself.

So, as a developer I'd expect no default styles applied on anything which is not a Vaadin Component, but I'd rather like to have a Vaadin "app shell" component I can choose to use providing all the default styles I need to build my app easily.

That is:

- if I don't use the Vaadin "app shell" I start clean (i.e. browser default, so I can apply my CSS/reset framework of choice);
- if I use/extend a `AppShell` component as my main layout, I import a default set of styles or theme-based ones (e.g. Lumo).

**Comment by pleku** [comment]
Decided to add to `ThemableLayout` 
```java
void setBoxSizing(BoxSizing boxSizing) { }
BoxSizing getBoxSizing() { } // default returns BoxSizing.UNDEFINED
```
Other values are CONTENT-BOX and BORDER-BOX.
For `VerticalLayout`, or any layout that has `padding` on by default we apply the `setBoxSizing(BoxSizing.BORDER_BOX);` by default too. (Don't forget to override the javadocs to declare the changed default).
