### ISSUE TITLE
@ClientCallable should support return values

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4050]
Given
```
@ClientCallable
public void removeTodo(int index, String text) {
...
}
```

I really want to be able to provide information back to the client about whether the item was deleted, or if e.g. an optimistic locking / merge conflict occurred. The logical way would be
```
@ClientCallable
public boolean removeTodo(int index, String text) {
```

**Comment by Legioth** [comment]
On the client side, one quite obvious API approach would be that `element.$server.foo(1, "foo")` returns a `Promise`.

**Comment by Legioth** [comment]
Alternatively, return values for return channels could be implemented as a core primitive. This might make sense if we'd position return channels on handles as the fundamental mechanism for any communication from the client to the server since it would then be beneficial to make that mechanism as flexible as possible.

In that case, there would be a separate method for registering a return channel that returns a promise on the client. In addition to the arguments array, it would also receive a proxy to the promise callbacks that should be used to pass a value or an error back. Passing values back by calling methods instead of throwing or using the return value enables the return channel to be fulfilled asynchronously.

The signature of the registration method would thus be
```
void addReturnChannel(String name, SerializableBiConsumer<JsonArray, PromiseProxy> handler);
```
The signature of the promise proxy would be
```
public interface PromiseProxy {
  void resolve(Object result);
  void reject(String message);
}
```
`result` could be any type accepted as a parameter to `executeJavaScript`.

**Comment by rob-64** [comment]
My group is really looking forward to this change; is there an ETA/info on what version and when the next drop is that will include this change?

**Comment by Legioth** [comment]
This feature barely missed the train for Vaadin 14.1. It will be in Vaadin 14.2 that will be released at some point in the beginning of next year.
