### ISSUE TITLE
New interface `HasTitle`

### ISSUE THREAD

**Issue by azaberlin** [vaadin/flow#4058]
`HtmlComponent` has methods setTitle/getTitle for setting the html title of an element. This method should be made generally available through an interface `HasTitle` (like `HasValue` or `HasClickListener`).

**Comment by pleku** [comment]
Hello. So you would want to add the getter & setter for `title` attribute with a mixin interface instead of having to expose the methods ? What type of components you have in mind that would benefit from this ?

I'm a bit sceptic about adding this mixin interface, since I don't see what value it brings trying to put something so trivial into a mixin interface that is not that often needed. And also it is not encouraged to use the `title` because it has accessibility concerns: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title
Thus I'm not sure I want to promote it on framework level.

**Comment by pleku** [comment]
Closing this issue as don't really see any point in adding it at the moment. Please comment if you have new information to provide.

**Comment by HawkSK** [comment]
For anyone who would want this in their project:
```java
public interface HasTitle extends HasElement {
    default String getTitle() {
        return getElement().getAttribute("title");
    }

    default void setTitle(String title) {
        if (title == null || title.isBlank()) {
            getElement().removeAttribute("title");
        } else {
            getElement().setAttribute("title", title);
        }
    }
}
```
