### ISSUE TITLE
Extract interface HasValueChangeListener from HasValue to prevent type clashes for some components.

### ISSUE THREAD

**Issue by azaberlin** [vaadin/flow#4059]
Some components will not be able to implement the interface `HasValue` when they implement own `setValue/getValue` methods with native types, for example `ProgressBar`.

This becomes problematic when I want to use the value change listener functionality provided by the `HasValue` interface. To be able to use it anyway the change listener functionality should be extracted into an own interface `HasValueChangeListener`.

**Comment by Legioth** [comment]
What kind of code would be interested in using `HasValueChangeListener` but not `HasValue`?

**Comment by azaberlin** [comment]
As described above: a component, that uses native types as value, like our standard component ProgressBar (just an example, users may also implement own components with usage of native types).

**Comment by Legioth** [comment]
In what way would that kind of definition help?

Would there be external API users that current require an instance of `HasValue` but that could be changed to instead require a `HasValueChangeListener` instance`. Note that the main purpose of `HasValue` is for use with `Binder`,  and that case would not work without the other API from `HasValue`.

Or would `HasValueChangeListener` somehow work as a mixin interface with a `default` method for helping the component implementation? I don't see how the `addValueChangeListener` method could have a `default` implementation without also making `HasValueChangeListener` extend `ComponentEventNotifier`,  which in turn make it so that `HasValue` cannot extend `HasValueChangeListener` without also creating a strong tie between `HasValue` and  components (which is the unfortunate tie that we have refactored away during the last week).

**Comment by azaberlin** [comment]
Just had a look into the current HasValue impl and now I see what you mean - getValue is used inside the ValueChangeListener parts and therefor cannot be uncoupled this easy. 

The idea was simply to provide a out of the box ValueChangeListener functionality without the need of using the rest of HasValue since sometimes these parts like getValue are implemented already. But makes also sense that it cannot be decoupled and there must be implemented on my own in these cases if needed.
