### ISSUE TITLE
Create HasPlaceholder interface

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#4068]
Similar to `HasEnabled` in https://github.com/vaadin/flow/issues/3816

**Comment by pleku** [comment]
@mvysny what for would you want to use this mixin interface for ?

Even though it is very generic bit of API and works the same way for all the components, meaning that it could be thus in a mixin interface, I don't see it would add that much value.

**Comment by mvysny** [comment]
In Karibu Testing I'm allowing the user to filter the components also based on the placeholder. However, there is no unified interface that can return the placeholder for a component, and therefore I have to have the following function:
```
val Component.placeholder: String?
    get() = when (this) {
        is TextField -> placeholder
        is TextArea -> placeholder
        is PasswordField -> placeholder
        is ComboBox<*> -> this.placeholder  // https://youtrack.jetbrains.com/issue/KT-24275
        is DatePicker -> placeholder
        is Input -> placeholder.orElse(null)
        else -> null
    }
```

It doesn't have to be a mixin interface, it could be just an interface with single method, `String getPlaceholder()`.

**Comment by vaadin-miki** [comment]
bumping this, as it would greatly help
reasoning similar to https://github.com/vaadin/flow/issues/3241

**Comment by Vinetos** [comment]
Hello, I would have this feature too.
I saw that HasPlaceholder has existed in previous version (Vaadin 13). 

I need it because I'm rewriting part of component in a 'fluent' way (.with pattern) and all xxxFields, ComboBoxes, TextAreas implements this.

It should be applied to the interfaces `HasValue`

**Comment by vaadin-miki** [comment]
@Vinetos (and everyone else looking to have this functionality implemented, for that matter) - the interface `HasPlaceholder` (and a mixin for `.withPlaceholder()`) is present in SuperFields (https://github.com/vaadin-miki/super-fields/), the add-on that I am an author of

so if you do not mind using a third-party add-on, feel free to use SuperFields while this issue is still in the works :)
