### ISSUE TITLE
"endRequest called when no request is active"

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4071]
Seems to happen when you redeploy a `@Push` enabled application. Browser console says

```
Push connection re-established using websocket
21:34:09.738 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185 JSON parsing took 0ms
21:34:09.738 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185 Received push (websocket) message: for(;;);[{"meta":{"sessionExpired":true}}]
21:34:09.738 client-52731741FE58EF8056D7E6EA323C8436.cache.js:1049 Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission.
Eq @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:1049
21:34:09.738 client-52731741FE58EF8056D7E6EA323C8436.cache.js:1065 Handling message from server
21:34:09.738 client-52731741FE58EF8056D7E6EA323C8436.cache.js:1006 Handling dependencies
21:34:09.739 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185 handleUIDLMessage: 0 ms
21:34:09.739 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185 Setting heartbeat interval to -1sec.
21:34:09.739 client-52731741FE58EF8056D7E6EA323C8436.cache.js:1001 Closing push connection
21:34:09.739 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185  Processing time was 1ms
client-52731741FE58EF8056D7E6EA323C8436.cache.js:210 endRequest called when no request is active
HB @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:210
21:35:09.763 vaadinPush.js?v=1.0.0.beta9:3259 Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent). - wasClean: false
log @ vaadinPush.js?v=1.0.0.beta9:3259
warn @ vaadinPush.js?v=1.0.0.beta9:3265
_websocket.onclose @ vaadinPush.js?v=1.0.0.beta9:1517
21:35:09.764 client-52731741FE58EF8056D7E6EA323C8436.cache.js:1068 Push connection closed
21:35:09.764 client-52731741FE58EF8056D7E6EA323C8436.cache.js:782 Reopening push connection
21:35:15.788 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185 Push connection re-established using websocket
21:35:15.790 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185 JSON parsing took 0.1ms
21:35:15.790 client-52731741FE58EF8056D7E6EA323C8436.cache.js:185 Received push (websocket) message: for(;;);[{"meta":{"sessionExpired":true}}]
21:35:15.790 client-52731741FE58EF8056D7E6EA323C8436.cache.js:1049 Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission.
Eq @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:1049
Qo @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:1068
(anonymous) @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:1037
ob @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:439
rb @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:931
(anonymous) @ client-52731741FE58EF8056D7E6EA323C8436.cache.js:638
_f @ vaadinPush.js?v=1.0.0.beta9:2765
_invokeFunction @ vaadinPush.js?v=1.0.0.beta9:2754
_invokeCallback @ vaadinPush.js?v=1.0.0.beta9:2884
_websocket.onmessage @ vaadinPush.js?v=1.0.0.beta9:1457
21:35:15.791 client-52731741FE58EF8056D7E6EA323C8436.cache.js:1049 Ignored received message because application has already been stopped
```

**Comment by mpilone** [comment]
I'm seeing this same error in Chrome when attempting to close the session and redirect the user on logout. The logic is using the example logout logic from the Flow documentation. This is causing some complaints/confusion from my users. It might also be related to #5492.

The following sequence on the service side _seems_ to make it go away but it isn't clear why or what other effects it may be having:

```
ui.getPage().executeJavaScript(String.format("window.location.href='%s'", url));
      // Apparently necessary to avoid a spurious javascript error in Chrome:
      ui.getInternals().getPushConnection().push();

      ui.getSession().close();
      // Also apparently necessary:
      ui.close();
```

Configuration:
- Push: long polling
- Flow: 1.4.2
- Vaadin: 13.0.2
- Chrome: 73.0.3683.103

Test case attached.
[Bug 4071 Test Case.zip](https://github.com/vaadin/flow/files/3081028/Bug.4071.Test.Case.zip)

**Comment by Braus** [comment]
This bug is still valid in my version: 13.0.2

**Comment by Braus** [comment]
Found this bug too

**Comment by mobileWMS** [comment]
Unless I am mistaken, I found this bug as well.

**Comment by Braus** [comment]
@mobileWMS I solved this issue by using code to configure push instead of using annotations. I also reported that:
https://github.com/vaadin/flow/issues/5864
Perhaps it'll do something for you as well.

**Comment by mobileWMS** [comment]
@Braus I tried various ideas from #5864 and none of them worked.  I left my comments there on what I did.

**Comment by Braus** [comment]
@mobileWMS sorry to hear that perhaps could you describe in detail what you are doing so that the devs can look into it deeper. What version are you using?

**Comment by mpilone** [comment]
I updated my test case to simplify it even more. This is very reliably reproduced on Chrome and intermittently on Firefox with a similar, but different JSON error notification popup. The issue still exists in v14. It isn't clear how to perform a clean user logout when push is enabled.

Configuration:
- Push: long polling
- Flow: 2.0.10
- Vaadin: 14.0.3
- Chrome: 76.0.3809.132
- Firefox: 69.0

[Bug 4071 Test Case.zip](https://github.com/vaadin/flow/files/3627058/Bug.4071.Test.Case.zip)

**Comment by mobileWMS** [comment]
Flow version '2.0.12', platform version '14.0.5', vaadin7 version '7.7.17' ( so I am using MPR )
Coding on Windows 10, using Eclipse 2019-06 (4.12.0)
Problem occurs in logout code, like @mpilone.

- Testing in Chrome 77.0.3865.75 - very quick appearance of the endRequest error that users can see.  Did not look at console because of error message.
- Testing in Firefox 69.0 - same as Chrome, obvious to users.  Did not look at console because of error message.
- Testing in IE 11.356.18362.0 - no obvious problems, BUT if I open the console I see the same problem there.  Farther up in console I see an error about response not containing a valid server id, and this all happens before "Navigation occurred" log message in Console.
- Testing in Edge 44.18362.329.0 - no obvious problem, but console showed much the same things as IE.

I can say that, in my tests, if I call `currentUi.getPage().executeJs("window.location.href=''");` and do NOT call `VaadinSession.getCurrent().getSession().invalidate();`, I do not get the error.  So the problem seems to be related to invalidating the session, maybe?

Tell me if you need more information, but my basic goal is the same as @mpilone.

I tried a lot of things, using Chrome as my browser most of the time.  See below:
1. Out of curiosity, I decided to try using `VaadinSession.getCurrent().close();` instead of `VaadinSession.getCurrent().getSession().invalidate();`.  This did not fix the issue.  It actually causes another issue entirely, in addition to this one, because things are not properly cleaned up.  Yes, this is not valid, was just experimenting.
2. Then I tried doing `VaadinSession.getCurrent().close();` before `VaadinSession.getCurrent().getSession().invalidate();`, but that did not help either.  It did not cause other problems, just did not fix my endRequest problem.
3. Same thing happens whether I do `currentUi.navigate("");` or `currentPage.reload();`.  Also, same thing happens if I move `currentUi.navigate("");` to before I call `VaadinSession.getCurrent().getSession().invalidate();` ( with or without calling `VaadinSession.getCurrent().close();` ).
4. I changed `currentUi.navigate("");` to `currentUi.getPage().executeJs("window.location.href=''");`, and still get the same problem if I call `VaadinSession.getCurrent().getSession().invalidate();`. 
5. Now, what is really interesting is that if I do NOT call `VaadinSession.getCurrent().getSession().invalidate();`, I don't get the error.  Obviously, `currentUi.navigate("");` does nothing if I don't call `invalidate`, but `currentUi.getPage().executeJs("window.location.href=''");` works without error.
6. Commenting out `@Push` and any references to `UI.access` of course removes the problem.  If I just comment out all references to `UI.access`, but keep `@Push`, we still have the problem.  This makes sense considering the comments of others.
7. For the sake of completeness, I also tried programmatic `UI.getCurrent().getPushConfiguration().setPushMode(PushMode.MANUAL);UI.getCurrent().getPushConfiguration().setTransport(Transport.WEBSOCKET);` and declarative `@Push(value = PushMode.MANUAL, transport = Transport.WEBSOCKET)`.  I get this error, even though I am not actively using push, it is simply enabled.

**Comment by mobileWMS** [comment]
Not sure if this helps, but I seem to get this error after logging out, when it tries to refresh the screen.  In other words, I have multiple browser tabs open.  I logout of the current browser tab, all other tabs ( besides current ) go to logout page as expected, no endRequest error.  Main tab, from which I logged out, takes a little longer, but when it finishes, I get the endRequest error, and the other tabs ( already on logout page ) start refreshing and get the endRequest error as well ( assuming I click to the tab quickly enough, while Chrome is still spinning in the browser tab ).  It could be happening inside invalidate, I suppose, or when the page actually "refreshes".

**Comment by Kivinaama** [comment]
Vaadin support says we may have the same issue, though the actual error message is different. 
Config (MPR):
- Platform 13.0.13
- Vaadin 7.7.15
- Spring Boot 2.0.7.RELEASE

Happens with different browsers: Edge, Chromium Edge, FireFox, Chrome
Also this can happen when navigating between pure Flow views, or mixed Flow with MPR wrapper views.

We get "Trying to start a new request while another is active". This happens seemingly randomly when navigating between views with Flow Routing. Client console shows:
```
Sending xhr message to server: {"csrfToken":"...
client-35B1FB3429E59E02EBC15A74B735E49E.cache.js:188 Received message with server id 19 but expected 10. Postponing handling until the missing message(s) have been received
client-35B1FB3429E59E02EBC15A74B735E49E.cache.js:189 Gave up waiting for message 10 from the server
CB @ client-35B1FB3429E59E02EBC15A74B735E49E.cache.js:189
client-35B1FB3429E59E02EBC15A74B735E49E.cache.js:749 Resynchronizing from server
client-35B1FB3429E59E02EBC15A74B735E49E.cache.js:193 Trying to start a new request while another is active
AB @ client-35B1FB3429E59E02EBC15A74B735E49E.cache.js:193
```

Apparently the client does not recover from this synchronization mismatch issue?

Server-side logging indicates all the tasks related to the xhr trigger from client are executed, views are populated with data but it just never gets shown on the client.

If we use "production" packaging we get the same hanging issues but the error is now shown.

**Comment by mpilone** [comment]
@Kivinaama You may also be running into issue #2210 with the resynchronization.

**Comment by JohnDavidJordan** [comment]
I recently tried to get session timeout working (but it is not with Vaadin 14.0.8). I was playing around with the setting of closeIdleSessions and the session timeout. We never got this message, but now it comes up when we first access the application. It is very annoying. Both the session timeout issue and this endRequest call message need to be resolved ASAP, we are close to our application deployment date...

**Comment by TatuLund** [comment]
@JohnDavidJordan @bogdanudrescu Just adding here, that John is referring to this issue https://github.com/vaadin/flow/issues/6763

**Comment by bogdanudrescu** [comment]
Someone else may continue to fix into https://github.com/vaadin/flow/pull/6798
