### ISSUE TITLE
Lumo.java should not place <custom-style> inside <body>

### ISSUE THREAD

**Issue by jouni** [vaadin/flow#4076]
Overriding font styles for the `<html>` element using `shared-styles.html` does not work, since `Lumo.java` is overriding those styles by placing styles inside the `<body>` element.

`getBodyInlineContents` should probably be `getHeadInlineContents` (or have both options available), and produce the content before any app-specific HTML imports are processed so that the CSS cascade order or as expected.

**Comment by jouni** [comment]
The example on https://vaadin.com/docs/v10/flow/theme/theming-crash-course.html does not work for this reason (setting the font-size for the html element).

**Comment by caalador** [comment]
Do you have a way to get the `<custom-style>` to be put in the head?

The browser moves the custom-style to the body as it is not a tag valid inside <head>.

**Comment by jouni** [comment]
Some of the Lumo files have such includes inside the main HTML imports, such as color.html: https://github.com/vaadin/vaadin-lumo-styles/blob/master/color.html#L4

Also, shared-styles.html is placed in the head element, and it also contains a custom-style tag.

I’m not sure what the problem could be? I suppose browsers treat custom-tags differently depending on if they are directly on the page or inside an import?

**Comment by Artur-** [comment]
Unrelated but when creating an offline page manually you might want to mimic the behavior of the generated bootstrap page. This would be easier if there was e.g. one style import instead of a style block with some styles and then some Lumo imports if you are using Lumo (which I guess is currently really the only option)

**Comment by pleku** [comment]
>Also, shared-styles.html is placed in the head element, and it also contains a custom-style tag.

Shared styles `custom-style` is added by JS instead of being written in the initial page response, so the browser doesn't touch it.

We can try maybe to hack around this by adding a `<script>` in the initial response that adds the custom style added now in java in JS to see if wouldn't be moved by the browser. Thus it would replace this part from `Lumo.java`:

```java
Collections.singletonList("<custom-style>\n"
                + "    <style include=\"lumo-color lumo-typography\"></style>\n"
                + "</custom-style>");
```

**Comment by denis-anisimov** [comment]
- The issue is confirmed: I have a test which reproduce the issue.
- The investigation part: it seems the suggested hack works as expected.
- The fix is on the way.
