### ISSUE TITLE
Vaadin dialog can't applying custom css

### ISSUE THREAD

**Issue by ebatgerel** [vaadin/flow#4115]
`vaadin-dialog` cannot apply css

Here is my part of some code:

```
<dom-module id="car-dialog" theme-for="vaadin-dialog-overlay">
  <template>
    <!-- Start Style -->
      <style>
      </style>
    <!-- End Style -->
  </template>
</dom-module>
```

```
:host {
  * {
    box-sizing: border-box;
    &::before,
    &::after {
      box-sizing: inherit;
    }
  }

  [part="backdrop"] {
    background: #3f3f3f;
  }

  [part="overlay"] {
    background: #3f3f3f;
    outline: none;
  }

  .wrapper {
    display: block;
    max-width: 1140px;
    padding: 0 15px;
    margin: 0 auto;
    &::after {
      display: block;
      clear: both;
      content: " ";
    }
  }
}
```
Above codes rendered and imported normally. But can't applies on components.

-Expected behavior

Custom styles have to apply.

- Actual behavior

Can't apply custom styles

This seems new update prevents something or i can't even explain.

**Comment by limonte** [comment]
Hello @ebatgerel 

We recently changed the styling mechanism in https://github.com/vaadin/vaadin-dialog/releases/tag/v2.0.0-beta4

Now, in order to style parts you still need to use style modules, but the dialog's `<temlate>` should be styled outside the style module, with just regular CSS, e.g. in the `<style>` tag:

```html
<dom-module id="car-dialog" theme-for="vaadin-dialog-overlay">
  <template>
    <style>
      [part="backdrop"] {
        background: #dcf;
      }

      [part="content"] {
        padding: 0;
      }
    </style>
  </template>
</dom-module>


<style>
  .wrapper {
    background: #3f3f3f;
    color: #fff;
  }
</style>

<vaadin-dialog opened>
  <template>
    <div class="wrapper">Styled dialog</div>
  </template>
</vaadin-dialog>
```

jsfiddle with working example: https://jsfiddle.net/6r5htd05/291/

PS. The right place for this issue would be https://github.com/vaadin/vaadin-dialog/issues

**Comment by ebatgerel** [comment]
@limonte  Thank you very much.
