### ISSUE TITLE
Provide a route name producer SPI

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4117]
The PR 
https://github.com/vaadin/flow/issues/4104
makes possible to have route path which is derived somehow based on the annotated class name.
The logic is hardcoded.
It should be possible to specify a custom name produced/strategy (somehow) to be able to generate route path instead of having it hardcoded.

**Comment by Legioth** [comment]
Alternatives for how this could be registered:
1) Classpath scanning, i.e. the same way that `@Route` classes are found. Problematic if multiple implementations are found on the classpath.
2) ServiceLoader, i.e. same as the above, but slightly more explicit.
3) Annotation on the main layout class, problematic if there are multiple main layotus
4) Parameter in `@Route`, problematic since you need boilerplate for each navigation target class
