### ISSUE TITLE
DomEvent should return the actual current Component , not the element it has been registered to.

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/flow#4129]
I attempted to do the following:

I have a checkbox which shows the current selected element and on expanding a list with other chooseable components. This looks like this:

```
<div>
<showed element>
<div>
</div>
<other element1>
<other element2>
</div>
```

Lets say, i register a DomEvent using onclick to `<other element1>` .
Now, I change some values of `<other element1>` on clientside.
If i now click on `<other element1>` , i recieve from the Event the same Element it was before switching its values on clientside.

So, do I have some misunderstanding regarding how this event works? 

Or can I achieve what i was trying to do this way on server side alone?

**Comment by Legioth** [comment]
What is missing in your case is probably that you don't tell Flow that is should update the values on the server-side representation of the element. Flow doesn't do this automatically since there's so much that changes all the time in the browser, that it would be quite much overhead to always synchronize it all.

See https://vaadin.com/docs/v10/flow/element-api/tutorial-user-input.html for instructions on how to configure this.

**Comment by TheSilentHorizon** [comment]
@Legioth well, thats easy. Thanks 👍
