### ISSUE TITLE
Run IE11 tests nightly for Flow

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4219]
https://github.com/vaadin/flow/commit/7c1cb464b59d09fee1405ccbe0ca52b92ed53b75 added a way to run IE11 tests. We should be running those nightly for Flow.

**Comment by pekam** [comment]
Current status with the tests: ~118 failing tests (after #4245 and #4254)
Here's some info I've gathered (doesn't cover everything):
- All 76 template tests fail because they use es6 class syntax and there's no transpilation (same for the 2 webcomponent tests)
- Scroll position tests are quite flaky. Some have both passed and failed in different builds and there might be only one pixel difference, like `expected y scroll position <337> but was <338>`.
- I'm afraid there are also a lot of individual reasons for individual test failures.
  - For example `ElementStyleIT.customPropertiesWork`: Polymer uses ShadyCSS polyfill to make Custom CSS properties work inside web components, but this doesn't work outside, like in the test we use the Element API to set the properties in the light DOM. So we don't actually have a polyfill that would enable this test case to work on IE11.

So adding the production build with transpilation should fix most of the problems. But using the maven plugin in `flow-test-root-context` is not that straight-forward.
- There are tests for using Lumo or a custom theme, so the plugin complains about multiple theme declarations
- I couldn't find correct resource path parameters for maven plugin that would work for every case. I mean, I got a message that this resource does not exist, and noticed that it's missing `frontend/`, so I added this to the path. But then it complains that something else does not exist, and it has a double `frontend/frontend/` in the path. I'm not sure, but maybe this is because of using both `context://` and `frontend://`

**Comment by pekam** [comment]
Currently 47/227 IE11 tests failing. They are muted for now, so we at least can notice in `flow-dev-feed` if the build fails which means that we've broken something new.

I created a support task about improving the IE11 tests: https://github.com/vaadin/flow/issues/4319
so the support person for example can continue with these if/when there's extra time.

I think this issue can be closed now.
