### ISSUE TITLE
Add API for getting browser window size

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#4320]
Related to #4312

`WebBrowser` gives information on the screen resolution, but there is as far as I can tell no way of getting information on the viewport size. In many cases where #4312 would be useful, you would also need to know the initial size before starting to listen for changes.

**Comment by pleku** [comment]
Available in `2.0.0.beta1` with `Page.retrieveExtendedClientDetails(
            ExtendedClientDetailsReceiver receiver)`

**Comment by RaimundBarbeln** [comment]
I have just tried out 2.0.0.beta1.
`Page.retrieveExtendedClientDetails( ExtendedClientDetailsReceiver receiver)` just gets me the screen size.
But the initial request was for the viewport size. And i need the initial vieport size for my application.
The Title of the issue is a bit misleading.

**Comment by pleku** [comment]
So did I understand correctly, @RaimundBarbeln, you are interested in getting `document.body.clientWidth` and `document.body.clientHeight` instead of `window.screen.height` and `window.screen.width` ?

**Comment by RaimundBarbeln** [comment]
Yes, if those are the ones that are returned by the resize listener in #4312, that is exactly what I need. I need the initial viewport size to create pixel-exact SVG Images before the browser window is resized.

**Comment by pleku** [comment]
@RaimundBarbeln I've created https://github.com/vaadin/flow/issues/5717 based on your feedback and will take a look if we could add those still.

As a workaround, since `2.0` you can actually execute any JS from server side and get the result to server side. That API is in `Page::executeJS` and there you could fetch the data you need. 

But we should of course have the framework provide the most commonly needed details automatically!
