### ISSUE TITLE
Not all key listeners are working

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#4351]
Based on https://vaadin.com/forum/thread/17149460/textfield-key-listener-for-esc-and-arrow_down

Create a basic Flow application, add a component with listeners:

```
public void keyListener() {
    TextField searchTF = new TextField();
    searchTF.addKeyPressListener(Key.ESCAPE, e -> {
        Notification.show("ESCAPE");
    });
    searchTF.addKeyPressListener(Key.ENTER, e -> {
        Notification.show("ENTER");
    });
    searchTF.addKeyPressListener(Key.ARROW_DOWN, e -> {
        Notification.show("ARROW_DOWN");
    });
    add(searchTF);
}
```

Expected: all listeners work
Actual: `ESCAPE` and `ARROW_DOWN` listeners are not triggered

**Comment by SomeoneToIgnore** [comment]
As @tsuoanttila pointed out, Vaadin 8 has issues with GWT interfering with key codes.
Need to investigate if it is the case and, if possible, fix the issue.

**Comment by denis-anisimov** [comment]
I'm closing this ticket because this is how JS works.
`key press` event is not always fired for any keys. JS doesn't allow handle key press events for `ESC` and other special keys via event handler.
But you may add a listener for `key down` and `key up` events which always work (for the special keys as well).

So please use `addKeyDownListener`/`addKeyUpListener` methods instead.
