### ISSUE TITLE
Element method callFunction produces error message event when working

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4404]
The method com.vaadin.flow.dom.Element#callFunction seem to work but produces an error message.

I have a simple Div where a client side event listener should be registered on server side to allow drag and drop handling:

```
Div dragMe = new Div(new Span("Drag me"));
dragMe.setId("XYZ");

Element dragMeElement = dragMe.getElement();
dragMeElement.setProperty("draggable", true);

dragMeElement.callFunction("addEventListener('dragstart', e => alert(e))");
```

The function `addEventListener` seem to be called correctly, since the event listener is called on client side. 

Nevertheless I get also an error message: "(TypeError) : $0.addEventListener(...) is not a function". This is odd, since it seems to work.

**Comment by Artur-** [comment]
The first parameter to `callFunction` must be only the name of the function so it would be quite surprising if your example works

**Comment by pleku** [comment]
I'm guessing it is just a side effect that it works correctly, because of how Flow client engine does the call and it is JS ... basically doing `element.addEventListener('dragstart', e => alert(e))();`

I'm not sure if we really want to anything for this since it is a user error that also works accidentally ...
