### ISSUE TITLE
Poor loading times in Microsoft Edge Browser

### ISSUE THREAD

**Issue by andreasbean** [vaadin/flow#4406]
Loading a flow app in Microsoft Edge is extremely slow.

**Please assign the issue to an engineer and investigate it.**

Related to #4358

**Comment by pleku** [comment]
Hello. When it comes to performance with browsers I think it is much feasible to work on concrete things instead of _generic performance_. Thus I'm closing this issue and would rather focus on the case mentioned in #4358. If there are other cases where Edge is performing extremely slow (it should have a different type of UI / components), then further issues should be opened with example cases attached. Thanks.
