### ISSUE TITLE
Spike: Investigate making all components & webjars an OSGi bundle with extracting & repackaging

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4490]
Here is an example of making just one single webjar an OSGi bundle https://github.com/webjars/jquery/pull/58

The purpose of this issue is to investigate pom.xml configuration to unpackage all webjars and then repackage those as a single OSGi bundle that will make Flow and Flow web component integrations OSGi compatible.

**Comment by denis-anisimov** [comment]
I've made a copy of our skeleton starter project:
https://github.com/denis-anisimov/skeleton-starter-flow

Its build is changed so that all webjar resources are extracted and put into `frontend/bower_components` which is available as a web resource.

So as a result there is no need to handle webjars anymore and the only task for now is to make available those resources in OSGi.

The project has no any relation to OSGi at all. And this is web project (not a jar bundle for OSGi) but it shows how we may get rid of webjars completely and just use web resources with webjar content instead.

The only variable here (which needs a configuration): `frontend` folder whose location may differ in various projects.

On the other hand it shouldn't be a web project anyway. It should be an OSGi jar bundle so we should place the extracted resources into the predefined folder e.g. `META-INF/resources/frontend`.

What we can do is : make some JAR project which depends on `vaadin-core`. If it has similar configuration then all resources (for all our components) will be extracted into a resources folder and we may make it OSGI compatible: provide everything is needed (manifest, activator to register the resources in web via HTTP service and so on). The result will be jar OSGi bundle with all component resources.
So the resulting jar may be just included as is into OSGi project along with original component jars (the Java code is still needed and our web components should be OSGi compatible) : there is no need anymore in transitive webjars (which are not OSGi compatible).

The same configuration can be done for any limited number of component to do the same: some Jar which is OSGi ready.

I'm going to apply this configuration for existing OSGi test which are available for `flow-root-context`.
We have a number of web components used there along with tests for tests for custom Polymer templates.
They are excluded currently since we cannot get `polymer` library from the webjars. But with this config all those resources will be available and tests can be enabled.
