### ISSUE TITLE
text-align in TextField is ignored

### ISSUE THREAD

**Issue by DSW-PS** [vaadin/flow#4499]
Setting text-align on a TextField does nothing. If looked at with an object inspector (Chrome, ...) it shows the style only applied to the vaadin-text-field "wrapper", not to the input itself.

To reproduce just use the starter project and add a TextField with text-align set:

`TextField tf = new TextField();`
`tf.setValue("should be aligned right");`
`tf.getStyle().set("text-align", "right");`

The text inside will still be aligned left. 

![image](https://user-images.githubusercontent.com/36918037/43842372-7e21bd84-9b25-11e8-8c28-70e21c263ba8.png)

If you apply it to the input with an object inspector, the last characters will be greyed out (unless the field has focus - maybe interference by the suffix-slot?).

![image](https://user-images.githubusercontent.com/36918037/43842463-b960dfa6-9b25-11e8-8dff-d371804bc60f.png)

**Comment by denis-anisimov** [comment]
Hi,
thanks for reporting but I don't see a reason why `tf.getStyle().set("text-align", "right");` should do what you need.

The only reason why you expect this is the behavior of of `input`  DOM element.
But `vaadin-text-field` is a web component and doesn't have to behave in the same way as `input`.

So:
- Server side Java code in this case doesn't do anything except set style to the `vaadin-text-field` web component on the client side
- As a result this behavior is just a behavior of a client side web component.

I don't see anything about your usecase in the web component documentation.
Here is an example as you may style your component properly:

https://vaadin.com/components/vaadin-text-field/html-examples/text-field-styling-demos

I don't see why this is a bug.
If you think that the style should be applied in the way you expected for the web component then please create a ticket for the web component : https://github.com/vaadin/vaadin-text-field

**Comment by DSW-PS** [comment]
@denis-anisimov:
Given that Vaadin 10 provides the option to set styles directly, I expect that if I set a "text-align" (or any style really through the HasStyle interface) on a TextField it would actually affect the part where I can enter values.

**Comment by Legioth** [comment]
@DSW-PS This has nothing to do with whether you can set styles, it has to do with the fact that the `<vaadin-text-field>` component is not implemented to use the `text-align` style in the same way as `<input>` does.

To control the alignment of the text input, you'd have to create a custom style module for `<vaadin-text-field>` that applies the style for the `[part=value]` selector. I have never done this myself, but I believe https://github.com/vaadin/vaadin-themable-mixin/wiki/Extending-the-Default-Theme-Module could work as a starting point, except that you'd want to define the `include` for the Lumo theme instead of the default theme that is used in that example.

You might also want to submit a ticket at https://github.com/vaadin/vaadin-text-field where you ask for a feature that would make the alignment styleable using a CSS variable or similar.

One last option would be to run a small JS snippet to inject an inline style into the appropriate location. This would look something like `UI.getCurrent().getPage().executeJavaScript("$0.focusElement.style.textAlign='center'", tf.getElement());`.

**Comment by Legioth** [comment]
@web-padawan Great. That's way easier than any of the haxxors that I suggested!

Just to clarify, the Java code for doing this with Vaadin 10 would be `tf.getElement().setAttribute("theme", "align-right");`.

In an upcoming version (tentatively Vaadin 12), this will be further simplified to `tf.addThemeName("align-right")`, or if you prefer to not have a magic string in your code, you can do `tf.addThemeVariants(TextFieldVariant.LUMO_ALIGN_RIGHT);`.

**Comment by DSW-PS** [comment]
@web-padawan Thank's a lot, that is exactly what I was looking for!
