### ISSUE TITLE
HasComponents.remove default implementation should not throw IllegalArgumentException 

### ISSUE THREAD

**Issue by samie** [vaadin/flow#4528]
Expect silently ignoring removal of missing component and returning boolean true if a component was present. Instead `IllegalArgumentException` is thrown. This causes either error 500 crashes of application when non-existing components are removed or unnecessary try-catch-code in applications.

Overall, looks like that on high level `com.vaadin.flow.component.HasComponents` interface is very similar to` java.util.List`. However, the list API naming and behaviour is very different without any obvious reason. Unless clearly needed by some other features, consider following familiar and established Java API practices.

**Comment by denis-anisimov** [comment]
I think it's better to separate several different requests in the ticket.
I'm going to fix the request which is about exception on `remove`.

But there are two different cases:
- if the component that is requested to remove has no parent then no exception will be thrown
- if the component has a different parent then I think the exception should be thrown. I'm going to keep the existing behavior.

Other requests about `List` API are enhancements. 
It's a shame that we missed `List` API approach from the very beginning .
But now it's an API change.
So it needs to be done separately. 
We definitely can't port this into `1.0`.

So could you please create a separate ticket for this?

Also please let me know if you disagree with the throwing an exception even if the component has a different parent.

**Comment by Legioth** [comment]
What's the reason for doing `foo.remove(bar)` in cases when `bar` is not a child of `foo`?

In the generic case, this sounds like programmer error, for which a runtime exception is generally a suitable outcome since it helps the programmer realize that there's been some kind of mismatch and potentially also discover that some more fundamental assumption doesn't hold true.

**Comment by denis-anisimov** [comment]
I definitely agree with @Legioth in case if `bar` is already added.

But I think there is a sense to avoid an exception when the component has not been added to any parent yet.

That may simplify code because e.g. you may want to have no component shown from the very beginning (and you don't want to use visibility).
But then you write you code so that it removes some components on action.
This action may be done independently of originally shown components.
And then in your code you just walk through some components filtering and removes them.

(At some point you add them back). And you don't want to check whether the component has been really added to the parent or not yet.

So this is useful behavior.

And yes, if the component has already another parent then this is a programming error.

**Comment by samie** [comment]
Yes, splitting this is actually several smaller issues but better look it as a whole. 

To clarify: In our use case is was just **accidental double removal of a component**. This happened on remove called twice from different user actions (out navigation and a button click). 

While code-wise it does not look like an obvious programming error, it still caused 500 and the whole application crashes quite dramatically. We should try to protect developer from creating bad UX like this either by having proper examples or more 

I guess right the developer solution would be to use try-catch on removal, but feels unnecessary code, since the second removal could just be ignored in most of our double-removal-case: We just want to be sure the component is not there anymore. Furthermore, I think this extra try-catch is quite inconvenient to use, if the remove call is e.g. inside a single line lambda.

It would be most convenient to allow also null components to be ignored and endorse application code like this:
```
onUserEvent(e -> parent.remove(component));
```
Ignoring both null values and non-existent components, if this information has no user logic in my application.

Now this needs to be something like to be this to avoid full application crashes and to be fully correct:
```
onUserEvent(e -> {
    try {
        parent.remove(component);
    } catch (IllegalArgumentException ignored) {}
    } catch (NullPointerException ignored) {}
});
```
Or how would that be in the documentation examples?

Without knowing better, I feel that roughly following the API boolean return behaviour in `java.util.List` classes for insertion/deletion is most logical for a typical Java developer, and we could also ask this another way around: what is the use case for throwing an exception that a boolean return value would not solve?
