### ISSUE TITLE
Inconstant loading order of theme files causes css override issues

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/flow#4602]
This issue has two distinct aspects, both stemming from the fact that the order in which theme files and the application's custom styles are loaded is not constant but varies in unpredictable ways.

**Case 1: Using Lumo as the theme, and applying tweaks to components with custom theme modules**
- Any custom theme modules are loaded up-front when the application loads.
- If the initial view of the application loaded into the browser does not contain e.g. `vaadin-button`, the Lumo theme modules for `vaadin-button` are not loaded.
- When a` vaadin-button` is loaded into the UI for the first time, its Lumo theme modules are loaded.
- Since the Lumo theme modules have been loaded _after_ the application's custom theme modules, their css will override any css with selectors of the same weight.
- The only workaround seems to be to artificially inflate the specificity of styles in the custom theme modules, either by adding `!important` after every property, or e.g. by prefixing each selector with `:host(vaadin-button)`.
- This issue can be easily missed by developers since it only occurs if the component in question is not present in the view initially loaded into the browser.

**Case 2: Using a custom theme with Lumo as basis**
- To clarify, this means creating a custom theme class and theme module files for each component, which import their Lumo equivalents.
- Since developers will rarely want to create a new theme from scratch, basing the custom theme on Lumo, by importing its component theme modules into the theme's custom theme modules, is the most reasonable option.
- This is also a workaround for Case 1, since the custom theme modules are now loaded simultaneously with the Lumo modules.
- The problem is instead that Lumo's default variable values sometimes (randomly?) override any values specified in the custom theme.
- This seems to be caused by the fact that Lumo theme modules for components import the Lumo base files containing the default values, and that these are sometimes (randomly?) loaded into the browser _after_ the custom theme's global stylesheet.
- This issue can also be easily missed because it only happens sometimes. In Chrome I've been able to reproduce it fairly consistently by soft-reloading (Cmd-R) the page, but I suspect that it depends on purely stochastic factors such as file size.
- I have not been able to find a reliable workaround.

@jouni knows more about the issue.

**Comment by Legioth** [comment]
The workaround in both cases is most likely that anything that you know about that *must* be interpreted before your own stuff *must* explicitly imported (i.e. `<link rel="import">`) by your stuff so that the browser will delay interpreting your stuff until the other stuff has also been interpreted.

In Case 1, this means that your custom theme HTML file should have a HTML import for the `vaadin-button` theme file.

In Case 2, this means that each of your own global theme module must also have HTML imports for the Lumo base files.

**Comment by rolfsmeds** [comment]
First of all, I think you got case 1 and case 2 mixed up a bit there:
Case 1 is using Lumo with theme modules on top.
Case 2 is using a custom theme whose component modules import their lumo equivalents.

So if I understand your suggestions correctly, your're saying:
1. In case 1, my custom theme modules need to import the corresponding theme modules from Lumo.
2. In case 2, my custom theme's global html file needs to import all of the Lumo base files.

I've tried both, but neither seem to work.

**Comment by Legioth** [comment]
I believe we're talking about the same thing, but apparently my analysis is based on some assumption that doesn't hold true. It should be possible to verify each assumption independently of the other factors with some simplified experiments.

The first assumption is that evaluation order actually has an impact. We can test that with two separate buttons where one imports the Lumo file and the other imports your own file (at this point not containing any Lumo imports). Clicking the buttons in one order should always lead to a working result and clicking in the other order should always lead to a broken result.

The second assumption is that cross importing in general affects evaluation order. To avoid relying on any other assumptions, we would need to define a bunch of custom elements, `<x-a>` through `<x-c>`, that each logs a distinct row when their constructor is run. We would then define `a.html` and `b.html` which each only contains a tag for the respective element. A button that imports both of those should sometimes log `x-a` first and sometimes `x-b` first. There would finally be `c.html` which contains an import for `a.html` and a tag for `<x-c>`. A button that imports both `a.html` and `c.html` should consistently log `x-a` before `x-c`, even if loading of `a.html` is artificially delayed.

If both those assumptions hold, then we can be sure that the order of initializing `<custom-style>` affects the outcome and that adding cross imports affect initialization order. In that case, we would have to look for more subtle reasons for the observed defects.
* What's the impact of custom element definition order during the initial load: What if `<custom-style>` is upgraded before `<dom-module>`? What if `<vaadin-button>` is upgraded before either of the other relevant elements?
* Could some part of the evaluation be happening through e.g. `setTimeout` or in a microtask in a way that makes it more sensitive to exact loading timings compared to when loading the imports from separate buttons?
* Is each import loaded exactly once? Is each import actually loaded and not accidentally triggering a 404 error or something similar?

Is there anything here that is inherent to Flow, or would the same problems also occur in a similar Polymer application?

**Comment by jouni** [comment]
> Is there anything here that is inherent to Flow, or would the same problems also occur in a similar Polymer application?

Flow handles to component imports, so the developer can’t clearly control the import priority of those.

**Comment by jouni** [comment]
Made a quick test using Polymer 3 – so JS Modules instead of HTML Imports, but that should not make a difference – where I load `shared-styles.js` upfront, which overrides `--lumo-primary-color to red and uses that for the native button color.

When you click the button, `vaadin-button.js` is lazily loaded and added on the page, which causes the global `--lumo-primary-color` to be overridden. The vaadin-button theme override in `shared-styles.js` is not affecting the vaadin-button theme.

From an implementation point of view this is expected, I suppose, but it is a bit unexpected to the user/developer.

One possible fix is to import `vaadin-button/theme/lumo/vaadin-button-styles.js` from `shared-styles.js`, like Leif suggested, since we are sort of depending on that to be available in order for our customizations to have any effect.

It might be that we should avoid encouraging this kind of “shared styles” approach altogether, and instead find ways to make it easy to author styles more modularly (load global styles upfront and component specific styles when the component is loaded) so that all styles in an app can be loaded when needed (vs everything upfront). I suppose Rolf’s case 2 is basically that?

Not sure if this provided any new info.

**Comment by rolfsmeds** [comment]
My proposal is twofold:

1. Lazy load custom theme modules similarly to the components own files -- this way any theme module for e.g. `vaadin-button` will be loaded simultaneously with the raw and Lumo styles for that component. This should fix the issue in my Case 1.

2. Remove imports of the Lumo "foundation" stylesheets (color, typography, etc) from the Lumo stylesheets for each component, and simply expect them to be imported separately, e.g. in shared-styles.html. This should fix the issue in my Case 2.

**Comment by rsivan** [comment]
Just wanted to add my own clash with this issue, starting a couple of days ago, when I tried to set a different size for the various Lumo fonts. My first instinct wat to switch the order of the annotations for HtmlImport and Theme, which did not work, and I think, after reading the current thread, I finally understand that this is related to the lazy loading nature of modern JS.
Rolf: why would your proposal item 2 work? Isn't a lazy load going to happen AFTER the user custom modifications is already processed by the client?

**Comment by rolfsmeds** [comment]
@rsivan the rationale behind my proposal #2 is that currently each Vaadin Component's Lumo stylesheet (aka theme module) imports the Lumo base stylesheets containing the default values for each property, and these are loaded _after_ whatever values you set because they're lazy loaded, and thus override your values. So my proposal is to remove those imports from the Lumo stylesheets for each component, so that the loading of the Lumo base stylsheets (and thus the default values) could be controlled by the developer who can make sure they are loaded before custom values (e.g. by importing them in their own non-lazy-loaded base stylesheet).

That being said, I'm still not 100% sure about the mechanisms behind the case 1 and case 2 issues -- just guessing based on my understanding of Flow, Lumo, html imports and my own limited tests -- so I can't claim any certainty in the validity of the proposed fixes.

**Comment by pleku** [comment]
Since in Vaadin 14 npm all the frontend files are server in one bundle for the initial page, I think this is not anymore an issue.
For the compatibility bower mode, I have no idea what should be done for this ? @jouni do you have any suggestions how we should fix this ? Also, @enver-haase you have BFP'd this so please comment what you'd expect us to do and can you switch to use npm mode instead (if I'm right and this is not an issue there) ?

**Comment by jouni** [comment]
I think this issue was already fixed in v13, by prioritizing the built-in component style sheets/modules over custom ones, using the `vaadin-`, `lumo-` and `material-` prefixes as indication of the built-in ones.

All style sheets/modules being bundled in the initial page load wouldn’t by itself solve the issue, as the modules can still be in an order that the built-in ones are registered later.

The priorization based on the style sheet/module ID seems like a workaround, though, and it would be great to figure out how to make this behavior more deterministic and predictable for the user. I don’t have a clear idea for that at the moment.

**Comment by enver-haase** [comment]
As far as I can see the problem went away with Vaadin14's npm mode.
