### ISSUE TITLE
Id annotation is spring aware

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/flow#4634]
Id annotation seems to be spring aware. Is this intentional and documented somewhere? For example we had a uiscoped spring component (MyCustomDialog) that was extending Dialog and then in a polymer template vaadin-dialog which was injected to java side with Id annotation and it turned out that the instance was not pure Dialog but actually that uiscoped spring component extending dialog (MyCustomDialog).

**Comment by denis-anisimov** [comment]
This is not exactly true.

`@Id` instantiates components via `ComponentUtil` class which uses the `Instantiator::createComponent`  method ( `ComponentUtil::componentFromElement`).

`Instantiator::createComponent` delegates the execution to the `getOrCreate` method which first check whether there is a managed bean available and use it if there is only one such bean.
Otherwise it instantiates a bean.

May be `Instantiator::createComponent` implementation should be changed in Spring so that it never tries to get an existing bean.
Or may be change a logic so that it checks the exact class.......

**Comment by Legioth** [comment]
Checking the exact class is probably the way to go. If I recall correctly, something similar was manually done for the Vaadin 8 version of Bakery.

**Comment by denis-anisimov** [comment]
Comments extracted from a PR for the proper fix:

The method `Instantiator::createComponent` is called from the ComponentUtil::componentFromElement and this method says: `Creates a new component instance ....`
`Instantiator::createComponent` should never do get. It should always do create.

- we should reimplement Instantiator::createComponent.
- we should reimplement SpringInstantiator::createComponent.

Both should not use `getOrCreate` at all but implement create semantic.
