### ISSUE TITLE
Setting the same innerHTML property twice clears it

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#4644]
When the `innerHTML` property of an `Element` is set, the content is first cleared.

If the property is set to the same value as the previous, the change is not communicated to the client, only the clearing, and as such the value is cleared.

*Steps to reproduce*

1. Add a button and a Div to a page
2. When clicking the button, call `div.getElement().setProperty("innerHTML", "Something");`

*Actual results*

On the first click, the inner HTML is set. On consecutive clicks, it is cleared.

*Expected results*

On the first click, the inner HTML is set, and is retained after consecutive clicks

**Comment by Legioth** [comment]
This happens because of the way `setProperty("innerHTML", value)` is handled in a special way to explicitly remove all server-side children. What happens is that the `removeAllChildren()` method sends instructions to the client to also remove children that the server might not have been aware of. The final piece of the puzzle is that when you set the same property value again, the server assumes that it doesn't need to send an update to the client since the client already has that value of `innerHTML`.

You can work around this by using `executeJavaScript` to bypass both problematic pieces of logic. This would then be something along the lines of `div.getElement().executeJavaScript("this.innerHTML = $0", "foo");` when using the new `Element.executeJavaScript` shorthand that was introduced in Vaadin 12.

**Comment by zanonmark** [comment]
The workaround `this.getElement().executeJs("this.innerHTML = $0", text)` worked properly until 14.0.5, while upgrading to 14.0.7 broke everything.

**Comment by stefanuebe** [comment]
I still use the setProperty("innerHTML", value) and simply check before, if innerHtml is already the same value as the value I want to set (`Objects.equals(value, getProperty("innerHTML")`). Worked fine so far.

**Comment by melDavila** [comment]
I use this works around:

String tmp = "<div hidden=true>" +System.currentTimeMillis() + "</div>";
myDiv.getElement().setProperty("innerHTML",getTxt()+ tmp);
