### ISSUE TITLE
Verify that the platform is OSGi compatible

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4658]
Add an IT to vaadin/platform that verifies that Flow and all the components in the platform snapshot build are OSGi compatible. An example of OSGi ITs can be taken from the Flow nightly validation build for OSGi (https://github.com/vaadin/flow/tree/master/flow-tests/servlet-containers/felix-jetty).

**Comment by denis-anisimov** [comment]
It may be possible to reuse the existing IT tests (per component) via making then OSGi compatible in the similar way as existing `flow-test-root-context` module has been modified to produce a `-ui` clarifier jar which is WAB OSGi file .

In this way there will be no need to create new IT tests for every component.

But this will require some configuration in the component so that it produces test UIs which are OSGi compatible and also some components have to be made functional (e.g. grid requires its connector to be available via HTTP which is not a part of the ticket to make component OSGi compatible).

**Comment by pleku** [comment]
The test should use _all_ of the Vaadin components in it, and verify that those work (render, are clickable or whatnot).

**Comment by denis-anisimov** [comment]
PR : https://github.com/vaadin/platform/pull/479

**Comment by denis-anisimov** [comment]
More issues in platform: 
- https://github.com/vaadin/platform/issues/483
- https://github.com/vaadin/platform/issues/484
