### ISSUE TITLE
Listen to filtered events (keyup for enter, right click)

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#468]

**Comment by Artur-** [comment]
The low level implementation for this could be adding
```
Element.addEventListener(String eventType, String filterExpression, DomEventListener listener, String... eventDataExpressions)
```

The `filterExpression` would be like `eventDataExpressions` but instead of just being included in the event message to the server, it would decide if the event is fired at all. 

The client side should forward the event to the server if at least one `filterExpression` matches but on the server the matches need to be filtered out so that only matching listeners are fired. An keyup listener for `enter` must never receive an event for `escape` even if somebody else is listening for that.

Implementation-wise the `filterExpression` should probably be included in `eventDataExpression` for filtering on the server side.

**Comment by Legioth** [comment]
There is also https://github.com/vaadin/flow/issues/467 that might be related since both basically need a server-side API for defining logic that determines under which conditions a client-side event should be sent to the server. The main difference is that in this ticket the decision is `send now` vs `never send`, whereas #467 also needs a way of postponing the handling of an event, i.e. `send now` vs `maybe send later`.

Similarly to how `enter` events shouldn't be passed to the `escape` listener, debouncing of one event listener shouldn't cause another listener to be debounced.

For a really low-level experience, we could unify both concepts so that `filterExpression` would instead be `filterOrScheduleExpression`. In addition to evaluating to `true` or `false` for immediately sending or discarding, the expression would also be allowed to produce a `Promise` that would trigger sending of the event when being fulfilled (if ever).

For a more high level API, it might be appropriate to use some kind of builder. One approach for this could be to add manipulation methods to the registration returned by the regular "simple" `addEventListener`. We might even consider including `eventData` there as well instead of the current varargs parameter. All this could be implemented on top of a low level `addEventListener` method that uses the `filterOrScheduleExpression` concept. I'm also starting to consider whether `eventData` values should also only be delivered to the event handler for which it was registered.

In that way, the example with enter immediately and other keys debounced could be expressed like this.

```java
element.addEventListener("keypress", handleEnter).filter("event.key == 'Enter'");
element.addEventListener("keypress", handleAnyKey).filter("event.key != 'Enter'").debounce(debounceTimeout);
```

**Comment by Artur-** [comment]
#3684  is also about this

**Comment by Legioth** [comment]
Basic implementation in https://github.com/vaadin/flow/pull/3912. Still waiting for the dust to settle on https://github.com/vaadin/flow-and-components-documentation/pull/75 before updating documentation.

**Comment by Legioth** [comment]
Documentation in https://github.com/vaadin/flow-and-components-documentation/pull/93
