### ISSUE TITLE
Change in "Class Binder<BEAN>"

### ISSUE THREAD

**Issue by shadikhani** [vaadin/flow#4680]
in "https://vaadin.com/api/platform/11.0.1/com/vaadin/flow/data/binder/Binder.html", the "writeBean(Object) or writeBeanIfValid(Object)" should change to "writeBean(Object), writeBeanIfValid(Object) and validate(Object)" whenever we talk about the bean level validator.

**Comment by gilberto-torrezan** [comment]
Looks like this is a ticket for [Framework](https://github.com/vaadin/framework), and not Flow.

Do we have the same problem in Flow's Binder?

**Comment by shadikhani** [comment]
I edited the issue. Whenever it talks about the "bean level validators", the "writeBean(Object) or writeBeanIfValid(Object)" should change to "writeBean(Object), writeBeanIfValid(Object) and validate(Object)".

**Comment by pleku** [comment]
The issue description is a bit unclear, I'm not sure what should be done. Maybe this is trivial fix to do if you know the problem, and should be just fixed directly instead of creating an issue about ?

Closing this issue, please reopen, comment here or create another with more information if this is important.
