### ISSUE TITLE
Image component File convenience api

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#4681]
It would be nice if the Image component had simple way of using a File object as the source instead of a String url or AbstractStreamResource. This is a quite typical beginner use case (I have a picture and I want to show it on my app) and while the AbstractStreamResource allows you to read a file with a FileInputStream, this is not very discoverable by looking at the API.

**Comment by Legioth** [comment]
Exposing this kind of API might be convenient, but it's would also to some degree encourage doing things in the wrong way.

Static images (i.e. already existing files) should typically be served statically from `src/main/webapp` (or `src/main/resrouces/META-INF/resources` in a .jar`) instead of being tied to each user session. The exception is of course cases where access control is also required, but for those cases there are also more efficient solutions.

**Comment by pleku** [comment]
This looks like a _won't fix_ after no further comments have been opened in a while. In case it would be needed, I think a new issue will appear at some point..
