### ISSUE TITLE
UI.getCurrent().add(Components... ) is not working.

### ISSUE THREAD

**Issue by muksihs** [vaadin/flow#4690]
Version 11:

- Description of the bug

Calling UI.getCurrent().add(someComponent) does not add the component to the active UI body tag.

- Minimal reproducible example

UI.getCurrent().add(new Label("some label"));

- Expected behavior

The Label would be added to the body tag.

- Actual behavior

The DOM is not updated.

**Comment by muksihs** [comment]
Work around:

UI.getCurrent().getSession().access(()->{
				System.out.println("command via session");
				HasComponents context = UI.getCurrent();
				context.add(new Label("ADD TO UI VIA SESSION EXECUTE"));
		});

This implies that ThreadLocal fetch of the UI while in the main view isn't working correctly or something.

**Comment by muksihs** [comment]
This in a view's constructor. The operation works correctly inside #onAttach.

**Comment by Legioth** [comment]
From where is the `SteemVaadinView()` constructor run? I suspect what happens here is that it's run from outside a regular request handling context, which in turn means that it's fully expected that an `access()` call is needed. 

Try running your code with assertions enabled (e.g. passing `-ea` as a JVM parameter). This should reveal any cases where you're modifying the UI state in an unsupported way.

**Comment by denis-anisimov** [comment]
I'm pretty sure this is known "issue":

- if you modify the `UI` children during the normal request then nothing will be done since `Router` "takes care" about this: before route component is set everything is removed from `UI` element in the `UIInternals::removeServerSideChildrenFromUI`  method. So any component which you have added manually is really added but then removed by the router.
- If you modify the `UI` after router has done its job then this modification will be there just because router doesn't modify the `UI`  instance anymore.

This is quite confusing behavior which discovered over and over again and we at least have to document it somewhere.

**Comment by Legioth** [comment]
What's the purpose of calling `removeServerSideChildrenFromUI`. Could we maybe remove it? I guess it will only have an impact if you have overridden `UI.init()` or if doing something similar to what's done in this ticket?

**Comment by denis-anisimov** [comment]
It's called inside `showRouteTarget`. 
The main purpose it to replace the component which is the current route.
May be it can be done in a more accurate way. I don't know the details. 
Just know the reason of this behavior.

**Comment by muksihs** [comment]
If called from onAttach every works as naively expected. Clear documentation I think is the fix.

**Comment by Legioth** [comment]
I couldn't find any other reason for detaching all children except that it's the most convenient way of ensuring any previous chain root is detached. I created a PR that finds the previous root and only detaches it instead of detaching all children: https://github.com/vaadin/flow/pull/4699
