### ISSUE TITLE
setFilter doesn't update visible rows in Grid immediately

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow#4721]
In Vaadin 8 I called setFilter and the state (visible rows) of Grid changed immediately. In Vaadin 10, grid changes set of visible rows only after additional user action in the browser (e.g. click into a text field on the form).

**Comment by vlipovetskii** [comment]
Please change the status from enhancement to bug, since users can't use the filters now. It's completly unacceptable to them.

**Comment by Legioth** [comment]
How is this issue reproduced? My simple test route seems to work exactly as expected
```
@Route("grid")
public class FilteredGrid extends VerticalLayout {
    public FilteredGrid() {
        ListDataProvider<String> dataProvider = new ListDataProvider<>(
                Arrays.asList("one", "two", "three", "four"));

        dataProvider.setFilter(value -> value.length() == 3);

        Grid<String> grid = new Grid<>();
        grid.addColumn(value -> value);
        grid.setDataProvider(dataProvider);

        add(grid, new Button("Update filter",
                event -> dataProvider.setFilter(value -> value.length() == 4)));
    }
}
```
Initially, `one` and `two` are displayed. After clicking the button, `four` is displayed.

**Comment by heruan** [comment]
It works for me too, when calling `setFilter` the grid refreshes with filtered content.

**Comment by vlipovetskii** [comment]
I call setFilter from TextField.addValueChangeListener. A user types text in the TextField, and filter should change visible rows in Grid. This chain works like a charm with Vaadin 8 but not with Vaadin 10.

**Comment by Legioth** [comment]
This is not an issue with `setFilter`, but rather with how `TextField` fires value change events. By default, text fields only submit the new value to the server when the user presses the [enter] key or when the field is blurred. This is changed compared to Vaadin 8 where there's a `LAZY` change mode that is used by default.

Since there no `LAZY` mode implemented for Vaadin 10, the default is `ON_CHANGE` (which reacts to [enter] and blur). There is also an `EAGER` mode, but it's not used by default since it's too chatty in many situations. See https://github.com/vaadin/vaadin-text-field-flow/issues/114 about getting a `LAZY` mode also for the new TextField implementation.

This example works for me. Note that you must change the value change mode of the text field.
```
@Route("grid")
public class FilteredGrid extends VerticalLayout {
    public FilteredGrid() {
        ListDataProvider<String> dataProvider = new ListDataProvider<>(
                Arrays.asList("one", "two", "three", "four"));

        Grid<String> grid = new Grid<>();
        grid.addColumn(value -> value);
        grid.setDataProvider(dataProvider);

        TextField filter = new TextField("Filter", valueChange -> {
            String filterValue = valueChange.getValue();
            if (filterValue.isEmpty()) {
                dataProvider.clearFilters();
            } else {
                dataProvider.setFilter(value -> value.startsWith(filterValue));
            }
        });
        filter.setValueChangeMode(ValueChangeMode.EAGER);

        add(grid, filter);
    }
}
```
