### ISSUE TITLE
Navigation using JS

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#476]
It should be possible to navigate to another view using Javascript, i.e. using the router link feature from Javascript without having a `<a routerLink href="target">`

**Comment by Haprog** [comment]
We have this

```java
@ClientCallable
public void navigateTo(String path) {
	if (path.startsWith("/")) path = path.substring(1);
	UI.getCurrent().navigate(path);
}
```

But this simple method only works for URLs without query parameters.

See https://vaadin.com/api/platform/com/vaadin/flow/component/UI.html

`navigate(String location)` throws an exception if the `location` contains query parameters so instead of that in that case we would need to use `navigate(String location, QueryParameters queryParameters)`.

But when calling from JS I would expect a single method that handles both variations (so it could parse the query params to create `QueryParameters` object and use that version of the method instead when needed).

**Comment by pleku** [comment]
Closing as old and outdated issue. If it would become important, it will resurface.
