### ISSUE TITLE
@Theme Annotation sets the theme attribute in the body instead of the html tag

### ISSUE THREAD

**Issue by appreciated** [vaadin/flow#4765]
### Description
The [`Theme`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/theme/Theme.java) Annotation causes the `theme=...` to be set in the `body` tag instead of the `html` tag. 
This causes in the case of Lumo dark that __some__ css variables are still overwritten by values of the light theme. 

[You can find a more detailed example here](https://github.com/vaadin/vaadin-lumo-styles/issues/51)

### Reproducible example
Any Vaadin 10 and 11 Application that contains a `ComboBox` and uses the Lumo dark Theme suffers from this issue.

###  Expected behavior
The values of the CSS Variables of the dark theme should never be overwritten by the values of the light theme. As already stated this could be archived, by setting the `theme=...` in the `html` tag instead of the `body` tag.

### Actual behavior
The values of the CSS Variables of the dark theme are __sometimes__ overwritten by the values of the light theme. F.e. the shadow of the overlay in a ComboBox. 

### Versions
- Vaadin 10 and Vaadin 11 
- Windows and Probably all other platforms
- Reproduced on Chrome and FF.

**Comment by pleku** [comment]
For now we can fix this (and backport the fix) by duplicating the theme attribute from the annotation to `html` element too. Then, starting from eg. `V13` we can remove the attribute from `body`.

**Comment by pleku** [comment]
Related to https://github.com/vaadin/vaadin-lumo-styles/issues/51

**Comment by denis-anisimov** [comment]
The problem is API method name.

`AbstractTheme` has the method `getBodyAttributes`.
`Lumo` theme implements this method so that it returns `theme` key with a value depending on variant.
`BootstrapHandler::handleThemeContents`  method adds everything from  `getBodyAttributes` as attributes to the document body.

What we should do is: add attributes to the `html` tag, not its body.

And then there are a number of questions:
- is it a common case that we should add attributes returned by the `getBodyAttributes` method to `html` instead of `body` ?
- if the answer to above question is yes then `getBodyAttributes` should be renamed. Which means API change.

I expect the answer to the first question yes since the only attribute that are returned by the `getBodyAttributes` method is `theme` (at least in both standard themes `Lumo` and `Material`).

If the answer is no then we need one more method `getHtmlAttributes` along with `getBodyAttributes`.

In both cases it's API change though in the second case we may add a new method with default implementation so that it doesn't break anything.

And I'm not sure which way I should fix this even on the implementation level:
- should I repeat all the attributes from `getBodyAttributes` on the `html` tag level
- or should I just add them to `html`  tag instead of `body` 

In the second case we have to do something about the method name.
In the first case we may keep it as is for now but we still need to rename or add one more method to `AbstractTheme` in the `master`  branch.

What should I do ? @pleku

**Comment by denis-anisimov** [comment]
Adding @caalador for this discussion as well.

**Comment by appreciated** [comment]
Any updates in this?

**Comment by pleku** [comment]
@denis-anisimov for V13 (master branch) we can fix this immediately by adding the `getHtmlAttributes` method with default implementation and move the `theme` attributes for `Lumo` and `Material` to that one. Since there probably is no case for adding the attributes to `body` instead of the `html` tag, probably could also add `@Deprecated` with comment on javadocs that `getHtmlAttributes` should be used instead. 

But for a fix that could be ported back to V12 or V10 it gets rather ugly when we want to fix the bug without breaking API and changing behavior. We probably need to add logic in the `BootstrapHandler` that duplicates anything added to `body` also into `html`, but only for `Lumo` and `Material` (latter is only V12).
This way we don't break any custom implementations that expect the behavior to stay the same.
There is still the theoretical possibility that we will affect some application theming with this change, so we need to highlight it on release notes.

**Comment by Frettman** [comment]
I'm using Vaadin 14.1.17 (in a Spring Boot application) and have exactly the same problem. `theme="dark"` is set on the body instead of on the html tag. Setting a breakpoint in `Lumo#getHtmlAttributes` leads me to TaskUpdateImports where those attributes are added using this template: `document.body.setAttribute('%s', '%s');`

`BootstrapPageBuilder#handleThemeContents` is never called because I'm not running in compatibility mode.
