### ISSUE TITLE
Generate resource URls based on content and make them cached forever

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#478]

**Comment by Haprog** [comment]
I think this would be really helpful for the website making it easier to have better caching and also cache busting. Mainly we would benefit from good cache busting atm. so that user's would get a mix of old and new resources (can cause style and logic problems) after site update when some resources are cached and others are not.

Related to this it might also be needed to have some API for getting generated asset paths for use in custom code (in JS and Java) and maybe also some extra processing of asset paths in HTML and CSS files (maybe using some custom syntax for wrapping asset paths that would get replaced with final deployed path)?

**Comment by Legioth** [comment]
The only remaining file that comes to mind is `vaadinPush.js`.

**Comment by mshabarov** [comment]
We use service worker for offline apps in V23 and in `StaticFileServer::writeCacheHeaders` the cache headers are added. Not sure this issue is valid / needed.
