### ISSUE TITLE
Upload events not fired on Vaadin 11.0.2

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4785]
Downloaded the latest bakery starter (11.0.2), added a simple view with a simple upload component. None of the upload related event listeners are fired. With 11.0.0 and 11.0.1 it worked.

```
@Route(value = "upload", layout = MainView.class)
@PageTitle(BakeryConst.TITLE_UPLOAD)
public class UploadView extends VerticalLayout {

    public UploadView() {
        MemoryBuffer singleBuffer = new MemoryBuffer();
        Upload upload = new Upload(singleBuffer);
        upload.setAutoUpload(true);
        upload.addSucceededListener(event -> System.out.println("hi")); // prints "hi" only in 11.0.0/.1, not in .2 

        add(upload);
    }
}
```

**Comment by denis-anisimov** [comment]
Please _ALWAYS_ spend some time to localize the issue.
You are making a ticket in Flow using a big custom project which doesn't strongly connected to Flow.
There is .always a chance that the bug is not in Flow.

In fact you are using wrong repository.
The bug is about `Upload` so it should have been created in `Upload` repo.

In reality this is a Spring add-on bug which is known (and there is already ticket for that).
`Upload` works fine in non-Spring project.

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/spring/issues/381

**Comment by andrea-tomassi** [comment]
> Please _ALWAYS_ spend some time to localize the issue.
> You are making a ticket in Flow using a big custom project which doesn't strongly connected to Flow.
> There is .always a chance that the bug is not in Flow.
> 
> In fact you are using wrong repository.
> The bug is about `Upload` so it should have been created in `Upload` repo.
> 
> In reality this is a Spring add-on bug which is known (and there is already ticket for that).
> `Upload` works fine in non-Spring project.

Of course you are right on the deep cause of the issue. But it is also true that Flow 11.0.0 and 11.0.1 Uploads are currently working fine. 
This is why I wonder if Flow 11.0.2 could still keep the previous behavior, just as a workaround in the meanwhile Spring fixes the real issue.

**Comment by heruan** [comment]
> But it is also true that Flow 11.0.0 and 11.0.1 Uploads are currently working fine with Spring (I can confirm that, too).

The fact that with 11 uploads were working is not entirely true: they worked only in certain cases due to a side-effect of how the Spring add-on was overriding the servlet dispatcher bean, which was causing other kind of troubles (see discussion in https://github.com/vaadin/spring/issues/331).

This was fixed in 12, so now there is a consistent behavior: upload doesn't work.

Of course 12 is in beta, and I expect uploads will be fixed before release.

**Comment by denis-anisimov** [comment]
One more time : `Upload`  work with Flow with any version.
Flow doesn't introduce any new issue/code which influence on this behavior.

Spring add-on has a workaround which allow to have a servlet mapped to "/*" along with Spring endpoints.
It does it via forwarding. 
In previous Spring add-on version there as one solution which caused other issues.
But this solution allowed to work `Upload`  _in some cases_. There were a bug about the same thing with  `@EnableMVC` annotation. 
Currently the previous solution is removed completely and as a result forwarding works inconsistently with `Upload`.
There is nothing to do in Flow. It's a pure Spring add-on issue.

**Comment by nuriaruiz** [comment]
> Downloaded the latest bakery starter (11.0.2), added a simple view with a simple upload component. None of the upload related event listeners are fired. With 11.0.0 and 11.0.1 it worked.
> 
> ```
> @Route(value = "upload", layout = MainView.class)
> @PageTitle(BakeryConst.TITLE_UPLOAD)
> public class UploadView extends VerticalLayout {
> 
>     public UploadView() {
>         MemoryBuffer singleBuffer = new MemoryBuffer();
>         Upload upload = new Upload(singleBuffer);
>         upload.setAutoUpload(true);
>         upload.addSucceededListener(event -> System.out.println("hi")); // prints "hi" only in 11.0.0/.1, not in .2 
> 
>         add(upload);
>     }
> }
> ```


I solved it by putting this in application.properties:
spring.servlet.multipart.enabled = false
