### ISSUE TITLE
Allow getting the ComputedStyleValue 

### ISSUE THREAD

**Issue by appreciated** [vaadin/flow#4833]
There is a possibility to get the Element's styles by using [`com.vaadin.flow.dom.Element::getStyle()`](https://vaadin.com/api/com.vaadin/flow-server/1.2.2/com/vaadin/flow/dom/Element.html#getStyle--). 

But the Element API currently does not allow getting the [computed Style Value](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) of a CSS Variable.
It would be really nice to have either the API of `com.vaadin.flow.dom.Element` or the API of  `com.vaadin.flow.dom.Style` extended by a function `getComputedStyleValue(String variable);` that returns the Element scoped value of the passed CSS variable.

**Comment by Legioth** [comment]
Computed styles are, as the name implies, computed by the browser based on lots of different factors. It's not feasible for us to re-implement all the logic for doing those calculations on the server.

Furthermore, there are lots of different thing that might trigger some computed style to change, and there is no good browser API for getting notified when that happens. This means that we cannot in any reasonable way automatically synchronize browser-computed values to the server so that they would be available for use from Java logic.

This only leaves the option that there would be separate method for asynchronously fetching specific values from the browser. Using this kind of API would be quite inconvenient, and the asynchronous nature actually means that there would many cases where it's not practical to do things in that way.

**Comment by pleku** [comment]
>It would be really nice to have either the API

Why would it be really nice ? What are you trying to achieve and why are you trying to achieve it ?

**Comment by appreciated** [comment]
> Furthermore, there are lots of different thing that might trigger some computed style to change, and there is no good browser API for getting notified when that happens. This means that we cannot in any reasonable way automatically synchronize browser-computed values to the server so that they would be available for use from Java logic. 
These are some understandable arguments why computed styles should not be used.

> Why would it be really nice ? What are you trying to achieve and why are you trying to achieve it ?

I have a specific usecase where getting the mentioned value for a specific DOM Element is needed. 
Let's assume I want to bind the value of a TextField to a css variable of a specific Component. 

![example](https://user-images.githubusercontent.com/1729845/49445257-d34c0400-f7d1-11e8-8a8f-cd54af864354.PNG)

While overwriting the value is easy (via `Styles::set(...)`) getting the initial value is a "real pain" and I currently haven't found a way to do this easily with flow. If the id of the TextField is set this can be done as follows:
```
document.getElementById("text-field").value = getComputedStyle(document.documentElement).getPropertyValue('--lumo-primary-color')
```

I agree that "... re-implement all the logic ..." is not a good idea. 
So extending the API to `get the ComputedStyleValue` shouldn't be the requirement. 
What I'm currently missing is a bit on top of `void Element::callFunction(...)`. 
Something that could be described as follows `String Element::callFunctionAndReturnValue(...)`.

If you know an easier way to archive the same result let me know.

**Comment by Legioth** [comment]
Something along the lines of `callFunctionAndReturnValue` would indeed be very useful in many cases. There's already an open enhancement request for that feature: https://github.com/vaadin/flow/issues/1724.

Please note still that the return value would be something asynchronous like `CompletableFuture<String>` instead of immediately returning a `String` instance, or alternatively the return value would be `void` and instead you'd pass a callback as one of the parameters to the method.

**Comment by appreciated** [comment]
> Something along the lines of callFunctionAndReturnValue would indeed be very useful in many cases. There's already an open enhancement request for that feature: #1724.

Then I'll close this issue in favor of mentioned one.

> Please note still that the return value would be something asynchronous like CompletableFuture<String> instead of immediately returning a String instance, or alternatively the return value would be void and instead you'd pass a callback as one of the parameters to the method.

If the result comes synchronous or asynchronous doesn't really matter to me as long as I'm able to receive it 😉. And sure a non blocking call makes more sense in that case.
