### ISSUE TITLE
Spike: prototype a keyboard shortcut API for layouts / UIs

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4842]
The goal of the spike is to investigate how will it work to be able to solve these two use cases:

When building a form, I want to add a keyboard shortcut to the layout for the save button, so that I don't have to do it for every single field in the form separately (and save time)

When building an app, I want to add a keyboard shortcut for the whole UI, so that the user can access certain features of the app easily from anywhere

The outcome of this spike should demonstrate the usage of the API, which should be similar to #4841, and to see if there are any difficulties related to some web components.

**Comment by bogdanudrescu** [comment]
A layout needs to implement `Focusable` and invoke `setTabIndex(-1)` to be able to generate keyboard events.

It's a bit cumbersome to expect a user of the API to do both actions especially in 2 different places.

Maybe we could create an Annotation to only set the tabIndex, without the need of implementing Focusable, or some other method to register the tabIndex for a layout and see if that is enough, though I can't state any side effects (tabIndex set withour Focusable).

The other issue is that the layout must have `outline: none;` in `style` otherwise the focus rectangle will be there when focused.
