### ISSUE TITLE
ComboBox calls value change event with null value randomly

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/flow#4862]
Consider code that sets ComboBox value in server and adds value change listener

> combo.setDataProvider(new ListDataProvider<>(Arrays.asList("1", "2", "3")));
> combo.setValue("1");
> combo.addValueChangeListener(e -> System.out.println("this should not be called immediately"));

One would expect in this case that value change event would NOT be fired immediately but instead until user has changed the value from client side. However what happens seems to be randomly calling value change event with value null. See attached example project (based on project base starter) that demonstrates two identical templates that contains ComboBox that behave differently. One event listener does not get called initially while another does.

This started happening after updating from Vaadin 11.0.3 to 12.0.2

[comboboxsetnull.zip](https://github.com/vaadin/flow/files/2675698/comboboxsetnull.zip)

**Comment by denis-anisimov** [comment]
Doesn't seem it happens randomly.
The second injected combobox always invokes a value change listener.

I'm pretty sure that this listener is invoked from the client side as a reaction of default  `null` value.
That's expected behavior **_IF_** the value has not been set from the server side explicitly.
But this value is set from the server side. So there should not be any updates from client.

I think it relates somehow to the fact of using injected comboboxes via `@Id`. This functionality has a lot of issues. May be this is one of those.

**Comment by pekam** [comment]
This bug needs quite specific conditions to occur. You need to have two different `PolymerTemplates` with `@Id`-mapped combo boxes, and both of these `PolymerTemplates` need to be `@Id`-mapped inside a parent `PolymerTemplate`. If you create and add the `PolymerTemplates` that wrap the combo boxes with Java, the bug doesn't occur. If the combo boxes are in the same inner `PolymerTemplate`, the bug doesn't occur.

So I was able to reproduce it only with exactly this structure:
```
        PolymerTemplate
             /      \
          @Id       @Id
PolymerTemplate    PolymerTemplate
          /            \
      @Id              @Id
    ComboBox         ComboBox
```

Couldn't reproduce this by doing the same with `TextFields`.

**Comment by pekam** [comment]
I created a workaround for `ComboBox`: https://github.com/vaadin/vaadin-combo-box-flow/pull/174

It sets the missing value-property via JavaScript, because setting the property is ignored via the Element-API in this specific scenario.

There still seems to be a bug in Flow's `PolymerTemplate`/`@Id`-feature. Otherwise it's hard to explain how this specific scenario causes the bug to occur, while for example using `parentComponent.add(polymerTemplate1, polymerTemplate2)` doesn't.
