### ISSUE TITLE
Text Javadoc could be improved

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/flow#4882]
`Text` Javadoc does not describe the component well enough. Even though `Text` extends `Component`, it is unclear that it can't be styled. An attempt to style a `Text` also results in an unclear error message:
>Caused by: java.lang.UnsupportedOperationException: This instance is immutable

Javadoc should provide more information and probably an `@see` to `Span`.

**Comment by denis-anisimov** [comment]
The ticket is confusing: it's about `Text` component but it says something about style.
There is no API in `Text` which can be used to style the component.
Every such component should implement `HasStyle`  interface. But `Text` doesn't implement it intentionally.

So there is no simply API which can be called to style `Text`.
You still may use Element API but this has no any relation to Component API. It's just different API.
`Text` implementation already improved so that any attempt to use Component API to set property or attribute will throw a _meaningful_  exception.

So as a fix for this ticket I will extend javadocs for `Text`  and mention that you can't set any attribute and style the component but that will target Element API usage rather.
