### ISSUE TITLE
Create RouteConfiguration for developer dynamic route handling

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4890]
For a better DX the developer should have a class `RouteConfiguration` which he can use
to edit the registered routes (dynamically add/remove).

For adding there should be methods that allow
- utilising annotations
- adding collections
- defining all parts programmatically

Developer should be able to request from the configuration all existing routes and
add route change listeners.

The configuration should be able to batch configure a single registry e.g. offer a way to utilise `RouteRegistry.update()`

`RouteConfiguration` should not be a data storage only a delegator.

All the registry editing convenience methods should be removed from RouteUtil.

**Comment by pleku** [comment]
Any methods that are removed from `Router` to `RouterConfiguration` should be deprecated and marked for removal in V15.

All the `getUrl` methods in `Router` should be also deprecated and marked for removal in V15, with a comment that _there is no replacement planned because you should be using either RouterLink or UI.navigateTo. If you need this for something else, please create an issue to github.com/vaadin/flow._

**Comment by pleku** [comment]
Update the tutorial to be based on this https://github.com/vaadin/flow-and-components-documentation/pull/362

**Comment by Legioth** [comment]
> All the `getUrl` methods in `Router` should be also deprecated and marked for removal in V15, with a comment that _there is no replacement planned because you should be using either RouterLink or UI.navigateTo. If you need this for something else, please create an issue to github.com/vaadin/flow._

Should I already now create an issue about being able to populate template-based navigation logic based on server-side navigation target classes, or should we maybe just leave those methods as non-deprecated?
