### ISSUE TITLE
Create WebComponent annotations

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#4916]
Create annotations WebComponent and WebComponentProperty.

WebComponent should be a class annotation.
WebComponentProperty should be for methods and fields.

**Comment by Legioth** [comment]
Is it described anywhere how those annotations would be used in practice?

**Comment by caalador** [comment]
`@WebComponent("my-custom-component")` will be used to collect and register the `<my-custom-component>` as a WebComponent on the server that will be served when a request for `my-custom-component.html` (later to be handled for `.js`) comes.


`@WebComponentProperty(value = "name", initialValue = "Joe")` is used on a field or a method as

```
@WebComponenProperty(value = "name", initialValue = "Joe")
private String name = "";
```
or
```
@WebComponenProperty(value = "name", initialValue = "Joe")
public void setName(String name) {
  nameField.setText(name);
}
```

`@WebComponentProperty` will be used to generate properties and propertyMethods for the served component.

**Comment by Legioth** [comment]
What does it mean to have `@WebComponentProperty` on an instance field? Apparently, the initial value will be present immediately when the element is upgraded in the browser. I might also imagine that value changes are propagated from the client to the server, but it's not clear how anyone would use that since there's nothing that shows how server-side logic can react to such changes. Can the property value also be updated from the server, and in that case how? What about initial values for properties with some other type than `String`?

For methods, it looks like the same idea as `@ClientCallable` except that the JS functions would be attached directly to the element instance instead of in a separate `$server` namespace? In that case, the thinking in https://github.com/vaadin/flow/issues/4925#issuecomment-452202352 might be of interest. What does `initialValue` mean for a method?

**Comment by caalador** [comment]
`initialValue` is set as the initial value for the property in the sent WebComponent html/js.

As such I don't see a problem in converting the initialValue String to Boolean, Number or Object depending on the property type as it's generated into the sent html/js.

**Comment by caalador** [comment]
1. A property value change on the client will generate a $server.sync that will update the property on the server which would then fire an event on the server.
2. the property value will always be a property with notify and sync observer.

the annotation initial value will be synced from the client after everything bound and override the "Hello" with "bar"

**Comment by Legioth** [comment]
1. So I'd have to do something like `getElement().addPropertyChangeListener("foo", event -> ...)` to get notified if the value is changed?
2. The problem there is that a server-side `this.foo = "update";` would cause things to become out of sync without any good way for the developer to understand what's going on. Another aspect of this is the confusion with two different ways of defining an initial value that will override each other.

Based on this, I would suggest an alternative API:
```
private final WebComponentProperty<String> foo = new WebComponentProperty<>(defaultValue);
```

With this API, there would only be one way of setting a value (`foo.set("update")`). It's also possible to add a typesafe value change listener without using a magic string for the property name.

The annotation for exporting a callback could instead be `@WebComponentMethod` to avoid a naming conflict with the property holder class.
