### ISSUE TITLE
Replace the owners form in Spring Petclinic with a Flow SSWC

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4940]
Fork the Spring Petclinic and replace the https://github.com/spring-projects/spring-petclinic/blob/master/src/main/resources/templates/owners/createOrUpdateOwnerForm.html with a Flow SSWC `<owner-form>` that implements the form using our components in a form layout.

So the `<owner-form>` is disguised as a web component and actually is a Vaadin Flow Spring Boot application. For this, you will need to make another module for the Flow application, and probably also move entities and Spring Data classes to another module.

The `<owner-form>` will probably (?) get the owner ID as a property when is opened, and then after save/cancel operation is done, the Flow app would either
a) update the URL
b) fire an DOM event that the Spring app catches
c) trigger a JS callback (Promise) that has been passed to it by the embedding application

**Comment by denis-anisimov** [comment]
I have doubts that I understand correctly the request in the ticket.

`createOrUpdateOwnerForm.html` form is somehow handled internally my Spring MVC once URL `/owners/new` or `/owners/{ownerId}/edit` is requested.

So I see two ways of replacing this form:
- remove mappings (or redirect to other other, external URLs) or replace anchors with e.g. `/owners/new`   to something like `http://host:another_port/new`.
- keep mapping as is but replace the content.

Tickets says : `So the <owner-form> is disguised as a web component and actually is a Vaadin Flow Spring Boot application.` So it means that we should have one more Spring boot application running on a different VM in addition to original Spring boot application?

In this case the first way with replacing the URLs should be chosen.
But then I don't understand why we are talking about embedding/web component.
Another web server serving its own URL has no any knowledge of the original page. It will just show 
the page from the another web application as is.
It means at least that there will be no any navigation bar header which is used in the original application (or we will have to duplicate it).
But anyway: no any embedding here at all. And two pages doesn't share DOM tree so it's just simply not possible to fire or do whatever on the client side.

In case of the second option: replacing the content `createOrUpdateOwnerForm.html` form means that I should just register an additional `VaadinServlet` which serves specific URLs within the same existing Spring boot application.

I think  it should be the second option since the first one almost has no sense.

**Comment by pleku** [comment]
>In this case the first way with replacing the URLs should be chosen.
But then I don't understand why we are talking about embedding/web component.
Another web server serving its own URL has no any knowledge of the original page. It will just show
the page from the another web application as is.
It means at least that there will be no any navigation bar header which is used in the original application (or we will have to duplicate it).
But anyway: no any embedding here at all. And two pages doesn't share DOM tree so it's just simply not possible to fire or do whatever on the client side.

For this case we want to be able to reuse the Java code to access the backend, thus the Flow application (that is embedded as a web component) will be running in the same project as another module, running on the same server (and JVM) and have its own servlet.

The Flow web component should be a part of the page that the existing Spring MVC app is loading. The existing app will need to 
- import `owner-form.html` to the page from the url of the Flow app
  - can be done with JS if no access to `<head>` otherwise
- add the <owner-form></owner-form>` web component to the HTML and communicate to it from JS using the web component properties, which the Flow app will read and use to populate the web component data and store data, and then to fire event (or the other mentioned options) when e.g. save has been done.

You can [inline JS in Thymeleaf](https://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#script-inlining-javascript-and-dart)

**Comment by denis-anisimov** [comment]
OK, thanks.

**Comment by denis-anisimov** [comment]
Probably I'm doing something wrong but this scenario doesn't work for me:

I made a branch https://github.com/denis-anisimov/spring-petclinic/tree/web-component

`webcomponents` is a module of the project.
Vaadin servlet is registered with `/vaadin/*` mapping.
`owner-form` is added to `createOrUpdateOwnerForm.html`  .
Its `_registerElement()` method calls `flowRoot.$server.connectWebComponent` but this RPC goes to
`http://localhost:8080/owners/?v-r=uidl&v-uiId=0`.
Since Vaadin servlet it mapped to `/vaadin/*` this request is not handled by Vaadin and nothing works.

It looks like "webcomponents support" should properly detect the URL where Vaadin RPCs go instead of relying on plain non-embedded behavior.

**Comment by pleku** [comment]
Are the `src` correct for the resources ? Are those actually served right (no 404) ?
```html
<script type="text/javascript" src="/frontend/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
 <link rel="import" href="/vaadin/web-component/owner-form.html">
```

>but this RPC goes to `http://localhost:8080/owners/?v-r=uidl&v-uiId=0`.
This would seem to me that instead of the web component, it is loading normal vaadin bootstrap page and sending some update to server ? I am just guessing though.

@caalador can you take a look ?

**Comment by denis-anisimov** [comment]
```
<script type="text/javascript" src="/frontend/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
 <link rel="import" href="/vaadin/web-component/owner-form.html">
```
Those are served right and works as they should.
For the first one I've mapped a `VaadinServlet` to `frontend/*` URI.
The second one works as it should (I've added Spring boot `ServletContextInitializer`  which takes care about `WebComponentRegistry` ).

`connectWebComponent` is supposed to be called on `WebComponentUI`  instance and RPC is trying to do that.
But it does it in the same way as for a regular Vaadin application, using the currently opened URL which is `http://localhost:8080/owners/new` . It doesn't know that Vaadin application is mapped to `/vaadin/*` and in fact webcomponents logic in Flow doesn't have anything related to such situation.

**Comment by caalador** [comment]
That's true. but you can add the import for UI as a link by yourself to get it up also.

**Comment by caalador** [comment]
Perhaps the Generated file shouldn't try to import the UI but it would be up to the user to add the import to the page themselves

**Comment by denis-anisimov** [comment]
The `UI` is initialized via the link `<link rel="import" href="/vaadin/web-component/web-component-ui.html">`.

This link is in the generated `owner-form.html` file (which is correctly served by Vaadin).
Generated `owner-form.html` works correctly: all imports work, Vaadin UI is initialized via import `<link rel="import" href="/vaadin/web-component/web-component-ui.html">` and `_registerElement()` method works.
It tries then call the `connectWebComponent`  method. And this method can't work since it doesn't know anything about mapping of Vaadin application. It's located on the page which is loaded from the 
`http://localhost:8080/owners/new` URL and since there were no any changes on the client side logic it tries to connect the server side by the regular URL. But Vaadin application is mapped to the different URI and client side doesn't know anything about that.

**Comment by caalador** [comment]
Oh. True the client side does a `conf.setServiceUrl(WidgetUtil.getAbsoluteUrl("."));` with the server not giving anything specific for it.

**Comment by denis-anisimov** [comment]
yep.

**Comment by denis-anisimov** [comment]
Do I correctly understand that the web-component form should save the owner as a result of the button click (so this is a part of the web component logic) and then redirect to the petclinic application page?

So functionality wise it should implement the existing controller logic (save bean using JPA repository and redirect to the created owner page) inside the web component without delegating to the existing controller method (via making a client side request which contains all the data so that OwnerController is able to handle the incoming request).

**Comment by pleku** [comment]
>Do I correctly understand that the web-component form should save the owner as a result of the button click (so this is a part of the web component logic) and then redirect to the petclinic application page?

>So functionality wise it should implement the existing controller logic (save bean using JPA repository and redirect to the created owner page) inside the web component without delegating to the existing controller method (via making a client side request which contains all the data so that OwnerController is able to handle the incoming request).

That was the original idea, have it save things to the backend through Flow instead of the Spring app. Otherwise using Flow would not make much sense compared to using just a Polymer template there.

So the form is in that way full control of the editing of the owner entity. Does it make sense in your opinion ?

**Comment by denis-anisimov** [comment]
Sure. Otherwise the form is just a proxy which gives L&F and nothing else.
It also allows to apply binder and and binder based validation.

On the other hand `OwnerController` also does some validation. And there could be a theoretical usecase when the developer would like to keep this Spring validation.
But in this case there is no much sense to use Vaadin embedded component since it will require a lot of efforts to make the component acting as a proxy only without any logic.

**Comment by denis-anisimov** [comment]
The code is here https://github.com/denis-anisimov/spring-petclinic/tree/web-component.
It should work with the latest Flow SNAPSHOT which contain a number of fixes for server side webcomponents.
