### ISSUE TITLE
Shortcuts: Add alternative shortcut event handler which gets ShortcutEvent

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#4953]
Current shortcut handlers take no parameters and the handler has no way of knowing which shortcut invoked it, if the handler is used for multiple shortcuts.

Implement an overload for registering a handler, which receives a ShortcutEvent (contains at least key information).

**Comment by pleku** [comment]
### Acceptance Criteria
- Add `addShortcutListener` methods to `UI` and `Shortcuts` to accept `ShortcutListener<T> that gets `ShortcutEvent<T extends Component>` instead of `Command` (see `addShortcut`) 
- `ShortcutEvent<T extends Component>` should have details about:
  - `getKey() Key`
  - `getKeyModifiers() Set<KeyModifiers>`
  - `getSource() T extends Component // this is what is currently known as "owner", the thing that the listener is registered on`
   - `getLifeCycleOwner() Component`
