### ISSUE TITLE
Some css properties seem not to be synchronized to the client side. 

### ISSUE THREAD

**Issue by appreciated** [vaadin/flow#4976]
When setting the following css property nothing happens on the client-side:
```
Div div = new Div();
div.getStyle().set("display", "-ms-grid");
add(div);
```
But when retrieving it 
```
String style = div.getStyle().get("display"); // -> style = "-ms-grid"
```
The value is not malformed in any way so it should be set also on the client side.

**Comment by Legioth** [comment]
I think this mostly out of our control. It seems like the browser ignores invalid values when applied by assigning values to the `style` property of DOM elements. I tried this in Chrome by selecting an element in the Elements section of the developer tools and then running `$0.style.display="-ms-grid"`, which had no effect. Assigning the value as `$0.setAttribute("style", "display: -ms-grid")` does on the other hand stick.

To be able to bypass this, we would have to concatenate values everything as an attribute instead of incrementally updating the `style` object, as also described in https://github.com/vaadin/flow/issues/4974#issuecomment-456393534.

**Comment by appreciated** [comment]
@Legioth first of all thanks again for your time 🙏! I managed to archive what I wanted by using:
```
Component::getElement().callFunction("setAttribute","style",value);
```
But thats quite some workaround 😐 
Using 
```
component.getElement().setAttribute("style", value);
```
didn't work as expected. Does using `setAttribute` also update the properties incrementally?

> To be able to bypass this, we would have to concatenate values everything as an attribute instead of incrementally updating the style object, as also described in #4974 (comment).

Hopefully there is a simpler way to fix this, but currently I'm clueless in that aspect.

**Comment by appreciated** [comment]
>  I tried this in Chrome by selecting an element in the Elements section of the developer tools and then running $0.style.display="-ms-grid", which had no effect. Assigning the value as $0.setAttribute("style", "display: -ms-grid") does on the other hand stick.

Executing `$0.style.display="-ms-grid"` in works in IE which I guess is all that matters. document.getElementById("content").style.display="-ms-grid"

**Comment by Legioth** [comment]
There's custom logic in `Element.setAttribute` that delegates to `StyleAttributeHandler` when the `style` attribute is set from the server. That handler parses the provided string and applies those styles in the same way as when directly using `setStyle()`. We're doing things in that way to get the expected outcome from something like this:
```
element.setAttribute("style", "width: 20px");
System.out.println(element.getStyle().get("width"));
```

On the client, the styles are always applied in the way described in the linked Stack Overflow answer, e.g. by assigning a property to the magic `element.style` object.

I will close this issue since the only thing we could do about it would be to change the client-side logic to apply styles as an attribute instead of through `element.style`. This potential change is already also covered through #4974 since it would also be required for that functionality.
