### ISSUE TITLE
HasUrlParameter confusing

### ISSUE THREAD

**Issue by romst** [vaadin/flow#4982]
To me at least, the name of the class is quite confusing, since I expected the interface to help me with parameters like "?theme=*" as alternative to "VaadinRequest.getCurrent().getParameter(*)", while it's actually a variable part of the route.

If still possible, I would like to suggest a rename (HasRouteParameter?), maybe even an actual class for the URL query (HasUrlQuery?) to replace the VaadinRequest call. Especially if you have a lot of parameters or even encrypted parameters, the HasUrlParameter variant is not an option.

Minimum change would be to improve the JavaDoc, since I had to search online what the interface actually does.

**Comment by ujoni** [comment]
In the tutorial for [Routing and URL Parameters](https://vaadin.com/docs/v12/flow/routing/tutorial-router-url-parameters.html), see "Query parameters". The query parameters are accessible through the `Location` given by the `BeforeEvent event`.

Would that alleviate some of the pain of using `HasUrlParameter`?

**Comment by romst** [comment]
Yes, I've somehow completely missed the "Query parameters" part of that tutorial.

Still, it doesn't feel like the interface is adding much. In many cases, you probably don't need the generic parameter, and since it's part of the location, it could be omitted. 
Also, I don't like the naming of "setParameter", since it's not a setter, but an event hook. "onNavigate" would be more fitting, maybe even with a **NavigationEvent**, instead of an **BeforeEvent**.

**Comment by pleku** [comment]
We actually had a discussion about renaming the url parameters to path parameters a while back as we were adding support for having the parameters in the middle. Changing the name for path parameters was on the table, but we decided not to do the change since _url parameters_ were used by other frameworks too (iirc Spring MVC) and we decided to keep the same name for not causing changes to existing applications.

Thanks for the feedback. I don't think we're going to change this at this point though as it has not been a major issue for users, while we acknowledge that the initial naming could have been different.
