### ISSUE TITLE
WebComponent security

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5005]
Create a security feature that can be used to not serve a `WebComponent` from the server if a missing security key is missing from the request.

This will be needed for instance when you have a `WebComponent` that gets data from a backend database that shouldn't be available for everyone.

- Extend `@WebComponet` annotation with a boolean `isSecured`, `needsAuthentication` or the like
- `WebComponentProvider` should check this for found web-component request and ask from `session.getService().getAuthentication()` if it's ok to serve for request. If not OK then return HttpServletResponse.SC_FORBIDDEN [403]

- Create `public interface Authentication` and `DefaultAuthentication implements Authentication`
- Make it possible to set your custom `Authentication` implementation

**Comment by Legioth** [comment]
I'm not sure I understand the purpose of this feature. Why cannot the developer instead define a regular `WebComponentProperty` for the security key and then do something like this in the constructor:
```
if (!"secrets".equals(secretKeyProperty.get())) {
 add(new Text("You cannot see secrets unless the correct secret key is provided"));
 return;
}
showSecrets();
```

**Comment by caalador** [comment]
You probably could, but then you would actually need to check the property after a value change and populate after the inital back and forth as if you check in the constructor you get the initalValue that you have set.

Also the better choice instead of the property would probably be
```
@WebComponentMethod("authenticate")
public void auth(String key) {
Assert key.equals(something);
// do init of data etc.
}
```

**Comment by caalador** [comment]
https://github.com/vaadin/flow/tree/issues/5005_secure_key

**Comment by denis-anisimov** [comment]
I think the approach with properties is the most convenient one.

The original approach suggests to block even the component generation in case of "insecure request".
To be able to do that the `link` import element should be properly handled (not the element itself but the URI which it contains).
So instead of having just :
`<link rel="import" href="web-component/my-component.html">`
one should use something like this:
`<link rel="import" href="web-component/my-component.html?some_ugly_hash&may_be_other_params">`

Then we will need to ask something (via SPI) whether the query string is OK or not.
- we will need to parse somehow the query string and make a contract around parsed data for the SPI
- we should ask SPI inside a `RequestHandler`  where almost no context is available: there is no  `UI` yet, we can't use `Instantiator` to create an authenticator instance (implementation-wise it's an issue since we will need to make new API for loading this instance  overall and reimplement it in DI every time because users will want to use DI to make a decision in the authenticator).

And the only win is: the web component is not even generated, UI is not instantiated, the wrapper is not created.

But I think it's not worth our efforts:
- if we don't want to show the component at all because of absence of authentication then the initial page should be generated without the import at all (it moves a pice of authentication to the embedding application side)
- if the authentication is failed because it's an attempt to get an access without permission then there is no need to care how many requests will be done during the invalid attempt of access
- on the other hand if the request is valid then the round-trips between the client and server side will happen anyway.

Also I see general usecase when your embedded web component should behave differently depending on provided security token: e.g. it should give access to different  pieces of functionality depending whether you are authenicated user/admin/super-admin.
And the basic original usecase in the ticket is superseded by this requirement.
But the requirement means more complicated logic than just allow/deny and it's already possible to do it via the properties mechanism. So no need to invent one new way for simple subcase.

So I'm going to write a tutorial just using the properties approach

**Comment by Legioth** [comment]
How would it even work with something like `<link rel="import" href="web-component/my-component.html?some_ugly_hash&may_be_other_params">` if we also take production bundling into account?

One additional concern is that failed authentication should preferably not cause errors in the browser, but instead the exported web component should have a way of showing some alternatives contents with e.g. a login form or a message about the need to log in.

**Comment by denis-anisimov** [comment]
> How would it even work with something like <link rel="import" href="web-component/my-component.html?some_ugly_hash&may_be_other_params"> if we also take production bundling into account?

We still generates the "web-component/my-component.html" content in production (though it's not anymore HTML and it shouldn't be `link import` but a script tag). So would work in the same way.

>One additional concern is that failed authentication should preferably not cause errors in the browser, but instead the exported web component should have a way of showing some alternatives contents with e.g. a login form or a message about the need to log in.

That's also true.
