### ISSUE TITLE
WebComponent handling in Production mode

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5008]
Investigate how to handle  `WebComponent`s in production mode whit bundling.

**Comment by pleku** [comment]
@Legioth in #4984:
>If each web component has its own bundle, then how do you avoid loading multiple copies of Polymer which each wants to register their own `<dom-module>` custom element?
>
>If the web component uses the hosting page bundle, then how will it know how to translate the URL for `@HtmlImport("bower_components/vaadin-button/vaadin-button.html")` into `frontend-es6/vaadin-flow-bundle-a006a12d1fd571e.cache.html`.

**Comment by pleku** [comment]
This is about investigating two things:
1) embedding a Flow app in production, it has a bundle and expects that the embedded doesn't have anything conflicting
2) the embedding application has already loaded everything, and expect that the embedded Flow application doesn't try to import anything

**Comment by pleku** [comment]
As based on #5226, we need to either make the web component generation happen during build time so that is available for the transpilation and bundling, or we can test first if the generated web component works in ES5 required browsers without transpilation and it would just import the flow es5 bundle (or let Flow client engine do it?).

**Comment by denis-anisimov** [comment]
So one more round of investigation has shown:
- we can't use the generated web component Polymer template declaration as is (it doesn't work in IE11)
- we may generate "transpiled" template content and it works but there are a number of disadvantages:
   - the transpiled content is an issue by itself since it's not simple code anymore
   - it depends on the way of our approach in the handling of generated component. If we change the way then it's not easy to change the transpiled code
   - the content depends on browser (it's different in es5 and es6 cases)
   - the transpiled content is in 1.5 times more without minification (vs minified). And it's very inconvenient to generate minified version .

Overall the generation of transpiled content is badly maintainable.

It has been decided to go with the other way: generate the content at the build time and transpile everything using the plugin.
This way we don't even need to care about the content of the generated web component : we can change the content at any time without any other changes.

**Comment by denis-anisimov** [comment]
The first issue is extracted #5382
