### ISSUE TITLE
Extend the automatic servlet initialisation to also work with WebComponents

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5070]
Currently Flow will automatically initialize the Servlet if there is a Route available.

This should be extended so that the Servlet is initialized when there is a `@Route` or  a `WebComponentExporter<C extends Component>` available.

 `ServletDeployer` contains the logic for this.

**Comment by pleku** [comment]
The documentation should be updated that the servlet will be automatically registrated.

**Comment by Legioth** [comment]
> The documentation should be updated that the servlet will be automatically registered.

I'd suggest taking it one step further. The basic documentation shouldn't mention servlets at all since that would just be confusing when the user doesn't have to care about it at all. There can still be a notice in some advanced section about how to override the configuration that is applied by default.

**Comment by pleku** [comment]
One thing to consider is that when the embedded application is working as a Portlet, there should be a way to not register the servlet out of the box. It might be enough that the Portlet registration disables the servlet registration.

**Comment by denis-anisimov** [comment]
When you are talking about documentation you mean the tutorial O believe.

The problem is that the current tutorial can't avoid a custom servlet registration at all.
The existing tutorial is trying to be simple so that it uses the same WAR with two servlets : the main app servlet and SSWC servlet which should be registered to a custom URI. So no automatic registration.

The tutorial which uses the automatic registration should use either a static page with SSWC or it should be about two WAR files deployed may be to separate servers.
The static page is a very artificial example so I would avoid it int the tutorial.
The example with two WARs is more complicated than the example with one WAR. 
Such example requires another tutorial section (I personally think the existing tutorial is easier than an example with two WARs and recommend to keep it) and totally separate ticket is required to write it from scratch. It's not a small task.

As a result: I will only add a _NOTE_ to the existing tutorial instead of do it other way around: make it by default and make a note that servlet can be registered manually.
