### ISSUE TITLE
SPIKE: make a proposal that unifies the WebComponentProperty and @WebComponentMethod

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5078]
Current API is a bit confusing, the `WebComponentProperty` and `@WebComponentMenthod` are overlapping and confusing a bit. Those should be unified somehow, probably only one thing should be needed for handling the property for:
- updating the value to client
- automatically getting updates for the value from client
- being able to react when the value changes

Make a proposal (without implementation) that showcases the usage by updating the following example & tutorial:
- https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/advanced/tutorial-sswc.asciidoc
- https://github.com/denis-anisimov/spring-petclinic/blob/web-component/webcomponents/src/main/java/org/springframework/samples/webcomponent/OwnerForm.java

Should also consider that the embedding application should be able to listen for changes on the properties (e.g. by getting events when changed).

**Comment by denis-anisimov** [comment]
I think I don't really understand the ticket since:
- neither tutorial nor the `petclinic`  example doesn't use `@WebComponentMethod`. And they already works fine. So `WebComponentProperty` is functionality is enough for them.
- `@WebComponentMethod` is just another convenience way to implement similar functionality which is provided by the `WebComponentProperty` .

- `WebComponentProperty` allows has `set`  method which allows to update the value. Theoretically it should send the value from the server side to the client side which allows to update value to client as required in the first item (not sure whether it really does with the current impl but this ticket is not about impl).
- It's possible to add a listener to `WebComponentProperty` which allows getting updates and being able to react on value changes. This is demoed in the tutorial and `petclinic`  example.

So I don't see how tutorial/example can be updated since they already uses the functionality.

Listen changes on properties: `set` method of `WebComponentProperty`  should update the client side value which should produce a change event in the Polymer component representing the web component. So on the client side you should be able to add a listener via `.addEventListener('property_name-changed', listener)` and receives the notification about the `property_name`  changes (again: not sure that it works with the current impl).

The only not clear thing is `@WebComponentMethod` usage.
Several things here:
- the annotation name is confusing for the functionality which is provided by the method annotated with it.
- I'm not sure about usecase to invoke a server side method (theoretically annotated with `@WebComponentMethod`) from the client side. The embedded web component should be self-contained. And exposing any method/internals of it looks weird: you don't really have an access to internals of generated Polymer component. So why there should be a way to invoke a _server side_ method and not invoke any other client-side method (which just doesn't exist there at all)?
- If you want to call a server side method as a part of the internal component implementation then you always may add another component inside embedded web component and call this method on it via `ClientDelegate`.

The current behavior of `@WebComponentMethod`  is just a convenience.
Every time when you use `WebComponentProperty` you have to add the listener to it. Without the listener there is no any way to get _the real value from the client side_ even initially set. If you call `get` on  `WebComponentProperty`  instance in the CTOR of you server side web component or even in the `onAttach`  method then the value will be the default value specified in the  `WebComponentProperty`  declaration and not the value from the client side.
So you have to add a listener to the instance to be able to set the real client side value.
`@WebComponentMethod` is already a listener. So it just allows to reduce the amount of boilerplate code which you need to write.
But `@WebComponentMethod` is not a replacement for `WebComponentProperty` :
- if you need to track the property value then you have to introduce a field in the class and save it there. `WebComponentProperty` does it for you automatically.
-  `@WebComponentMethod`  doesn't allow to send a value to the client side.

So in case you don't need to track the value and update the value from the server side to the client side the  `@WebComponentMethod` is more convenient to use  than `WebComponentProperty` .

But as I said: 
- the annotation name is confusing.
- `WebComponentProperty` functionality supersedes `@WebComponentMethod` functionality. Though `@WebComponentMethod` is more convenient in many cases.

As a result: I don't know what should be done with `@WebComponentMethod`. Whether it should be just removed, renamed or its functionality should be changed to behave like `@ClientDelegate`.

But : I've written the tutorial and the `petclinic` so I'm not a proper person for this ticket apparently.
I will work on another one and let someone else to work on this one.

**Comment by ujoni** [comment]
Since this ticket is about leveraging and improving the existing server-side web component API, I tried to have a go at improving the Pet Clinic example. I was unable to affect credible changes to the example. All the things I though of mostly resulted into falling back onto existing Flow API conventions and methods as the other Spike ticket aspires to do. If we try to take the `WebComponentProperty` construct away, we immediately arrive at the `Element` API or something similar.

So instead of changing the Pet Clinic example, I created a more hypothetical example which allows more room for demonstration. Since this example has discreet web component properties, I added a few Annotations to be used in conjunction with the property definitions. These annotations are meant for the `xxxWebComponentGenerator` to either use or discard - hence annotations rather than member variables of properties.

The below example is built from a perspective the we might in the future have a way to dictate what kind of generator is used to produce the Web Component. In the example, we aim to produce a Polymer 3.0 Web Component, but a Vue, or even React (though a large deviation) components could be a possibility. Hence the WebComponent aims to define a generic template asset, as well as a functioning web component.

```java
@WebComponent("test-web-component") // -> test-web-component
public class TestWebComponent extends Div {

    /*
        WebComponentProperty wrapping a Person-class instance.
        Has @NotifyChange annotation for automatically generating dom-events
        when property is updated.

        This is always true with the current implementation.
     */
    @NotifyChange // polymer: notify
    private Property<Person> personProperty = new Property<>(Person.class)
            .as("person");

    /*
        Simplified property, allowing for boolean values, bound to an
        attribute owned by the component by @LinkToAttribute - this mirrors
        Polymer's 'reflectToAttribute'

        Should the binding be two-way, and should it be defined separately.
        Is the binding property's or attribute's option? (Usually, it is of
        the property).
     */
    @LinkToAttribute // polymer: reflectToAttribute
    private BooleanProperty showFullName = new BooleanProperty();

    // or IntegerProperty?
    private Property<Integer> legalAge = new Property<>(18, Integer.class);

    private TextField firstName = new TextField();
    private TextField lastName = new TextField();

    public TestWebComponent() {
        /*
            Binder which is tied to the firstName and lastName of the Person
            bean hidden inside 'Property<Person> personProperty'.
         */
        Binder<Person> personBinder = new Binder<>(Person.class);
        personBinder.bind(firstName, "firstName");
        personBinder.bind(firstName, "lastName");

        personProperty.setBinder(personBinder);

        showFullName.addValueChangeListener(event ->
                lastName.setVisible(event.getNewValue()));
    }

    /*
        Mirrors Complex Observers from
        https://polymer-library.polymer-project.org/3.0/docs/devguide/observers

        This annotation would be provided by PolymerWebComponentGenerator or
        something similar - not a native annotation to flow. Used to
        demonstrate potential extensions.
     */
    @PolymerPropertyObserver({"user.age", "legalAge"})
    private void onPropertyUpdate(int age, int legalAge) {
        getElement().setAttribute("adult", age >= legalAge);
    }
}
```

I am with Denis that `@WebComponentMethod` is a little bit superfluous and if provided, should come from a specialized WC Generator that provides something familiar, like a `PolymerWebComponentGenerator` assumed in the example.

I am not sure how much the generated web component was supposed to be able to leverage the support of the library the component is based on (polymer, etc), but currently we are "missing out" on some of the features. For example, template data binding does not work. We cannot write `<span>{{property-name-here}}</span>`; the property value won't be bound there and the result is a weird string rather than dynamic text.

**Comment by Legioth** [comment]
Looking at existing web components, e.g. there are four fundamental concept for how logic on the host page interacts with the component.

1. Persistent state that is accessible through attributes or DOM node instance properties, e.g. the current value.
2. Instance methods that can be called to perform one-time actions, e.g. to explicitly validate the current value and update the internal state of the component depending on the result.
3. Fired DOM events, e.g. that the current value has changed.
4. Assigning children to slots, with the component internally reacting to slotchange events for further processing.

My understanding is that `WebComponentProperty` or any naming variation of that allows a component implemented on the server to offer API aspect 1.

API aspect 2 would instead be covered by how I understand `@WebComponentMethod`. I don't see how this is in any way be overlapping with `WebComponentProperty`. One is about persistent state, the other is about one-time actions (e.g. RPC).

I'm currently not sure whether the two remaining API aspects can be implemented in any nice way with our current designs. Adding slots to the shadow root can be done through `new Element("slot")`, but we don't provide any high-level API for that, not for listening to slotchange events. Anything ought to be possible with `executeJavaScript` (assuming I can target the web component instance by passing it as an argument), but that's a gain a low-level detail.

**Comment by Legioth** [comment]
Handling persistent state, i.e. property or attributes, needs the following details defined in a way that the code generator can find them: property name, property type, initial value and whether it should be reflected to an attribute. Furthermore, the runtime needs to provide a way of seeing the value set from the client, listening to value changes and setting a new value that should be sent to the client.

Instance methods requires the code generator to know the name of the method. At runtime, there needs to be a way of knowing what server-side logic to run if the client-side method has been invoked.

DOM event firing doesn't need anything when the code is generated. It only needs an API method for actually firing an event based on an event name and optional details to include in the fired event.

Slot handling needs nothing when code is generated. At runtime, it needs to be possible to add slots and to optionally also a slotchange listener.
