### ISSUE TITLE
SPIKE: use existing Flow API to modify embedded Flow application in DOM

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5079]
Make a proposal that updates the following example and tutorial 
* https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/advanced/tutorial-sswc.asciidoc
* https://github.com/denis-anisimov/spring-petclinic/blob/web-component/webcomponents/src/main/java/org/springframework/samples/webcomponent/OwnerForm.java

by using exising concepts like element API, property change events, `ClientDelegate`(?), `Tag` maybe even `PolymerTemplate`/`TemplateModel` instead of `WebComponentProperty`, `@WebComponentMethod` and `WebComponent("foo")`.

So this will highlight the case where I can simply just take an existing Flow server side component, and export it as a web component without reworking the logic that much. The metadata that should be available for the the web component generator is 
- web component tag name
- web component properties that are declared, so that it will be easier for the embedding app to know what API it can use

**Comment by denis-anisimov** [comment]
The conversation of `OwnerForm` may look like this:

```
@Tag("owner-form")
@WebComponent(value={ @WebComponentParameter(name="actionname", type=String.class), @WebComponentParameter(name="owner", type=Double.class)})
public class OwnerForm extends Component implements HasComponents {

    public OwnerForm() {
       getElement().addPropertyChangeListener("actionname",
                event -> saveButton.setText(getProperty("actionname","")));
        getElement().addPropertyChangeListener("owner",event -> setOwner(getProperty("owner", -1d) ));
    }

    // everything else is the same except {@code setOwner()} method which now should 
   // accept double and convert it to Integer
}
```

So here:
- we are reusing `@Tag` and don't set the tag name in `@WebComponent`  annotation.
- `@WebComponent` annotation mark the class generally as a SSWC (so it doesn't have `@HtmlImport` with the declaration) and it's Polymer template file is generated.
- The generator uses a metadata from `@WebComponent`  annotation (if any): properties. Properties are declared in the same way as `WebInitParam`  : they have the property `name`  and `type` methods in the annotation.
- There is an issue with `type` parameter : we support quite limited number of types for properties. The types are `String` , `boolean` ,  `double` , `JsonValue` . It's an open question do we need to support other types ( so do we need converters) . In the example we will need to declare `double` instead  of `Integer` (this is inconvenient). Otherwise we will need a static validator for the types used there.
- The property is used as is in Flow Element API. So the "actionname" property is the property of `OwnerForm` component's `Element` .
- The SSWC represents exactly the polymer element on the client side without any aggregation. So the `OwnerForm` instance is the server side representation of `owner-form` element. It allows to use Flow API to set property, get property, add a property listener, add a `@ClientDelegate` method to call a server side method.
- In the example it implements `HasComponents` mix-in which allows to add any component directly inside the  `owner-form` client-side element.
- `addPropertyChangeListener` method is used to get  a notification about property change from the client side to the server side.

Such approach allows to to any required action:
- get the value of the property on the server side
- be notified about change of the property on the server side
- set the property value on the server side so that it's set on the client side as a result
- add a listener on the client side for the property change event 
- call JS directly on the  `owner-form` element which allows to fire any kind of event with the component as a source.

The inconvenient thing is: 
- you have to add a server side listener for the property change every time when you use the property.

Without a listener you will not be able to get a value set on the client side (even initially): it needs to be send from the client side to the server side and if you use the property value in the component CTOR or even in `onAttach` method then the value is not yet the client side value.

So we may allow to use a method which is a listener method for the property change inside the component. So instead 
```
getElement().addPropertyChangeListener("actionname",
                event -> saveButton.setText(getProperty("actionname","")));
```
it would be 
```
@WebComponentPropertyListener("actionname")
private void onActionNameChange(String actionName){
    saveButton.setText(getProperty("actionname",""));
}
```
It allows to avoid writing boilerplate `getElement().addPropertyChangeListener` all the time. 
But this is optional way. You always may use `getElement().addPropertyChangeListener`  just because you can.

Another way which should theoretically already work out of the box is using `PolymerTemplate` with a model class. The only issue is that we a going to get rid of this concept. But anyway it's worth to mention:
```
@Tag("owner-form")
public class OwnerForm extends PolymerTemplate<OwnerModel> implements HasComponents {

    public interface OwnerModel extends TemplateModel {
           void setActionName(String name);
           String getActionName();

           Integer getOwner();
           void setOwner(Integer ownerId);
    }

    public OwnerForm() {
       getElement().addPropertyChangeListener("actionname",
                event -> saveButton.setText(getModel().getActionName()));
        getElement().addPropertyChangeListener("owner",event -> setOwner(getModel().getOwner()));
    }

    // everything else is the same 
}
```

The benefit here is : 
- no need to declare metadata since it's already send from the server side to the client side via the model properties declaration 
- No need to have converters. They are already there and model supports a number of built-in types.
- Better way to set/get properties avoiding Element API : `getElement().getProperty("property_name")`.

But still an issue with a property listeners: you need to add a property listener to get the value from the client side.

Tutorial code may be converted using those ideas in absolutely obvious way.

**Comment by Legioth** [comment]
I'd say that the overall drawback of any of the suggested approaches here is that the character combination `actionname` (disregarding slightly inconsistent casing) is repeated multiple times and at least one of those is always as string constant that will from time to time contain typos that the complier cannot catch.
