### ISSUE TITLE
Form View bug

### ISSUE THREAD

**Issue by ChristopheFM** [vaadin/flow#5107]
Hello, I have an interface using **Vaadin 10.0.7** with **Java 1.8** which has a Form. It looks like it works on any device except for Safari on iPhone. 

The problems are:

- when the user selects an element of the form (textfield, combobox or radiobutton), the screen scrolls to the top of the view. The focused element if now not visible anymore. Only when the user starts typing, the screen scroll back to a "good" position.

-> In this case a good position is having the focused element on the top of the view. It would be very nice to have that "good position" by default when focusing an element of a form.

- when selecting the "arrow" of a combobox, the list of items opens and you can select one. But, when you click on the textfield of the combobox, the list of items don't open. It only opens when you start typing.

-> Is it possible to always open the list of items of a combobox when focusing that element?

Reproduction of the scenario:

1. Create a FormLayout with enough items to be able to scroll on a mobile device.
2. Open the FormLayout with Safari on iPhone.
3. Scroll to the bottom of the FromLayout and select an element.
4. The screen will jump to the top of the FormLayout and back down when you start typing.

**Comment by ZheSun88** [comment]
Hi @ChristopheFM , I am trying to reproduce this bug as you reported, but failed. Everything works as expected for me.

- I am using [A project base](https://vaadin.com/start/lts/project-base) with add enough(around 20ish) TextFields in a FormLayout;
- I have tested with 10.0.7 and 10.0.11(which is the latest release);
- I am using an Iphone 7 plus with IOS `12.1.4`;

All other steps are the same as your scenario.
One thing i would like to suggest you is update the vaadin version to 10.0.11 and test again. There might be some cache problems also.  If the bug is still reproducible for you, can you provide a demo project for us. 

Thanks

**Comment by ChristopheFM** [comment]
Hi @ZheSun88 ,

I noticed that I could update the version of Vaadin and did it. It looks like it works, but no in a consistant way. Approximative 7/10 times it works. It doesn't scroll to the top anymore but I think the Safari browser doesn't focus correctly and the user experiences some strange behaviours some times... With this I mean that the browser is focused in such a way, that the user can't even scroll anymore. Waiting 1sec resolves the problem.

If you want, close the post. I'll open it if the problem becomes persistante or worse

Thank you

**Comment by ZheSun88** [comment]
Hi @ChristopheFM , 
Thanks for the reply. 
For now, I am going to close this ticket and please open another one when it becomes persistent and better with a project that can make bug reproducible. 

Thanks
