### ISSUE TITLE
Abstract view annotated with @Route gets published

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#5114]
If you create an abstract super class for your views, that gets published as a route, but naturally fails when user tries to navigate there.

Tested with 12.0.6, with following code snippet:

```
@Route
public abstract class AbstractView extends VerticalLayout {
    
}

public class SomeView extends AbstractView {

    public SomeView() {
        add(new Paragraph("Some"));
    }

}
```

In Spring apps this currently works correctly, in CDI apps only the abstract class gets published https://github.com/vaadin/cdi/issues/279 .

**Comment by mstahv** [comment]
As discussed in [vaadin/cdi#279](https://github.com/vaadin/cdi/issues/279) there might be app server specific differences how this works. I tested with jetty-maven-plugin

**Comment by denis-anisimov** [comment]
I'm not sure about `gets published as a route` meaning.

In my case when I run a test I'm getting the exception:
```
java.lang.RuntimeException: javax.servlet.ServletException: Exception while registering Routes on servlet startup
    at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart (ServletContainerInitializersStarter.java:69)
```
with a cause :

```
Caused by: com.vaadin.flow.server.InvalidRouteConfigurationException: Navigation targets must have unique routes, found navigation targets 'com.vaadin.flow.RealRoute' and 'com.vaadin.flow.AbstractRoute' with the same route.
    at com.vaadin.flow.server.startup.RouteTarget.validateNormalTarget
```

So we should improve our validation at startup  and don't register a route whose class is an interface or an abstract class.

**Comment by denis-anisimov** [comment]
The issue is more complicated than it seems.

The route validation for checking a single class per route path is done during the registration.
So there is no pre-validation. Registration has quite a lot of logic internally which is used to check uniqueness.
We probably should not filter out discovered abstract class  (even though they can't be instantiated): this strategy relies on the fact that we instantiate classes directly via their CTOR.
This assumption is wrong generally: the navigation targets are asked via `Instatiator` which may use other approaches than direct instantiation (like Spring where bean may be found by it's subclass).

But then we should allow to register abstract classes along with normal classes ( as it's done now).
And we need a way to resolve a conflict of classes with the same route target : if one of the class is `abstract`. 
And this is not easy since once route is added then current implementation adds some addition configuration to it and it fails if we register a route conditionally (e.g. we don't register a route with an abstract class if there is already a route with a normal class): it still tries to do configuration for a route which has not been added.

So even functionality-wise it's not that hard to avoid the exception but implementation-wise it's hard to change the existing code in the way to reuse and avoid breaking API changes.

**Comment by denis-anisimov** [comment]
CDI issue : https://github.com/vaadin/cdi/issues/284
But may be in fact this is not CDI issue.
