### ISSUE TITLE
Investigate memory occupied by parsed `stats.json` file in server

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5123]
stats file is huge, and it might hit server performance when maintaining the parsed object permanently in memory

**Comment by TomRauchenwald** [comment]
We noticed this as well.
In our case, the stats.json file is about 28MB. 
When loaded into a String, it uses about 55MB of heap.
`FrontendUtils.getStatsContent()` also calls `FrontendUtils.streamToString()`, which does a `replaceAll()` on the String, which builds the result in memory as well. 

I noticed that the stats.json file also includes various sources (if you look for the "source": key). Are they really needed in this step?

**Comment by pleku** [comment]
Hi @TomRauchenwald, thanks for the details. You are right on your observations. In defense, I can say that the parsing and replacing operations are only done once per application.

But this issue has actually been fixed since, and is already available in Flow 2.2 prereleases, which should be used in the upcoming 14.2 release. You can see #6922 and #6919 for reference. In tests the `stats.json` file size has dropped from 42mb to 686kb (-54x), so it should also help a lot for the memory usage.

To test this, you can try the first prerelease of 14.2 in 10 days or try immediately with Flow `2.2.0.alpha5` (or later prerelease) by adding the https://maven.vaadin.com/vaadin-prereleases/ repository and explicitly declaring a newer `flow-bom` version.

**Comment by pleku** [comment]
Closing this issue as it has been handled already with #6922 and #6919 for Flow 2.2.0alpha4.
