### ISSUE TITLE
IE11 & Edge fail

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5207]
@adexerivera commented on [Fri Mar 01 2019](https://github.com/vaadin/platform/issues/572)

We can't make work our vaadin application on IE11 or Edge. We are using vaadin version 10.0.11.

View image with webcomponent-lite.js error.

We use maven for dependencies, through some dependency we've this webcomponentsjs versions:

- org.webjars.bowergithub.webcomponents:webcomponentsjs:1.2.0
- org.webjars.bowergithub.webcomponents:webcomponentsjs:1.2.6

![errorsie11 edge01](https://user-images.githubusercontent.com/1585009/53641200-22b19d00-3c26-11e9-8728-fbd2f5a296fa.PNG)

**Comment by denis-anisimov** [comment]
Unfortunately the image with error doesn't allow to us to identify and reproduce the issue.

Please provide the project and steps which we should do to reproduce the issue.

**Comment by MichaelF25** [comment]
I am experiencing the same issue. I've started about a year ago with the Vaadin 10 Spring Boot Full Stack Starter App (Bakery). And fortunately, I've saved the unmodified app, since you can't download it anymore for Vaadin 10. After running via `mvn spring-boot:run` and trying to access the app on port `8080` via Edge (IE11 is not an issue for me), just an empty browser window is displayed and the JS console is filled with fatal error messages. Chrome, FF and Safari are working and since I am a MacOS user, my first customer using Windows with Edge stumbled over this issue :(

How could I share the unmodified Vaadin 10 Bakery Full Stack app? I am allowed to do this (licensing)?

**Comment by MichaelF25** [comment]
https://vaadin.com/forum/thread/17851939/was-vaadin-10-bakery-app-starter-ever-working-in-ms-edge-and-or-ie11

**Comment by pleku** [comment]
Issue fixed according to the forum thread above and has since been fixed in product.
