### ISSUE TITLE
Using Designer with OSGi Bundles

### ISSUE THREAD

**Issue by QNENet** [vaadin/flow#5219]
The OSGi basic starter copies all of the bower components into the frontend directory. All of approx 27mb.

To use designer in bundles created for additional routes using OSGi DS approach it might be necessary to include the full set of bower components in every additional bundle.

It may be possible to just use the polymer dir from the bower components but i do not know if anything else is required..

Can the frontend bower components be placed in a separate bundle to ease this problem in an OSGi environment?

**Comment by denis-anisimov** [comment]
Let's understand first whether this is an issue or not....
>The OSGi basic starter copies all of the bower components into the frontend directory. 

Yes, it does. This statement is about base starter project. And this is how it's done.
This is not a part of Flow/Platform or something we require to do. This is just an example how you may 
workaround WebJars problem.
You don't have to go with this solution in your project.

So I don't see an issue here.

If it's just a question then please use https://vaadin.com/forum/ for questions.

I can answer here: yes, you may extract all webjars into a separate "resources" bundle.
But then you have to register those resources using `OsgiVaadinContributor` or `OsgiVaadinStaticResource` services to make them available in the web. Otherwise they won't just work since they are in the separate bundle.
And of course the separate bundle should be OSGi compatible bundle.

**Comment by QNENet** [comment]
I believe there are issues with webjars when considering multiple OSGi route bundles and also with using Designer with multiple OSGi route bundles but your reply has been of some value.

Thanks for your reply.

**Comment by denis-anisimov** [comment]
Well, if you have an exact issue then please create a ticket with a proper description and steps to reproduce. I believe we have issues with routes in multiple OSGi bundles.

If the issue is not generic but related to Designer only then please create a ticket for designer.

But anyway please provide exact description and make every ticket per one issue so that they are localized.
