### ISSUE TITLE
Investigate embedded Flow application production mode issues

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5226]
The value we want to deliver is to be able to have embedded Flow applications to work in the production mode.

You should investigate what is the minimum viable technical solution that delivers that value. Some considerations:

Transpilation
- we need to either have the generated web component available for transpilation, or make sure that it is generated into a format that works without transpilation. None of the generated web component features should break in ES5.

Polyfills
- Polyfills will be a part of the bundle file (except webcomponents loader and webcomponent-lite which are added by the Flow application before the bundle), and this is fine, as it is with the basic Flow bootstrap. The generated web component file, like other Flow pages, works just fine even though the polyfills are not inlined in the initial response.

Bundle
- the generated web component runs Flow application which will import the bundle file for the embedded Flow application

**Comment by denis-anisimov** [comment]
Some notes how SSWC works and how production mode works:
- There are two classes which participates in SSWC handling: `WebComponentProvider` and `WebComponentBootstrap`.
- The first class generates the web component HTML Polymer element definition which **_should be imported_** by the application where the SSWC is embedded.
- The second class handles the `web-component-ui.html` import . In fact this class creates a special `WebComponentUI` class for the embedded application. It's triggered by the import inside the generated template (see above) : `<link rel="import" href="web-component-ui.html">`.
- "Production mode" (transpiration to ES5) does several things:
  - scans Java files for annotations like `@HtmlImport` to filter only those imports which are used
  - generates `vaadin-flow-bundle.html` with all the HTML imports/JS files found during scanning
  - Uses the above file as `index.html` and runs transpilation
  - Transpilation generates two folders: `frontend-es5`  and `frontend-es6` . The main file which is generated is file with name like `vaadin-flow-bundle-1e5ff382738fe4d.cache.html`. 
- When Vaadin application is run in the production mode it uses either `es5` or `es6` folder and **_imports_** only the generated/transpiled files(s) instead of a number of `@HtmlImport`s, JS, etc..

To be able to use SSWC component in the production mode we should be able to report somehow to the transpiler that our SSWC polymer files (currently generated by the `WebComponentProvider`) should be transpiled. So we need to include them somehow to `vaadin-flow-bundle.html`.

So there are two first technical subtasks:
- produce a file which should be written to the local FS (instead of generating it on the fly)
- take care about this file somehow so that it's included into `vaadin-flow-bundle.html` and transpiled in the result.

The first task is doable in fact: we don't really need `WebComponentProvider` (we still can keep it in the development mode).

`WebComponentProvider` uses 3 sources to produce the content:
- `VaadinRequest `
- `VaadinSession`
- WebComponent metadata

(also it uses `VaadinResponse` but only to write the generated result).

WebComponent metadata is available from `WebComponentExporter`s. We may get this data without any servlet: just scanning Java source files during the build process. This can be done as a part of maven plugin.

`VaadinRequest` is used to set value for the servlet context path. The latter value is needed to resolve the path `frontend/bower_components/polymer/polymer-element.html` correctly. It should not be really needed when file becomes a part of bundle (after transpilation) since during the transpilation only relative part on the filesystem should be resolvable and there will be no such path already in the generated file.

So the only thing which we don't have available during the project assembly is `VaadinSession`. But the `VaadinSession` instance is used only for one thing: get the root element id: https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/communication/WebComponentProvider.java#L92

This requirement can be workarounded via changing the way of the web component initialization.
See below the sketch how this can be done.

See branch:
https://github.com/vaadin/flow/tree/wip-sswc-production
(diif via PR:)
https://github.com/vaadin/flow/compare/wip-sswc-production?expand=1#diff-9ec8216f98efaaac1e0adab46d9b1f2d

Note that this cannot be used as is since the SSWC which we use in our tests doesn't work as is.
I had to modify it to be sure that this solution works somehow: I've removed the second SSWC element from the `index.html` file. For some reason the generated Polymer template throws an exception and it doesn't work. But I'm pretty sure this is solvable.

The result is : the file is still generated via `WebComponentProvider`  but now it doesn't use VaadinSession` instance at all. So we don't have to generate the file on the fly. We may generate it along the project build.

The next step is to include the generated files into `vaadin-flow-bundle.html`. This is a pure technical task. We may modify maven plugin for this somehow or generate temporary Java file with `@HtmlImport` annotation to reuse already existing plugin functionality. That's just an implementation detail.

As a result in the end we can get the application where SSWC components Polymer files are transpiled and included into `vaadin-flow-bundle-xxxx.cache.html` file(s).

**Now we should be able to bootstrap somehow this application being embedded.**

Currently SSWC are bostrapped in the follwoing way: the application page should include
```
<script type="text/javascript" src="./frontend/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
  <link rel="import" href="web-component/client-select.html">
```

The first script takes care about polyfills (the second item in the ticket).
The second line imports the web-component pseudo Polymer definition HTML file. The file doesn't really exist: it's generated on the fly (currently). So here is some "magic" which you should be aware of.

The generated Polymer template file contains import 
```
<link rel="import" href="web-component-ui.html">
```
And this import initiate the web component bootstrap.

Since we don't generate anymore the Polymer template we can't use `<link rel="import" href="web-component/client-select.html">` anymore.

So the question is: how to bootstrap web components UI for the production mode?

I think we should not use import like this:
`<link rel="import" href="vaadin-flow-bundle-xxxx.cache.html">`

There are several reasons:
- It doesn't initiate the server side logic itself.
- The server side logic reads actually generated `vaadin-flow-bundle-manifest.json` to see which bundles files to load : see  `BundleFilterFactory` class.
- There is (server side) logic which selects which folder to use : `frontend-es5` or `frontend-es6`.
- All those things are already done by the application during bootstrap so there is no sense to duplicate this logic.
- etc.

So instead we should make a fake URI which initiate web component UI bootstrap.
Currently this fake URI is : `web-component-ui.html` (and it's imported from the generated file via `<link rel="import" href="web-component-ui.html">`).

Now instead of WC import via `<link rel="import" href="web-component/client-select.html">` we should import `<link rel="import" href="web-component-ui-production.html">` (or the same `<link rel="import" href="web-component-ui.html">` because server side is able to detect the production mode) and boostrap the application in a regular way except creating a WebComponent UI in the same way as `WebComponentBootstrap` does.

So in the end in production mode: 
- we don't need `WebComponentProvider` 
- reuse `WebComponentBootstrap` (may be with some modifications) or make another one specific for the production mode
- instead of writing in the main application lines
```
<script type="text/javascript" src="./frontend/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
  <link rel="import" href="EMBEDDED_WC_URL/web-component/client-select.html">
```
write 
```
<script type="text/javascript" src="./frontend/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
  <link rel="import" href="EMBEDDED_WC_URL/web-component-ui.html">
```

WebComponent UI should be boostrapped along with the bundle.
And everything should theoretically works.

**Comment by ujoni** [comment]
Currently the `WebComponentProvider` uses `WebComponentConfigurationRegistry` to retrieve the correct `WebComponentConfiguration`. That configuration is given to `WebComponentGenerator` which produces the web component. 

The `WebComponentConfigurationRegistry` is very lazy when it comes to constructing the configuration objects. It is done on the first request for each web component as the current model has to be able to actually construct to the configuration and the exported component using `Instantiator`.

Is there a way to get access to the `Instantiator` during build-time, or do we need to figure out some other way around that?

Or do we say that DI is not viable for embedding web components when using pre-generated resources. We could retain the current mode as a fallback.

**Comment by denis-anisimov** [comment]
The current implementation can be changed.
I don't see a strong need to be able to use DI for `WebComponentExporter`s.
In fact I don't event like the access to the `Instantiator` via `VaadinService.getCurrent().getInstantiator()` (as it's done now). 

It assumes that the method is called from the dispatcher thread when `VaadinService.getCurrent()` is set and this is a very strong assumption.
API would have been designed so that it requires a `VaadinService`  instance explicitly (somehow via a parameter) to be called.

`WebComponentExporter` represents a web component meta data. And I see this is as static data (so there is no need to use DI here).
But it also allows to produce a web component instance. And this instance should be produced via DI.
