### ISSUE TITLE
Refreshing a view with a session scoped component throws error "No child node found with id -1"

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5229]
Adding an autowired, session-scoped component to a view will throw an error on the client when refreshing the page. 

Since the `add` method first removes the component from any old parent, I would expect this to work. I assume the problem is with the component having a reference to a parent that does not exist.

### Code example

    @Route("session")
    public class SessionScopeComponentTest extends VerticalLayout {
    
        public SessionScopeComponentTest(MyComponent myComponent) {
            add(myComponent);
        }
    
        @VaadinSessionScope
        @SpringComponent
        public static class MyComponent extends VerticalLayout {}
    }

### Steps to reproduce

1. Open the page
2. Refresh the page

### Expected results

The component is added both times

### Actual result

An error is thrown on the client: `Assertion error: No child node found with id -1`

### Versions

Platform 13.0.0
Chrome 72.0.3626.121

**Comment by denis-anisimov** [comment]
`@VaadinSessionScope`  means that the bean stays the same within  the session.
You had one `UI` with your `MyComponent` added.
Then you refresh the page.
As a result a new `UI` instance is created.
In this new `UI` instance you add the same `MyComponent` instance.

The result is : exception.

The expected result is wrong.
The actual result is the correct one.

You are using `@VaadinSessionScope` incorrectly: it's always a mistake to declare a Vaadin Component session scoped because you may not use it in that case.
`@VaadinSessionScope`  should be used only with beans that represents some data and never UI elements.

**Comment by Legioth** [comment]
Would it make sense to detect this particular case (or any other known scope that is too wide as well, e.g. singleton) and eagerly produce a helpful error message instead of only failing with a weird message only when the component is being reattached in some other UI?

**Comment by denis-anisimov** [comment]
It definitely makes sense to detect such mistakes and report them properly.
But I'm not sure whether this is possible implementation-wise.

**Comment by Legioth** [comment]
Would it be possible to iterate the metadata for all registered beans at startup and look for incompateible scope definitions for any bean type that extends `Component`?

**Comment by denis-anisimov** [comment]
The answer to that question requires Spring knowledge more than I have.

**Comment by Legioth** [comment]
Looks like I've already been on the same track previously: https://github.com/vaadin/spring/issues/288

**Comment by denis-anisimov** [comment]
Right.
