### ISSUE TITLE
Avoid using anything directly in window.Vaadin.Flow

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5252]
There are currently a couple of hooks published directly on `window.Vaadin.Flow`. These might not work properly with the new embedding feature since there's the possibility that multiple "applications" might be loaded in the same window, thus cause those hooks to always target whichever one was published last.

Based on a randomly opened page, the keys on that object can be grouped into these categories:
* Dangerous stuff that won't work without adjustment: `resolveUri`, `sendEventMessage`
* Stuff that should most likely be disabled when embedding: `pwaIPUI`
* Connector logic that might be shareable assuming there isn't a version mismatch, `datepickerConnector`, `selectConnector`, `comboBoxConnector`, `timepickerConnector`, `contextMenuConnector`, `ironListConnector`, `gridConnector`
* Generic bootstrap logic that is safe for reuse: `clients`, `initApplication`, `getAppIds`, `getApp`, `registerWidgetset`

**Comment by pleku** [comment]
To help get started, as seen in https://github.com/vaadin/flow/blob/master/flow-client/src/main/java/com/vaadin/client/ApplicationConnection.java#L182 the appId is not used for the published functions `resorveUri` and `sendEventMessage`, but should be.

**Comment by pleku** [comment]
>Connector logic that might be shareable assuming there isn't a version mismatch, datepickerConnector, selectConnector, comboBoxConnector, timepickerConnector, contextMenuConnector, ironListConnector, gridConnector

For now we can forget the registering of connectors because different versions of the components don't work on the same page anyway.

**Comment by denis-anisimov** [comment]
`resolveUri` and  `sendEventMessage` are quite specific.
I was not able to find any usage of `resolveUri`  except explicit call in IT test.
But I will fix it anyway.
`sendEventMessage`  is used in `RendererUtil`. This method needs to be exposed to be able to use renderers with event event handlers. So it's quite specific for component rendering.
Will be fixed.

`pwaIPUI` should not be an issue since it's inside template which is read and used only when PWA is enabled.
And I guess PWA should be disabled on the server side (instead of doing this on the client side) in case Embedding is used.
I need to check the rest of the client side code....
