### ISSUE TITLE
update theming documentation for npm

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5307]
The theming documentation refers to HTML imports at least in the following files:
- https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/theme/application-theming-basics.asciidoc
- https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/theme/integrating-component-theme.asciidoc
- https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/theme/theming-crash-course.asciidoc
- https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/theme/theming-overview.asciidoc

**Comment by caalador** [comment]
https://polymer-library.polymer-project.org/3.0/docs/devguide/style-shadow-dom

**Comment by caalador** [comment]
```
import { htmlLiteral } from '@polymer/polymer/lib/utils/html-tag.js';

import myCSS from "style.css";
let myCSSLiteral = htmlLiteral(myCSS);
...
class MyElement extends PolymerElement {
  static get template() {
    return html`<style>${myCSSLiteral}</style>...`;
    ...
  }
  ...
}
```

**Comment by pleku** [comment]
So based on https://github.com/vaadin/flow/issues/5308, we will (first) go with the approach of:
- having a webpack plugin that automatically converts css file contents into P3 based theming (wraps as html, adds JS execution to include as a string in browser)
- the convention for the css file will be to use:
   - using a comment line before the css that specifies how the css will be wrapped into html
   - the syntax for the comment line should be similar to the html generated html, e.g.
```css
/* <dom-module id="my-styles" theme-for="my-themable-component"> */
:host { display: block; }
```
will be changed into following html (that is included with js)
```html
<dom-module id="my-styles" theme-for="my-themable-component">
    <template>
        <style>
            :host {
                display: block;
            }
        </style>
    </template>
</dom-module>
```
- the css file should be importable from Java components with an annotation
- the css file should be importable from any js module, the plugin modifies the import, e.g. `my-component.js`:
```javascript
import "./my-component.css";
...
class MyComponent extends ThemableMixin {
}
```

The plan is to now rewrite all the theming documentation (mentioned on first comment in issue) based on this approach, and then evaluate the feasibility and DX of the approach.

**Comment by Legioth** [comment]
Overloading `import "./my-component.css"` to have a custom meaning in Vaadin projects seems like a really bad idea since we have [CSS modules](https://github.com/w3c/webcomponents/issues/759) around the corner. We would basically end up being incompatible with the web platform.

I would instead suggest that we'd look into something that aligns with the core idea of that spec, i.e. importing the styles to a variable (`import styles from './my-component.css';`) and then somehow programmatically "publishing" those styles to some context, e.g. `VaadinThemeModuleHelper.themeFor("my-themable-component", styles)` (names pending). There would be separate helper methods for emulating `<dom-module theme-for=...>`, `<custom-style>` and whatever other use case we want to support.

We could for now make that work with the output of https://webpack.js.org/loaders/css-loader/ (maybe also combined with e.g. `to-string-loader`). Later on when CSS Modules would be standardized, we could simply update the implementation in `VaadinThemeModuleHelper` to automatically detect which format is used and treat the value accordingly.

For the Java API, we could introduce custom annotation API for defining `<dom-module>` and `<custom-style>` dependencies that would automatically cause the appropriate JS to be generated into `main.js` (or `some-chunk.js` if/when we implement support for splitting). This could be something like `@CssImport("./styles.css")` for a `<custom-style>` import and `@CssImport(value = "./my-component.css", forComponent = MyComponnent.class)` or `@CssImport(value = "./my-component.css", forTag = "my-component")` for `<dom-module>` imports. That same annotation could potentially also have a `theme` attribute that would make the annotation ignored unless the application is configured to use a specific theme.

**Comment by manolo** [comment]
**Updating the initial design in #5308 with @leif suggestions**

Since in P3 all styles need to be loaded using ES6 imports, it means that we need `.js` files with the following structure

my-styles.js
```javascript
const template = document.createElement('template');
template.innerHTML = `<style>:host {display: block}</style>`;
document.head.appendChild(template);
```
But this gives a bad DX since writing styles into a backticks block is a hassle.

In vaadin v13 the developer is used to write styles in `.html` files, but because we don't need to define webcomponents in `.html` and we don't have html imports anymore, the ideal solution would be that the user writes their styles in plain `.css` files and they inform flow to import styles via annotation.

my-styles.css
```css
:host {
    display: block;
}
```

MyComponent.java
```java
@CssImport("frontend://my-styles.css")
MyComponent extends Component {
}
```

The annotation would instruct flow to extract the file from the `.jar` container and copy it to the `node_modules/@vaadin/flow-frontend` folder as we already do with addons JavaScript connectors to make it accessible to webpack, as well as it would introduce a couple of line in the generated application entry point so as webpack can eventually add it to the shipped bundle.

main.js
```javascript
import styles from '@vaadin/flow-frontend/my-styles.css';
const template = document.createElement('template');
template.innerHTML = `<custom-style><style>${styles}</style></custom-style>`;
document.head.appendChild(template);
```

In order to make this work, we need some magic able to read the `.css` content and return it as a string, until importing css is supported in webpack.
This can be done by using the [css-loader webpack plugin](https://webpack.js.org/loaders/css-loader/)


Therefore, this should be needed to add to the project configuration

package.json
```json
{
  "devDependencies": {
    "css-loader": "latest",
  }
}
```
webpack.config.js
```javascript
module: {
  rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      }
  ]
}
```

Because we need additional information for wrapping `.css` we need some annotation properties in java annotation


MyComponent.java
```java
@CssImport(value = ".my-styles.css", id = "shared-styles")
MyComponent extends Component {
}
```

main.js
```javascript
import styles from './my-styles.css';
const template = document.createElement('template');
template.innerHTML = `<dom-module id="shared-styles"><template><style>${styles}</style></template></dom-module>`;
document.head.appendChild(template);
```

MyComponent.java
```java
@CssImport(value = ".my-styles.css", themeFor="vaadin-button")
MyComponent extends Component {
}
```

main.js
```javascript
import styles from './my-styles.css';
const template = document.createElement('template');
template.innerHTML = `<dom-module id="a-random-id" theme-for="vaadin-button"><template><style>${styles}</style></template></dom-module>`;
document.head.appendChild(template);
```

**Comment by jouni** [comment]
> The plan is to now rewrite all the theming documentation (mentioned on first comment in issue) based on this approach with having the webpack plugin, and then evaluate the feasibility and DX of the approach.

It would probably be better to evaluate the DX with users before writing the Webpack plugin, to avoid unnecessary work.

**Comment by pleku** [comment]
Issue for DX testing the approach: https://github.com/vaadin/flow/issues/5501

**Comment by Legioth** [comment]
The client-side aspects are also described in https://github.com/vaadin/vaadin-themable-mixin/issues/49.

**Comment by pleku** [comment]
Superceded by
- https://github.com/vaadin/flow/issues/5538 for `@CssImport`
- https://github.com/vaadin/flow-and-components-documentation/issues/602 for updating existing documentation
