### ISSUE TITLE
SPIKE: investigate what is the best way to apply npm/jsmodule/polymer 3 based theming

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5308]
As it stated in https://polymer-library.polymer-project.org/3.0/docs/devguide/style-shadow-dom#style-modules the theming is applied a bit differently in P3.

Adding that boilerplate to all of the theming files in an application seems quite awful experience, so we should investigate if we can help the Java developers some how.

The main use cases for theming that should be easy to do are
1) tweak the look and feel of the components (application) with some custom css properties for e.g. lumo theme
2) add a new style module or customize an existing style module for theming a view/application

**Comment by pleku** [comment]
For instance we could add some magic that allows users to write CSS which goes inside the `<style>` tags and/or the custom HTML tags and we automatically wrap that with the JS code to make it work as a JSModule.

**Comment by manolo** [comment]
Follow discussion in components channel https://vaadin.slack.com/archives/C3TGRP4HY/p1554109720029900

**Comment by manolo** [comment]
Since in P3 all styles need to be loaded using ES6 imports, it means that we need `.js` files with the following structure

my-styles.js
```javascript
const template = document.createElement('template');
template.innerHTML = `<style>:host {display: block}</style>`;
document.head.appendChild(template);
```
But this gives a bad DX since writing styles into a backticks block is a hassle.

In vaadin v13 the developer is used to write styles in `.html` files, but because we don't need to define webcomponents in `.html` and we don't have html imports anymore, the ideal solution would be that the user writes their styles in plain `.css` files and they inform flow to import styles via annotation.

my-styles.css
```css
:host {
    display: block;
}
```

MyComponent.java
```java
@CssImport("frontend://my-styles.css")
MyComponent extends Component {
}
```

The annotation would instruct flow to copy the file to the `node_modules/@vaadin/flow-frontend` folder as we already do with addons JavaScript connectors, as well as it would introduce a line in the generated application entry point so as webpack can eventually add it to the shipped bundle.

main.js
```javascript
import '@vaadin/flow-frontend/my-styles.css';
```

In order to make this work, we need some magic able to wrap the `.css` content into a `.js` file that can be imported by using JavaScript. This can be performed in two ways:

- Make flow parse and modify the file before it's copied to the `node_modules/@vaadin/flow-frontend` 
   - this would be simpler for the project configuration point of view 
   - would be more transparent for the user
   - But it needs also to consider transformations to files located in the `/frontend` folder
   
- Configure webpack to do the work.
   - It needs a webpack plugin to be published in `npm`.
   - The plugin might be re-usable in 'vaadin-connect' projects or even in polymer-3 elements.
   - This seems much more versatile and easier to maintain.

Therefore, considering the solution with the webpack plugin it would need the following configuration in the project:

package.json
```json
{
  "devDependencies": {
    "vaadin-css-plugin": "latest",
  }
}
```
webpack.config.js
```javascript
module: {
  rules: [
    {
      test: /\.css$/,
      loader: 'vaadin-css-loader'
    }
  ]
}
```

Because we need additional information for wrapping `.css` we need a way for  for annotating`.css` with html specific CSS syntax, for instance (probably not the best syntax, we need to discuss it):

my-styles.css
```css
/* @dom-module(id = 'my-styles', theme-for = 'my-themable-component', )  */
:host {
    display: block;
}
/* @custom-style(include = 'my-styles')  */
:host {
    background: grey;
}
```

which would produce something like:

my-styles.js
```javascript
const template = document.createElement('template');
template.innerHTML = `
<dom-module id="my-styles" theme-for="my-themable-component">
    <template>
        <style>
            :host {
                display: block;
            }
        </style>
    </template>
</dom-module>
<custom-style>
    <style include="my-styles">
        :host {
            background: grey;
        }
    </style>
</custom-style>`
document.head.appendChild($template);
```

**Comment by web-padawan** [comment]
Overall approach and `vaadin-css-loader` LGTM. We could consider some options for organising CSS:

1. annotating `.css` files as suggested above
2. using folder structure + file names, e.g.

```
styles/
|
|-- custom-styles/        # Stylesheets to wrap in <custom-style>
|   |-- my-app-theme.css
|
|-- components/ 
|   |--vaadin-button/     # Stylesheets to wrap in <dom-module theme-for="vaadin-button">
|       |-- my-button.css  
|   
`-- shared/               # Stylesheets to wrap in <dom-module id="..."> for "include"
        |-- colors.css
```

In the latter case, we probably could also use CSS `@import` statement in stylesheets instead of `include` annotation. We will have to parse and process content of CSS files, which shouldn't be complex e.g. with PostCSS parser, as otherwise we will need to parse to get annotations anyways.

**Comment by pleku** [comment]
>using folder structure + file names, e.g.
This folder structure doesn't take into account the possibility of having multiple themes, and having styling for a component for different themes, like Lumo and Material. Currently we have a convention for this with replacing the raw component file `component-name/src/component-name.js` with `component-name/theme/theme-name/component-name.js`
