### ISSUE TITLE
Dependencies should be more locked in to avoid breakages

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#5320]
Dev dependencies should be locked in and only allow the exact version listed.

Also for the generated package.json the dependencies should be locked in as
we can not guarantee that all future versions will work as expected.

The user should be able to trust that if he runs the project in the morning and
again from a clean slate i the evening that the project handles the same. 
(Even more so for a production build where todays build should result in the same package as last months without any changes done)

**Comment by pleku** [comment]
We need to guarantee that the versions that we provide are always working. The generation of the package.json should be something that is touted as _takes the latest versions and is quite risky since nobody will know what you get_ and thus it should be never pushed to users (specially when trying out the products) to use that feature. Or then the generated file should use locked versions of tested dependencies instead of the latest ones.

**Comment by pleku** [comment]
For now lets commit the package.json and package-lock.json for Beverage Buddy and Component add-on starter.

**Comment by pleku** [comment]
Will be made happen by https://github.com/vaadin/flow/issues/5465
