### ISSUE TITLE
debug helping text for optional URL parameter misleading

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow#5328]
Can be seen e.g. in the lottery examples (training).

When there is an @OptionalParameter then the debug messages when you point the URL to a non-existing route is "foobar (requires parameter)".
It would be nice if the message could be corrected.

Leif Åstrand   [1 month ago]
Should indeed say "supports optional parameter" and be a link. Please create a ticket unless one already exists.

**Comment by Legioth** [comment]
The relevant code is in https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/router/RouteNotFoundError.java

**Comment by dfcortes** [comment]
Hey @Legioth, I would like help to fix this.

**Comment by Legioth** [comment]
@dfcortes For the general procedure, please have a look at https://github.com/vaadin/flow/blob/master/CONTRIBUTING.md for an overview of the overall practices and some guidance for setting up your IDE in https://github.com/vaadin/flow/blob/master/README.md#setting-up-eclipse-to-develop-flow.

When it comes to the actual feature, I would assume that the conditional logic in `RouteNotFoundError` would get an additional clause for the case when there is a route parameter but that parameter is marked as optional.

Please let me know if there's some specific aspect that would need further clarifications.

**Comment by dfcortes** [comment]
@Legioth My apologies for the delay to solve this issue. Currently I'm working on it.

I'm adding this validation for the case when there is a route with an optional parameter in the `RouteNotFoundError` class: `parameter.isAnnotationPresent(OptionalParameter.class)`

But, I'm blocked because of the validation is returning false in all cases. Looks like the annotation info is gone in the reflection process, here: https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L578. 

`GenericTypeReflector` is internally using `GenericTypeReflector` which get the type parameter:

![GenericTypeReflector](https://user-images.githubusercontent.com/6531181/59450585-2204d700-8dcf-11e9-96a8-746799828f69.png)

I'm using this when debugging the code:

![exampleCode](https://user-images.githubusercontent.com/6531181/59451338-dd7a3b00-8dd0-11e9-8c26-17a1c58c6e0c.png)

I would appreciate any suggestion.

**Comment by Legioth** [comment]
The `@OptionalParameter` annotations has `@Retention(RetentionPolicy.RUNTIME)`, so it should be available at runtime. Your debugger screenshot seems to be related to looking for annotations on a type, not on a method parameter?

Seems like `RouteData` doesn't directly contain any information about whether the parameter is optional or not. On the other hand, it seems like the existing helper method `ParameterDeserializer.isAnnotatedParameter` will do exactly what you need.

**Comment by dfcortes** [comment]
You're right, I was verifying the annotation in a type, I was a bit confused about it.

Thanks for the feedback, the `ParameterDeserializer.isAnnotatedParameter` helps to complete the code changes.

**Comment by dfcortes** [comment]
I just created this PR with the changes: https://github.com/vaadin/flow/pull/5914
