### ISSUE TITLE
Spike: scanning the classpath for used frontend resources and only adding those to main.js

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5338]

**Comment by manolo** [comment]
Did already a research as part of https://github.com/vaadin/flow/issues/5339, once evaluated  different libraries for visiting bytecode,  the faster and api easier is org.objectweb.asm. We don't need to add an extra dependency because we have net.bytebuddy.dynamic already in classpath that has a copy of needed visitors for bytecode.

https://gist.github.com/manolo/87a0955cc6dfe20a0149fe1bb5bedc73
