### ISSUE TITLE
I want to be able to fluently fire events when embedding Vaadin components

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5383]
The current `fireEvent` API exposed by `WebComponent` has three overloads and takes cumbersome parameters, such as `EventOptions` and `JsonValue`. For example:

```java
@Override
public void configure(WebComponent<MyComponent> webcomponent, MyComponent component) {
    component.addSomeEventListener(event -> {
        JsonObject json = new JsonObject();
        json.put("name", "John Doe");
        json.put("age", 27);
        EventOptions options = new EventOptions(true); // bubbles
        webcomponent.fireEvent("event-name", json, options);
    });
}
```
(please excuse the potential minuscule mistakes in the above code :)

Instead, I'd like to configure `fireEvent` fluently and with better visibility to the various options involved. Such as:

```java
@Override
public void configure(WebComponent<MyComponent> webcomponent, MyComponent component) {
    component.addSomeEventListener(event -> {
        webcomponent.fireEvent("event-name")
            .data("name", "John Doe")
            .data("age", 27)
            .bubbles()
    });
}
```

**Comment by Legioth** [comment]
Two observations related to the suggested API:

1. Should probably stick to established vocabulary related to custom events and use `detail` instead of `data`.
2. This kind of operation almost needs a terminating action, but that would on the other hand make the API much more complicated. We can technically implement this with the same kind of beforeClientResponse collection semantics that is also use e.g. or the fluent keyboard shortcuts. At the same time, this is a slightly different scenario since you cannot do anything at all after the action has been sent to the client, whereas e.g. a keyboard shortcut registration can still technically be reconfigured in a later round trip. At the very least, this should thus be implemented so that calling any of those methods after the command has been sent should throw a clear exception.

**Comment by ujoni** [comment]
>     1. Should probably stick to established vocabulary related to custom events and use `detail` instead of `data`.

Ah, yes. That makes sense. Should we go with the `withDetail(...)` which implies the ability to add multiple "details"

>     2. This kind of operation almost needs a terminating action, but that would on the other hand make the API much more complicated -- (omitted the rest)

If we want a termination, it sounds like a builder approach where we'd have something like:
```java
webComponent.buildEvent("my-custom-event").withDetail("event-id", someIdVar).bubbles().fire();
```
But since the nature of events is to perish after firing, I'd somewhat like to stay away from ⬆️ that. But then again, maybe it would make sense to have the builder and allow reconfiguration:

```java
EventBuilder builder = webComponent.buildEvent("my-custom-event").withDetail("event-version", 3)
    .bubbles();

int eventId = 0;
component.addEventListener(() -> {
    builder.withDetail("event-id", eventId).fire();
    eventId++;
});
```
or some such hypothetical.

The current `EventOptions` we have are:
- bubbles
- cancellable (does not make super much sense with custom events)
- composed

Are those the names we want to use or do we have more Java-y names available?

**Comment by Legioth** [comment]
The "problem" with not having a terminator is that it might make it slightly more difficult to understand the code for someone who isn't familiar with the implementation details:
```
webComponent.fireEvent("my-custom-event") // Great, the event is fired
  .withDetail("event-id", someIdVar); // Wait, it wasn't fired after all? Or was it "unfired" and then a new one fired? When will it actually fire?
```
Taken to the extreme, one might get the impression this would work:
```
// Prepare firing an event???
MaybeFiredMaybeNot event = webComponent.fireEvent("my-custom-event");
// Actually fire it???
fireButton.addClickListener(click -> event.withDetail("event-id", someIdVar));
```

At the same time, I'm not sure that the risk of that kind of confusion is a bigger or smaller problem than the additional API required for a builder approach.

With regards to the names of the event options, my gut feeling is that a developer would still have to be familiar with the JavaScript semantics to be able to choose which options to use. This would imply that it's best to stick to the JavaScript names instead of trying to invent anything for the sake of Java.

**Comment by ujoni** [comment]
I assume that the most confusion happens right in the `fireEvent("my-event")` call especially if the user would like to add data to the message but does not necessarily need it. It is not super natural to expect a such a direct command to be fluently configurable.

After this talk, I am personally in favor of the builder approach, as the additional API of one `fire()` call doesn't really bother me much. It is 7 extra characters, and a clearer functionality (hopefully).

**Comment by Legioth** [comment]
My main concern with the builder isn't the number of extra characters, but rather that it's yet another thing that you might accidentally forget to do and then you would have a hard time understanding why the event isn't actually fired. In either case, we're talking about quite subtle differences. Either approach would still be good enough based on my current understanding.

One thing that is missing from the current API suggestion is the distinction between `detail: {"foo": "bar"}` and `detail: "bar"`, i.e. how to define just a single primitive value as `detail` instead of building a complex object with multiple properties.

If introducing the builder, then I'm still considering whether we should also offer a shorthand method for firing a named event without any specific configuration and maybe also one for firing with default options and a simple `detail` value.

**Comment by pleku** [comment]
Why would I need to use additional `.fire()` when I've already added the chaining with `fireEvent("my-event-name")` ? I don't see why there would have to be a terminating operation for this, if someone would access the returned object later on when the fire-event command has been sent to client, I would expect exceptions be thrown.

**Comment by Legioth** [comment]
If using a builder API approach, then you would start the chain with something like `buildEvent("my-event-name")` and not with `fire("my-event-name")`.

The primary purpose of the terminating operation would be to make application code code easier to understand without requiring the reader to understand that `fire("my-event-name")` does actually not fire the event immediately, but only at some not-completely-obvious point in the future.
