### ISSUE TITLE
Unreachable methods in Shortcuts API and general questions about how the API is supposed to be used

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/flow#5407]
Hi,

As we're attempting to consume the shortcut api we have discovered a couple of peculiarities.

Shortcuts.addShortcutListener has an overloaded method that is not marked as static, since the constructor of the Shortcuts object is private that method is uncallable.

Raw shortcut registrations can not be constructed since the ShortcutRegistration constructor is package-private.

ShortcutRegistration objects has a flag "allowEventPropagation" (default false) that is supposed to stop browser events from propagating. It is unclear what it supposed to do since the components supplied are:

1. The lifecycle owner of the shortcut which doesn't necessarily share the hierarchy of whatever dom node generated the event.
2. The root ui component from which the events are sourced.

Since this doesn't describe the dom hierarchy of whatever is generating the keyboard events, where should this hypothetical event propagation stop? At the root node?

Secondly, and what I feel is a bit of a larger issue is how is this api supposed to be used? Since the shortcut keys are sourced from the root object and are global we feel confused about how we are supposed scope keyboard shortcuts.

I.e. if we want to bind a shortcut in some component in the application to the letter 'a' then that letter can no long be used in any input field, modal or search box since that will trigger the shortcut. 

One of the ideas we had was to build a side framework which injects 0-size component into the root component for which we toggle visibility to simply be able to handle the current keyboard shortcut state. But we felt it was better to get a guiding statement about how it is supposed to work rather than hack something together on top of it first.

**Comment by ujoni** [comment]
Hello @brp-benjamin!

Thank you for the query. I am sad to say that the missing `static` modifier on the `Shortcuts.addShortcutListener` is a clear bug. Thank you for bringing it to our attention.

Now, for your questions:

First, `ShortcutRegistrations` are not meant to be constructed manually they are a result of calling one of the methods which add a shortcut and the registration provides further configuration options.

The default behavior with `preventPropagation` is that once the keyboard event matching a shortcut has been caught by a shortcut listener on the DOM, the event is either stopped there, or `allowEventPropagation` has been called for the shortcut. The event originates an active element, which usually is the element that has focus. If no such element exists, the event origin is `<body>`.

As to the scope of the shortcut, one can use `ShortcutRegistration::listenOn(Component)` method to define where on the DOM tree the shortcut listener should be registered. In practice this means that the shortcut keyboard event matching the shortcut will only be caught from the elements under the given `Component`.

The subject of blocking typing is handled by calling `allowBrowserDefault()`. Since writing in a text field is just the default handling for keyboard events when the text field is focused, allowing browser's default behavior results into the characters being typed out (_and_ the shortcut activating). But, if possible, I would suggest using modifier keys in conjunction with the "activating" key, such as CTRL+Y, to avoid similar situations when dealing with global shortcuts.

If you haven't done so already, please have a look at out [Shortcut tutorial](https://vaadin.com/docs/v13/flow/components/tutorial-flow-shortcut.html) and if you have further questions, don't hesitate to ask!

**Comment by brp-benjamin** [comment]
Thank you for the feedback it was really helpful in helping us use the API. One thing we encountered that is not really covered by the tutorial and your feedback was the need to "layer" shortcut keys in order to be able to open modal dialogs on top of the current layer. I have created a separate ticker for that feature request #5422

**Comment by pleku** [comment]
As this issue is more questions & feedback (thanks for that) and separate issues have been created about the bugs & improving the feature, I'm closing this issue. Please create new specific tickets about things that need fixing, thanks.
