### ISSUE TITLE
Move frontend/main.js generation into target directory

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5423]
Currently flow-maven-plugin generates `frontend/main.js` file in the project whenever it's run.
It might be confusing since in some cases like java-only project (for instance, https://github.com/vaadin/skeleton-starter-flow), there might be no `frontend` directory at all.

When we get the fragments out, it will get worse and there will be more files around `main.js` polluting the sources.

Need to keep in mind that currently the dependency verification logic is using the fact that `main.js` file is in the project's structure: https://github.com/vaadin/flow/blob/2.0/flow-server/src/main/java/com/vaadin/flow/server/frontend/NodeUpdateImports.java#L198
This needs to be adjusted when the file is moved.

**Comment by pleku** [comment]
Isn't `main.js` possibly also maintained by users ? If they know what they are doing and opt for manually defining chucks or optional imports ? Then using `target` is impossible as it is always cleared.

Isn't the current location also _future proof_ in terms of hybrid projects ? @Legioth 

Shouldn't we instead add documentation, like in readme or such, to describe what `main.js` does and what other files there might be around it, and explain what those are and what role do those have ?

Are not needed in version control or should those be added to `.gitignore` ?

**Comment by SomeoneToIgnore** [comment]
Either I did not understand something or phrases

> Isn't main.js possibly also maintained by users ?

> Are not needed in version control or should those be added to .gitignore ?

kind of contradict each other.

Good questions anyway, we need to understand what do we allow to do with the file and act accordingly afterwards.

**Comment by manolo** [comment]
User can still maintain their main file, the best option is to modify their  `webpack.config.js` and replace `frontend/main.js` with `frontend/app.js` then they might either `import ../target/..../main.js`  or have everything configured there, and disable the `update-imports` goal

**Comment by manolo** [comment]
As additional note, when we have chunks we will ve polluting the sources even more, because we need an extra `.js` file per chunk

**Comment by Legioth** [comment]
It gets quite complicated for the user if the same file path can in some cases be modified by the user and in other cases it's automatically generated.
* The user cannot be sure that their own modifications won't at some point be overwritten by the generator.
* It is not very practical to combine the convenient generated content with your own customizations. This is a problem mainly if the generated content changes frequently (i.e. the case of `main.js` whenever you add a new template or component to the application) or if there are occasional big changes (e.g. default Flow setup changes to need different webpack plugins when updating to a new version).
* `.gitignore` becomes messy.

Instead, I think we should aim towards separating user-maintained and generated files from each other. The generated file should preferably be in a location that is by default already covered by `.gitignore` (e.g. `/target`) whereas the file maintained by the user would be e.g. in the project root or `/frontend`.

The remaining question then is mainly how to make a connection between the user's file and the generated file. I think there are three basic approaches there with different trade offs. I'm not yet certain whether there's one "universal" approach that we would use in all cases or if it would make more sense to define guidelines for which approach to use in which cases.
* Allow configuring the generator through a separate configuration file. With this approach, configuration would only be possible for things that our generator explicitly supports.
* Make the generated file references the user's own file if such a file exists when the generator is run. This means that the generated file is the primary file and in overall control. The degree of control offered to the user's file depends on how that file format's native inclusion mechanism works.
  * As a special case, instead of using the file format's own inclusion or referencing mechanism, it might also be feasible to directly include the contents of the user's file inside the generated file.
* Have the user's own file as the primary file, and make it have a reference to the generated file. With this approach, the user is free to completely remove the reference if they don't want to benefit from generation at all. In most cases, the most user-friendly approach here is that there is by default a really simple user-maintained file that only contains a reference to the generated file and nothing else. This file would reside in version control and thus on one hand increase discoverability and transparency, but on the other hand increase the apparent complexity of a "simplest possible" project setup.

**Comment by pleku** [comment]
>We might not need any configurability at all for now.

Agreed.

> My expectation is that we will eventually need a way of including individual embeddable Flow views and their client-side dependencies as a small part of a larger application that otherwise uses its own client-side logic and setup. For that to work, we cannot assume that Flow owns files like package.json, main.js or webpack.config.js

Predicting the future is quite difficult and while we should mind what might happen, we need to make decisions based on what will work today and tomorrow.


Is `main.js` the only file we should move? What is the list of files to move?

How do we still keep it possible for the user to define the their own chunks? Since I'm quite sure that is a must have, once you optimize your application into production you cannot lose the file. So what is the work flow for users who want to customize and control the main.js and Webpack config?

**Comment by pleku** [comment]
The `stats.json` file is something that should be either moved or just cleaned up https://github.com/vaadin/beverage-starter-flow/issues/334, or is there some reason why it should be kept in version control ?

**Comment by pleku** [comment]
Update from daily: we just move `main.js` but keep everything else where it is, because the user might want to control those. We only create package.json and webpack-config.js once and then the users are free to modify and control those if necessary.

**Comment by Legioth** [comment]
To my knowledge, we are currently generating four files: `package.json`, `webpack.config.js`, `main.js` and `stats.json`. Each file has slightly different characteristics, so lets go through each of them.

### stats.json
This is the easy one. It's a huge file (~20mb for Beverage Buddy today) that should definitely not be in version control. It's recreated based on various factors whenever anything changes. The user should never have any need to directly use or modify this file.

### webpack.config.js
The contents of this file is fully hardcoded, so "copied" would be a better description than "generated". The challenge here is that there might be situations when application want to make tweaks to the configuration. Right now we're only offering an all-or-nothing approach - if the file already exists, then we never modify it again. This becomes problematic the day something changes in Flow that would require an update to the configuration, since any existing projects would keep using their old copy of the file.

My suggestion is that we would instead produce a file that could either be dumped somewhere in the local file system or statically imported from e.g. a npm module that we would set as a dev dependency in `package.json`. My gut feeling right now is that it would be better to store the file locally since that keeps the door open for later on making parts of the file generated based on some configuration instead of being completely static.

The default project setup would contain a really simple `webpack.config.js` file that only includes our default configuration and uses it as-is. Developers could then have the choice to either supplement the default configuration (e.g. add an additional `entry` item or add `sass-loader` for use with their own frontend resources), or remove the code that imports the default and instead take full responsibility for maintaining their own configuration.

### package.json
Generated based on annotations in Java classes. and a couple of hardcoded dev dependencies for webpack. As long as the application doesn't contain anything except Flow, this would be good enough. The moment we want to allow developers to create a hybrid application, they would need to add their own dependencies and probably also define their own `scripts` section.

The easiest way we can enable that would be that we actually generate a separate `package.json` file based on the Java classes, and then the `package.json` file in the application root would have the generated file as one of its dependencies (or one separate for dev dependencies). To ensure updates to the generated `package.json` is actually picked up, we would have to update its version number every time it's updated (e.g. as a hash of its contents), and then also update the one entry in the root `package.json` file to reference that version. Aside from that, we would not touch the root `package.json` file at all.

### main.js
Generated based on annotations in Java classes. I see two use cases for why an application developer might want to impact the contents of this file: adding their own global frontend logic, or configuring how the dependencies are split out to chunks.

Adding their own global logic can just as well be done by adding a separate entry script in their custom `webpack.config.js`. In that case, the `main.js` file is however quite confusing. We could consider renaming it to e.g. `flow-dependencies.js` instead to make its position clearer.

When it comes to splitting things into chunks, it's not really helpful for the developer to manually change this file since they would have to remember to update it every time they make any changes that affect the dependencies. Instead, any meaningful support would instead be based on the idea of controlling how the file contents are generated based on annotations in Java classes.

### Summary
I would propose that for now, we move and rename `main.js` and split up `webpack.config.js` into one user-modifiable simple file and a separate file that the user should never modify.

For later, we should also consider splitting up `package.json` and give more control over chunk divisions in `main.js`.

**Comment by Legioth** [comment]
> We only create package.json and webpack-config.js once and then the users are free to modify and control those if necessary.

This is the problem. Those files won't stay up-to-date with this all-or-nothing approach.

For `package.json`, the main challenge is how to combine the user's own customisations with the content generated based on what's on the Java classpath. If I manually add something to `package.json`, then it stays there. If I add a new dependency to `pom.xml`, then it appears in `package.json`. If I update the version number in `pom.xml`, then the corresponding version number in `package.json` is not updated. If I remove the dependency from `pom.xml`, then it remains in `package.json`. These problems would be solved if there would be a separate generated `package.json` that is always rebuilt from scratch and then the main `package.json` file would have a reference to the generated one.

For `webpack.config.js`, the main challenge is when anything changes in the file that Flow would have generated. Examples of this kind of change could be that we add something for loading css files or change the default babel settings to work better with new browsers. The problem is that those changes will not take effect for old projects. Depending on the case, this would either mean that things break down (because something in Flow requires the updated configuration to work properly), or then old users are just not automatically getting access to the latest fixes or improvements.

**Comment by pleku** [comment]
>This is the problem. Those files won't stay up-to-date with this all-or-nothing approach.

Do you have some data that shows how it is a problem ? A bigger problem than introducing a lot more complex setup for all users is ?

The all or nothing approach is pretty simple in the manner that if you take the road of updating things yourself, then you need to also necessarily do changes after updating the platform version, if there are additions that require changes. I'm betting that it won't be a problem for most users since they don't update things themselves.

The package.json updating questions probably warrant a separate issue, if we have some issues with this. I'm fine waiting for DX testing feedback and then doing changes, rather than guessing things upfront. Or is there something we have not covered yet:
1) When should the user add things themselves to `package.json` but not to Java ?
- currently there is no mention anywhere in the documentation that you should add anything to package.json, except in the beverage buddy readme it is explained what it is
- this would actually imply that it should be in `/target/` because it is not even part of the version control
2) Adding a new dependency to `pom.xml` adds something to `package.json` ?
- I think soon this would only be applied if something is using the added thing either in Java or project templates
3)  If I update the version number in `pom.xml`, then the corresponding version number in `package.json` is not updated
- I would consider this a bug. If you update an add-on version, the package version declared with the annotation in Java code should change, and changes should end up to `package.json`

I agree the current situation for `package.json` can be seen confusing, *if you would need to update it yourselve, but why do you need to do that?*

I would keep it simple for now and focus on other areas for adding more user value than this. Please create separate issue for `package.json` file location. Same for `webpack-config.js`. Those can be considered on against other options for improvement.

**Comment by manolo** [comment]
> This is the problem. Those files won't stay up-to-date with this all-or-nothing approach.

- `package.json` is not a problem, when we create it we don't set any version, it's not needed since it does not produce any npm package that needs to be deployed to npm repos. We use `npm` cli to update it, so we don't truncate anything that the user has set manually, we neither set the version here, we just check that a specific depencency is there for instance there is a `@vaadin/vaadin-grid` there
- `webpack.config.json` is much problematic, we need to define the output folder that sometimes is variable depending on the version e.g `target/myapp-1.0-SNAPSHOT/` if it's a `.war` or `target/classes/META-INF/resources` when a `.jar`. One good solution is that we have a meaningful variable in the file that it's updated each time the plugin goal is executed `mavenBuildOutputFinalName = 'target/....'` which is a value that we know during maven build. If the user does not want this variable to be updated they can change the name. In addition we could maintain a version in variable or in a comment so as we could warn the user when their webpack config is not aligned with flow default

**Comment by Legioth** [comment]
> Do you have some data that shows how it is a problem ? A bigger problem than introducing a lot more complex setup for all users is ?

My suggestion would reduce complexity for all users. 

> I'm betting that it won't be a problem for most users since they don't update things themselves.

Their main problem is that the file in their project will not automatically be updated when they update to new version of Flow.

Let's continue the discussion about `webpack.config.js` in https://github.com/vaadin/flow/issues/5464 where I've summarized all the problems with the current implementation and also offered some suggestions on what to do instead.

**Comment by Legioth** [comment]
`package.json` currently has problems because it's not kept fully in sync with `pom.xml`. Any trivial fix to those issues would instead cause problems for anyone who wants to also manager their own dependencies. We should choose whether we want to support that use case, and then adjust the implementation in one direction or another.

Let's continue that discussion in https://github.com/vaadin/flow/issues/5465.
