### ISSUE TITLE
Validate that all node tools and requirements are met when running the project

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5432]
Add a goal to our plugin that is run in `validate` phase and fail with the appropriate message and indications.

This code can be re-used also when  dev-mode-handler is run.

Acceptance Criteria:
- [x] Fail if node is not found
- [x] Fail if npm is not found
- [x] Do not fail when not detected things that can be installed by plugin or dev-mode 
- [x] Fail if something is wrong in their versions of installed things
- [x] The error message should be clear about what is needed to pass the check
- [x] The error message should have links to documentation for how to use the frontend-maven plugin or for instance a link to install instructions for npm (for all platforms)
- [ ] Add short instructions to flow documentation on how to use frontend-maven-plugin to install node (and npm)
- [x] The way to find `node` and `npm` should be aligned with the code runing them in plugin or dev-mode

**Comment by SomeoneToIgnore** [comment]
Related to the 

> Add short instructions to flow documentation on how to use frontend-maven-plugin to install node (and npm)

point:

I don't think it should be done, because:
* we detect `node` and `npm` installed globally, we cannot detect the local ones since we're running a detection code from `flow-server` that may not have any access to the FS
* https://github.com/eirslett/frontend-maven-plugin says that it installs the tools locally only
