### ISSUE TITLE
Embedding Flow fails to find resource in production mode 

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#5474]
Error given by browser console:
`GET http://localhost:8080/frontend-es6/vaadin-web-components/person-display.html 404 (Not Found)`

For a servlet def:
```java
@WebServlet(urlPatterns = { "/vaadin/*"  })
public class WebComponentVaadinServlet extends VaadinServlet {
}
```

**Comment by ujoni** [comment]
Code:
https://github.com/ujoni/skeleton-starter-flow/tree/embedding_production

**Comment by denis-anisimov** [comment]
I cannot reproduce it.
No any error in the console.
Not sure what should I see in the browser but in my case there is a line:

`This is John Doe and they are 15 years old. is a child`

I'm using Chrome. May be it's different in IE11 or other browser which you use.
Please try at least Chrome.

One thing which may be relevant : the starter project uses platform.
The Flow version in platform should be suitable for the project.
But it might be that the maven plugin version is not suitable.
The plugin is declared as:

```
 <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
```

Try to use locally built and installed plugin which is (NB!) **flow-maven-plugin** (not _vaadin-maven-plugin_).
```
<plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>flow-maven-plugin</artifactId>
                        <version>1.5-SNAPSHOT</version>
```

In my case everything worked out of the box. May be because the required plugin version is already available via the platform.

Please reopen the ticket if you still have an issue.
