### ISSUE TITLE
BeforeEnterObserver !possible security issue!

### ISSUE THREAD

**Issue by Braus** [vaadin/flow#5533]
Version: Vaadin flow (13) 
Environment: Windows 10 + Google Chrome

Hi everyone,

So I found what I believe to be a quite severe security issue regarding the beforeEnterObserver interface.

### Actual behavior
When using beforeEnterObserver the code in the beforeEnter method is executed after the constructor. because you never want any code to be executed for reason as long as the user is not allowed to see the page I would expect that it wouldn't work this way. of course you can just move your code to the beforeEnterObserver method but that's not what you expect.

### In short
Unfortunately the code in the constructor is executed before the beforeEnterObserver.

### Expected behavior
That the code in the beforeEnter method is executed before the constructor.

Is it intended to work this way? If so the name is abit misleading...  and I'd advice to update the documentation so it's clear that the constructor code is executed before the beforeEnterObserver, I wouldn't even mind to do it myself but then I would need verification that  it is intended to work tihs way.

Perhaps it's also a suggestion to make like a BeforeEnterObserver interface and a AfterEnterObserver interface.

I was thinking that you could do something like this to execute BeforeEnter before the constructor (see reflection):

```
Method method = View.class.getMethod(methodName, ...);
method.invoke( ...);
```

Kind regards,

**Comment by Legioth** [comment]
It's not possible to call any instance method on a class before its constructor has run. Using reflection doesn't helpe since the `invoke` method in `Method` requires the target instance as its first parameter (or `null` when invoking `static` methods).

"Before enter" in the name refers to the fact that the component is added to the parent layout and shown to the user only after all "before enter" handlers have been run. There's also an "after" handler that is run after the component tree has been set up based on the current navigation request (if it actually proceeds that far).

What we could do is to clarify the documentation to point out this case.

**Comment by Braus** [comment]
Hi Legioth, it's not as easy to implement as abc. but I made a simple example as seen below. you would need to make another class but you dont need to use that one for routing etc, the class could be dynamically instantiated get with reflection too.

I've heard that it might also be possible on bytecode with weaving but I don't have any experience with that. But if you deem this too rough I can understand.

The interface:
`public interface BeforeEnterTest {
    public void beforeEnter();
}`

A simulation for a page:
`public class aView implements BeforeEnterTest{
 
    String Message = "hi world";
   
    public String greet(){
        return Message;
    }
    
    @Override
    public void beforeEnter() {
        System.out.println( "Shooooo");
    }
}`
the reflection part:
`public class simpleContext {

    public simpleContext() {
        BeforeEnterTest theInterface=null;
        if(BeforeEnterTest.class.isAssignableFrom(aView.class)){
            //Method method = null;

            theInterface = new BeforeEnterTest() {
                @Override
                public void beforeEnter() {
                    try {
                        try {
                           Method method = aView.class.getMethod("beforeEnter");                         
                           method.invoke(new aView());
                        } catch (NoSuchMethodException ex) {
                            Logger.getLogger(simpleContext.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SecurityException ex) {
                            Logger.getLogger(simpleContext.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(simpleContext.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalArgumentException ex) {
                        Logger.getLogger(simpleContext.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InvocationTargetException ex) {
                        Logger.getLogger(simpleContext.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            int a = 5+5;
        }
        theInterface.beforeEnter();
    }
    
}`

**Comment by heruan** [comment]
@Braus I don't fully understand the security implications of having the instance already created before attaching the component (i.e. "before entering"); for example, I use `beforeEnter` for security purposes and I *need* the instance in there, but I don't see any security implication for that. I also have UI-scoped components as Spring beans, which instances are reused.

I'm interested in your security concerns, can you elaborate on them?

**Comment by Legioth** [comment]
`method.invoke(new aView())` in the provided example means that the (implicit) `aView` constructor is first run to create an instance, and only after that is the instance passed to `Method::invoke` which uses reflection to call `beforeEnter`. You can see this if you add an explicit constructor to `aView`:
```
public class aView implements BeforeEnterTest {
  public aView() {
    System.out.println("ooooohS");
  }
  ...
}
```

An instance must exist before instance methods are called, and the instance does not (properly) exist until the constructor has run. It is indeed possible to call instance methods while the instance is being created, e.g. from a constructor in a super class. Doing this is seen as a very bad practice since in that situation there might be weird situations such as `final` instance fields that have not yet been initialized.

**Comment by Braus** [comment]
@heruan I was using some logging depending on page usage for internal legal reasons. If I found out the code would've run before entering a page I could've been in serious legal problems. 

@Legioth The reason I made this an issue is because I remember code behaved this way in a different programming language so I had different expectations. I guess for now there is not a clean way to do this or perhaps there is but I don't know about it.. Anyway thank you for looking into it.

**Comment by heruan** [comment]
@Braus It seems it's more of a wrong expectation than a security issue, right? TBH I don't see the need for any warning/note about the `beforeEvent` method being invoked without a component instance, since it's how Java works.

In your case, I suggest placing logic that needs to be run when the component is effectively attached registering a handler for the `AttachEvent` or overriding the `onAttach` method (definitely not in the constructor); having a component instance constructed doesn't mean it's sent to the client (e.g. components as scoped Spring beans).
