### ISSUE TITLE
Remove HtmlImport to NpmPackage workarounds when addons updated

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5535]
- There is a `vaadin-core-shrinkwrap` task to remove in `NodeUpdatePackages.java`
- There is a flag in the maven plugin

**Comment by manolo** [comment]
Be aware that
 - The `TaskUpdatePackages` can be removed since we have all our components annotated
 - The  `convertHtml` in removal in `NodeUpdater` breaks non ported to NPM Addons

**Comment by denis-anisimov** [comment]
And now I don't understand what to do:
- `NodeUpdatePackages` doesn't exist.
- `convertHtml` from the maven plugin flag is used in every  `NodeUpdater` subclass. 
- If `convertHtml` flag is removed from the plugin ( as it's said in the main description) then which value should I use for `NodeUpdater` subclasses?
- `The convertHtml in removal in NodeUpdater breaks non ported to NPM Addons` : what does it mean ? If we still should care about not ported to NPM add-ons then should this ticket be done at all?
- `The TaskUpdatePackages can be removed since we have all our components annotated`: contradicts to the previous: if we should care about non ported to NPM add-ons then it may not be removed....

At the moment with the initial description and the additional comments I don't understand the ticket at all.

Please clarify it so that anyone else than you/initial implementor may work on it.
Otherwise please assign it to someone who is able to understand this description.

Please always carefully write a ticket description assuming that no-one understand how things are done (no any context). The worst tickets ever made by developers.

**Comment by manolo** [comment]
Ok, then close this ticket once `TaskUpdatePackages#getShrinkwrapJson` and related code is removed.

Then open another ticket to discuss which kind of support do we keep in V14 for mapping `HtmlImport` to `JsModule`.
