### ISSUE TITLE
Using KeyNotifier inside of Composite.initContent() leads to StackOverflowError

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#5553]
Tried to add a simple key listener for a form inside a composite. Initializing the key listener inisde the initContent method leads to an infinite loop of creating the composite and finally to a stack overflow error.

This example class displays the simple test case to reproduce the error (usable in the normal project starter):

```
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.Key;
import com.vaadin.flow.component.KeyModifier;
import com.vaadin.flow.component.KeyNotifier;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("")
public class MainView extends Composite<VerticalLayout> implements KeyNotifier {

    @Override
    protected VerticalLayout initContent() {
        VerticalLayout layout = new VerticalLayout();

        Button button = new Button("Click me",
                event -> Notification.show("Clicked!"));
        layout.add(button);

        addKeyUpListener(Key.ENTER, event -> button.click(), KeyModifier.CONTROL);

        return layout;
    }
}
```

**Comment by Legioth** [comment]
As a workaround, you can use `beforeClientResponse` to postpone the registration until it's safe:
```
UI.getCurrent().beforeClientResponse(this, context -> addKeyUpListener(...));
```

**Comment by denis-anisimov** [comment]
The only thing which is bad here is `StackOverflowError`.

It's incorrect to call `addKeyUpListener` method on `Composite` in it's init method: it's not yet initialized.

`addKeyUpListener`  could be aware of the fact that the element is not initialized and this could have be done except that `addKeyUpListener`  is a default method in the interface.

So `addKeyUpListener` may not know that it's called on `Composite` and it has no sense to overrode any possible default method in `Composite` in advance.
Instead this should be done by the developer himself.

The proper ways of doing things here is simple:
- don't call `addKeyUpListener`  on `Composite`: call it on `layout` ( the content).
- override `addKeyUpListener`  in your class since the default impl doesn't fit your purposes.
- a plenty of other ways.

What I've done: as a fix I've added the check that there is no infinite loop like in this situation so `getContent` calls itself (and `initContent`) because the content is `null` on every call.
So there will be a meaningful exception which explain that you are doing something unexpected.
