### ISSUE TITLE
Do not assume VaadinRequest is VaadinServletRequest

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/flow#5565]
A few places in the code do a class cast from `VaadinRequest` to `VaadinServletRequest` even when it is not needed. It will cause problems with non-servlet deployments, like #4760.

Related are a few places that use `ServletContext` to store attributes. That is now possible directly with `VaadinService` (#5500), so it should be done that way.

**Comment by pleku** [comment]
Copying a comment from @mcollovati in #3722:
>Most of the points listed on the issue are already done; missing changes may be
>
>* introduce `String getServicePath()` method in `VaadinService`; this could be used in place of VaadinServletRequest.getServletPath().
>* `ServletHelper` could be renamed to `ServiceHelper` and actual `ServletHelper.getContextRootRelativePath`
could replace call to `VaadinServletRequest.getServletPath` with `VaadinService.getServicePath` so the cast to `VaadinServletRequest` could be removed

To get rid of `ServletHelper`, we would have to keep it around in Flow 2.x / V14.x but just deprecate it in favor of `ServiceHelper`.

**Comment by denis-anisimov** [comment]
`ServletHelper.getContextRootRelativePath`  is used only inside `VaadinServletService::getContextRootRelativePath`  impl.
So I don't see any reason to have this method as a helper since it's just an impl detail of `VaadinServletService` and another impl will be in other `VaadinService`  impl.

So I will just remove this method from the new helper class.

Also `ServiceHelper`   is a confusing name for the helper since it's used in the functionality which handles requests.
So I'm going to rename it to `HandlerHelper`.
