### ISSUE TITLE
Add the ability to resolve multiple npm package versions

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5567]
Right now we update `package.json` with all `@NpmPackage` annotations  found in classpath.

The approach covers:
  - Adding new packages when found
  - Updating versions when upgrading a dependency
  - User can add their own frontend packages

But it does not cover:
  - Resolving multiple versions when the package is found more than once in classpath
  - Removing dependencies when package is removed
  - Ability of the user to pin a version and ignore the rest

References 

https://vaadin.slack.com/archives/C6X43FE8M/p1556101857002300

**Comment by Legioth** [comment]
>Removing dependencies when package is removed

This one seems like a completely separate thing, so I created https://github.com/vaadin/flow/issues/5569 for that purpose.

**Comment by pleku** [comment]
So currently we have issue for the case where:
1) a `Foo` component declares a dependency to `@NpmPackage(value="foo.js", "1.0.0")`
2) the `package.json` for `foo.js` declares it depends on `bar.js` version `^1.0.0`
3) a `Bar` component declares a dependency to `@NpmPackage(value="bar.js", "1.0.0")`

This leads to a situation that npm will load two version of `bar.js` and both end up to the browser and things will 🔥 . 

To solve this for the application projects, the `npm-shrinkwrap.json` can be used ?
To solve this for the add-ons (and our components), we should support using `^` in the `@NpmPackage` annotation and trust in semver ?

**Comment by Legioth** [comment]
I _think_ that in that situation, the `^1.0.0` dependency will be satisfied by the `1.0.0` version. It would be more tricky if `foo.js/package.json` would depend on version `^1.1.0` instead.

Supporting `^` in `@NpmPackage` would only "help" if `Bar` would actually define a version range for its dependency, which it might not want to do e.g. in case it knows there are semver incompatibilities.

I think two thing are really needed here:
1. Some way for the application developer, who might not know anything about how npm works, to be aware of the version conflict.
1. An easy way for an application developer to resolve the conflict, i.e. documentation that tells the user how to make it so that e.g. version `1.1.0` is used regardless.

One interesting observation here is also that there are two different types of conflicts:
* Two separate `@NpmPackage` annotations on the classpath define conflicting versions of the same dependency.
* A transitive `package.json` definition conflicts with either a `@NpmPackage` version or another transitive `package.json` definition.
