### ISSUE TITLE
Do not allow duplicate imports in @JsModule and Page#addJavaScript

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#5573]
See https://vaadin.slack.com/archives/C6RAXJATF/p1556260750094700

It's possible to add the same js file twice into the browser, when both JsModule annotation is present and the method is called.

Loading the same JS file twice is excessive and might break the app.

Would be also good to check the ticket for the JavaScript annotation and the method call.

**Comment by ujoni** [comment]
This needs to be verified with platform `14.0.0.rc1`.

**Comment by manolo** [comment]
After https://github.com/vaadin/flow/pull/5784 only external JavaScript or JsModules (basically those starting with `http://` `https://` ) are passed to the client to be dynamically loaded, everything else should be added to the application via annotations so as they are in the bundle.

Problem here is when the user needs to add a JavaScript dynamically, we still need to support this, the ideal is that the scanner is able to detect calls to `Page#addJavaScript` and update the bundle.

This might be fixed in the same way than  adding routes dynamically https://github.com/vaadin/flow/issues/5509

Closing this issue in favor of https://github.com/vaadin/flow/issues/5623 which describes exactly the problem
