### ISSUE TITLE
Losing context root when navigating to root

### ISSUE THREAD

**Issue by kasprzakpawel** [vaadin/flow#5582]
Application loosing context when navigate to root.
We've got HomeView registered with root.
`@Route(value = "")
public class HomeView extends ...`

After navigation
`UI.getCurrent().navigate("");`

Application lose context (from: "http://localhost:8080/app" to "http://localhost:8080") 
Previously (Vaadin 12.0.7), the URL haven't change at all (which also wasn't correct).

Navigation to root should change URL, but shouldn't change application context.  

Details:

- Vaadin: 13.0.4 / Flow 1.4.3
- Java: 1.8 202 x64
- OS: Win10 PRO x64 PL
- Browser: FF 67.0b14 (x64), Chrome 73.0.3683.103 (x64)

**Comment by peholmst** [comment]
Confirmed.

**Comment by peholmst** [comment]
The problem is in `Location.java`:

```
if (params.isEmpty()) {
    return !basePath.isEmpty() ? basePath : "/";
}
````

if the `basePath` is empty, which it is when navigation to `""`, then `/` is pushed to the browser history. This is not a relative path but an absolute path and that is why the context path is lost. Pushing an empty string would be considered a relative path and have the expected behaviour. However, this is how it used to be implemented. On April 8, 2019, the line in question was changed to instead use `/` if `basePath` is empty and I don't know why.

**Comment by peholmst** [comment]
Ah, apparently FireFox and Safari do not support pushing an empty string to the browser history, which is why this fix was made. However, the behavior is incorrect on at least FireFox even with the fix, because `/` removes the context path there as well (as stated in the original ticket description).

**Comment by peholmst** [comment]
Navigating to `.` instead of `/` seems to work on both Chrome, FF and Safari. Will make a PR as soon as I have an integration test ready.

**Comment by mvysny** [comment]
I don't think the problem is in the Location.java, but rather in the code which takes the output getPathWithQueryParameters() and pushes it blindly into the browser's history.

The fix has made the Location API inconsistent:

* `emptyLocation.getPath()` returns `""`, while
* `emptyLocation.getPathWithQueryParameters()` returns `"."`
