### ISSUE TITLE
Some frontend related error/warning messages are not visible enough

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#5646]
We should make frontend related messages more visible in console output.
- When npm or node are not found, the message is not visible, we also should break at this point
- When we run bower legacy mode message message message is not noticeable 

Consider colors, boxes, and also display those after the servlet container is initialised instead on in the middle of its output

**Comment by caalador** [comment]
To be taken into consideration for the bower mode message is the gradle support:

```
The error message is only specific to the Vaadin Maven plugin.

For Gradle users this should not be shown as it is a call to action which a user cannot do anything about right now.
```

**Comment by Legioth** [comment]
The situation related to the message about Bower vs npm will change based on https://github.com/vaadin/flow/pull/5695.

For the case of missing npm or node, it does indeed seem like failing early is a better alternative than continuing to run in a situation that is either completely broken or with significantly diminished development mode functionality.

**Comment by ujoni** [comment]
### Acceptance criteria
- When npm or node are not found, display a more notable message (colors and such)
- Make compatibility mode message more noticeable (it is already pretty big tho, maybe add color?)
- display messages after the servlet container is initialized instead on in the middle of its output

**Comment by denis-anisimov** [comment]
I would say the description is a bit contradictory and doesn't match the current code state:
- if we are going to break the build or stop the servlet deployment then no need to articulate anyhow the messages. They will be either the latest visible ones or maven will report then as a failure message.
- we should not use any specific visual signs or colors in the messages because: the logger doesn't support them (concerning the compatibility mode) and the messages come from exception message in case of maven build. Exception message cannot contain any special characters.
- the compatibility mode message has been already improved and made quite big and visible as a part of a separate ticket. I don't see how I can do it even more visible. Again: this is a log message. We should not use special characters there.
- we had an issue to remove all special characters from the output since some consoles doesn't support them and they are shown as `?` signs which is confusing.


As a result what will be done:
- maven build will fail right away with a message in the `MojoExecutionException` instance which describes the reason of the failure. It should be enough for maven build since it's quite visible (no any colors, special characters)
- `DevModeInitializer` will throw an `ServletException` with a proper message describing an issue. Hopefully it's enough to make the reason visible. I don't see what more we may do here : we may not stop the servlet container since one web app doesn't have to be a single WAR deployed to a web server. So it's the responsibility of the servlet container to do something properly when a `ServletContainerInitializer`  fails.
- the compatibility mode message won't be changed anyhow.
