### ISSUE TITLE
@JsModule annotations are ignored for classes retrieved from the Spring application context

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5658]
Given the following server-side `PolymerTemplate`

    @Tag("my-template")
    @JsModule("src/my-template.js")
    @Component("my-template")
    @Scope("prototype")
    public class MyTemplate extends PolymerTemplate<TemplateModel> {
    }

the template `my-template.js` is not included in the build, when the class is only retrieved through the application context.

### Steps to reproduce

Add the class to a `Component` in one of the following ways

    add(applicationContext.getBean(MyTemplate.class));

    add(applicationContext.getBean("my-template", Component.class));

### Actual results

The `my-template.js` file is not included in the build.

### Expected results

`my-template.js` is included in the build.

### Versions

Vaadin 14.0-SNAPSHOT

**Comment by Legioth** [comment]
The first case with using a class literal `MyTemplate.class` would work if the bytecode scanner would follow such references, as has also been suggested in https://github.com/vaadin/flow/issues/5509#issuecomment-493344448.

If only using the bean name, then there isn't really anything that can work fully automatic. Instead, we'd have to rely on something like `mainUnreached.js` as suggested in https://github.com/vaadin/flow/issues/5509#issuecomment-484377403.

**Comment by mehdi-vaadin** [comment]
It's expected that the solution of #5509 will also solve this one. However, a test is needed here to make sure that it works and will work.

**Comment by manolo** [comment]
This part is fixed already:

`add(applicationContext.getBean(MyTemplate.class));`

But this one cannot be fixed, at least without the user adding classes to be visited somehow.

`add(applicationContext.getBean("my-template", Component.class));`

I feel that we should close this ticket since there is a way to fix it (using classes instead of literals). In the future, when we implement chunks in #5537  we might have extra parameters to specify which extra classes to visit  per chunk

**Comment by eriklumme** [comment]
I have no objections against closing

**Comment by Legioth** [comment]
Partially fixed by #6041. The rest cannot reasonably be fixed.
