### ISSUE TITLE
Investigate and decide what to do with add-ons which are not migrated to NPM.

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#5679]
Follows up #5535.

Our components are migrated to NPM so there is no any issues with them.
But add-ons which are not migrated still requires some workarounds that are implemented in maven plugin (to handle `HtmlImport`s  instead of NPM related annotations).
The question to answer: do we want to support non migrated addd-ons (which works in bower mode only, `HtmlImport` based) with the modern Flow version (which is NPM based).

And related question: what to do with related workarounds in maven plugin code.

**Comment by manolo** [comment]
makes not sense to support 3rdParty addons that are not migrated to npm because 
  - we cannot in a reliable way figure out the mapping between the bower import path and the npm package for WC dependencies
  - we cannot assure that any `.html` template in the addon has the equivalent `.js` P3 file

We still support those addons that do not have `HtmlImport` but `JavaScript` annotations. Though they might fail if they are not written in a way that is Js-strict

**Comment by Legioth** [comment]
Would add-ons still work if the developer would manually add a appropriate `@NpmPackage` and `@JsModule` annotations to their own application? I guess all that is needed for that is that the `@HtmlImport` annotation is ignored?

In that case, we could at least document that as a workaround.
