### ISSUE TITLE
Vaadin.developmentMode is false in the browser console when running spring-boot:run with V14

### ISSUE THREAD

**Issue by eriklumme** [vaadin/flow#5680]
Tested with a custom project as well as the master branch of `skeleton-starter-flow-spring`. Although this uses that as an example, I do not think the problem is unique to that starter.

When running a V14 project with `spring-boot:run`, and in the browser console typing `Vaadin.developmentMode`, the output is `false` even though the application is in development mode.

It correctly returns `true` with the V13 branch of the starter.

### Steps to reproduce

As of 14.5 15:45 Finnish time

In a console, run

    git clone git@github.com:vaadin/skeleton-starter-flow-spring.git flow-starter
    cd flow-starter
    mvn install spring-boot:run

In the browser console, type `Vaadin.developmentMode` and press enter

### Actual results

The output is `false`

### Expected results

The output is `true`

**Comment by Artur-** [comment]
With the plain Java base starter, it works as expected

**Comment by Artur-** [comment]
There are multiple problems here. The value of the boolean is determined by this code
https://github.com/vaadin/vaadin-development-mode-detector/blob/master/vaadin-development-mode-detector.html#L6

The webpack process run from the servlet is run using `-d`, this causes the comments to be retained in the output and the dev mode detector works as expected.

When you compile with `mvn install` using `vaadin-maven-plugin`, webpack is run without `-d` and dev mode is incorrectly detected.

Because of #5677 you have to compile the bundle using `mvn install` and thus seemingly it is broken with Spring and works without.

Now Flow will correctly always tell that we are in dev mode. Probably this should be used instead of guessing based on comments in bundle or not

**Comment by Legioth** [comment]
So potential courses of action would be:
1) Fix #5677 (there's already a pending PR for this).
2) Change `vaadin-maven-plugin` to also use `-d` in case dev mode is enabled. This might also have positive effects for e.g. the ability to use sourcemaps in some situations.
3) Update the devmode detector to ignore the minification test if Flow says that dev mode is enabled.

**Comment by Artur-** [comment]
This has been fixed. Dev mode detector is handled in https://github.com/vaadin/vaadin-development-mode-detector/issues/23
