### ISSUE TITLE
Make proper VaadinOSGiService

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/flow#5736]
Current OSGi support is based on a fake `ServletContext` which makes little sense. The solution can most likely be improved by creating a dedicated `VaadinService` that takes care of everything related to OSGi.

Closely related to #5735.

**Comment by denis-anisimov** [comment]
I'm closing the ticket since I don't see how dedicated `VaadinService` may help to solve issue which are solved with fake `ServletContext`.
The fake servlet context allows to avoid writing a lot of code dedicated to the OSGi to run `ServletContainerInitializer`s.
In Flow `2.X` version we have no `ServletContext`  available anyhow to be able to execute `ServletContainerInitializer`s.
This is the only reason why fake  `ServletContext`  is used: it's passed to the `ServletContainerInitializer`s and then collected data is transferred to the real context when it becomes available.
So there is quite much sense for this fake `ServletContext`  in fact.
A custom `VaadinService` doesn't help here anyhow because it doesn't even exist when `ServletContainerInitializer` are executed.

In the `master` Flow `6.0` it's done already in a totally different way and there is no any fake context anymore.
