### ISSUE TITLE
Introduce `VaadinContext` and delegate storing attributes to it

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/flow#5751]
Follow up to #5500 

In certain cases `VaadinService` is not available, but the underlying `ServletContext` is. Create `VaadinContext` class that would allow setting and getting attributes just as `VaadinService` does now, and provide getter method for that in `VaadinService`.

**Comment by ujoni** [comment]
Branch feature/portal should have most of the changes done, except version compatibility. This will be brought in with the portlet support.

### Acceptance criteria:
- [ ] This change should be `+0.1.0` instead of `+1.0.0` (`ApplicationRouteRegistry::getInstance` takes `ServletContext in master, but feature/portal has replaced it with `VaadinContext` - provide backwards compatible overload).
