### ISSUE TITLE
webpack.config.js is not updated

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5790]
When upgrading from beta2 to SNAPSHOT, you would expect #5456 to be fixed and the built artifact to be named something else than `index.js`. This is not the case, it is still `index.js`. Only if you for some reason happen to delete the autogenerated `webpack.config.js`, then the artifact is renamed.

As a user, I would expect the autogenerated config to be updated by a new autogenerated config, whenever it changes.

**Comment by Legioth** [comment]
Related to https://github.com/vaadin/flow/issues/5464

**Comment by manolo** [comment]
IMO, this is an invalid issue because the file is being updated.

But we agreed to update only the variables pointing to output folders but not split the file or override it always. Therefore the user can either :
- ignore this file in git and clean in each build, when they dont need any custom plugin or configuration
- otherwise the user can configure everything and still flow updates the two variables pointing to the output folder

Until we have stable version of flow, it's responsibility of the user to regenerate the file. When we introduce a change not covered by the variables we update in future versions, we should develop a check that warns the user to regenerate the file.

Other options like split the file in a part that it's always modified by flow, or make the file owned by flow always and use some API so as the user can introduce their own operations, is something that needs a design, because it's quite difficult to cover most cases

**Comment by manolo** [comment]
An easy fix is to check for a version tag, so as we can give a clear message to the user to invite to regenerate the file, opened a ticket for that #5823

**Comment by caalador** [comment]
**Acceptance:**
 - webpack.config.js should be generated to `target/xyz` and a default modifiable webpack.config.js should be generated to the project root that the user can edit. As visioned in #5464 `Split the modifiable and unmodifiable parts into separate files, so that the modifiable file by default imports the configuration from the unmodifiable version and uses it as-is.`
 - The generated configuration file should always be updated.
 - The maven plugin should contain junit tests for testing that updating and adding files in wanted conditions happens as expected.

**Comment by Legioth** [comment]
I'll elaborate the practicalities of my vision from #5464 since it's slightly vaguely.

My core idea is that the generated file could have the same contents as today, and then by default the user-owned file would look something like this:
```
/* A comment that describes the purpose of this structure */
const flowDefaults = require('./some/location/generated-webpack.config.js');
module.exports = flowDefaults;
```

The magic comes from how the user can modify `flowDefaults` before exporting anything. Some examples. Please note the explicit checks to verify that the original structure is as expected. This is something that we cannot force users to do, but we can show good example in any documentation that we write.
```
const flowDefaults = require('./some/location/generated-webpack.config.js');

// Add a custom plugin
flowDefaults.plugins.push(new MyPlugin());

// Update the rules to also transpile `.mjs` files
if (!flowDefaults.module.rules[0].test) {
  throw "Unexpected structure in generated webpack config";
}
flowDefaults.module.rules[0].test = /\.m?js$/

// Include a custom JS in the entry point in addition to generated-flow-imports.js
if (typeof flowDefaults.entry.index != "string") {
  throw "Unexpected structure in generated webpack config";
}
flowDefaults.entry.index = [flowDefaults.entry.index, "myCustomFile.js"];

module.exports = flowDefaults;
```

**Comment by t-gergely** [comment]
> if (typeof flowDefaults.entry.index != "string") {
>   throw "Unexpected structure in generated webpack config";
> }

I tried  that based on the current webpack.config.js and it DOES throw.  Then what?
