### ISSUE TITLE
Deploying two war files in development mode to the same servlet container causes webpack conflicts

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5822]
System properties are global inside an servlet container. The code assumes they are local to the web application.

When the first app is deployed, a webpack is started.

Then the second app is deployed, the first webpack is used.

**Comment by manolo** [comment]
problems here are two:
- System property set to inform where the token file with the build info is, it was set because a second way to inform the running app how it was build.
- System property to reuse the webpack forked server when servlet container reloads

First can be removed, I wen the PR putting the token file in the class-path (#5807) 
For the second we need some mechanism to inform the app after servlet is reloaded whether there is a webpack running when in devmode, we might add to the system-property the application name

**Comment by denis-anisimov** [comment]
I don't know the details and where system properties are set but it might be that 
https://github.com/vaadin/flow/issues/5805 relates to this.

**Comment by denis-anisimov** [comment]
Apparently I cannot start dev mode server for wars being deployed to the servlet container at all:
- I have tomcat 
- when I deploy a war to it then it tries to start dev mode: ` com.vaadin.flow.server.startup.DevModeInitializer - Starting dev-mode updaters in /Users/denis/Downloads/apache-tomcat-9.0.21/webapps`
- But then it fails since it's WAR and dev mode is not able to find files in FS : `com.vaadin.flow.server.startup.DevModeInitializer - Skipping DEV MODE because cannot read '/Users/denis/Downloads/apache-tomcat-9.0.21/webapps/package.json' file.`.

So please provide exact steps to reproduce or make another ticket about dev mode for WAR files (which I believe has been already discussed but for Spring).

**Comment by Legioth** [comment]
Based on discussion in #5876, it seems like the actual issue is that the webpack dev server is used when running from a deployed .war file. Changing the logic so that the dev server is used only when running in a non-packaged way would also solve this issue.

**Comment by caalador** [comment]
Issue was tested to be fixed with 2 dev mode wars running together.
Fixed by #5909 as now we do not start a webpack dev server in development mode when executing a packaged war.
