### ISSUE TITLE
Reload causes Assertion error: No child node found with id -1

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#5830]
- Description of the bug
Reload of the page causes:

client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:196 Assertion error: No child node found with id -1

- Minimal reproducible example
I have a Route with VaadinSessionScope and when I hit CTRL+R (Reload) this error occurs.

- Versions:
    - Vaadin / Flow version
13.0.7
    - Java version
11
    - OS version
Windows 10
    - Browser version (if applicable)
Chrome Version 74.0.3729.169 (Official Build) (64-bit)
but also with Firefox and other browsers

**Comment by simasch** [comment]
The reason was that I added @Component to my Route. Without it - no problem occurs.

**Comment by Legioth** [comment]
> I have a Route with VaadinSessionScope and when I hit CTRL+R (Reload) this error occurs.

This cannot work, because it would mean that the same view instance would be shared between all UI instances (i.e. browser tabs) within the same HTTP session (i.e. the same browser instance). A component instance cannot be attached to multiple locations at once. This also happens when you reload the page because the browser doesn't provide any way of distinguishing a reload from opening a new browser tab.

To fix this, change all your ui component classes to be UI scoped or prototype scoped.
