### ISSUE TITLE
Is frontend compiled successfully?

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow#5939]
Vaadin 14 beta3. Created with `vaadin init --pre`

When running `spring-boot:run` through IntellJ, the following question is printed in the console:

```
----------------- ?  Frontend compiled successfully. ? -----------------
```

**Comment by caalador** [comment]
There is some charset fault in the console as the actual output for the question mark is [0xd83d, 0xdc4d]:
`----------------- 👍  Frontend compiled successfully. 👍 -----------------`

**Comment by denis-anisimov** [comment]
Hm............
What should we do with this?

Why do we use unicode in the console output ?

Ok, let it be an enhancement.
I would say:
- technically it's a bad idea to use non standard unicode for the console output.
- Using those codes makes the output nicer but .... They don't have to be supported by the console
- If it's possible: detect whether these symbols are supported by the console and use them only if they are supported.

Otherwise we should just remove all such symbols from the output at all.

**Comment by caalador** [comment]
We should probably just drop them. same for the exception message

**Comment by Legioth** [comment]
@vlukashov or someone else who worked with Connect might have some similar experience that might be helpful here as well?

**Comment by caalador** [comment]
Those are our own log outputs 
```
    private static final String FAILED_MSG = "\n------------------ 🚫  Frontend compilation failed. 🚫 -----------------";
    private static final String SUCCEED_MSG = "\n----------------- 👍  Frontend compiled successfully. 👍 -----------------";
```

what we read from webpack output is:
```
    private static final String DEFAULT_OUTPUT_PATTERN = ": Compiled.";
    private static final String DEFAULT_ERROR_PATTERN = ": Failed to compile.";
```

**Comment by vlukashov** [comment]
> @vlukashov or someone else who worked with Connect might have some similar experience that might be helpful here as well?

As far as I remember, in Connect there was no special effort to detect Unicode support in the console to turn emojis on / off.
