### ISSUE TITLE
Frontend-only changes trigger full app restart

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#5947]
Vaadin 14.0.0.rc1

When I make changes to the frontend code, I expect the changes to be visible without a full app restart. Now this takes much longer because every frontend change triggers not only a webpack compilation, but also a Java app restart.

This issue can be reproduced both with and without Spring Boot (with `skeleton-starter-flow-spring` and with `beverage-starter-flow`):
 - start the app in dev mode (`mvn jetty:run` / `mvn spring-boot:run`)
 - make a change in a .js template file
 - see that a webpack compilation is triggered (as expected)
 - see that the Java app restart is triggered (not expected)

![frontend-changes-trigger-full-app-restart](https://user-images.githubusercontent.com/22416150/59819687-a99f9800-9331-11e9-8cd1-373e843b8403.gif)

**Comment by Legioth** [comment]
This most likely happens because the webpack update causes an updated `stats.json` file to be written out to `/target/classes`. This directory is in turn watched for changes by Spring Boot devtools. To fix this, it might be enough to add an entry for `stats.json` in `spring.devtools.restart.additional-exclude` in your `application.properties` files. If this helps, then we should most likely add it to relevant starters as well.

There might also be a similar effect for non-spring applications with e.g. the scan interval setting for the Jetty Maven plugin. If that is the case, then we could also include a similar exclude in the plugin configuration for starters that use Jetty.

**Comment by vlukashov** [comment]
Adding a `spring.devtools.restart.additional-exclude=META-INF/VAADIN/config/**` line into the `application.properties` file helps. It prevents the app restart for frontend file changes. Thanks @Legioth !

**Comment by pleku** [comment]
Fixed for the spring project base & bakery, but attempts for project base to fix Jetty restart have not worked.

I might be missing something, but I tried to specify the `stats.json` to be excluded by adding:
```xml
                <configuration>
                    <scanIntervalSeconds>2</scanIntervalSeconds>
                    <scanTargetPatterns>
                        <scanTargetPattern>
                            <directory>target/classes/META-INF/VAADIN</directory>
                            <excludes>
                                <exclude>**/stats.json</exclude>
                            </excludes>
                        </scanTargetPattern>
                    </scanTargetPatterns>
```
But for some reason it is not picked up and restarts keep on happening.
