### ISSUE TITLE
Running Vaadin 14 project in npm mode decides to skip npm install and fails because NPE from getStatsFromWebpack

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow#6023]
Vaadin 14 rc3. 
Spring project created with Eclipse plugin preview. Eclipse v2019 latest.

Project works first, but at some point due to errors I removed a few files and node_modules folder. Debug as Java Application to the Spring Boot project starts the app (server), but does not work due to NPE at com.vaadin.flow.server.frontend.FrontendUtils.getStatsFromWebpack(FrontendUtils.java:349) ~[flow-server-2.0.2.jar:2.0.2]

I can observe that node_modules does not contain much anything. In the log I see the build skips npm install. Removing target, package.json, package-lock.json and webpack.*.js and running the project again now starts npm install and my node_modules is again 17k files.

[rc3-spring-fail.txt](https://github.com/vaadin/flow/files/3358978/rc3-spring-fail.txt)

**Comment by mehdi-vaadin** [comment]
I tried to reproduce it using Eclipse plugin preview. After creating the project, I ran `mvn install` and I got this error:
```
  Failed to find the following imports in the `node_modules` tree:
      ➜ @vaadin/flow-frontend/flow-component-renderer.js
  If the build fails, check that npm packages are installed.

[INFO] Updated /Users/mehdi/eclipse-workspace/my-starter-project/target/frontend/generated-flow-imports.js
[INFO] Running webpack ...
Hash: 677c0d156d1d5d33c613
Version: webpack 4.30.0
Time: 7157ms
Built at: 07/09/2019 11:08:58 AM
 2 assets
Entrypoint bundle = build/vaadin-bundle-4334868b8893557fa814.cache.js
Entrypoint bundle.es5 = build/vaadin-bundle.es5-aceb16b7bde3950865bc.cache.js
[18] ../target/frontend/generated-flow-imports.js?babel-target=es5 + 83 modules 745 KiB {1} [built]
     | ../target/frontend/generated-flow-imports.js?babel-target=es5 770 bytes [built]
     |     + 83 hidden modules
[19] ../target/frontend/generated-flow-imports.js?babel-target=es6 + 83 modules 662 KiB {0} [built]
     | ../target/frontend/generated-flow-imports.js?babel-target=es6 772 bytes [built]
     |     + 83 hidden modules
    + 18 hidden modules

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js?babel-target=es5' in '/Users/mehdi/eclipse-workspace/my-starter-project/target/frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 13:0-58

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js?babel-target=es6' in '/Users/mehdi/eclipse-workspace/my-starter-project/target/frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 13:0-58
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.910 s
[INFO] Finished at: 2019-07-09T11:08:58+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:14.0.0.rc3:build-frontend (default) on project my-starter-project: Execution default of goal com.vaadin:vaadin-maven-plugin:14.0.0.rc3:build-frontend failed: Webpack process exited with non-zero exit code.
[ERROR] Stderr: ''
```

**Comment by denis-anisimov** [comment]
I couldn't reproduce the issue with various combinations of files removal.

BUT I've reverse engineered the code based on the log file.
`Skipping "npm install"`  is from the log of the `TaskRunNpmInstall` 
and it's printed when `TaskUpdatePackages`'s `modified` flag is false and `shouldRunNpmInstall` returns `false`.

`modified` flag should be `false` since there were no any modifications in `json` files since there were no changes. So it's OK.

But `shouldRunNpmInstall`  should return `true`.
Here is what it returns:
```
installedPackages == null
                    || (installedPackages.length == 1 && FLOW_NPM_PACKAGE_NAME
                            .startsWith(installedPackages[0].getName()))
```

So if `installedPackages` is not empty (or contains more than one flow npm package) then `npm install` won't be executed. 
There is at least one mistake: `installedPackages` may not be `null` if `nodeModulesFolder` is directory which is checked before that.
The check should be done against the empty array and not `null`. This I'm going to fix.

Here is what happened in my opinion:
- the testing machine is Win
- the removal of `node_modules`  didn't succeeded : _may be_ everything has been removed but the directory has not been removed because it has been blocked for some reason. Windows is blocking directory removal if there is some process which uses it somehow.
- the code didn't check that even though the directory exists it's empty and skipped `npm install`.

As I said: I will correct the check.
But this is just a part of the story: FS check against directory emptiness is not reliable.
I may imagine the situation when `node_modules`  is not cleaned up completely but only subset of subdirs are removed. In this case the command won't be rerun and it will be again the same issue.
Another case: accidental blocking some files by running npm process which has not been killed for some reason.
On this case Windows allows to remove `node_modules` (internals) but it will not remove the dir itself and all files which are blocked by some process. And again we will get the same issue.
