### ISSUE TITLE
flow-maven-plugin's configuration `frontendDirectory` does not work

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6024]
I was attempting to have `frontend` directory on the same level as the module which attempted to use it:
- `./my-module`
- `./frontend`

Configuration was:
```xml
            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>flow-maven-plugin</artifactId>
                <version>${project.version}</version>
                <executions>
                    <execution>
                        <configuration>
                            <frontendDirectory>${project.basedir}/../frontend</frontendDirectory>
                        </configuration>
                        <goals>
                            <goal>prepare-frontend</goal>
                            <goal>build-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

instead of successfully loading the files from the new location, errors were given:
```
[ERROR]
[ERROR]   Failed to resolve the following files either:
[ERROR]    · in the `/frontend` sources folder
[ERROR]    · or as a `META-INF/resources/frontend` resource in some JAR.
[ERROR]        ? ./src/Dependency.js
[ERROR]        ? ./src/themed-component.js
[ERROR]   Please, double check that those files exist.
[ERROR] -> [Help 1]
```

**Comment by mehdi-vaadin** [comment]
It should be investigated to see how much effort it needs to be fixed. If it needs a lot of effort then it might not be worth fixing and the `frontendDirectory` config parameter should be removed.

**Comment by denis-anisimov** [comment]
There are several issues here:
- `frontendDirectory` is used as a parameter everywhere. So it's really possible to set it. But the directory which is set as `frontendDirectory` value will be translated to the `FrontendUtils.WEBPACK_PREFIX_ALIAS` (`Frontend`) as a path prefix. The path with `Frontend` will be written into `generated-flow-imports.js` . Then webpack somehow should resolve this prefix. Apparently it  resolves it to the project root `frontend`.
- `frontendDirectory` can be also set as a property `vaadin.frontend.frontend.folder` and this is the only way to set it for web application (if plugin is not used).
- the error/exception message ignores `frontendDirectory` value and use `frontend` to refer `frontendDirectory`.

In any case the passed `frontendDirectory` parameter is used correctly.
As mentioned above : it's written as `Frontend`.
But web pack should be configured to know how to decode `Frontend` (if possible).
I don't know how to do it. Haven't found any documentation about it.
May be @manolo knows it.

Another issue: using `frontendDirectory` in the error messages instead of `"frontend"`.
I will make a PR for this.

**Comment by denis-anisimov** [comment]
Update : 
`Frontend` is configured as an alias in the generated `webpack.config.js`:
```
resolve: {
    alias: {
      Frontend: frontendFolder
    }
  },
```

and this is how the `frontendFolder`  is initialized there:
```
const frontendFolder = `${baseDir}/frontend`;
```.

Apparently when the `webpack.config.js` is written it doesn't use the correct folder value.
