### ISSUE TITLE
Big values sent from javascript to server are converted to e-notation

### ISSUE THREAD

**Issue by brp-jimmy** [vaadin/flow#6028]
**Description**
As title states, sending big values from javascript code to the server using @ClientCallable will be converted to e-notation for some reason.

E.g. 53387546 will be converted to the string "5.3387546E7"

Is this intended behavior?

**Example**
in view.html
`__changeSelectedItem(event) {
                this.$server.selectItemFromClient(53387546);
}`

in view.java
`@ClientCallable
    private void selectItemFromClient(String itemId) {
        presenter.clientSelectPassage(Long.parse(itemId));
 }`

The code above will throw an NumberFormatException.

**Versions**
Vaadin flow 13.0.8
Java 8
Chrome 75.0.3770.100

**Comment by mehdi-vaadin** [comment]
If the type of the parameter, `itemId`, is `Integer` it works correctly.

**Comment by Legioth** [comment]
What happens here is that the value is JSON encoded in the browser as `53387546` and then parsed into a JsonNumber on the server. Numbers in JSON are always 64 bit floating point values, i.e. `double` in Java terminology. Next, the value is passed as parameter of type `String`, which is the point where Java's standard rules for converting a `double` into a `String` kicks in and gives you the `E` notation. What you're observing is thus basically the result of doing `new Double("53387546").toString()`.

I don't think there's anything Flow can do about this since there isn't in general any way of knowing what kind of String representation the user expects. Using `double` semantics is the best guess since that's the only way that can deal with the full range of values that the client might send.

**Comment by brp-jimmy** [comment]
Ah, that explains it. Thanks!
