### ISSUE TITLE
Reduce build time

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6049]
Build in TC lasts 20 minutes, IT’s needs 12’.

Each time we run a IT module, it takes about 30 seconds on average, because of the compilation, preparation, building and starting the servlet container.

If we can share modules with the same build and run requirements for multiple tests.

We have currently about 30 modules, that we might reduce to 6 - 10.

Note that each time that we introduce a new IT module we penalize build time of PRs and flow builds, instead we should look for the best module for running our new test.

**Comment by denis-anisimov** [comment]
The ticket description is too common.
I'm pretty sure it will never be done with such general description: it doesn't contain any specifics.
Which modules are extra ? Which modules we may drop ?
Which modules can be united together ?

For every module there was a reason why it has been created.
E.g. theming modules may not be combined with other modules because other modules contains implicitly or explicitly another theme (e.g. module which tests a custom `MyTheme` may not contain `Lumo`  theme in the classpath or any other theme) otherwise it won't work.
Sometimes this reason may be workarounded but it required some non-trivial efforts.
It means that this is not obvious : what exactly should be done.

So I would recommend make an exact proposal : a collection of modules set where every set of modules may be united together.

That will make a ticket concrete.
Otherwise as I said: I don't expect this will be done ever.

**Comment by pleku** [comment]
As the build time has deteriorated reusing this issue now to (re)start an investigation on the builds:
- where is the time spent, at the moment 50-60 minutes
- suggestions on what could we do with that, coordinating with the platform-release team

**Comment by knoobie** [comment]
> suggestions on what could we do

I've seen a blog post (https://spring.io/blog/2020/06/08/migrating-spring-boot-s-build-to-gradle) from the spring boot team about they reasoning to switch to Gradle. This could be interesting for your investigation. 

> "In terms of reducing the project’s build time, migrating the build to Gradle has undoubtedly been a success. As noted above, a full Maven-based build was taking an hour or more, both on CI and on developers’ own machines. Over the last four weeks, the mean successful build time with Gradle has been 9 minutes 22 seconds[...]"

**Comment by miguelatvaadin** [comment]
It seems to me that it has been replaced by https://github.com/vaadin/flow/issues/9885 and https://github.com/vaadin/flow/issues/9887.

**Comment by miguelatvaadin** [comment]
After some investigation, several possible improvements aroused (summarized):

- reuse forks for unit tests
- parallelize module execution
- reuse frontend compilations
- review some of the tests

which should lead to a huge build time reduction.

As a result, some new tasks have been created and this issue will be followed from there:

- https://github.com/vaadin/flow/issues/9885
- https://github.com/vaadin/flow/issues/9887
