### ISSUE TITLE
Icon and Image conflict

### ISSUE THREAD

**Issue by vlipovetskii** [vaadin/flow#6060]
```
StreamResource streamResource = ...; // created from the external (not resource file) "../file.png"
...
add(Icon(VaadinIcon.ABACUS)) 
add(Image(streamResource)) 
...
```
Expected behavior: Icon and Image are displayed.
Actual behavior: Icon is not displayed, Image is displayed.

If an Image is created from the file, which is located in `src\main\resources\META-INF\resources\file.png`, without `StreamResource`, there is no conflict.

Vaadin 13.0.10

**Comment by denis-anisimov** [comment]
Cannot reproduce this.

Here is the code I use :

```
@Route("")
@PWA(name = "Project Base for Vaadin Flow", shortName = "Project Base")
public class MainView extends VerticalLayout {

    public MainView() {
        StreamResource resource = new StreamResource("a", () -> makeImage());
        add(new Icon(VaadinIcon.ABACUS));
        // add(new Image(resource, "b"));
    }

    private InputStream makeImage() {
        try {
            URL url = new URL(
                    "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png");
            return url.openConnection().getInputStream();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
```

Both images are shown on the page.
Platform `rc4`.

So : please  provide a complete source code, all other info (the platform version) or better just attach the project where I may reproduce the issue.

**Comment by denis-anisimov** [comment]
Sorry, didn't notice that this is V13 initially.

But I'm not able to reproduce it with V13 either.

The platform version is `13.0.10`.
Same thing : both images are shown.
I'm using the external URL instead of local file for producing an input stream.
But I don't see a difference here since on the client side it doesn't matter how the images is produced.
So it may be a server side issue but then it's not about Flow code but rather an application code: if
the input stream is correctly provided then it just works.
So may be this is an application issue with reading a local file (making an input stream).

So anyway more details are needed (do you have any exception during a project execution ?)

**Comment by ujoni** [comment]
Abandoned as stale. Please recreate the ticket if the problem persists.
