### ISSUE TITLE
Cannot use `${styles}` constant in templates

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6064]
If we try to split a `.js` file in two files, so as the styles are in a `.css`  file, there is a security feature in the `html-tag` which prevents to interpolate constants, thus this syntax does not work.

```
import { PolymerElement } from  '@polymer/polymer/polymer-element.js';
import { html } from  '@polymer/polymer/lib/utils/html-tag.js';
import styles from './my-view.css';

class MyView extends PolymerElement {
  static get template() {
    return html`
      <style>${styles}</style>
      <div id=“content”>Content</div>
    `;
  }
}
customElements.define(‘my-view’, MyView);
```

The reason why `html` does not support this syntax is described in https://github.com/Polymer/polymer/issues/5410 

We might use the syntax suggested in the ticket

```
import { PolymerElement } from  '@polymer/polymer/polymer-element.js';
import { html } from  '@polymer/polymer/lib/utils/html-tag.js';
import styles from './my-view.css';

class MyView extends PolymerElement {
  static get template() {
    const tpl = document.createDocument(‘template’);
    tpl.innerHtml = `
      <style>${styles}</style>
      <div id=“content”>Content</div>`;
    return tpl;
  }
}
customElements.define(‘my-view’, MyView);
```

But it breaks when flow parses it for resolving `@Id`. 
To fix this, we need to support the second syntax when parsing the template getter in https://github.com/vaadin/flow/blob/4cee638d83165c62d31630401a816459c8877f6f/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/BundleParser.java#L53 

In addition we need to update documentation using the second syntax or removing it until implemented in the section https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/theme/theming-crash-course.asciidoc

**Comment by manolo** [comment]
Implementation could be that in the BundleParser, instead of looking for a strict statement like this

```
  get template() {
     return html`[content-used-in-parser]`;
  }  
```

we should use the first backticks-block found in the function

```
get template() {
   ....
   `[content-used-in-parser]`
   ...
}
```

That would cover many other cases like the described above.

**Comment by Legioth** [comment]
To help users prevent causing XSS problems by accident (i.e. ignorance), I think it would be really great if any pattern that we show in documentation would be structured so that there's some explicit hurdle to pass before entering potentially unsafe territory. For that reason, I don't think it would be a good solution to include something that interpolates stuff into `innerHTML` as the default way in our documentation. 

What this means in practice is that we would need some explicit API for constructing a template element with external styles that would be implemented in a way that verifies that the passed value is indeed a representation of CSS rather than arbitrary HTML contents. I don't think it's worth the effort to implement anything special for this case for now, which means that we would instead recommend that the template's own styles should still be inlined in the template string instead of imported from a separate CSS file. We should thus update the affected documentation.

The situation will be better once we integrate support for lit-element since that library already has a built-in solution for this kind of case through the special `styles` property.

We might still, as a separate ticket, relax the parser logic used for `@Id` mapping handling so that it can deal with other structures. Even in that case, I'd prefer that the pattern recommended in our documentation would avoid using `innerHTML` but instead use `html` to construct the basic template and then programmatically create a `style` element and assign the CSS contents as `textContent` on that element and finally insert the style element as part of the `content` of the template created by `html`.

**Comment by Legioth** [comment]
https://github.com/vaadin/flow/issues/6079 created for relaxing the logic in `BundleParser`.

**Comment by pleku** [comment]
### Acceptance Criteria
- change the example https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/theme/theming-crash-course.asciidoc#styling-polymer-templates to mention that you need to inline the styles for polymer templates
