### ISSUE TITLE
Auto-reload of Template

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#607]
This is a development-time convenience feature. When the server is run with `productionMode = false`, the framework listens for changes to used template files. When a change is discovered, the template is reparsed and the updated template tree is pushed to the browser for all active sessions, where it is immediately used to re-reender that part of the DOM.

**Comment by heruan** [comment]
I'm bumping this now since with ES modules in V14 the DX related to this pretty much collapsed.

In Bower mode, JRebel was able to push changed templates immediately and automatically; e.g.

- Project A (JAR): contains `META-INF/resources/frontend/my-template.html`
- Project B (WAR): depends on project A

Then running Project B with JRebel, a change in Project A's `my-template.html` was immediately available in the browser.

With ES modules, this no longer applies (at least I'm able to make it work); e.g.

- Project A (JAR): contains `META-INF/resources/frontend/my-template.js`
- Project B (WAR): depends on project A

Then running Project B with JRebel, a change in Project A's `my-template.js` isn't available in the browser and I need to restart the application… if I'm lucky, as 50% of the times I also need to `rm -rf node_modules target` in Project B root to avoid client errors such as:

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
```

I understand this is pretty old, but I hope it will be addressed ASAP now that V14 is released and since Vaadin's suggesting to migrate to ES module I expect many are already facing this.

**Comment by Legioth** [comment]
I've created https://github.com/vaadin/flow/issues/6347 for the possibility of loading frontend resources directly from the file system of a sub module instead of taking them from a jar.

I'd recommend that you create a separate issue for the problem with needing `rm -rf node_modules target` after updating resources in a sub module.

**Comment by markusherr** [comment]
This and #6347 are  now also a blockers for us to switch to Vaadin 14  with NPM / Polymer 3. 
I think every (non trivial) project consist of multiple Maven modules and the DX is just really bad right now. 
I also think #6306  is related to this.

**Comment by mehdi-vaadin** [comment]
I've closed this in favor of #6347.

**Comment by mehdi-vaadin** [comment]
I made a mistake. #6347 is only about sub-modules. Reopened the issue.

**Comment by joheriks** [comment]
Closing this ticket, as live reloading will now (in V17) trigger when any frontend resource is modified (and the main ticket covering monitoring submodule resources is #6347).
