### ISSUE TITLE
Running P3 migration tool generates additional files

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6102]
Running `mvn flow:migrate` for beverage-buddy generates extra files into the project's `./frontend` folder.

Steps to reproduce (at least on windows machine):
- clone beverage-buddy
- checkout `v13` branch
- check that you are using vaadin `14.0-SNAPSHOT`
- run  `mvn vaadin:migrate`
- let the magic happen
- check out `./frontend`

Expected result:
![image](https://user-images.githubusercontent.com/45562391/61535205-56a52780-aa3a-11e9-83bf-551f5e0e949c.png)

Actual result:
![image](https://user-images.githubusercontent.com/45562391/61535217-602e8f80-aa3a-11e9-8f7e-7f5ce6fb3d12.png)

`Modulizer` seems to create the extra `.gitignore` when it detects a project under version control, and some bit somewhere runs testing for the frontend components as the coverage is from `jasmine`.

Weird bit is also having `./frontend/frontend` - should probably be just `./frontend`?

**Comment by denis-anisimov** [comment]
>Weird bit is also having ./frontend/frontend - should probably be just ./frontend?

You should use `/src/main/webapp/frontend` technically via config parameter as a resource folder to migrate (it's already a parameter).

But yes, normally people will specify (or even not specify at all anything) `src/main/webapp`  as a resource root instead of `/src/main/webapp/frontend` . So we should take care about it.

Since it was just the first iteration of the tool it's fine that it you have to specify `/src/main/webapp/frontend` explicitly.
But for the complete migration tool we should take care about this magic `frontend` folder automatically and this is what I'm already doing now.

Other things are also improvements to deal with many unexpected things with modulizer: we should remove everything that is not needed (or just don't copy this into the final folder).
There is already a logic which filters things which are copied.
We just need to extend it.
