### ISSUE TITLE
Cannot deploy a distributable app in production mode

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6129]
When trying to deploy a distributable WAR on a WildFly cluster, I'm getting:

```
The deployment axians-demo.war will not be distributable because this feature
is disabled in web-fragment.xml of the module flow-server-production-mode-2.0.4.jar.
```

**Comment by Legioth** [comment]
I guess it wouldn't hurt that we'd include `<distributable />` in that web fragment since the fragment on its own doesn't add anything to the session. The same also applies for the compatibility mode fragment that is being added right now.

As a workaround, you can enable production mode by manually setting the servlet context parameter instead of including the shorthand dependency.
