### ISSUE TITLE
Improve error messaging for missing bundle or an out of date bundle

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#6137]
Maven goals that build an exploded war before running the server, such as `wildfly:run` or `jetty:run-exploded`, currently use webpack production mode. To enable using webpack dev mode with these goals, one currently has to manually remove the `build-frontend` goal from `vaadin-maven-plugin` in `pom.xml`. To enable building both production mode wars with the same `pom.xml`, `vaadin-maven-plugin` should support a `skipBuildFrontend` that skips the `build-frontend` goal.

**Comment by Legioth** [comment]
Another way of reaching the same benefits would be to change the default Maven setup so that `<goal>build-frontend</goal>` is only part of the production build profile. In that way, `wildfly:run` would automatically use a webpack dev server. To support this change, we would have to do some other small tweaks instead related to e.g. how various error conditions are reported.

**Comment by caalador** [comment]
As discussed we should remove the `build-frontend` goal from the default maven plugin goals and only run it in the production profile.

For the development mode war we could just have a profile also that can be targeted if you want to create a war that is run in development mode, but without the dev-server.

**Comment by pleku** [comment]
Related to this, because the `spring-boot:run` is also setup to execute `build-frontend` for spring boot project base, the issue https://github.com/vaadin/flow/issues/6027 is still reproducible.

**Comment by Legioth** [comment]
`spring-boot:run` does not run `build-frontend`. The tricky situation is if you first do e.g. `mvn install` and then after that launch the `main` method from the IDE.

**Comment by Legioth** [comment]
If we change the default in the starters, then I think there are three potential error situations:
* If you build a non-production war and deploy it on a different machine, then the frontend dir location defined in `flow-build-info.json` doesn't exist and npm dev mode cannot be started.
* If you build a non-production war, do changes in the project and then deploy the war, then it will use old Java classes from the war but new frontend files through the dev server. This might or might not lead to any obvious problems and might also be difficult to detect.
* If you build a production war from Maven, do some changes to the project and then run or package the project from your IDE, then the original production bundle will be used together with new Java classes. This might or might not lead to any obvious problems and might also be difficult to detect.

To help the user understand what goes on, we could consider these updates to logging and error messages:
* Ensure that there is a clear error message if the frontend dir location defined in `flow-build-info.json` doesn't exist. The error message should suggest doing a production build.
* Always log a message to the console when dev mode is starting to show the user the local file system location from which frontend files are taken. This message isn't an error, but rather increases the chance that the user can understand what goes on if Java an frontend files are not in sync. Preferably, the message should be printed only after the initial lines from webpack have been printed because anything before that will most likely not be noticed. We might even consider to also print this particular message to the browser console since the user is just as likely to look there to understand why their client-side integrations misbehave.

For the last potential error situation with Java classes changed after the production build has been built, I don't really have any idea on how we could help the user understand the situation. This is on the other hand most likely the least common situation, so it might be acceptable that we don't do anything specifically for it.

**Comment by Legioth** [comment]
One small detail that might help understand the situation when using an old production bundle would be that we simply log a line that tells when the currently used production build has been built. This info could be stored in `flow-build-info.json`.

**Comment by Legioth** [comment]
In addition, it would be great if the error message in case the dev server cannot be started would also be explicitly displayed in the bootstrap page so that the developer will have maximal chance of seeing it.

**Comment by Legioth** [comment]
One edge case that might happen in some cases is that the `npmFolder` designated in `flow-build-info.json` happens to exist even though it's used for some purposes and thus doesn't contain the project's files. We can detect that situation based on whether an appropriate `webpack.config.js` file exists, similarly to what is described in https://github.com/vaadin/flow/issues/6233.

**Comment by Legioth** [comment]
Because applications from start.spring.io won't have anything related to `vaadin-maven-plugin` in their `pom.xml`, we might have to add some extra information to the error message.

In particular, the user cannot simply activate the `production` profile if they don't have any production profile. To deal with this, we might have to add a link to some relevant documentation about how to setup a production build from scratch (with or without Maven).

**Comment by denis-anisimov** [comment]
@joheriks , @Legioth : what's the final solution for the ticket ?
The original description refers to `skipBuildFrontend` .
But then there is a long discussion without the exact solution/acceptance criteria.
Also the ticket says `Improve error messaging` but the description is about `skipBuildFrontend`.
I'm confused.

**Comment by Legioth** [comment]
Split up into three separate issues (in order of importance based on my subjective evaluation): https://github.com/vaadin/flow/issues/6396, https://github.com/vaadin/flow/issues/6397 and https://github.com/vaadin/flow/issues/6398
