### ISSUE TITLE
There are a number of classes which miss @since tag

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#6155]
E.g. `CssImport` , `JsModule` , etc.

I don't know whether we add them automatically, should we add an empty `since` or should we add a proper `since`.

If this is done automatically then this ticket may be just closed.

**Comment by mehdi-vaadin** [comment]
### Acceptance criteria
- [ ] Add empty since tag to all the classes in the branch 1.0
- [ ] Run the `updateSinceTags.sh` script for the branch 1.0 and push
- [ ] Cherry-pick the previous commit to branch 1.2
- [ ] Add empty since tag to all the new classes and methods in the branch 1.2
- [ ] Run the `updateSinceTags.sh` script for the branch 1.2 and push
- [ ] Cherry-pick the previous commit to branch 1.3
- [ ] Add empty since tag to all the new classes and methods in the branch 1.3
- [ ] Run the `updateSinceTags.sh` script for the branch 1.3 and push
- [ ] Cherry-pick the previous commit to branch 1.4
- [ ] Add empty since tag to all the new classes and methods in the branch 1.4
- [ ] Run the `updateSinceTags.sh` script for the branch 1.4 and push
- [ ] Cherry-pick the previous commit to master branch
- [ ] Add empty since tag to all the new classes and methods in the master branch
- [ ] Run the `updateSinceTags.sh` script for the master branch and push

APIDIFF tool can be used to see the new classes and methods in a branch.

**Comment by mehdi-vaadin** [comment]
I started by adding empty `@since` to the classes that don't have it. I used these regular expressions to find/replace with `perl` command:
find: `(\*/\n((?!^import).*\n)*public (class|interface|enum|@interface))`
replace: `* @since\n$1`
But, it doesn't work. Couldn't figure out why. The following is the complete script I created.
```
#!/bin/bash

noSinceFiles=`grep -L --exclude-dir=flow-tests --include \*.java -r "@since" .`

for f in $noSinceFiles
do
  echo "Fixing $f..."
  perl -pi -e '$a=1 if(!$a && s/(\*\/\n((?!^import).*\n)*public (class|interface|enum|@interface))/* @since\n\1/);' $f
done
```

**Comment by ujoni** [comment]
I've been adding missing `@since` tags to class Javadocs. 

I could not figure out a nice way to add those tags to methods (especially methods that were added in version after the original class version). But then again, that has not seemed to be the convention (Vaadin 8 does not have those, nor do we have any empty since tags on methods.)

If we need those, it will be an undertaking. Maybe there exists a better tool for it. I've been using IntelliJ's Javadoc inspection tool (which does not seem to believe in `@since` tags for methods).
