### ISSUE TITLE
Migration via migration tool failed

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow#6208]
At the end of the migration tool run I got:
```
[1/2] 🌀  Converting Package...
Out directory: /home/vaadin/tmp/spring-secured-vaadin/target/migration
Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: url.replace is not a function
    at Object.replaceHtmlExtensionIfFound (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/src/urls/util.ts:32:14)
    at Object.generatePackageJson (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/src/package-manifest.ts:205:24)
    at Object.<anonymous> (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/src/convert-package.ts:133:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/lib/convert-package.js:17:58)
    at <anonymous> }  reason:  TypeError: url.replace is not a function
    at Object.replaceHtmlExtensionIfFound (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/src/urls/util.ts:32:14)
    at Object.generatePackageJson (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/src/package-manifest.ts:205:24)
    at Object.<anonymous> (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/src/convert-package.ts:133:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vaadin/tmp/spring-secured-vaadin/target/migration/node_modules/polymer-modulizer/lib/convert-package.js:17:58)
    at <anonymous>
[WARNING] Don't know how to resolve Html import 'frontend://bower_components/iron-form/iron-form.html'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:22 min
[INFO] Finished at: 2019-08-09T13:33:28+02:00
[INFO] Final Memory: 35M/521M
[INFO] ------------------------------------------------------------------------
```

**Comment by paulroemer** [comment]
When running the application I get:
```
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '/iron-form/iron-form.js' in '/home/vaadin/tmp/spring-secured-vaadin/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 15:0-33
```

The updated code:
```
@JsModule("/iron-form/iron-form.js")
 public class LoginView extends VerticalLayout {
```

**Comment by pleku** [comment]
### Acceptance Criteria
- [ ] For any non-Vaadin html-import , we log the following:
```In Xyz.java file, added a JS module import that you need to manually map to the correct package vendor from npm```
- [ ] The added `@JsModule` should convert eg. `iron-list/iron-list-html`, to

**Comment by denis-anisimov** [comment]
I would like to split a number of issues here which are not stated explicitly here.

The original description contains two subissues:
- `<rejected> TypeError: url.replace is not a function`
- `[WARNING] Don't know how to resolve Html import 'frontend://bower_components/iron-form/iron-form.html'`

The first one doesn't prevent migration tool from doing its job. Everything is converted fine even with this error message.
The error message comes from `Modulizer`. I'm getting it all the time but it doesn't break anything.
The error comes from the external process and we can't influence on it (we may hide it but in other cases there may be an important reason why Modulizer fails, so it's not an option).

The second one is an issue with an external component imported as `'frontend://bower_components/iron-form/iron-form.html'`.

And yes: we don't know the vendor, so path in `JsModule` import is not correct.
The acceptance criteria is good for this situation but this is not the end of the story.

In fact there is a third issue:
- the migrated project can't be built.

That's mentioned in the first comment in the ticket.

In fact the migrated project won't be built regardless of external component or Vaadin component.
The reason is : `@JsModule` is not enough.

The migration tool is primarily intended to rewrite custom Polymer templates. For such cases we don't need an additional `@NpmPackage` annotation which just may not be generated added since we don't have information to do that.

So in any case Vaddin component or external (e.g. Polymer component) which is not defined in the project we still have an issue: the migrated project won't be built.

The reason: `@NpmPackage` annotation is required and it's never added by the migration tool.
As I mentioned we don't have data to generate `@NpmPackage` annotation automatically: we don't know at least the version of the package (also we don't really know the package name).

And as I mentioned : we may not do this even in case of Vaadin component.

So: I'm going to generate one more log message in case of external ("bower_component") component which says that `@NpmPackage` needs to be added manually.

**Comment by ujoni** [comment]
I added your suggestion about the `@NpmPackage` into the acceptance criteria. @denis-anisimov does it look correct to you?

**Comment by denis-anisimov** [comment]
>The path format should be described here.

I'm not sure I understand what it means. But otherwise looks OK.

**Comment by adexerivera** [comment]
Hello in my case occurs the same and never get my login.js migrated file, look this [link ](https://vaadin.com/forum/thread/17797778/17809591)where show the example please.

**Comment by denis-anisimov** [comment]
Hi,
I doubt it's the same.
See my comment here about the issues in the ticket : https://github.com/vaadin/flow/issues/6208#issuecomment-524820507.

This ticket is about having `@HtmlImport("something in bower components")` 
If you have ` login.html` ( `login.js` ) then it's not a bower component.
Which means this is a totally different issue.

If you see `<rejected> TypeError: url.replace is not a function` then it has no relation to the result.
As mentioned here `https://github.com/vaadin/flow/issues/6208#issuecomment-524820507` this is not a problem at all.

Apparently you have a different usecase. Please create another ticket with the description how to reproduce.

**Comment by mehdi-vaadin** [comment]
Regarding the error message that is mentioned in the first comment, I think it's worth mentioning it in the migration tool document that it's a known issue and the user doesn't need to worry about that. As @denis-anisimov said:
> The first one doesn't prevent migration tool from doing its job. Everything is converted fine even with this error message.
The error message comes from Modulizer. I'm getting it all the time but it doesn't break anything.
The error comes from the external process and we can't influence on it (we may hide it but in other cases there may be an important reason why Modulizer fails, so it's not an option).
