### ISSUE TITLE
After migration process - Polymer not defined exceptions.

### ISSUE THREAD

**Issue by tdq** [vaadin/flow#6213]
I used V13 Business App starter and first migrated to V14 with compatibility mode.
After that I prepared everything according to documentation for migration to npm and launched migration tool.
After that I launched the application and got (ReferenceError) : Polymer is not defined exceptions in console.

- Expected behavior: migration tool will correctly replace `Polymer.` by something related to V14
- Actual behavior: (ReferenceError) : Polymer is not defined 
- Versions:
    - Vaadin / Flow version: 14.0.0.rc9
    - Java version: 1.8.0_201
    - OS version: macOS 10.14.6 (18G87)
    - Browser version (if applicable): FF 68.0.1

**Comment by markusherr** [comment]
In my experience the  "(ReferenceError) : Polymer is not defined" is a follow up error of some other error.
We also had that same error but it was not related to Vaadin at all. 
The cause was, that the command line arguments passed to Java when starting the application was too long and was cut off, resulting in a lot of ClassNotFoundExceptions in Spring Boot / Vaadin Flow. 
The reason for the long command line was, that the classpath for some reason got a lot bigger.
The ClassNotFoundExceptions caused the HTML / JS to not be loaded correctly (including the polymer-element.js) which caused the mentioned error.
Setting up ItelliJ to pass the classpath as a file instead of passing it directly as argument helped.

But you error might be a different one. Just wanted to note, that it might not be related to Vaadin.

**Comment by denis-anisimov** [comment]
Hi,

if I correctly understand there are two things in the ticket:
- migration tool result 
- the migrated application execution

The issue as I understand is about the migration tool: it produces something which can't be used as is.
The result of the migration tool is the application which shows `(ReferenceError) : Polymer is not defined` exceptions in console.

But this (`(ReferenceError) : Polymer is not defined`) is not the ticket essence.
The problem is in the migration tool, right ?

You are mentioning as the expected behavior: `migration tool will correctly replace Polymer` .
Does it mean you know already the exact reason of the migration tool bug ?

Could you please provide a file which is not migrated (or not migrated properly) by the migration tool ?

The description of the ticket  is too generic. We  need steps to reproduce the issue.
Could you please provide additional information ?

**Comment by denis-anisimov** [comment]
I'm closing the ticket since there is no response for 2 months.
