### ISSUE TITLE
Prototype server-side navigation events with client-side routing

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6220]
When using a server-side route through `flow.navigate` I want server-side `BeforeEnterEvent`, `BeforeLeaveEvent`, and `AfterNavigationEvent` events to be triggered when entering / leaving the view, so that I can keep using these events in the same way as if there is no client-side routing involved.

This task it to prototype possible implementations, and to clarity the basic design choices:
- Try passing client-side events to the server
- Try keeping the navigation state on the server and trigger lifecycle events there
- One difficult thing is that in some cases, we cannot let client-side navigation continue until some server-side event has been processed. In other cases, it would be inefficient to wait for an additional round trip.
 - should listeners added to the `UI` instance via `ui.addBeforeEnterListener()` / `ui.addBeforeLeaveListener()` / `ui.addAfterNavigationListener()` be called for pure client-side navigation, or only when server-side navigation is involved?
 -  when triggering a server-side event for client-to-server / server-to-client navigation, what type is used to represent the client-side view to the server-side event handler?
 - try to prototype how to prevent / redirect navigation from server-side code

**Comment by manolo** [comment]
## Events in Route:

Route does not send events, instead it checks for the existence of the `onBeforeEnter` and `onBeforeLeave` methods in the view element in order to prevent navigation.

- `onBeforeLeave` is executed in the current view component before attaching a new one.
- `onBeforeEnter` is executed in the component corresponding to the new view to be displayed, just before it is attached and after `onBeforeLeave` was called in the previous element.

When one of the methods return a `{cancel: true}` object the navigation is aborted, other options is an empty object to continue with navigation or a `{redirect: {}}` to change it.

It's already considered that these methods can return a promise, which would make possible to ask to the server to see if the navigation can happen.

## Events in Flow

Flow considers `BeforeEnterObserver` and `AfterNavigationObserver` observers for  notifying components.

- `BeforeEnterObserver`: attached components implementing this will be notified before a new navigation happens. There is the posibility to reroute to another navigation target.
- `AfterNavigationObserver`: attached component implementing this interface will receive an event after all navigation tasks have resolved.

We might use these events to prevent a new navigation from client side in the case for instance that a view cannot be closed because of a dirty status, or also for doing server cleanups when the view is detached. 

## Possible Implementation

### Server side

The `JavaScriptBootstrapUI` can expose two methods that can be called from client-side route in the `onBeforeEnter` and `onBeforeLeave` phases. The signature might be:

```java
@ClientCallable
public void onBeforeLeave(String callbackName, String currentRoute, String nextRoute) {
}

@ClientCallable
public void onBeforeEnter(String callbackName, String currentRoute, String prevRoute) {
}
```

In the case the server is not prepared for closing the view, or for creating the new one, it would reject the client promise so as navigation does not succeed.

Note, that although `ClientCallable` does not support promises it can be workarounded as described later. The  `JavaScriptBootstrapUI` has already a method able to create the view and connect with the client container element using client side promises.

```java
@ClientCallable
public void connectClient(String clientElementTag, String clientElementId, String flowRoute) {
}
```

The way how flow would create views and execute `BeforeEnterObserver`s and  `AfterNavigationObserver`s to prevent navigation from client side should follow the current API, so as for the java developer perspective she continues extending the interfaces for being notified.

### Client side

The work-flow of the router in the client  might have the flowing workflow

#### First navigation
-  Route executes the `route.navigate` method to obtain the component for the first route. It returns a promise that resolves to the element for the view.
-  Route executes `onBeforeEnter` in the new element before attaching it.
  - If it resolves to an object with the `{cancel: true}` property, routing is cancelled.
  - Route redirects to a different route if the resolved object has the `{redirect: {}}` response
  - Otherwise navigation happens and route inserts the element in the outlet.

#### Next navigations  
-  Route executes the `onBeforeLeave` on the current attached element.
  - If it resolves to an object with the `{cancel: true}` property, it aborts navigation.
  - If it resolves to `{redirect: {}}`, it continues with the new redirected route.
  - Otherwise route executes the `route.navigate` method for the new route.
- Route executes `onBeforeEnter` in the view element and continues with the cases described in the first navigation flow section.


## Issues to consider

### Router 
1. The execution of navigation methods in router is out-of-order. The new component to display is computed before event in the previous element is executed, it means that `route.navigate` is always executed, thus the element has been resolved before the method in the previous element might prevent navigation. For Flow views, this is a critical problem. [354](https://github.com/vaadin/vaadin-router/issues/354)

2. Router calls `navigate` when the router not changes, which implies a new round trip, and causes issues in the server UI. [355](https://github.com/vaadin/vaadin-router/issues/355)

3. When a navigation is prevented, router might keep new pathname in the url bar [329](https://github.com/vaadin/vaadin-router/issues/329)

4. We might change router to use events instead of adding new methods to elements which seems an odd API.

### Flow
Flow does not support remote server calls that resolve to Promise value. Though, it can be workarounded by conbining a client-server with a server-client call. The workaround might cause problems if callbacks are not cleaned appropriatelly. [4050](https://github.com/vaadin/flow/issues/4050)

```java
@ClientCallable
public void onBeforeLeave(String callbackName, String currentRoute, String nextRoute) {
  boolean dirty = form.isOpened(); 
  this.getPage().executeJs(String.format("document.body.$['%s'](%b)", callbackName, dirty));
}
```

```js
const element = await flow.navigate(cfg) as any;
const flowServer = (document.body as any).$server;
const clientCallbacks = (document.body as any).$;
element.onBeforeEnter = function(e: any, args: any) {
  const callId = `flow-cb-${clientCallbacks.counter ++}`;
  return new Promise((resolve) => {
    clientCallbacks[callId] = function(reject : boolean) {
      delete clientCallbacks[callId];
      if (reject) {
        resolve(args.prevent());
      } else {
        resolve();
      }
    };
    flowServer.onBeforeEnter(callId, currentRoute, nextRoute);
  });
};
```

We might consider to implement promises in flow `ClientCallable` implementation before facing this in order to simplify client code and proly avoid other issues.

### Comunication 

Views in flow should be able somehow to tell the router when the round trip is necessary for routing notificatons.
  - The flow `connectClient` method can send to the client information about whether the element should implenent `onBeforeEnter` and/or `onBeforeLeave` methods.
  - Flow needs to visit view components in the returned view in order to discover that the view has components that register `BeforeEnterObserver`s and/or  `AfterNavigationObserver`s

**Comment by manolo** [comment]
Prototype branch: https://github.com/vaadin/beverage-starter-flow/tree/ccdm-prototype-navigation-events
