### ISSUE TITLE
Implement routing in JavaScriptBootstrapUI 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6221]
- The remote method `document.body.$server.connectClient` in the UI class should accept the routing information and outlet
- The UI should override methods for correct routing.
- In the case of an inexistent route it should insert some message in the browser outlet area. An error here or a 404 might ruin the client UI.
- It might be a remote call for destroying the view and free memory
- It might be a way to reuse view after a small while like in webcomponents implementation, or detach it for ever after a expiration time.
- Client side should be synchronized  to know whether to reuse the view.

**Comment by vlukashov** [comment]
JavaScriptBootstrapUI  should be able to respond to `flow.navigate` by using the `@Route` resolution on the server side (as much as possible reusing the existing implementation), create a virtual child of the JavaScriptBootstrapUI, and return it to the client side to be passed to Vaadin Router as the action result.

 - it's OK to return a server-side 404 page so that for the client side it would look like a successful navigation
 - the dev mode Flow 404 will only list server-side views, and no client-side views, and that's OK
 - do not consider navigation events at this point, see #6220
 - the server-side resources are not fried / reused until the next call to flow.navigate or the session expires
 - Flow session expiration handling is out of scope for this ticket

DoD: the beverage buddy proto with 2 ss views and 2 cs views should be possible to implement with this version of Flow.
