### ISSUE TITLE
Allow running dev mode without flow-build-info.json if cwd points to a valid project directory

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#6233]
It is currently possible to launch a Spring Boot application started by running the `main` method of the `@SpringBootApplication` class, but it looks like this works by accident based on the current working directory of the JVM process rather than as an officially supported feature. Furthermore, you need to explicitly disable `compatibilityMode` to avoid the error that is thrown when the setting isn't explicitly defined in either direction.

We could make this an official feature and also remove the need for disabling `compatibilityMode` with this small adjustment to how we treat different possible error situations.

The first error situation to take into account is if you create a war file or do an exploded war deployment without a `flow-build-info.json` file. This can happen if you import the project to an IDE and then use features in the IDE for building a war file or deploying to a server without ever using the Maven plugin. The only difference compared to the Spring Boot case that we want to support is that the working directory of the server process will not be the project directory but instead e.g. the location of the servlet container binary. We can detect this situation by looking for the existence of a `webpack.config.js` file that declares a `flowConstants` variable, i.e. the same logic that is used by the Maven plugin to determine whether it should recreate that file. If the file exists, then we keep using the working directory as a project directory. If it doesn't exist, we fail with a helpful error message.

The other error condition to consider is cases where a `flow-build-info.json` file doesn't exist because the project is supposed to use compatibility mode, but the developer has not remembered to explicitly enable it. This situation can also be resolved with the same check based on the assumption that a `webpack.config.js` (with appropriate contents) file would not exist in a compatibility project.

The logic for how to operate would thus be as follows:
* If compatibility mode is explicitly enabled, use it.
* If no compatibility mode setting is defined (neither enabling nor disabling it, including configuration through `flow-build-info.json`), and the current working directory doesn't contain an appropriate `webpack.config.js`, then show the same error message that is now shown regardless of `webpack.config.js`.
* If compatibility mode is explicitly set to `false`, no `flow-build-info.json` file exists, and no appropriate `webpack.config.js` is found in the current working directory, then show an error message that suggest either triggering creation of `flow-bulid-info.json` or ensuring `webpack.config.js` is present in the working directory.
* If `flow-bulid-info.json` doesn't exist, but an appropriate `webpack.config.js` is found in the working directory, then launch a dev server with configuration based on the working directory location (and print a message to the log that explicitly mentions that automatic configuration based on the working directory is used).

**Comment by joheriks** [comment]
When fixing, remember to change the fallback values for `SERVLET_PARAMETER_PRODUCTION_MODE` (and the legacy `SERVLET_PARAMETER_BOWER_MODE`) in `PropertyDeploymentConfiguration` (https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/PropertyDeploymentConfiguration.java#L150) from `true` to `false`.

**Comment by Legioth** [comment]
Because applications from start.spring.io won't have anything related to `vaadin-maven-plugin` in their `pom.xml`, we might have to add some extra information to the error message.

In particular, this is a problem for multi-module Maven projects if you launch them from the root of the project using something like `mvn spring-boot:run -pl my-ui` since in that case your working directory will not be the place where e.g. the `frontend` directory is located.

**Comment by denis-anisimov** [comment]
@Legioth , I need clarification since I'm not able to match the current code with a description of how things works:

>If no compatibility mode setting is defined (neither enabling nor disabling it, including configuration through flow-build-info.json), and the current working directory doesn't contain an appropriate webpack.config.js, then show the same error message that is now shown regardless of webpack.config.js.

Could you please specify which error message ?
I can't understand from the description and a number of attempts to get any error message related to absence of compatibility mode setting.

The problem is : I'm trying to find a place where the error message (or any other error message) is shown.
I would say that it should be `DevModeInitializer` but in fact  I don't see any error message produced there.
May be it's `BootstrapHandler` which tries to read `stats.json` ... (at least it says something about `spring-boot:run`).
Anyway the error message content would be helpful.

Another issue with the approach is: with the current API it's not possible to know whether some property (like `compatibilityMode`)  has been set explicitly (to `false` or `true`): it's just possible to check its value which has `boolean` type and we set the value implicitly to some default value if it has not been set.
So this `If no compatibility mode setting is defined` is possible only inside the value getter which is not a proper place to have logic related to files/dev mode. 
So either a new API is required or `DeploymentConfiguration::getStringProperty`  needs to be used in addition to `DeploymentConfiguration::isCompatibilityMode` which is not technically correct since no-one said that `DeploymentConfiguration::isCompatibilityMode`  is implemented using `DeploymentConfiguration::getStringProperty` .

**Comment by manolo** [comment]
@Legioth what happens in the very first time: you import the project in your IDE and run it, but you have never run `mvn prepare-frontend`  or anything that generates the first `webpack.config.js` file ? 
Think that when devmode starts, it generates the `webpack.config` file if it does not exist, but in the solution exposed here, in order to run the devmode we still need it, it seems a loop condition that never succeed. Or am I missing something ?

**Comment by Legioth** [comment]
> Could you please specify which error message ?
I can't understand from the description and a number of attempts to get any error message related to absence of compatibility mode setting.

The easiest way of encountering a situation where the compatibility mode setting isn't explicitly defined is to take any V13 project and update the dependency version but not enable `prepare-frontend` and not add the `flow-server-compatibility-mode` dependency. Doing so will give you this error when you try to run the application:
```
java.lang.IllegalStateException: Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath. With Maven, this is handled by the 'prepare-frontend' goal. To use compatibility mode, add the 'flow-server-compatibility-mode' dependency. If using Vaadin with Spring Boot, instead set the property 'vaadin.compatibilityMode' to 'true' in 'application.properties'.
	at com.vaadin.flow.server.DefaultDeploymentConfiguration.checkCompatibilityMode(DefaultDeploymentConfiguration.java:270) ~[flow-server-2.0.8.jar:2.0.8]
```

> Think that when devmode starts, it generates the `webpack.config.js` file if it does not exist, but in the solution exposed here, in order to run the devmode we still need it

We're optimizing for the case when you're using a starter and thus already have a `webpack.config.js` file. If you start from a completely empty project, then you'd have to take the scenic route and run `prepare-frontend` manually at least once.
