### ISSUE TITLE
Notification doesn't show, instead warning is logged.

### ISSUE THREAD

**Issue by IEnoobong** [vaadin/flow#6253]
Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum or https://gitter.im/vaadin/flow

NOTE: Issues concerning certain component should go to the corresponding components repository.

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Description of the bug
Notification from interface doesn't show, rather a warning is logged
- Minimal reproducible example
I have an interface like this

```
public interface HasNotifications extends HasElement {

  default void showNotification(String message) {
    Notification.show(message, NOTIFICATION_DURATION, Notification.Position.TOP_END);
  }
}
```

I have a class that implements it as
```
@Route("invoice")
@PageTitle("Invoice")
@PreserveOnRefresh
@JsModule("./styles/shared-styles.js")
public class InvoiceView extends VerticalLayout implements HasNotifications, BeforeEnterObserver
```

Calling `showNotification("message");`

Doesn't work but gives the warning 
```
WARN 9616 --- [nio-8080-exec-2] c.v.f.server.startup.DevModeInitializer : Frontend dependencies have not been analyzed for com.vaadin.flow.component.notification.Notification. To make the component's frontend dependencies work, you must ensure the component class is directly referenced through an application entry point such as a class annotated with @Route.
```

Calling `Notification.show(message)` works
- Expected behavior
Should show Notification from the implemented interface
- Actual behavior
Doesn't show notification but logs warning
- Versions:
    - Vaadin / Flow version 14.0.0
    - Java version 8
    - OS version MacOS 10.14.6
    - Browser version (if applicable)

**Comment by denis-anisimov** [comment]
This is caused by the strategy of finding the components.
Previously byte code scanning was used and it was not able to find all cases when the components are used. Your components had to be referenced from entry points (like root component).

Now fill class path strategy is used in dev mode and it's also available in production mode.
In production mode byte code scanning strategy is still used but there is a fallback to full bundle.
So this should not be an issue anymore.
Please use the latest versions (it's fixed there).
Please let me know if still doesn't work.
