### ISSUE TITLE
Binder.hasChanges does not work

### ISSUE THREAD

**Issue by ywuliu** [vaadin/flow#6280]
- Description of the bug
Binder.hasChanges() does not work
- Minimal reproducible example

1: did not trace initial value
```
Class T
{
String t;
get, set..
}

T tInstance=new T();
tInstance.setT("1");

TextField t=new TextField();
binder.readBean(tInstance);
```

user set t value to "2", then, set t value back to "1";

hasValue changes return true

2: when binder with `<KeyValueSelect<T> extends Select>
T (V, String>

```
getEmptyValue()
{
 return new T(null,"")
}


Class KeyValueSelectCOnvert()
{
.....
}
```
hasValueChanges will return true forever  when original value is null-- when you disable this property, it still return false

- Expected behavior

for both case, it should return false

- Actual behavior

return true
- Versions:
    - Vaadin : 14 rc9
    - Java version 11
    - OS version  any
    - Browser version  any

**Comment by denis-anisimov** [comment]
Sorry, I'm not able to get anything from this description.

Could you please provide a code which I may copy paste and see the result?

In the description you mention : `hasValue`, `hasValueChanges`

`hasValueChanges will return true forever when original value is null-- when you disable this property, it still return false` : `true` or `false` ?

I don't really understand .

**Comment by joheriks** [comment]
Closing as no followup since the last 4 weeks.

**Comment by Kirawastaken** [comment]
> 
> 
>     * Description of the bug
>       Binder.hasChanges() does not work
> 
>     * Minimal reproducible example
> 
> 
> 1: did not trace initial value
> 
> ```
> Class T
> {
> String t;
> get, set..
> }
> 
> T tInstance=new T();
> tInstance.setT("1");
> 
> TextField t=new TextField();
> binder.readBean(tInstance);
> ```
> 
> user set t value to "2", then, set t value back to "1";
> 
> hasValue changes return true
> 

Please reopen this issue. I understand part 1 of his issue as I have found encountered this aswell.
Actually it surprises me that there aren't many more issues of this type open.

The Binder.hasChanges method adds an entry to the Binder.changedBindings HashSet whenever an actual change to the bound value occurs. However it seems to me that this HashSet is only cleared when the bean is removed, the binding is removed or the changes are written.

Changes are not verified for older values, which produces a problem. I think there are few developers opting to use readBean and writeBean instead of setBean which would explain why this problem still exists.

Now to the problem.
`Binder<User> binder = new Binder(User.class);
 Textfield field = new Textfield();
 binder.forField(field).bind(User::getFirstname,User::setFirstname);
 
 User user = new User();
 user.setFirstname("Karl");

 binder.readBean(user);
`

In this code snippet the field is bound to the binder and the bean is read in. Now "Karl" is the initial value of the textfield as far as the binder knows. 

User XYZ: empties the Textfield and writes "Fred"
User XYZ: empties the Textfield and writes "Karl"

At this point no changes were ever comitted. 
Binder.hasChanges returns true here.

However it shouldnt. Because if you add up everything that the user did, the intial value that was read into the field via the readBean method has not changes, it remains the same. 
Therefore, Binder.hasChanges should return false here.
