### ISSUE TITLE
CCDM: when a TS LitElement is imported asynchronously it's not displayed

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#6295]
This is a ticket for tracking an issue found when adding the `categories` view in client side in the 'beverage-starter-flow' application.

When view `client-categories.ts` is imported in the route action dynamically (https://github.com/vaadin/beverage-starter-flow/pull/420/files#diff-afb417a68f65c337d0b0a9e3d5f72eceR40), the output in the outlet is the string representation of the object `[object Object]`, otherwise, if the import is done synchronously (https://github.com/vaadin/beverage-starter-flow/pull/420/files#diff-afb417a68f65c337d0b0a9e3d5f72eceR21) the view is displayed correctly.

Apparently the cause is in the line https://github.com/Polymer/lit-html/blob/master/src/lib/parts.ts#L217 of the `lit-element` code, because the `instanceof` check does not pass even though the value is a `TemplateResult` when  the lit-html library and the client-categories component end up in different webpack bundles .

The resolution for this ticket should have the next steps

1. create a minimal demo (online sandboxes like glitch.com or stackblitz.com would be preferred)
2. create an issue in the lit-element repo
3. think of a workaround to use in CCDM if possible, otherwise import it synchronously as it's done now
4. once the problem is fixed in the library, remove the workaround or FIXME comments

**Comment by platosha** [comment]
Seems to be caused by not having `BabelMultiTargetPlugin.loader()` on `.ts` files in generated webpack config. Here is my idea  of what is happening:

- The view is `.ts` file and is dynamically imported, which makes a separate chunk
- The resolved file import path for the chunk is missing the `?babel-target` suffix because of skipping `BabelMultiTargetPlugin.loader()` for `.ts` files
- The chunk’s dependency import paths do not have that suffix too, normally the loader takes care of inheriting the suffix from parent imports
- At the same time, resolved file import paths in the index bundle have `?babel-target` suffix
- Webpack emits duplicate code for same dependencies with the suffix in the index bundle, and without the suffix in the view bundle

The following `webpack.config.js` workaround fixed the issue:
```js
const merge = require('webpack-merge');
const flowDefaults = require('./webpack.generated.js');

const {BabelMultiTargetPlugin} = require('webpack-babel-multi-target-plugin');
delete flowDefaults.module;

module.exports = merge(flowDefaults, {
    module: {
        rules: [
            { // Files that Babel has to transpile
                test: /\.js$/,
                use: [BabelMultiTargetPlugin.loader()]
            },
            {
                test: /\.ts$/,
                use: [
                    BabelMultiTargetPlugin.loader(),
                    'awesome-typescript-loader'
                ]
            },
            {
                test: /\.css$/i,
                use: ['raw-loader']
            }
        ]
    }
});
```
