### ISSUE TITLE
Vaadin 14 Starter App uses absolute path information

### ISSUE THREAD

**Issue by bjlemke** [vaadin/flow#6309]
Trying to deploy a Vaadin 14 starter project with plain java servlet technology stack to a different server leads to a path error.

Here are the details  :

I imported the generated project into eclipse.
From eclipse, I exported a war-File. The war-File then was deployed to a different server running Tomcat 9. During deployment, Tomcat already reported path errors.

I found out, that there seems to be some absolute path names in several node_modules subdirectories in the package.json files in the _where tag values.
( e.g.  "_where": "/Users/lemke/Downloads/vaadin14first/node_modules/htmlparser2", )

**Comment by Legioth** [comment]
A .war built from e.g. Eclipse will use development mode that gives faster build times and live reloading for changes to client-side dependencies.

If you want to deploy to an external server, then you need to do a production build. The easiest way of doing that is by using the Vaadin Maven plugin. If you use the default `pom.xml` e.g. from vaadin.com/start, then it will already have a profile for that purpose so that you only need to do `mvn -Pproduction package`.

There is already another ticket, #6137, about clarifying the error message for your case so that it would be more apparent how to deal with the case.
