### ISSUE TITLE
@Push: config method getPushConfiguration().setPushUrl needs change to support websocket and http

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#6320]
in Vaadin @Push config method getPushConfiguration().setPushUrl(). The **vaadinpush.js** will take the given url which is set in method setPushUrl(String url) for both http and ws for communication to the server.
This causing problem if app is configured for http and ws on different listen ports.

Proposal to change this method into 2 new methods:

`getPushConfiguration().setPushHttpUrl(String url)`: for http config
`getPushConfiguration().setPushWsUrl(String url)`: for websocket config

**vaadinpush.js** will take respective url when it needs communicate with server for @Push

[https://vaadin.com/forum/thread/17805732/vaadin-14-vaadinpush-js-websocket-failure-return-code-501](url)

**Comment by denis-anisimov** [comment]
Could you please clarify what you mean by:

> The vaadinpush.js will take the given url which is set in method setPushUrl(String url) for both http and ws for communication to the server.

HTTP can be used as a transport in Push. Websockets also may be used as a transport.
But you should not use both of them at the same time .

So I don't see an issue since only one transport should be used for Push.

If you mean by HTTP a "plain" (a normal communication without Push) between the server side and the client side then this url should not be used for this communication at all. 
As a result there should not be a problem.

`vaadinpush.js` should be used only for push related communication as I understand (though I'm not an expert in Push impl ).

**Comment by letrthang** [comment]
hi Dennis

there are multiple options in VaadinPush to communication with server: Websocket, webcoket_XHR...
let say i use webcoket_XHR and what i want with VaadinPush.js that:
- XHR(XMLHttpRequest) is at port **443** ( ok, this is standard for https)
- websocket is at port **8443**
how can I tell VaadinPush client for the second thing, port 8443 for websocket ?
that why i suggest to have 2 methods as above. of course we use default setting if user doesn't use these methods.

okay, maybe you ask guys VaadinPush.js implementer taking a look on this :))

**Comment by denis-anisimov** [comment]
Sure, I just have to clarify the issue.

> XHR(XMLHttpRequest) is at port 443 ( ok, this is standard for https)

There should not be any setting like this used in `vaadinpush.js`.
That's what I'm trying to say: this will be used regardless of Push. `vaadinpush.js`   should be used only for Push. Plain HTTP communication should be done outside of `vaadinpush.js`.
It's not 443 port for HTTPS in fact: it's ay port which your web server uses. 

>websocket is at port 8443

This is what `setPushHttpUrl` allows to configure. Just set the url with port using the method.
That's it.

It's possible to use Long Polling as Push transport. So I guess you are confused by Long polling HTTP url for XHR in `vaadinpush.js` .
But Long polling and websockets are mutually exclusive : you should not use both of them.
That's why it's enough to use one `setPushHttpUrl` .
"Regular" HTTP communication  (XHR) should not be affected anyhow by this setting.

If it's still not clear let's go with a concrete example avoiding guesses :
- do you have  an issue which XHR when you set the push URL via `setPushHttpUrl`  ?
- Please provide a code example and steps to reproduce if you have such issue.

**Comment by letrthang** [comment]
Dennis

When i set setPushHttpUrl(https://domain.com) then vaadinpush.js will access http at https://domain.com
And also websocket at wss://domain.com.

But our server listens websocket at wss://domain.com:8443.

This is because pivotal ws cloud server only allows ws listening  at port 8443.

**Comment by denis-anisimov** [comment]
I think you should use `wss://domain.com:4443` for `setPushHttpUrl`
or `https://domain.com:4443` if `wss`  doesn't work.

**Comment by denis-anisimov** [comment]
Let's return to the original issue:
`setPushWsUrl`  can't be used since this is a dedicated method for only one Push transport: WebSocket.
It means that we have to provide such method for any transport which is just a bad API.

`setPushHttpUrl`  has to satisfy your needs.
It should not change HTTP/HTTPS regular communication. It should affect ONLY Push regardless of transport.
If it doesn't then that's the issue: it has to work.
Then please either correct this ticket with a proper description (if this method doesn't work for you) or create a new ticket (and close this one).

**Comment by letrthang** [comment]
`setPushHttpUrl(wss://domain.com:4443) ` will work for wss but will not work for XHR.

However this case is quite specific. Usually in almost server (eg. AWS) both https and wss will listen at same port 443, so you just need` setPushHttpUrl(https://domain.com)` is enough.

so i close this case here.
