### ISSUE TITLE
compatibilityMode is not read from system property or web init param

### ISSUE THREAD

**Issue by samulivaadin** [vaadin/flow#6360]
Consider 
`@WebInitParam(name = "compatibilityMode", value = "true")`
or setting vaadin.compatibilityMode to true in system property in jetty-maven-plugin or adding flow-server-compatibility-mode dependency. One would expect compatibility be on. This is not the case with non-spring jetty runnable application. Application starts with npm when running mvn jetty:run. See provided example project. It has both pom.xml jetty-maven-plugin system env setup and WebInitParam set to compatibilityMode.

[compatibilitymode.zip](https://github.com/vaadin/flow/files/3558597/compatibilitymode.zip)

However several workarounds works:
1. Call mvn jetty:run -Dvaadin.compatibilityMode=true
2. Set @WebInitParam(name = "bowerMode", value = "true")
3. Set vaadin.bowerMode or com.vaadin.flow.server.compatibilityMode in jetty-maven-plugin

So it seems that compatibilityMode property gets overridden while older bowerMode or with full com.vaadin.flow.server package name does not. 

Tested with 14.0.2

**Comment by joheriks** [comment]
The recommended solution (adding `flow-server-compatibility-mode` dependency) works as long as `prepare-frontend` is not executed (OTOH if executed, `flow-build-info.json` will be generated for npm mode, *unless* -Dvaadin.compatibilityMode=true or -Dvaadin.bowerMode=true have been passed to Maven, since these influence how the token file is generated). Also absent `prepare-frontend`, setting compatibility mode by system property (`vaadin.bowerMode=true` or `vaadin.compatibilityMode=true`) works as well.

Forcing compatibility mode through `@WebInitParam` (or system property `vaadin.bowerMode` after `prepare-frontend`) currently results in bad behavior: npm and webpack start, though the application itself runs in compatibility mode. As the ticket description states, only `vaadin.bowerMode` and `com.vaadin.flow.server.compatibilityMode`) can be used to force this behavior. While this discrepancy  seems wrong, I am not sure that we ought to support setting the mode of operation in this way at all. @Legioth?

**Comment by caalador** [comment]
I guess that the compatibility mode gets overridden due to it being set to the `target/classes/META-INF/VAADIN/config/flow-build-info.json` by the `prepare-frontend` maven goal.
This setting overrides any other settings I expect.

**Comment by caalador** [comment]
The actual problem is in the way we read the configurations.

It works as expected if your servlet definition is:
```

@WebServlet(urlPatterns = { "/*", "/frontend/*"}, name = "infservlet", asyncSupported = false, initParams = {
    @WebInitParam(name = "compatibilityMode", value = "true")
})
```
Else flow will init a servlet for `/frontend/*` which doesn't have any init parameters and it seems that it gets read as last and thus we do not have the `compatibilityMode` flag as true.

**Comment by mcollovati** [comment]
Closing because compatibility mode is not supported anymore in the maintained Vaadin versions.
