### ISSUE TITLE
Investigate enabling npm install in prepare-fronted

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#6403]
There are multiple cases where npm install should have been run earlier
as server startup may have timeouts that are shorter than the downloading
and installation of node_modules see for instance #6369 

Investigate if enabling npm install on the preprare-frontend goal in 
maven frontend `Builder.enablePackagesUpdate(true).runNpmInstall(true)` would be plausible 
(will not cause unexpected problems) as
then we would have the majority of node_modules downloaded and installed
so that we have minimal work left to be done on server startup for the `npm install` part.

**Comment by caalador** [comment]
Another way would be to investigate possible offline npm possibilities that could be used with starter projects: https://addyosmani.com/blog/using-npm-offline/

**Comment by mehdi-vaadin** [comment]
Since we were having timeout errors in TeamCity builds, I have added the following steps to fix them for now:
- `com.vaadin:vaadin-maven-plugin:14.0-SNAPSHOT:prepare-frontend`
- `npm install`

After this issue is fixed, those steps should be removed from [Java 12: Skeleton Starter Spring build](https://bender.vaadin.com/admin/editRunType.html?id=buildType:Flow_StarterTests_NightlyBuilds_Java12SkeletonStarterSpring&runnerId=RUNNER_475&cameFromUrl=%2Fadmin%2FeditBuildRunners.html%3Fid%3DbuildType%253AFlow_StarterTests_NightlyBuilds_Java12SkeletonStarterSpring%26init%3D1&cameFromTitle=) and [Java 11: Skeleton Starter Spring build](https://bender.vaadin.com/admin/editBuildRunners.html?id=buildType:Flow_StarterTests_NightlyBuilds_Java11SkeletonStarterSpring).

**Comment by denis-anisimov** [comment]
>After this issue is fixed, those steps should be removed from

Hmmm.....
I don't think so.
This issue is investigation issue.
The outcome of this ticket is just verification that enable  npm install in the  `prepare-fronted` goal doesn't cause any issues.
I believe you are referring to a ticket which doesn't even exist yet: enable `npm install` in the `prepare-fronted` .
And I wouldn't say that we have to create such ticket. It should be dicussed.

**Comment by denis-anisimov** [comment]
I have not found any issues except that direct enabling `npm install` via `Builder.enablePackagesUpdate(true).runNpmInstall(true)` inside `PrepareFrontendMojo` throws an exception in `WebComponentModulesWriter::writeWebComponentsToDirectory`.
It fails because of check : 
```
if (!outputDirectory.isDirectory()) {
            throw new IllegalArgumentException(String.format("Path provided "
                    + "by parameter 'outputDirectory' (%s) is not a directory",
                    outputDirectory.getPath()));
        }
```
The `outputDirectory` is the `frontend` directory which doesn't exist yet when `prepare-fronted` is executed.
It can be fixed quite easy. I've just removed exception throwing and returned the empty set instead.
Most likely `FrontendWebComponentGenerator` can be just simply disabled in the `prepare-fronted` goal (this class invokes `WebComponentModulesWriter`).

Other than that there are no any issues.
I've checked skeleton-starter and bakery apps. 
No any problems with both of them.
Everything works fine.

Notes about "offline npm" (https://addyosmani.com/blog/using-npm-offline/):
- `npm --cache-min Infinity install vaadin-button` doesn't look working really faster than `npm install vaadin-button`.
- it still connects to the registry
- it also does something in addition to just update: `updated 1 package and audited 16586 packages in 5.838s`

So it doesn't seem that caching helps here a lot.

`local-npm` looks overcomplicated.

Anyway both of these things are can be solved by using `pnpm` instead which uses local repository with cached packages right away.

**Comment by Legioth** [comment]
One thing to notice is that this approach would only slightly hide the issues, but they would still not be fixed in all cases. In particular, there's the case of using Spring Boot either by launching a `main` method or using the Maven setup that you get from start.spring.io since neither of those setups will run `prepare-frontend`.

**Comment by pleku** [comment]
This doesn't look like it would help us improve the situation enough and I feel we should not invest at this currently. We do have other alternatives for improving the startup time or just switch to another tool (#6150 pnpm).

**Comment by Legioth** [comment]
> We do have other alternatives for improving the startup time

The purpose of this change is not to improve startup time. Instead, the purpose is to reduce the risk that the slow startup time leads to nasty errors.

**Comment by pleku** [comment]
>The purpose of this change is not to improve startup time. Instead, the purpose is to reduce the risk that the slow startup time leads to nasty errors.

True. But if I understood the comments correctly, this could help but not necessarily for Spring-boot main method startup times or times when you don't have `prepare-frontend` enabled. 

And at very last there is a comment
>Anyway both of these things can be solved by using pnpm instead which uses local repository with cached packages right away.

Which I, perhaps mistakenly, see as something which should bigger impact on the underlying problem than just moving things around.

**Comment by pleku** [comment]
Apparently we have not actually tested whether or not `Run on Server` will work with Eclipse (and not timeout), so we need to verify that:
- [ ] Test with Eclipse that the change actually fixes the timeout issue
- [ ] Test that "Build the project" in Eclipse which will execute `prepare-frontend` (#6103) doesn't cause any DX issues

**Comment by denis-anisimov** [comment]
Here is the branch with changes that runs `npm install` during `prepare-fronted` goal.
https://github.com/vaadin/flow/tree/6403-install-in-prepare

It has a hack which removes a piece of code. So it can't be used as is.
But I guess the removed code from `WebComponentModulesWriter::writeWebComponentsToDirectory` can be reverted but `withEmbeddableWebComponents(false)` needs to be used in the `PrepareFrontendMojo` class.

**Comment by denis-anisimov** [comment]
Here is a PR for running npm install in prepare-frontend goal:
https://github.com/vaadin/flow/pull/6619

The investigation results:
- running Tomcat via Eclipse servers tab (deploying the project) doesn't help anyhow. I'm getting a timeout error.
- if you do `mvn install` build the project using maven ( build a project just via eclipse doesn't run maven goals , it just compiles the classes) then it indeed helps to avoid a timeout.
- without the "fix" in prepare-frontend goal user is able to deploy the application on the second time because `npm install`  will install already node modules in the first attempt.

So effectively running npm install in prepare-frontend goal doesn't help if you are using only Eclipse actions.
You will need run explicitly run `mvn install`  from Eclipse to be able to deploy from the first time which is not obvious.
Though I'm not sure whether you have to run  `mvn install`  anyway to be able to deploy the project ....
I was not able to get a working application deployed on Tomcat via Eclipse in any way but that's a different issue.
Tested with skeleton-starter project.

The issue with inability to get a working project in Eclipse is related to Tomcat itself: I don't see working tomcat instance at all when I run Tomcat without anything deployed to it. But it should show at least its ROOT default Tomcat info servlet.

**Comment by Legioth** [comment]
> running Tomcat via Eclipse servers tab (deploying the project) doesn't help anyhow. I'm getting a timeout error.

Does that mean that `prepare-frontend` isn't run even though https://github.com/vaadin/flow/blob/922c7ef1c9b27e2c7e9349406f51c1860957de5f/flow-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml#L27 should cause that to happen? Or might it be that it was not triggered in your case if you just used an updated Maven plugin in a project that was already imported in Eclipse and thus never triggered the `runOnConfiguration` condition? If I remember right, `prepare-frontend` is supposed to be run when you import a project into Eclipse or if you manually do Project -> Clean...

**Comment by denis-anisimov** [comment]
Yeah....
Good question.
I don't know.

I have already a project in Eclipse opened.
So may be `prepare-frontend` has not been executed because I already had it opened.
Didn't try to make/import a new project.

**Comment by pleku** [comment]
This investigation ran its course and further developments will be handled separately.
