### ISSUE TITLE
Static content not shown when run as Jar and vaadin.productionMode=true 

### ISSUE THREAD

**Issue by markhm** [vaadin/flow#6415]
My Simple v14-based application does not show/load the static content when I run as JAR in `vaadin.productionMode` and I fail to see where things go wrong. Although I've experienced some instability, in development mode, the frontend works as it should.

I've reproduced this issue in my general purpose [Vaadin example repo](https://github.com/markhm/vaadin_examples).

It contains some examples for including D3js in Vaadin and has an Image logo and localization Images, which are sometimes shown and sometimes not. (The D3js content is also not loaded correctly at the moment, but that is probably related.)

To reproduce the problem, build using `mvn -Pprod clean package`.

Then, observe that running an unpacked version of the application shows the static content correctly. From the project root, run `ant runUnpacked`.

However, when the application is started as jar only, the static content is not shown. This is done via `ant runAsJar` (if needed rerun '`mvn -Pprod clean package`' before).

The url for both examples is: http://localhost:81/app.

I would like to run the application as JAR, so I can use the Windows service wrapper and install it as a service.

I am using:
- OpenJDK "12" 2019-03-19 on MacOS
- Vaadin 14.0.3 (latest)
- macOS 10.14.6 (latest)
- Chrome Version 76.0.3809.132 (Official Build) (64-bit)

I did take note of [this issue](https://github.com/vaadin/flow/issues/5416), but this only seems to solve the problem for one of my projects and the response is puzzling. It seems worthwhile to get to the bottom of this problem. 

Thank you very much for your help.

**Comment by denis-anisimov** [comment]
Hi, it looks like I'm not able to reproduce this....

>However, when the application is started as jar only, the static content is not shown. 

Could you please clarify what's the static content is ?
I see no difference between `ant runUnpacked` and `ant runAsJar`.
I think `ant runAsJar` is the same as `mvn spring-boot:run` actually and this command we are using all the time to work with spring boot projects.

Also your example is quite complicated.
You are registering your own servlet to handle `"/frontend/*"` mapping and then you use 
`frontend` schema to address your resources.
Please note that `frontend` schema is obsolete in V14. You should not use it.
I think you should access your static resources in some other way. 
I see at least two ways: 
- Make the resources available out of the box directly via web (I'm not sure which way it can be done within Jar Spring boot app). E.g. when you run the application via web server (like Jetty) you may set some location as a static web resource folder. It will be served by the _web server_. Currently you are using `VaadinServlet`  to be able to serve static resources in the `"/frontend/*"` mapping and this is as I understand the essence of the issue.
- Use `AbstractStreamResource` (`StreamResource`) in the `Image`  constructor. This will read the file dynamically from the classpath on every request . But this is essentially is the same as having your own servlet : the servlet does the same.

**Comment by denis-anisimov** [comment]
This should probably be moved into spring repo.

**Comment by markhm** [comment]
> Also your example is quite complicated. You are registering your own servlet to handle "/frontend/*" mapping and then you use frontend schema to address your resources.

It may be that I've missed the simpeler way of including and addressing static content. I don't have a specific need for it to be served by the VaadinServlet, I thought I was following the recommended practice.

Where can I read how to configure Jetty to serve the content directly?  🙏🏻

**Comment by denis-anisimov** [comment]
I don't think jetty configuration will help you here.
Because:
- Spring boot uses it's own bundled servlet container (which is Tomcat by default).
- Jetty is able to serve a folder as a static resource dir for WARs. I don't think it works for Jars.


Jetty maven plugin allows to configure static web resources via `baseResource` or 
 `resourceBases ` : https://www.eclipse.org/jetty/documentation/9.0.6.v20130930/jetty-maven-plugin.html
But as I said it won't help you most likely.

I would recommend to search info how to serve static web resources from Jar file.

**Comment by markhm** [comment]
Ok, allow me to take one step back. I don't have a requirement to use Jetty. 

I would like to build separate application packages (e.g. jars) for different environments that can be run on a Windows server and that can easily be maintained by an IT support team that does not have much Java or AppServer expertise. I was planning to use the Windows Service Wrapper for this, so the service can be easily restarted and is woken up automatically in case the server reboots. See these:

    https://www.baeldung.com/spring-boot-app-as-a-service
    https://github.com/kohsuke/winsw

As only constraint, I would like to avoid that I my runtime environment (whether my application is packaged as jar, war or run just from `mvn spring-boot:run`) expects the static content to be in a different place, based on which way the application is started. I don't want if-statements in the code for this. 

If you tell me running the application via `mvn spring-boot:run -Pprod` is really the recommended/only way to start a Vaadin Spring Boot application, that could be fine. Only downside will then be that I need to zip the package en when building and unzip on the server where it will be run. 

Btw: I got pointed in the direction of resolving an image location by Menu class in the Vaadin Spring Boot starter that was generated from [vaadin.com/start](https://vaadin.com/start), see line 50. 

Curious if I am missing anything. Thanks again for your thoughts.

**Comment by denis-anisimov** [comment]
I think we are going to a different direction now.

I suggest to focus here on a bug description.
The first thing which I've mentioned: I'm not able to reproduce the ticket.
I don't see the exact description of the current behavior and the expected behavior.
As I said: results for two executions looks the same.
So may be I'm missing something. 
Please describe the current result and the expected one in details so that it's possible to verify 
the bug.

The second is: you are using `frontendServletBean`. This is an extra thing which is a part of your application and not something works out of the box. It introduces additional extra part which may be a reason of the failure.

The application is too complicated for the ticket. Would be nice to have the issue localized.
So if something doesn't work it means that:
- either `VaadinServletService.getCurrent().resolveResource` doesn't return a correct value ( may be `null` ? )
- `VaadinServletService.getCurrent().resolveResource` returns a correct value but `frontendServletBean` doesn't return the resource using the resulting URL (which is based on `VaadinServletService.getCurrent().resolveResource` return value).

So in once case this is issue with `frontendServletBean` (which is a part of the app) and another case this is a  `VaadinServletService.getCurrent().resolveResource` issue.
That's the only meaningful thing here in this ticket.

Other thing is:
I believe `mvn spring-boot:run -Pprod` should behave in the same way as your `ant runAsJar` task.
I cannot imagine any difference: it doesn't unpack anything or sure.
That's why 
```
Only downside will then be that I need to zip the package en when building and unzip on the server where it will be run.
```
you don't need to do it.
But this is rather discussion about spring-boot than about the potential bug.

```
Btw: I got pointed in the direction of resolving an image location by Menu class in the Vaadin Spring Boot starter that was generated from vaadin.com/start, see line 50.
```
vaadin.com/start is just a web page. I believe you refer via line 50 to something else than a web page.

I would recommend to use `http://vaadin.com/forum/` to ask specific questions .

**Comment by markhm** [comment]
Ok, thank you for your clarification, much appreciated. I will use your remarks to modify my setup first and try to work around the problem I have with starting the application as jar. So I will close this issue for now. 

NB: The line 50 is in the Menu class of the application that is generated by Vaadin Start. When you  download the package for a new Spring Boot application, you should find it in the -ui part of the application.
