### ISSUE TITLE
Add caching to classpath scanning when looking for V14 annotations

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6426]
When scanning for annotations (`@JsModule`, `@CssImports`, etc), `WebComponentExporter`, `UIInitListener`, and `VaadinServiceInitListener`, the scanned files should be added to a scan result cache.
When we need to scan the files again after changes, the scanner would use the cache to avoid rescanning files that have not changed since the last scan.

Potential approaches (non-exclusive):
- Improve caching for scanned files / jars
- force add-ons to add metadata for included frontend dependencies
- Use another way of scanning for Spring Boot applications

Result:
- What is the impact on the repeated build use-case
- What is the estimated amount of work required to achieve caching
- Is it possible to reliably identify and cache scanned files at all?
- Scanning granularity: what is good enough?
  - File-level
  - Jar-level
  - Other options?
- Can we trust on the classic file system, or do we need to account for JBoss' vfs and similar anomalies
- Are the discovered approaches also Spring-compliant (make Spring super fast)?

**Comment by joheriks** [comment]
**Observation**. Given a root class `C`, `FrontendVisitor` scans `C` and all classes directly and transitively referenced (through annotations and fields) from `C` in order to populate an `EndPointData` instance with JS modules, JavaScript scipts, and CSS imports. Root classes are the `@Route`-annotated classes as well as all classes implementing `UIInitListener` and `VaadinServiceInitListener` in the project. The set of root classes is small compared to the set of transitively traversed classes.
 
**Observation**.  Scanning can be slow in large projects since it requires opening jars and traversing bytecode. Even in a small project like beverage-buddy it takes over 1 second on a modern laptop.

**Proposed solution**. After scanning, cache the resulting `EndPointData` instance for each root class `C` in a local file (in the project directory) for fast retrieval. In addition, cache the location URL (`jar://` or `file://`) of all transitively traversed jars and the time when the cache entry was crated. Cache structure:
```
C(1) -> { EndPointData(1), [ Loc(1)(1), ..., Loc(1)(m(1)) ], Timestamp(1) }
⋮
C(n) -> { EndPointData(n), [ Loc(n)(1), ..., Loc(n)(m(n)) ], Timestamp(n) }
```

Pseudocode for computing the `EndPointData` instance for a root class C:

```
if C in cache:
	cachedEndPointData, locs, timeStamp = cache(C)
	useCached = true
	for loc in locs:
		if lastModified(loc) > timeStamp:
			useCached = false
	if useCached:
		return cachedEndPointData
endPointData, jars = traverse(C)
cache(C) := { endPointData, jars, now() }
return endPointData
```

In the above, `lastModified(loc)` stands for the last modified date of the file at `loc` and `now() for the current time.

**Comment by joheriks** [comment]
**N.B. 1**. A large project will be needed to verify the benefit of the cache. There is a risk that the overhead of managing and loading the cache will offset the benefit in tiny projects, so it may make sense to only activate caching when the number of traversed classes exceeds a given threshold. 

**N.B: 2**. When several roots share a common dependency, there may be a lot of repetition in the transitive location lists. If this becomes a problem, consider storing a dependency DAG as a separate cache entity instead.

**N.B. 3**. Spring uses another method for collecting the classes to be scanned. The performance of this stage has been improved via https://github.com/vaadin/spring/pull/490

**Comment by ujoni** [comment]
Regarding the granularity of the cache, would it be jars or individual files? Or should we test to see if there are any real benefits to either approach? There is a good change that the jars contain a whole bunch of files that have not actually changed between builds, especially with larger libraries.

`JarEntry#getLastModifiedTime` seems to give accurate timestamps (based on very limited testing). I would assume that most libraries do not mangle that data.

**Comment by joheriks** [comment]
I was thinking jar level, as it is easier to implement and could be refined (keeping the same cache structure) if finer granularity is deemed necessary later. With file level caching the cache management will become more involved (opening jars and checking file timestamps) which could reduce performance improvement.

To keep this option open, I think we should implement *N.B.2* above, since increased granularity will make the location lists considerably longer.
