### ISSUE TITLE
CCDM: Provide a way for Flow to hook in to the index.html generation

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#6431]
For a Java-only (or Java-mostly) application that uses the new index html generation servlet and routing through the client-side, it would be beneficial if the initial UIDL to show could be embedded in the index.html page so that one redundant round trip can be avoided.

For cases that use `@PreserveOnRefresh`, it would instead be beneficial to embed the initial logic that extracts `window.name` and sends that to the server so that two round trips would be enough rather than 3 that would be needed to first load index.html, then load the empty Flow UI with the `window.name` extraction logic and only then loading the actual view contents.

**Comment by manolo** [comment]
I did some tests to see whether this feature should be implemented

### Measurements
#### fast network (without cache)
- regular server-bootstrapping: 4 req, 985KB size, 348ms total,  357ms load
- client-bootstrapping without initial: 9 req, 996KB size, 158ms total, 30ms load
- client-bootstrapping with initial: 8 req, 993KB size, 166ms total, 194ms load
#### slow 3G network (with cache)
- regular server-bootstrapping: 4 req, 985KB total, 33.9KB transferred, 2770ms total, 2790ms load
- client-bootstrapping without initial: 9 req, 986KB total, 34.7KB transferred, 4800ms total, 2050ms load
- client-bootstrapping with initial: 8 req, 993KB total, 31.7KB transferred, 2710ms total, 2750ms load

### Conclusions
#### Pros
 - One additional request, save 2sec in slow networks, 500ms in 3G.

#### Cons
 - Server session and UI is created in index.html even tough the user might never navigate to a server route
 - We cannot set headers to cache the index.html
 - In PWAs when offline, we cannot cache the index host page because contains incorrect uidl, instead we need to provide an offline page.

### Implementation
The PR for the implementation does not activates the feature unless the user adds the following configuration:

```
# src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
com.vaadin.flow.server.ClientIndexInitialListener
```
In addition user might extend the `ClientIndexInitialListener` for customising which routes adds the UIDL

```
class MyInitialListener extends ClientIndexInitialListener {
        @Override
        public boolean isValidRoute(VaadinRequest request) {
            return request.getPathInfo().equals("/");
        }
}
```

**Comment by manolo** [comment]
I did some experiments with beverage app in jMeter to request the index.html in production with and without the `vaadin.initialBootstrap` set.

JMeter test was configured to run a set of users with a ramp time of 10 seconds without looping.

The result of maximun number of simultaneous users without causing any error was:
 - index.html without initial Uidl: 6000 users, throughput 499 hits/sec.
 - index.html including initial Uidl: 1500 users, throughput 142 hits/sec.

Jetty server for the first case was consuming in my local machine 1.1GB during the test, whereas in the second one it was taking 4.3GB.

The main reason is that returning the hosting application page with the fully ui set, in this case the reviews view of beverage

<img width="1112" alt="no-session-index" src="https://user-images.githubusercontent.com/161853/65855939-89379e80-e360-11e9-8d7a-378b7a64698a.png">
<img width="985" alt="session-index" src="https://user-images.githubusercontent.com/161853/65855940-89379e80-e360-11e9-97dc-b92cfa52f73f.png">

**Comment by Legioth** [comment]
So if we assume that the user would otherwise never end up loading a server-side view, then the there's around 280% overhead.

What if we instead assume that the user will still end up on a server-side view? Then the primary question is how much the experience of the individual user is slowed down by having some UIDL generated and downloaded that they still end up not needing.

**Comment by Legioth** [comment]
For the initial set of measurements, I would assume that `regular server-bootstrapping` and `client-bootstrapping with initial` are essentially the same thing: load a HTML payload that contains the initial UIDL and then load some JS to actually make sense of that UIDL. I don't understand why there would be almost a 2x difference between those two in the case with a fast network.
