### ISSUE TITLE
Create a mega bundle during development time.

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#6462]
During development time the size of the client bundle doesn't matter 
as much as the startup time.

To make startup faster we should in development mode generate the 
`generated-flow-imports.js`  file using the components found during
annotation scanning and skip byte code scanning.

This would mean that we may have un-used components in the bundle
during development time and development build might work differently
than a production build when the production build uses a component 
that has been excluded by byte code scanning.

Production mode should be able to generate a fallback chunk for cases
where used components are not found #5623

**Acceptance criteria:**
 - Development mode should build the generated imports using annotations found
   - Flag to run byte code scanning in dev mode should be added
 - Production mode should use byte code scanning
   - Production mode should with a flag skip byte code scanning
   - Production mode should support a fallback chunk if component is not in the main bundle

**Comment by Legioth** [comment]
Note that #5623 is much more general than the quite basic fallback chunk functionality that would be needed to cover this case.

**Comment by pleku** [comment]
So to clarify some details:
- npm install will happen only initially and when new component dependencies appear to classpath? 
- Webpack will be only started once when the generated import is missing and then it is shut down?
- When the user restarts the server or there is a context reload, everything is scanned again but Webpack is only started when new things are discovered (same as npm)
- what happens when one is manually editing js modules that are in the project, like using designer? How will those changes go live without Webpack (or is it still started)?
- how can the user opt in for the old mode when in development? I'd presume the mega bundle would be the default (at least for new projects) as it is faster

**Comment by caalador** [comment]
> npm install will happen only initially and when new component dependencies appear to classpath?
npm install will be run initially and when components are added

> Webpack questions:
Webpack in dev mode will work as now. So we will run up the dev server that will catch all changes as now.

> how can the user opt in for the old mode when in development? 
Flag should be made available to opt in for byte code scanning in dev mode.

**Comment by Legioth** [comment]
I think there's some confusion with the terminology here. "Mega bundle" here refers to a bundle that is larger than what might be absolutely necessary. It's not the same as a "precompiled bundle".

A mega bundle would not change anything with regards to running npm or webpack. The only thing that would change is that preparing to start webpack in dev mode would be faster because we would skip the step that find which parts of the classpath are actually reachable and instead include everything.

Starting webpack only on demand by using a precompiled bundle would require some additional thinking, especially when it comes to the application's own frontend files, and even more so when taking #6347 into account. This is already discussed in https://github.com/vaadin/flow/issues/6248.
