### ISSUE TITLE
Dynamically added components don't work

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6486]
I'm migrating my Vaadin 13 (Bower) app to 14 (NPM), and I have an issue with a layout which is shared by different apps and it's configurable by each app.

This is the layout:

```java
public class MainLayout extends AppLayout implements RouterLayout {

    public MainLayout(@Qualifier("branding") Optional<Component> branding,
            @Qualifier("navigation") Optional<Component> navigation,
            @Qualifier("footer") Optional<Component> footer) {
        branding.ifPresent(this.getBranding()::add);
        navigation.ifPresent(this.getNavigation()::add);
        footer.ifPresent(this.getFooter()::add);
    }
}
```

and this is how an app configures it:

```java
@SpringBootApplication
public class Application extends SpringBootServletInitializer {

    @Bean
    @Scope("prototype")
    @Qualifier("branding")
    public Component branding() {
        return new AxiansLogo();
    }
}
```

Problem is, this way the dependencies for `AxiansLogo` aren't fetched and it's rendered without its Shadow DOM.

I know there is `@Uses`, but the layout doesn't know which components will be injected! I have many cases like this, as the application is very modular and a lot of components are injected this way.

**Comment by javier-godoy** [comment]
Related to #5623

**Comment by Legioth** [comment]
In the Vaadin 13 app, did you define any custom code splitting for the production build (`<fragments>` in the configuration of `vaadin-maven-plugin`)?

If you didn't do anything like that but rather allowed everything from the classpath to be included in the production bundle, then https://github.com/vaadin/flow/issues/6481 will most likely fulfil your needs. The plan is to get that one fixed within a week or two.

If you did use code splitting, then the issue that you're looking for is most likely https://github.com/vaadin/flow/issues/5537. That functionality is a more convenient replacement for `<fragment>` that we were planning for Vaadin 14 but had to cut out of the scope. We are still hoping to get it implemented sooner rather than later, but I cannot give any more exact update on the schedule right now.

**Comment by denis-anisimov** [comment]
This is already fixed via using full CP scanning in dev mode and fallback chunk in production mode.
