### ISSUE TITLE
Remove all things marked as `@deprecated` in 3.0 Flow

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6510]
Remove all things annotated with `@deprecated` and all Bower mode related code for Flow 3.0 release.

**Comment by pleku** [comment]
### Acceptance Criteria
- [ ] No deprecated API in Flow 3.0
- [ ] Javadocs for deprecated API in 2.2 is updated to mention that "This is removed in Flow 3.0 (Vaadin 15)."

As a note for doing this task, it might be that not all deprecations are yet picked to the 3.0 (ccdm) branch, so one should make sure all deprecations from master branch (2.2 currently) are removed in 3.0 branch.

**Comment by mehdi-vaadin** [comment]
There are classes and methods in `ccdm` (Flow 3.0) branch that were deprecated in `ccdm`. E.g. `BootstrapListener` is deprecated in favor of `IndexHtmlRequestListener` or `BootstrapPageResponse` is deprecated in favor of `IndexHtmlResponse`. Should we just remove them instead of making them deprecated?

@vlukashov commented
>V15 comes with a 'V14 compatibility' mode where the deprecated APIs still work as in V14. For this mode to exist these deprecated APIs need to remain.
It's another question how many users would be using the 'V14 compatibility' mode in V15, but for now we assume it's needed.

@Legioth commented
> Might make sense to have the new compatibility mode report itself through the usage statistics system?

So, I won't remove the above mentioned deprecated things for now.

**Comment by mehdi-vaadin** [comment]
`MultiSelectionEvent.getNewSelection` which was deprecated in #7346 should also be removed.

**Comment by Legioth** [comment]
Why should we remove things that haven't been out as deprecated in even a single release?

**Comment by mehdi-vaadin** [comment]
By the time we release V15, 14.2.0 or 14.1x will have been released including that deprecation. Isn't this enough?
