### ISSUE TITLE
Shortcuts: multiple components to listen on

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#6570]
`ShortcutRegistration#listenOn` is very useful to fence a shortcut to a specific component, e.g. a field. It would be more useful if it would accept a var-arg arguments, for example:

```java
var shortcut = Shortcuts.addShortcutListener(this, button::click, Key.ENTER);
shortcut.listenOn(usernameField, passwordField);
```

**Comment by pleku** [comment]
### Acceptance Criteria
- add the var-args API as proposed for listening to multiple components
- add unit tests that validate that listeners are set properly and that unregistering the listener works e.g. `ShortcutRegistrationTest`

**Comment by mehdi-vaadin** [comment]
Since after this, we will have multiple `listenOnComponent`s and therefore multiple owners for `ShortcutRegistration`, the [`getOwner`](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/ShortcutRegistration.java#L367) method should be deprecated and a new method (`getOwners`) should be introduced.
