### ISSUE TITLE
Return Optional instead of null

### ISSUE THREAD

**Issue by hezamu** [vaadin/flow#664]
Return `Optional` instead of null everywhere, eg. in `getValue()` calls.

Enable this

```
String msg = textInput.getValue().map(value -> "Hello " + value + "!").orElseGet("Don't be shy");
greeting.setText(msg);
```

instead of forcing our users to do this:

```
String value = textInput.getValue();
if (value == null || value.isEmpty()) {
    greeting.setText("Don't be shy");
} else {
    greeting.setText("Hello " + value + "!");
}
```

Null checks are a code smell in Java 8, and forcing if-else checking opens up the door for bugs.

**Comment by mvysny** [comment]
I would actually strongly advise to NOT to use Optionals:
1. Kotlin properties won't work with such fields (since setters take String but getters produce something else)
2. The class is definitively not intended for use as a property of a Java Bean: https://stackoverflow.com/questions/29033518/is-it-a-good-practice-to-use-optional-as-an-attribute-in-a-class

**Comment by mvysny** [comment]
For example `Component.getId()` returns `Optional` while `Component.setId()` takes String. This duality borks Kotlin's `property` mechanism and hence Kotlin thinks there is just a read-only property `id` of type `Optional<String>` - it ignores the setter since it is of different type.

I believe Optional is a misuse in this case since according to https://blog.jetbrains.com/idea/2017/08/code-smells-null/ this is

> 1. Value was never initialised (whether accidentally or on purpose)

In this case the use of Optional is discouraged.

**Comment by pleku** [comment]
I'm going to merge this issue to #3801 in case we ever get to improve the APIs or add features for better reactive/functional programming support.
