### ISSUE TITLE
support the `generate-openapi-spec` goal in DevModeHandler

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6642]
Include into the Vaadin `DevModeHandler` for dev builds the following:
 - scan the sources for the `@VaadinService` classes (can be copied from Connect)
 - generate an `openapi.json` spec file (can be copied from Connect)
 - watch for changes in the source files affecting the `@VaadinService` classes and re-generate the `openapi.json` spec file

**Comment by manolo** [comment]
As I explained in the grooming, watching sources is not needed when using DevModeHandler because now the workflow is
- run the project in dev-mode, it runs `DevModeHandlerInitializer` that starts a new `DevModeHandler` instance, and runs `webpack-dev-server` in backup
- Change a `.java` file
- IDE compiles it and writes `.class`  to the `target/classes` folder
- Servlet container with hot-reload enabled restarts the server context
  - spring projects need the `spring-boot-devtools` dependency
  - jetty projects need `scanIntervalSeconds` set
- `DevModeInitializer` is run when servlet context reloads and run updaters
- `webpack-dev-server` instance running in background is reused

Note that changing a `frontend` file it should not fire a servlet restart, it's webpack that looks for changes and recreates bundles
