### ISSUE TITLE
define the authentication flow for Connect client in V15

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#6772]
1. How does the client know if the user is logged-in or not?
    - The client needs to know this to indicate in the UI that some action may require authentication.
2. If there are no server-side views, how would a server-side principal be created?
    - This principal is needed because #6754
3. Whether or not connect client should provide a login form?

Investigation, time box: 2 days

**Comment by manolo** [comment]
## CCDM Authentication


### Abstract

CCDM Connect handles ajax requests by trusting in spring MVC. The entry point of any request is the method  `VaadinConnectController#serveVaadinService` which visits application classes to execute the most appropriated service for the `service` requested.

After `serveVaadinService` discovers the business service method to execute, it should check for permissions before executing and returning the result.

#### Permissions

CCDM Utilizes the a set of annotations with the following priority order `@DenyAll` `@AnonymousAllowed` `@RolesAllowed` and `@PermitAll` 

Permissions are checked through the `VaadinConnectAccessChecker#check` method, returning an error `String` in the case of unsuccessful.

It uses `SecurityContextHolder` and `OAuth2Authentication` classes for do the checking.

#### Client

Connect client has the  `client.credentials` callback for asking for `user/password` pair when a `401` response happens.

Once the callback retrieves the login information, it calls the `connect.authenticateClient` method that utilizes oauth2 mechanism for authenticating the user.


### Implementation

#### Server

Flow server needs the `JSESSIONID`, thus we need to implement a way for automatically checking permissions against session.

Basically we need to modify `VaadinConnectAccessChecker#check` so as when in a Spring app, it asks `SecurityContextHolder` for the `OAuth2Authentication` to check permissions, otherwise the checker gets the `HttpServletRequest#getUserPrincipal()` to do the verification.

It's application responsability to either configure Spring security, or provide a way to set the `UserPrincipal` to the request. 

In both cases, if there is no authetication configured, only `@AnonymousAllowed` services would work.

When using regular session for authetication:
  1.- The application can use traditional Vaadin UI form for asking `user/password`, checking in server side, and storing the result in session.
  2.- The application can provide a `login(user, password)`  service annotated with `@VaadinService` and `@AnonymousAllowed` so as client-side views can authenticate using REST services.


#### Client

We should keep `client.credentials` callback for having a way to ask for `user/password` pair, or just to show a message, or redirect to a login form.

In addition we need a `client.authenticate` promise, that provides a way for calling a flow REST service for setting the `UserPrincipal`


#### Use cases

```
User -> BrowserApp -> server-route -> authenticated? 
  -> yes -> flow view
  -> no  -> server login-form

User -> BrowserApp -> client-route -> client view -> service request -> authenticated?
  -> yes -> 200
  -> anonymous -> 200
  -> no  -> client.credentials -> user/password -> client.authenticate -> server session -> 200
```

**Comment by vlukashov** [comment]
**Summary**:
1. How does the client know if the user is logged-in or not?
    The `client.checkLoggedIn()` method would be used for that. It currently requires the OAuth2 `/token` endpoint. With the session-based auth this endpoint is not available, so in order to implement this method there needs to be a new endpoint that returns the result of server-side check for `UserPrincipal`.
2. If there are no server-side views, how would a server-side principal be created?
    The application developer would have to create a client-side login form (or any other way to get user's username and password), then there are the `client.login()` method and the `client.credentialsProvider` callback which together give the connect client user credentials. Connect client uses its internal method `client.authenticate()` to submit the credentials to the backend (currently relies on the OAuth2 `/token` endpoint). A replacement for the `/token` endpoint needs to be implemented in a way that it creates a User Principal in a session on the backend.
3. Whether or not connect client should provide a login form?
    No, connect client should not provide a login form.
    However, if the login happens through a server-side view, Connect client should have an alternative for the `credentialsProvider` API that accepts a session ID and uses that in subsequent RPC calls.
