### ISSUE TITLE
Maven Flow Plugin: prepare-frontend incorrectly states that it populates the node_modules folder

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#6855]
- Description of the bug

The plugin.xml for Vaadin Maven Plugin states for the prepare-frontend goal that

> This goal checks that node and npm tools are installed, copies frontend
resources available inside `.jar` dependencies to `node_modules`, and creates
or updates `package.json` and `webpack.config.json` files.

It's not true - the `node_modules` folder is not created.

- Minimal reproducible example

1. git clone skeleton starter
2. mvn vaadin:prepare-frontend

- Expected behavior
- Actual behavior
- Versions:
    - Vaadin / Flow version: 14.0.12
    - Java version: 8

**Comment by denis-anisimov** [comment]
skeleton starter doesn't contain any frontend resources that needs to be copied.
That's why `node_modules` is not created.

In fact I don't see this is as an issue since `This goal checks that node and npm tools are installed, copies frontend
resources available inside .jar dependencies to node_modules` doesn't say that the `node_modules` is created.
It says that it copies frontend resources. And it really copies if they exist.

I think I close the issue since I don't see any error.
If you think that the sentence needs to be clarified please reopen.

**Comment by mvysny** [comment]
I see, so by the "frontend resources available inside .jar dependencies" is not meant the npm JS dependencies (which are also copied to node_modules, but by VaadinServlet in case of development mode when the app is launched), but only the contents of the `META-INF/resources/frontend` folder?

**Comment by denis-anisimov** [comment]
Yes and no.

contents of the `META-INF/resources/frontend` : yes.

It's not `VaadinServlet` who creates `node_modules`. It's `npm install`  (which is called within the servlet in dev mode, yes, but it's an external tool and process).

In one case the logic is really inside our code (copy).
In another case it's just a way how external `npm`  tool  works: we don't affect anyhow it.
The only thing is done is generating files with info about modules and packages (that info is read from annotations): there are no any resources in jar files.
