### ISSUE TITLE
Query API should mention that Query.getLimit() is depending on Grid's page size

### ISSUE THREAD

**Issue by mkemmerz** [vaadin/flow#6996]
Today I had some struggle with lazy loading data for my view. Basically all I wanted to do is set a custom value for the amount of items that are fetched at once by the DataProvider.

My first issue was how is the value for query.getLimit() set? It was 50 but I was not able to track down where this number was coming from.

I talk about this method:

```
DataProvider.fromCallbacks(
                        query -> {
                            int offset = query.getOffset();
                            int limit = query.getLimit();
                            List<SomeObject> valueToReturn = data.subList(offset,limit+offset);
                            return valueToReturn.stream();
                        },
                        query -> list.size() );
```

More or less by luck I found out that the Grid's page size is the default value for query.getLimit() which indicates how many items are fetched at once.

new Grid(30) -> query.getLimit() returns 30
new Grid() -> query.getLimit() returns 50 because 50 is the default page value

The [Query API](https://vaadin.com/api/platform/14.0.13/com/vaadin/flow/data/provider/Query.html) mentiones that the object is immutable so how do you change the value for getLimit()?

This dependency is mentioned in the Grid API but not in the Query API.
I think the dependency from Query.getLimit() to a Grid's pagesize should also be mentioned on the Query side so it is clear that the amount of items that are fetched can be adjusted.

**Comment by mehdi-vaadin** [comment]
Hi @mkemmerz, thank you for creating this issue.

> The Query API mentiones that the object is immutable so how do you change the value for getLimit()?

The component, e.g. `Grid`, that uses the `DataProvider` creates a new `Query` object and set the limit via its constructor each time it needs to request data and passes it to `DataProvider::fetch`. It may be more complicated in practice though.

>I think the dependency from Query.getLimit() to a Grid's pagesize should also be mentioned on the 
Query side so it is clear that the amount of items that are fetched can be adjusted.

I think since `Query` is used in several components and the limit is set from different places, it doesn't sound good to mention it in the Javadoc in `Query` class. On the other hand, the Javadoc of `Grid`'s constructor explains it well. See [this](https://vaadin.com/api/platform/14.0.13/com/vaadin/flow/component/grid/Grid.html#Grid-int-). The only place where we can improve our documentation is the document [Showing a List of Data with Data Providers](https://vaadin.com/docs/v14/flow/binding-data/tutorial-flow-data-provider.html). It should be mentioned that the `pageSize` of `Grid` determines the `limit` of `Query`.

**Comment by mkemmerz** [comment]
Thanks for the fast reply @mehdi-vaadin . 
The point 'Lazy Loading Data from a Backend Service' sounds like a good place for this so it would be clear that you can manually set the amount of items that are fetched from the backend.
