### ISSUE TITLE
Switching between npm and pnpm seamlessly

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7042]
Acceptance criteria:
- A project can be switched between using `pnpm` (the default) and `npm` (by setting the parameter `disable.pnpm`)
- Depending on the outcome of #7018 and #7021, we should check whether we can automatically clean a project that has files in the wrong mode or show a warning asking the user to manually clean
- Add a Bender job to check that the switching works in both directions (`pnpm` -> `npm` and `npm`  -> `pnpm` )

**Comment by denis-anisimov** [comment]
Two bender builds are created :
- Flow / PrivateStarter / TestsSwitch between PNPM and NPM
- Flow / PrivateStarter / TestsSwitch between NPM and PNPM

In both cases temporary steps are required:
- `package.json` removal 
- `package-lock.json` removal 

This issue is extracted to https://github.com/vaadin/flow/issues/7113
