### ISSUE TITLE
Thread per user session rather than per request

### ISSUE THREAD

**Issue by lucienbanholzer** [vaadin/flow#7067]
Dear vaadin support,

I am facing the following issue : 

when opening two tabs of my application in the same browser, the second request (ie the second page opened in the second tab) wait for the first one to finish before being processed by the framework.

Seems that there is a single thread per user session instead of one per request. 

Don't even sure this a bug or something that can be configured but I didn't find any topic about that in the official documentation neither than in forums.

To test it on a clean project I am using https://vaadin.com/start/latest with no custom config at all, 
I just modified the MainView like this : 

`@Route
@PWA(name = "Project Base for Vaadin Flow with Spring", shortName = "Project Base")
public class MainView extends VerticalLayout {

    public MainView() throws InterruptedException {

        Thread.sleep(8000);
        Label test = new Label("test");
        add(test);
    }
}`

and add a second view : 

`@Route("test")
public class View2 extends VerticalLayout {

    public View2() {
        Label test = new Label("test");
        add(test);
    }

}
`

To test I open two tab : try to access "/" in the first one and right after try to access "/test" in the second one. I have to wait 8 s to get the display on both pages.

Thanks a lot for your help.
Best regards,
Lucien

**Comment by Legioth** [comment]
The HTTP session is indeed the unit of concurrency in Vaadin. The reason for this is that each request also updates some session-scoped metadata that isn't safe to update concurrently from multiple threads.

Most of the state that is modified by a typical request is specific to the component tree that is rendered in any given browser tab (technically, a `UI` instance). We could in theory have two separate levels of locking where the session is only locked for short periods of time while most operations would be protected by a UI-level lock. We have chosen to not do it in that way because it would add lots of complexity and still not solve concurrency issues happening within the same UI instance.

Instead, it's recommended to schedule any slow processing on a separate thread that doesn't hold the session lock, and then use either polling or push to allow the results of that processing to be delivered to the browser. You can see e.g. https://vaadin.com/docs/v14/flow/advanced/tutorial-push-access.html or https://youtu.be/uSd5TXTL7ro?list=PLcRrh9hGNalnM3rB0spaaMUDFU_Bxz_BY for more information on how to do that.
