### ISSUE TITLE
onEnabledStateChanged is not called for child of non-component virtual child

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#7085]
When a component has a virtual child which isn't mapped to a component, then children of the virtual child element will not get any `onEnabledStateChanged` notifications when the enabled state of the parent component is changed.

```
@Route
public class Test extends VerticalLayout {
    public Test() {
        Div parent = new Div();

        Button button = new Button("Button") {
            @Override
            public void onEnabledStateChanged(boolean enabled) {
                System.out.println("On enabled state changed: " + enabled);
                super.onEnabledStateChanged(enabled);
            }
        };

        Element wrapper = new Element("div");
        parent.getElement().appendVirtualChild(wrapper);
        wrapper.appendChild(button.getElement());

        add(parent,
                new Button("Toggle enabled state",
                        event -> parent.setEnabled(!parent.isEnabled())),
                new Button("Log enabled state",
                        event -> System.out.println(button.isEnabled())));
    }
}
```

The `onEnabledStateChanged` invocation will happen as expected if doing any of these changes:
* Map a component to the virtual child: ` Element wrapper = new Div().getElement();`
* Append as a non-virtual child: `parent.getElement().appendChild(wrapper);`

This seems to be a regression or variation of https://github.com/vaadin/flow/pull/6315.

**Comment by denis-anisimov** [comment]
This issue is quite related to the #6315 from one point of view : the scenario is quite similar.
Except that there is no explicit state mutation in the #6315 : instead "attach" happens which should trigger the state change machinery.
This ticket has explicit mutation of "enabled" state (component is already attached).

So scenarios are similar but the code which is involved in handling is totally different.
Also the code which should be Element API based knows something about Component which is totally different layer of API.
This mixture and code split makes it extremely hard to maintain.

**Comment by Legioth** [comment]
Isn't the actual root cause that `Component.getChildren()` doesn't consider virtual child elements?

**Comment by denis-anisimov** [comment]
No no no , please don't mix this .
It started to go in a crazy direction.
Virtual child is not a child for sure. Considering it as a child will cause problems with index of the child.

This is the very good example how a feature introduced for one purpose with one usecase went of the control .......

**Comment by Legioth** [comment]
The problem is that it breaks the invariant that the component is a child of its own parent: 
```
component.getParent().ifPresent(
  parent -> Assert.assertTrue(parent.getChildren().anyMatch(
    child -> child == component)));
```

**Comment by Legioth** [comment]
What if there would be a separate overload of `getChildren()` that also includes virtual children?

(Yes, I know this is the wrong place for such discussions).

**Comment by denis-anisimov** [comment]
I suggest do not discuss this here.

No, the actual root cause has no anything to the fact that virtual child is not a child.
The root problem is using Component API which is another layer (higher abstraction layer) in Element API.
It's OK to use `StateNode`  in the `Element` impl but it's not OK to use `Component` in `Element`.
And that's the root: `Element` doesn't have to have a paired component which has been considered as a condition to stop traversing children.

`Element`  should fire an event and `Component`  should listen this event. So that `Element` doesn't know anything about `Component`. The dependency should be reversed.

Issue with considering virtual child as a child is out of the scope of this ticket.
It has sense to make a separate ticket about this but I don't see a proper solution for this anyway.
I agree that invariant is broken but as I said: something will be confusing anyway.
