### ISSUE TITLE
Error when stats.json is requested from external URL in local not with port 8080

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7134]
When `stats.json` is requested from an external URL in development mode with a port other than 8080 the following error occurs.

```
Failed to retrieve stats.json from the url http://127.0.0.1:8080/vaadin-portlet-static/VAADIN/config/stats.json.
```
It happens for example in the [Address Book Portlet Demo](https://github.com/vaadin/addressbook-portlet) if the port of tomcat server is changed in `server.xml`.

It seems that the following [line](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendUtils.java#L618
) in `FrontendUtils` class is the cause of this error. Because the hard-coded port of `8080` is used. 

```Java
    private static String getHostString(VaadinRequest request) {
        String host = request.getHeader("host");
        if (host == null) {
            host = "http://127.0.0.1:8080";
        } else ...
    }
```

The expected behavior is to find the port from the request and create the host string based on that instead of using hard-coded `8080`.

#### Versions
- Vaadin `14.2.0.alpha1`

**Comment by mehdi-vaadin** [comment]
One solution is that instead of returning `null` in `VaadinPortletRequest::getHeader`, when the header name is `host` the correct value is returned.

**Comment by caalador** [comment]
The correct thing to do would be to actually set the host string as full target path.
As noted in the documentation [external stats](https://github.com/vaadin/flow-and-components-documentation/blob/56b3d5ff48caf7f1e3162bda161076b7e272c39f/documentation/portlet-support/portlet-05-creating-multi-module-portlet-project.asciidoc#retrieving-frontend-resources-from-the-static-asset-artifact) 
NOTE! `If your web server is mapped to a different port, provide the full URL instead of a relative URL.`

**Comment by mehdi-vaadin** [comment]
Thanks @caalador. I didn't notice that. But, then the user has to handle different URLs for development and production modes.
