### ISSUE TITLE
RouterLink reuses UI/layouts while Anchor causes full-reload

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#7156]
Vaadin 14.1.2. It is not clear why RouterLink doesn't perform a full UI/layout reload when navigating, while an Anchor does.

Imagine that I have a view mapped to "foo"; RouterLink pointing to FooView emits `<a href="foo">` in the browser DOM and correctly reuses current UI/layouts. Anchor pointing to "foo" emits the very same DOM `<a href="foo">`  but causes full bootstrap+UI+layout instantiation, throwing away old instances and fully refreshing the page.

I believe that Anchor should behave the same way as RouterLink in case of local links.

**Comment by caalador** [comment]
RouterLink automatically contains the attribute `router-link` which makes it behave so that it doesn't reload the page. You can add the same attribute to the Anchor and it will work the same.
https://vaadin.com/docs/v14/flow/routing/tutorial-routing-navigation.html#using-standard-href-links
This is by design as such and the reload vs page update is done on the client depending on the attribute.

**Comment by mvysny** [comment]
Oh damn, my bad again. Thank you @caalador for educating me in a very nice and calm manner. I think we can close this one. Still, would you think that navigation within the app should happen without reloads regardless of the presence of the `router-link` attribute? Or is there an use-case for both cases?

**Comment by caalador** [comment]
Well one thing is that a router-link will send an RPC message to the server which would for a ok anchor target return an route not found exception.
