### ISSUE TITLE
Investigate running on server for plain servlet projects in Eclipse

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7300]
Test that _Run on Server in Eclipse_/_Debug on Server_ works for following servers with 14.2-SNAPSHOT:
- Jetty
- Tomcat

In case some server cannot be run from Eclipse, it should be documented to _Development Workflow_ section. We should check if the server/Eclipse combination supports live reload, and mention this in the documentation.

**Comment by denis-anisimov** [comment]
Tomcat : the same issue as https://github.com/vaadin/flow/issues/6369.

First run executes `npm install`. It takes too much time and server doesn't start due to timeout.
The second run works well since `npm install`  has been already executed by the first time.

**Comment by denis-anisimov** [comment]
Jetty: I haven't found how to run a web app via "Run on Server"  for Jetty.
It's not possible to register Jetty as a server (in Eclipse servers tab.
It's possible to install Eclipse Jetty integration which allows to run a web app on Jetty via special Run configuration "Jetty Webapp".
But it doesn't work because when I run e.g. skeleton project automatic deployment doesn't do anything:
```
[main] INFO com.vaadin.flow.server.startup.ServletDeployer - Skipping automatic servlet registration because there are no navigation targets registered to the route registry and there are no web component exporters 
```
Will make a ticket.

**Comment by denis-anisimov** [comment]
Two tickets are created:
https://github.com/vaadin/flow/issues/7387
https://github.com/vaadin/flow/issues/7386
