### ISSUE TITLE
Investigate running on server for CDI projects in IntelliJ IDEA

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7303]
Test that Run on Server in Eclipse/Debug on Server works for following EE servers (Run/Debug configurations) with 14.2-SNAPSHOT:

- TomEE
- WildFly 18
- RedHat JBoss EAP 7
- Oracle WebLogic Server 12.2.1
- IBM WebSphere Application Server 8.5 Liberty Profile and 9 

In case some servers cannot be run from IntelliJ, it should be documented to Development Workflow section. We should check if the server/IntelliJ combination supports live reload, and mention this in the documentation.

**Comment by pleku** [comment]
I'm betting these will be broken for the same reason as here https://github.com/vaadin/flow/issues/7448
So blocking this issue for now, no sense to test before that

**Comment by joheriks** [comment]
# Summary of investigation

Tested `skeleton-starter-flow-cdi` on the servers below in IntelliJ Ultimate. The start/stop/redeployment was handled by the launch configurations for the respective server integration plugins. 

| Server				| Version			|  Prod mode	| Dev mode	| Live reload	| 
| -					| -				|  -			| - 			| -			| 
| TomEE				| Plume 8.0.1		| ✅			| ✅ 			| ✅			| 
| Wildfly				| 18.0.1			| ✅			| ✅			| ✅			| 
| JBoss EAP 7			| 7.3.0.Beta		| ✅			| ✅			| ✅			| 
| WebLogic			| 12.2.1.4.0		| ❌†		| ❌†		| 			| 
| WebSphere AS		| 9.0.5.21			| ✅			| ❌*		| 			| 
| WebSphere Liberty	| 20.0.0.1			| ✅			| ❌*		| 			| 

† Application deploys without errors, but the served page enters a refresh loop in the browser (#7530).
&ast; `skeleton-starter-flow-cdi` crashes with `NoClassDefFoundError` (#7531). Plain `skeleton-starter-flow` crashes with `NullPointerException (#7542).

**Applies to all servers:** When creating the run configuration for the desired server and setting the artifact to be deployed, IntelliJ by default adds the `Build 'xxx:war' artifact` to the `Before launch` items. Before this item, you should add the `vaadin:prepare-frontend` goal manually:

<img width="885" alt="Screenshot 2020-02-11 at 16 18 20" src="https://user-images.githubusercontent.com/2838896/74244505-35fc3200-4cea-11ea-942d-f0fa3bc9ac8e.png">

Otherwise the artifact will be built without the token file, and while it may accidentally work if you have write access to the `bin` directory of the server installation, doing so will clutter the server's internal directories with `node_modules`, `package.json`, etc. Could we identify this scenario and just fail fast instead?
 
**Notes on WebSphere Application Server:** Installed on Windows. Required running IntelliJ as Administrator to be able to deploy to default installation location. WAS does not support WAR deployment, only EAR.
