### ISSUE TITLE
BeforeLeaveObserver.beforeLeave() not invoked on Page.setLocation()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#7401]
Vaadin 14.1.5. The `BeforeLeaveObserver.beforeLeave` is not invoked when the navigation is performed via `UI.getCurrent().getPage().setLocation()`. Related to #7287 .

It would be good to either fix this issue, or document `BeforeLeaveObserver.beforeLeave` that it's not invoked when the URL change is initiated by the browser.

Code which reproduces the issue:
```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        Button button = new Button("Click me",
                event -> UI.getCurrent().getPage().setLocation("/logout"));
        add(button);

        add(new MyButton());
    }
}

public class MyButton extends Button implements BeforeLeaveObserver {
    @Override
    public void beforeLeave(BeforeLeaveEvent event) {
        System.out.println("!!! Captured event: " + event);
    }
}

@Route("logout")
public class LogoutView extends VerticalLayout {
    public LogoutView() {
        add(new Text("Logged out"));
    }
}
```

Steps to reproduce:
1. Navigate to /
2. Click the "Click me" button
3. The view changes to `/logout`, however the beforeLeave() is not called and the `!!! Captured event` is not printed in stdout.

**Comment by johannest** [comment]
Even this doesn't seem to trigger `beforeLeave`
```new Anchor("http://www.google.com", "linkki")```

**Comment by TatuLund** [comment]
Also to be cross checked with this https://github.com/vaadin/flow/issues/7287

**Comment by joheriks** [comment]
By design, the `beforeLeave` method of any view implementing `BeforeLeaveObserver` (as well as other registered `BeforeLeaveHandler`s) is only called when navigation occurs within the routing subsystem, for instance via a `RouterLink` or by calling `UI::navigate`. Navigating by the requesting another URL on the client side, for instance via `Page::setLocation` or by typing a new URL into the browser, will result in the creation of a new `UI` and any `BeforeLeaveHandler` on the old UI are not guaranteed to be executed (not even when the old `UI` is disposed of). To make this clearer, will update the JavaDocs of `BeforeLeaveObserver` and `BeforeLeaveListener`.

The primary use case for `BeforeLeaveObserver` has been to enable easily postponing the navigation in case of unsaved data. There is a good case to be made that this should be possible also when the navigation is initiated unbeknown to the routing subsystem, such as when the user 
enters another URL, closes the browser tab, etc. However, this is to be considered a new feature as it will require multiple additions to the client side to catch these events.

The failing case above can be easily remedied by calling `UI.getCurrent().navigate("logout")` in place of `UI.getCurrent().getPage().setLocation("/logout")`.  In this case the `beforeLeave` method will indeed be called.
