### ISSUE TITLE
Test pin dependency versions for pnpm with 15.0-SNAPSHOT 

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7493]
Related to #7451 
Test with 15.0-SNAPSHOT that the versions file is used and versions are downgraded in a starter

**Comment by denis-anisimov** [comment]
The result of test : it doesn't work.
The reason is : unspecified `vaadin_versions.json`  file format.

Here is the example how entries are defined:
```
"vaadin-details": {
            "npmName": "@vaadin/vaadin-details",
            "javaVersion": "3.0.0.beta1",
            "jsVersion": "1.0.1",
            "component": true
        }
```

```
"iron-fit-behavior": {
            "npmName": "@polymer/iron-fit-behavior",
            "npmVersion": "3.0.2",
            "jsVersion": "2.2.1"
        }
```

So `vaadin-details` has only `jsVersion` and doesn't have `npmVersion`.
`iron-fit-behavior` has both `jsVersion` and `npmVersion`.

As a result the build fails with :
```
 ERROR  No matching version found for @polymer/iron-list@2.0.19
```

I don't know why some components (only vaadin apparently) have `jsVersion` and some have both `jsVersion` and `npmVersion` and what's the meaning of those.

But it seems that `npmVersion`  should be used first as a dep version and if it doesn't exist then `jsVersion`  should be used.

**Comment by denis-anisimov** [comment]
verified.
It works after the #7503.
