### ISSUE TITLE
Remove node_modules when switching betweeen npm & pnpm

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7528]
Related to #7461, when we detect a switch between npm/pnpm, we delete the old incompatible lock file and a new one is created.

Since npm and pnpm use a different `node_modules` folder structure, it would make sense to delete it after deleting the old lock file. This might take a bit longer first but would prevent bloating the disk with lots of unused files (or symlinks).

The folder should only be removed when it is detected present in the project root folder.

**Comment by denis-anisimov** [comment]
There is no any obvious way at the moment to detect that _SWITCH_ has been done from one tool to another.
That's why removal of `node_modules`  is dangerous: with intention to improve things we may do them worse than now because `node_modules`  in the worst case will be removed all the time (for some reason).
So please take care and find a reliable way to detect that switch from another tool to another tools has really happened (and not just the same tool is used and we remove `node_modules`  over and over again).
I'm not sure that presence of lock files is reliable way to detect switching.
May be instead the `node_modules`  structure should be checked (if there are differences) along with understanding which tool is currently running. If `node_modules`  structure is unexpected for the currently used tool then remove it. So we don't detect switching in fact but check the `node_modules`  structure for the tool instead.

**Comment by pleku** [comment]
I agree, we can probably never detect it 100 % reliably, because e.g. the user might have removed the lock file themselves. I would focus on the most common cases though, when the wrong lock file is present but not the correct one, we could just remove `node_modules` (and the wrong lock file) as it is most likely has wrong structure (tool).

But yes checking the `node_modules` structure would be more correct, if it can be done in a reasonable and reliable way.

**Comment by denis-anisimov** [comment]
Well, in fact even presence of `pnpm-lock.yaml` doesn't mean that `pnpm` is used in the project .
As a user I could had used `pnpm` myself (without Flow) then switched to npm and didn't remove the `pnpm-lock.yaml`  file.

**Comment by denis-anisimov** [comment]
So yes, it's better to rely on `node_modules` structure if possible.

**Comment by web-padawan** [comment]
Wouldn't the presence of `node_modules/.modules.yaml` be enough to detect the structure?
