### ISSUE TITLE
pnpm cannot be disabled with setting pnpmEnable config to false

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#7595]
#### Minimal reproducible example
- Open `skeleton-starter-flow` project v14 branch
- Set vaadin.version to `14.2.0.alpha4`
- Add the following to `vaadin-maven-plugin`
```xml
<configuration>
    <pnpmEnable>false</pnpmEnable>
</configuration>
```
- Run the application using `mvn jetty:run`

#### Expected behavior
`npm` being used.

### Actual behavior
`pnpm` is used, `pnpm-lock.yaml` and `pnpmfile.js` are generated. 
The following is part of the log.
```
[main] INFO dev-updater - Running `pnpm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
[main] INFO dev-updater - Generated pnpmfile hook file: '/Users/mehdi/Documents/GitHub/skeleton-starter-flow/pnpmfile.js'
```

**Comment by denis-anisimov** [comment]
Interesting.........
Why do you expect that maven configuration property affects the development mode ?

Maven config property affects _only_ the maven build (so production mode).
Since you are running `jetty:run`  then this property never takes any effect.
You should use either (another) system property or configure it via the init param.

So I would say this is not a bug.

Another thing that we may write this (_AND many many many other properties ) into the token file 
(I think Leif has such suggestion)  and read it from there.
But as I said this wasn't done initially and not a bug but rather an enhancement .
This is true for many properties which are currently read only either from system properties or from as init param.

**Comment by mehdi-vaadin** [comment]
I expect that because in the docs it wasn't clear that it's only about the production mode. See https://vaadin.com/docs/v15/flow/advanced/tutorial-switch-npm-pnpm.html. I think we can emphasize that the maven plugin config only affects production mode.

**Comment by denis-anisimov** [comment]
It's a bug in the documentation.

**Comment by knoobie** [comment]
Coming from V8 I would except that the maven plugin (with it's configuration) is executed when I run jetty:run. (Can be my fuzzy memory) with spring-boot:run it's definitely executed in V8. So I would expect the same for jetty:run.

**Comment by denis-anisimov** [comment]
Plugin configuration is executed.
But plugin configuration doesn't affect anyhow dev mode.
Plugin configuration affects only code which is a part of the maven plugin and this is only the production mode.

**Comment by knoobie** [comment]
Thanks for the clarification @denis-anisimov!
