### ISSUE TITLE
Issues with Scrollbar caused by 100vw set on body

### ISSUE THREAD

**Issue by romst** [vaadin/flow#7611]
Hi, I'm currently testing components for Vaadin 12.0.3 and noticed, that scrolling isn't really working good. As soon as the horizontal scrollbar appears, a vertical is added because of the vertical scrollbar.

I'm using a FormLayout, to which I've added some components with addFormItem. I'm testing on Chrome 71.0.3578.98

I've identified the problem to be caused by the body tag, which uses 100vw/vh instead of 100% for width and height. If I fix that in the Chrome Editor, it works perfectly.

**Comment by web-padawan** [comment]
Transferred this issue from `vaadin-core` because this is not a components issue.
There hasn't been any activity for a while, but I believe the actual problem is still there.

And it's actually by design, as described in #3749 and implemented in #3821.

So please decide whether this should be fixed (breaking change), or closed as won't fix.

**Comment by pleku** [comment]
This is indeed problematic in the case presented above with e.g. `VerticalLayout` as the main layout, but it is working fine for Bakery, both in login and after login. It is not reproducing when the root layout of the application is `AppLayout` since that will have

```css
    display: flex;
    flex-direction: column;
    position: relative;
    box-sizing: border-box;
    height: 100%;
```

I'm not sure if we can now easily switch this for 14.x series as it could be sort-of-a breaking change to switch from `100vw` to `100%`. @jouni any thoughts on what we should do, as in hindsight the default is not perfect. I cannot say if the breaking change is safe to be introduced or not. If it cannot be introduced, then this could be just closed as a _wontfix_.

A workaround for this is currently to set the style with `@BodySize(height = "100vh",width = "100%")` to the root layout in Java.

**Comment by jouni** [comment]
My gut says that changing from `100vw` to `100%` would be considered as a bugfix by nearly all users, and would not break any apps that already work as expected (full size without any scrollbars).

This is based on the assumption that no app really wants the behavior where they have both the vertical and horizontal scrollbars when only the vertical one is needed.

**Comment by pleku** [comment]
Thanks @jouni. So while we would not consider this a breaking change, it might be still good to note about this change in the release notes.
