### ISSUE TITLE
Un-deprecate VaadinServletConfiguration?

### ISSUE THREAD

**Issue by jhult** [vaadin/flow#7651]
It seems like [`VaadinServletConfiguration`](/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/VaadinServletConfiguration.java) still has some uses. It is used in [`DeploymentConfigurationFactory`](/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/DeploymentConfigurationFactory.java) and in some tests.

It is also used in cases where a Servlet is not automatically deployed (which is a supported configuration).

Based on the above, does it make sense to un-deprecate this class and add in any missing `SERVLET_PARAMETER_*`  values? If so, I'd be happy to take a shot at implementing it and creating a pull request.

**Comment by pleku** [comment]
Hi @jhult your observations are correct. The configuration was deprecated because the registering of your own servlet is discouraged. And if the users want to register the servlet themselves, they could just use `@WebServlet` and the parameters will just work from there. The purpose of `@VaadinServletConfiguration` was to provide an easier API to the Vaadin specific parameters.

So, in some ways it is now just dead code and the deprecation javadocs are missing the replacement. There is already though stated in javadocs:
```
 * Init params defined in <code>web.xml</code> or the <code>@WebServlet</code>
 * annotation take precedence over values defined in this annotation."
```

I think it could be clarified that "this will be removed in later major versions, and can be replaced with `@WebServlet`." This PR could be done now to `master` branch and then cherry-picked to 3.0, 2.2 and 2.1 versions (by the team).

Then once we go to next LTS version, we could mayhaps remove the annotation completely, but this PR cannot be made before that as we just bumped from 2->3 and will not want to do a major version bump just because of this code.

**Comment by pleku** [comment]
I've triaged this as a "bug in the javadocs".

**Comment by jhult** [comment]
I will add that relying on `@WebServlet` requires a continued dependence on the servlet-spec. Issue #4613 would aim to remove this dependence.

**Comment by denis-anisimov** [comment]
I'm going to remove this annotation completely now in the `master` (which is `19`).
I'm doing deployment configuration refactoring and this code is suitable for removing.
`@WebInitParam` annotation should be used instead in case of non automatic sevlet deployment.
