### ISSUE TITLE
Fix flaky test  TaskRunPnpmInstallTest.runNpmInstall_toolIsNotChanged_nodeModulesIsNotRemoved

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7664]
https://bender.vaadin.com/project.html?projectId=Flow_Snapshots_Flow22nightlySnapshots&testNameId=-6793477115550980227&tab=testDetails

**Comment by denis-anisimov** [comment]
This test has been disabled via `@Ignore`  long time ago in the `master`.
Then it has been enabled back by spawn thread PR with changes that should help to avoid failures.
Now it's reverted back to disabled with reverting commit for spawning new thread.
https://github.com/vaadin/flow/blob/master/flow-server/src/test/java/com/vaadin/flow/server/frontend/TaskRunPnpmInstallTest.java#L94

I'm not sure why `2.2` still has not disabled test: bot should have cherry picked the fix for it....
Perhaps it needs to be cherry-picked manually.
