### ISSUE TITLE
Install pnpm to {user_home}/.vaadin

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#7684]
In the case where node and npm are only installed in `{user_home}/.vaadin` folder (or require.home.node=true)
pnpm could also be installed there instead of reminding to install it globally as the user most likely doesn't want global installation of node.

This would also lessen multi-module builds installing pnpm for each module.

**Comment by denis-anisimov** [comment]
That makes a lot of sense except that this is very dangerous improvement: it may introduce a lot of regressions.

The implementation should be very careful and be aware of many possible problems.
See `FrontendUtils::getLocalPnpmScript` : it checks pnpm inside `node_modules/.ignored_pnpm/bin/pnpm.js` and `node_modules/.ignored/pnpm/bin/pnpm.js` .

With home directory those path will be different and also they still needs to be checked if pnpm is not used from a local installation.

I see here a huge number of possible issues with the code.

**Comment by denis-anisimov** [comment]
I would refactor ( totally rewrite) `FrontendUtils` first because it's very bad designed and hard to maintain.
It should not be an utility class anymore. It should be a class with a context.
E.g. the directory where everything is expected to be installed can be a part of the context:
- home directory will be this directory where everything is expected
- or project folder dir

Now home directory is not a contextual but it's hardcoded. As a result you don't know whether `node`  has been installed when asking for `pnpm` : you should just go through all possible locations and check all of them.

**Comment by denis-anisimov** [comment]
Blocked by #7771.

**Comment by mehdi-vaadin** [comment]
It should be tested on Windows, Mac, and Linux.
