### ISSUE TITLE
Investigate how to enable automatic browser reload on Java changes

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#7740]
Basically this would replace usage of livereload browser plugin with Spring Boot devtools. But it should target also other fast reload technologies like: JRebel, TomEE Maven Plugin and Hotswap Agent. For now Jetty Maven Plugin is excluded as it is quite slow due to full context reload.

- This is focused on the use case where you are building/changing a view and have it open in the browser next to the IDE (or on separate window)
- The target would be about 1-2 seconds from saving/compiling Java code to seeing the changes in the browser
- The user should be able to disable this for the running app from the browser from the notification that is shown when the reload happens, and later on enable it
- The user should be able to disable the reload by giving a parameter when the server starts up 

The screen can reload or just update the UI, doesn't matter as long as the changes are applied fast enough. The opened route chain should be the same.

Optionally the UI state could be preserved like with `@PreserveOnRefresh`, but this is a secondary target for now.

**Comment by joheriks** [comment]
Server-side investigation: The Spring boot live reload server is easy to hook into by opening a websocket connection to port 35729. For example, adding the following JavaScript to the page roughly emulates the functionality of LiveReload browser plugin: 

```
ws = new WebSocket("ws://localhost:35729")
ws.onmessage = function (msg) {
    data = JSON.parse(msg.data);
    if (data.command === "hello") {
        console.log("Hello LiveReloadServer")
    }
    if (data.command === "reload") {
        location.reload();
    }
}
```

The only supported commands seem to be `hello` and `reload`:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-devtools/src/main/java/org/springframework/boot/devtools/livereload/Connection.java

So we could implement this protocol on non-Spring Vaadin servlets as well, or alternatively use the same WS approach with our own protocol that applies to both Spring and non-Spring applications. Whatever is easier / makes more sense requires more investigation.

**Comment by joheriks** [comment]
Regarding preserving the state, that requirement directly conflicts with live reload. In fact, currently using `@PreserveOnRefresh` will *prevent* seeing any visible changes in the UI state that are due to the code change that triggered the recompile (because the existing components are reused). So for example if I change the a view by modifying its constructor, the effect of these changes will not be visible since the constructor is not re-run. The effect of changes in code that gets re-run on reload, such as attach listeners, would however be visible. The uses cases needs to be properly analyzed, but intuitively the former seems like a more common case compared to the latter.

**Comment by joheriks** [comment]
Auto-reload POc (client side works with Spring Devtools) here:
https://github.com/vaadin/flow/tree/live-refresh-poc
