### ISSUE TITLE
@Autowired not working in embedded components

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow#7861]
Vaadin 14.1.18

When I load an embedded component, @Autowired tags as well as other Spring injection annotations (e.g. @PostConstruct) are not wired up.

**Comment by knoobie** [comment]
Do you have an example? (Full class) Could be possible that you are missing an annotation.

**Comment by Legioth** [comment]
Seems like instances of `WebComponentExporter` are created using `ReflectTools.createInstance` rather than through `Instantiator` in `DefaultWebComponentExporterFactory.create()`.

**Comment by denis-anisimov** [comment]
@Legioth : yes.
That was an explicit decision made in back days to be able to use  `WebComponentExporter` to generate template without any runtime available (via maven plugin).

Template had to be generated for production mode and there is no any DI available to support any such feature.

As far as I remember it was done for compatibility mode which was the only mode that days.
Now in the master we have no compatibility mode and may be this is not any issue anymore.

But this ticket is for `14.1.18`...
Though there is no any mention about compatibility mode.

I would say this is not a bug at all : we never said that DI is supported by `WebComponentExporter`.
Though it doesn't mean that embedded component doesn't support any DI.

I'm not sure whether the fact that `WebComponentExporter` is created without DI is the same as the fact that embedded web component doesn't support DI: the factory which creates the component instance may be able to use DI even if `WebComponentExporter` is not created via DI.

So I don't understand what `When I load an embedded component, @Autowired tags as well as other Spring injection annotations` means.

The ticket has to have exact code and expected result description.

**Comment by martinisraelsen** [comment]
Code sample:

`
@SpringComponent
public class MyDataLoader {

   public String getString() {
      return "Hello World";
   }
}
`

Component
`
@SuppressWarnings("serial")
@SpringComponent
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class MyComponent extends Composite<Div> {

   @Autowired
   MyDataLoader myDataLoader;

   public MyComponent() {
   }

   @Override
   protected void onAttach(AttachEvent attachEvent) {
      super.onAttach(attachEvent);
      getContent().add(new Label(myDataLoader.getString()));
   }
}
`

Exporter
`
@SuppressWarnings("serial")
public class MyComponentExporter extends WebComponentExporter<MyComponent> {

   /**
    * @param tag
    */
   public MyComponentExporter() {
      super("my-component");
   }

   @Override
   public void configureInstance(WebComponent<MyComponent> webComponent, MyComponent component) {
   }
}
`

NPE in onAttach as myDataLoader is null.

`
java.lang.NullPointerException: null
	at bc.ui.views.embedded.servlet.MyComponent.onAttach(MyComponent.java:38) ~[classes/:na]
	at com.vaadin.flow.component.ComponentUtil.onComponentAttach(ComponentUtil.java:231) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.internal.nodefeature.ComponentMapping.lambda$onAttach$0(ComponentMapping.java:102) ~[flow-server-2.1.5.jar:2.1.5]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_212]
	at com.vaadin.flow.internal.nodefeature.ComponentMapping.onAttach(ComponentMapping.java:101) ~[flow-server-2.1.5.jar:2.1.5]
	at com.vaadin.flow.internal.StateNode.lambda$fireAttachListeners$6(StateNode.java:789) ~[flow-server-2.1.5.jar:2.1.5]
`

> I would say this is not a bug at all : we never said that DI is supported by WebComponentExporter

I find this comment quite worrisome. I understand that certain things, like Navigation isn't working in embedded components, but DI is hardly exceptional. https://vaadin.com/docs/v14/flow/embedding-flow-applications/tutorial-webcomponent-limitations.html does not mention DI either.

Is in unreasonable to expect that a component that is working in a regular Vaadin Application also works in an embedded Application/Component?

**Comment by martinisraelsen** [comment]
I did a workaround by creating a intermediate component that launches the DI component. Only issues is that I have to manually pass the properties, but it's a workable workaround.

**Comment by denis-anisimov** [comment]
>I understand that certain things, like Navigation isn't working in embedded components, but DI is hardly exceptional.

Please let's don't mix the concepts.
This is exactly why we asked you about the source code snippet.

In your source code you don't use DI in the exporter class anyhow.
And it's not supposed that anyone is going to use DI in the exporter class. I recall that I've explicitly written this limitation in the documentation (so it should be there if no one has removed it).

But DI may and should work in the embedded component itself. This has no any relation to the exporter.
Exporter is more configuration factory and it's doesn't have to be even called in the runtime.
But everything which is working in runtime should be DI capable .

So your sample should work.
Here is the code which is used to create an exported web component instance:
```
final C componentReference = instantiator
                    .createComponent(this.getComponentClass());
```

`Instantiator` instance is used here.
So the code is correct.
The only question : which instantiator is used here......

So there are two cases:
- your setup is not DI capable
- there is a bug indeed somewhere in our code.

So the information in the ticket is not enough to understand your setup.
To be able to use DI with your web component you should use Spring add-on and Spring servlet 
should be used to handle requests for your embedded web components.
In this case `Instantiator`  will be `SpringInstantiator` and it will create a component instance using Autowired capable bean factory.

So either this is a case and something is broken in our code or you don't have this setup.

Please provide the information about your Servlet setup for the embedded component.

**Comment by martinisraelsen** [comment]
Hi @denis-anisimov. It's entirely possible that something is missing in my code, but the same thing happens with the Vaadin Spring starter. Here's a sample app.

Run with mvn spring-boot:run
Go to localhost:8080. It should say that MyService is loaded
Go to localhost:8080/embedded. It should say that MyService is not loaded

[embedded-app.zip](https://github.com/vaadin/flow/files/4380838/embedded-app.zip)

**Comment by denis-anisimov** [comment]
OK, thanks for the example.
Now at least all required info is provided.
Someone will look into at some point.

**Comment by denis-anisimov** [comment]
Confirmed.

In the attached example 
```
@Autowired
   MyService myService;
```
`myService` is `null`  in `onAttach` method.

Apparently the component is not created via Spring propertly.

**Comment by denis-anisimov** [comment]
There are many mistakes in the example.

The first mistake which may be not related to the issue: 
```
@Service
public class MyComponent
```
`Service` is a stereotype annotated with `@Component` but it has no explicitly set scope.
Which scope the bean will have ? I assume it will be `singleton` which is always wrong for a component.

Another mistake is strongly related to the issue which makes it not a bug.
The embedded component is registered via the url pattern `"/components/"` which is handled by the `WebComponentServlet`. This servlet doesn't know anything about Spring.
As a result the standard Vaadin Web app mechanism is used to instantiate the web component which just creates a new instance via Reflection.
And this is expected behavior.
As a result : the `MyComponent` instance is made outside of Spring machinery (it should be instantiated via `SpringInstantiator` but the default one is used). That's why nothing is injected inside it.

You should use Spring add-on way to register a Spring Vaadin servlet for embedded components.

So this is not a bug.

**Comment by Legioth** [comment]
Is there documentation for how to be able to use DI injection in embedded components?

**Comment by denis-anisimov** [comment]
I think there is no such explicit documentation.
Separate docs ticket is needed.

**Comment by Legioth** [comment]
If it isn't reasonable that `MyComponentExporter` is created through `Instantiator` because of build-time limitations, then what about making the default implementation instantiate `MyComponent` based on the type parameter in that way?

**Comment by denis-anisimov** [comment]
Hmmmm....
I'm not sure which issue now you are talking about....

The ticket is not about `MyComponentExporter`.
I don't know actually the current state of code.
The embedded web component logic has been written without any my attention for NPM mode.
I don't know whether there is a real limitation for exporter creation nowadays.

I recall that for compatibility mode exporter may not have been created via `Instantiator` in production mode since exporter has been used at build time ( not runtime) where no any DI is available.
But I don't know whether the exporter needs to be instantiated during build time nowadays in produciton.
But anyway: this is a different issue and I'm not even sure which one. There were no any report about inability to use exporter in DI.
It should be possible to use embedded web component in DI for sure. The embedded web component is created via `Instantiator` , so it's only a question of using the correct instantiator and setup.
