### ISSUE TITLE
Add API for setting the UI direction

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#8021]
Currently, the document direction gets automatically set when `UI.setLocale(Locale)` is invoked. Change the behavior (and API) so that the direction doesn't get set automatically, but instead with an explicit API for the purpose:

```
myUi.setDirection(Direction.RIGHT_TO_LEFT)
```

Supplement the API with documentation showing how to use that method from the application's main layout. The code example would include our current list of RTL locales so that developers can easily copy-paste it but still be in full control over maintenance.

**Comment by Legioth** [comment]
For the documentation about the main layout, there are two different variations. 
* Setting the direction in the constructor requires minimal code, but won't react if the UI locale is changed afterwards.
* Making the main layout implement `LocaleChangeObserver` and calling `setDirection` from `localeChange` reacts to programmatic locale changes, but requires slightly more application code.

**Comment by rolfsmeds** [comment]
I think it's safe to assume that locale switching locales is a common requirement in apps that will utilize RTL mode. Although for now I suppose it would be acceptable to require a new session when switching between LTR and RTL.

Also want to note that IIRC the default locale is determined from the initial client response, and we don't want the UI to switch to RTL automatically **by default** if the client locale happens to be RTL, since that will break existing UIs that are not built to support it.

**Comment by Legioth** [comment]
That's the beauty of explicitly applying the direction from code in the application's main layout. You can do it based on the UI locale either during initialization or when handling a locale change event, depending on the use case.
