### ISSUE TITLE
Remove PWA install popup feature

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8038]
As noted in https://github.com/vaadin/flow/issues/6899#issuecomment-609595015 the `beforeinstallprompt` feature has been removed from the spec and browser vendors other than Chrome are likely not going to implement it.

Instead of what is suggested in #5530, we should remove the whole feature to avoid confusion. If browser vendors have decided that their UI must be used to install applications, we should follow that.

**Comment by pleku** [comment]
Yes, I agree that we should do this now after things have changed, but I failed to think forward on this after closing the aforementioned issue. The question is though that _in what versions can we include this breaking change and how_?

Couple of thoughts:
- For next Vaadin 14 (14.3 or 14.2 during beta), we could retain the existing functionality of prompting but make it deprecated first. Would be preferred that anyone who wants to keep their apps working like before (a lot of prompting but only in Chrome), would be able to do so. But default for any new V14 apps is to not have any prompt visible. This means that hiding it is done in example with a new flag in the annotation that is set for all starters ? Or then the other way around, anyone who still wants to use the feature would have to use the flag.
- For next release of Flow (V16 / 3.1 now but it is getting close to freeze), the feature is deprecated similarly as with 14.3 
- For next+1 release of Flow the prompt feature is removed completely. Deprecated code can be just removed as it would be "dead code", and this is not a big migration effort IMO.

Thoughts @Artur- ?

I think we could prioritize this issue to get it done soon.

**Comment by pleku** [comment]
So after quick reflection and the monologue above, I would propose the following behavior changes to be done:
- 14.2 (already in beta), we deprecate the install prompt in another beta and require existing apps to "opt-in" for showing the prompt. We still deprecate this flag in the `@PWA` annotation and clarify that it will go away in future because it is not in the spec
- 16 (soon beta) same as 14.2
- 17 feature is removed and any deprecated code with it as there is no replacement. This might be upsetting to those who only target Chrome but could be possible to be done for it (in a better way) in an add-on

**Comment by Artur-** [comment]
I don't see the rush here nor why would we would want to change it in an incompatible way.

Why don't we:
* Change starters so they do not use the prompt
* Remove the feature from V17
* Document in V14 why the feature should not be used and why it is going away in V17

**Comment by pleku** [comment]
Right, we do have the flag for it already in the annotation
```
boolean enableInstallPrompt() default true;
```

I see it is bit problematic due to being by opt-out instead of opt-in and thus I would be ready to change that. I suggested this as #5530 shows it is problematic and can cause annoying UX by default. So the behavior change would be from "unwanted behavior to better behavior with possibility to opt-in for old behavior". But I'm fine with either approach.

The starters and documentation can be anyway changed at any point for all versions.

**Comment by Artur-** [comment]
Once the starters are changed, it effectively becomes opt-in as no new projects use it. 

So there are two options:
1. You change the default and immediately break/change all existing apps which have not specified any value
2. You leave the default and remove it from say V17. When migrating, the user needs to remove the option if it is specified and only at this point the behavior in the app changes.

**Comment by pleku** [comment]
### Draft Acceptance Criteria
- [ ] Hide the install prompt in skeleton-starter-flow (master & 14 branch)
- [ ] Hide the install prompt in skeleton-starter-flow-spring (master & 14 branch)
- [ ] Hide the install prompt in skeleton-starter-flow-cdi (master & 14 branch)
- [ ] Hide the install prompt in bakery (master & 14 branch)
- [ ] Hide the install prompt in bookstore-example (master & 14 branch)
- [ ] Remove the install prompt from Flow 3.2 (master)
  - **This is a behavior altering change that should be highlighted in the release notes for 3.2 & platform, but we would not bump the major version just for this because the removed behavior is not working consistently in all browsers. It is also a breaking change for anyone who as explicitly disabled it but that should be very easy to fix by just removing the two words from the code.**
- [ ] Maybe: deprecate the `enableInstallPrompt` in 3.1 to say that it will be explicitly removed in 3.2 ?
- [ ] Change the javadocs for `@PWA` to mention that the install prompt will be removed in a later versions because it is only supported in Chrome browser and not desired UX. This could be cherry-picked to 2.1, 2.2, 3.0 and 3.1

**Comment by pleku** [comment]
@jm-ferreira is this really done:
> Change the javadocs for @PWA to mention that the install prompt will be removed in a later versions because it is only supported in Chrome browser and not desired UX. This could be cherry-picked to 2.1, 2.2, 3.0 and 3.1

Since I don't see any related changes in 2.2 branch ? There is documentation changes (in docs repo) but not in javadocs for 2.2 ? I could maybe skip 2.1 as 2.2 is coming out but at least 2.2 needs the javadocs to be updated that the feature is not supported and going away in upcoming version (v17)
