### ISSUE TITLE
Implement new methods to components implementing HasDataProvider interface

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#8172]
Any component implementing HasDataProvider should
implement the new interface methods.

`ListBox`, `CheckBoxGroup`, `RadioButtonGroup`, `IronList`, `Select`, `Grid`

Add demos to Grid:

```java
new Button("Export pdf", click -> PdfGenerator.get().export(grid.getAllItems()));
```

```java
Text contentSize;
grid.addActiveDataChangeListener(changeEvent -> {
    contentSize.setValue(changeEvent.getFullDatasetSize());
})
```

Follow up for #8171

**Comment by pleku** [comment]
While the API looks clean in #8171, here it is clear that it is not useful for other components than Grid and IronList. So it is not clear which option we should take:
a) bloat the API of all components by using the existing mixin interface
b) add another mixin interface which describes what is the API about and add it only to components that need it - getting all items based on current sorting & filtering and getting notified for data changes
c) just add the API directly to grid and maybe ironlist

**Comment by Legioth** [comment]
Good point about components that don't need it. Introducing as a _mixin_ interface only makes sense if the methods can have sensible default implementations. Otherwise, we would implement separately for each component and then optionally introduce a unifying abstract interface to support the theoretical use case of pulling data out of any compliant component (i.e. either grid or iron-list).
