### ISSUE TITLE
Add DataRefreshListener with DataRefreshEvent to DataProvider

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#8175]
Currently DataProvider has the `Registration addDataProviderListener(DataProviderListener<T> listener);` that fires a DataChangeEvent.
This has the problem that you have to explicitly cast to DataRefreshEvent to determine what was updated. 

So we should add a specific listener so you don't have to do the casting.

**Comment by Legioth** [comment]
My assumption is that `DataCommunicator` is the main user of that event. I'd rather have an explicit cast in `DataCommunicator` rather than complicating the `DataProvider` API.

Changing the API raises an interesting question about whether the existing `addDataProviderListener` method should still receive refresh events. Preserving the events means that users may still have to do an `instanceof` check when receiving the event. Not preserving would break backwards compatibility.

**Comment by pleku** [comment]
>My assumption is that DataCommunicator is the main user of that event. I'd rather have an explicit cast in DataCommunicator rather than complicating the DataProvider API.

The API is also used in components that don't use `DataCommunicator` but use `DataProvider`. Basically any listing component is interested in the refresh event(s) so it can render correctly.
