### ISSUE TITLE
Resynchronizing UI by client's request

### ISSUE THREAD

**Issue by hfffranzin** [vaadin/flow#8204]
If I leave the application open, without touching it for a few minutes later, this error occurs and I need to reload the page ...

Vaadin 15.0.5

2020-04-29 12:37:35.693  WARN 46170 --- [o-8080-exec-420] c.v.f.s.communication.ServerRpcHandler   : Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues

**Comment by Legioth** [comment]
Thank you for your report. We would need some additional details to help understand what's going on in this case. The fact that this only happens after some minutes of inactivity gives the impression that some kind of timeout is triggered somewhere, the key question is what timeout that is.

Some particular details that may be of interest
* Is there something like a load balancer, HTTP proxy or VPN between the browser and the server?
* Would it be possible to create an example application that someone from our team can run to reproduce the problem?
* Do you see any related messages in the browser's JavaScript console?

**Comment by hfffranzin** [comment]
@Legioth ... Thanks for the feedback.

is running directly on a server hosted in the cloud.

But I did some tests and changed the time to 10 minutes of the session ...
VaadinSession.getCurrent (). GetSession (). SetMaxInactiveInterval (600)

However, in development, the session is closed normally, but in production, not and when you click on something, it generates the error message on the server

JavaScript error:
Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent). - wasClean: false

**Comment by Legioth** [comment]
So there's something different between your production environment and the local development environment. The question is just what?

Some ideas:
* Do you use the same application server (e.g. Tomcat or Jetty) both locally and in production?
* Is there a possibility that there is some kind of load balancer or such in use on behalf of the cloud environment?

I've seen a similar case with unexpected websocket termination in a case that was otherwise quite different, but you could maybe still see if the same workaround might be effective. The trick was to set the `org.atmosphere.websocket.maxIdleTime` servlet parameter to a suitable value. `30000` was used at some point when experimenting, but I don't know if that was the value that they actually used. Some environments makes it easier to set servlet context parameters instead of setting a parameter for a particular servlet. In that case, you also need to set `org.atmosphere.cpr.AtmosphereConfig.getInitParameter` to `true` as a servlet context parameter to make Atmosphere look at servlet context parameters and not only servlet parameters for other configuration.

**Comment by masc3d** [comment]
Im seeing a similar issue with 14.2.0 except when it starts resynchronizing it won't do just once but  in an (seemingly) endless loop until switching to another view.

**Comment by masc3d** [comment]
conditions seem to be the same though. client-side / browser must be idle for a while for the issue to emerge.

**Comment by masc3d** [comment]
it's a spring setup and I have seen this when directly connecting to the server, no reverse proxy or balancer etc.

**Comment by hfffranzin** [comment]
@masc3d... so do you recommend that i do a reverse proxy?

**Comment by pleku** [comment]
Closing the issue issue due to inactivity. There is simply nothing we can do at this point without further details and steps to reproduce.
