### ISSUE TITLE
Fix disabled style for reload toggle

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#8234]
The Vaadin development gizmo currently utilizes pop-up notifications for the live-reload nudge and other noteworthy messages. For example:

<img width="448" alt="notifications" src="https://user-images.githubusercontent.com/2838896/81046052-3444a380-8ec0-11ea-9fef-53ff9814a9d4.png">

Clicking anywhere in a notification dismissed it to the message log (which is visible only after expanding the gizmo). By clicking "Don't show again", the message will no longer be shown as a pop-up on subsequent reloads but will immediately go to the message tray (which messages have been dismissed is remembered in localstorage):

<img width="512" alt="Screenshot 2020-05-05 at 17 46 01" src="https://user-images.githubusercontent.com/2838896/81079519-52c69100-8ef8-11ea-9691-fc171c296ad1.png">

User feedback from DX testing has indicated that it may be confusing that the notifications look similar to the expanded gizmo.

Perhaps minor: the toggle button in this case is *disabled* (i.e., it can't be toggled). However, it looks the same as when it is enabled but toggled off. May need to style it differently.

Possible alternatives:
* Do not use pop up-notifications, but rather expand the gizmo when a noteworthy message is added to the log.
* Do not use pop-up notifications, but show a badge on the gizmo that there are noteworthy unread messages there.
* Use pop-up-notifications, but style them differently.
* Other?

**Comment by joheriks** [comment]
## Acceptance criteria
* An acceptable solution has been determined
* The solution is implemented
* IT for updated notification behavior

**Comment by joheriks** [comment]
@juuso-vaadin Do you have an opinion on the design of this?

**Comment by juuso-vaadin** [comment]
I don't see an issue with notifications looking similar to expanded gizmo. They look similar by design as they are the same thing. Notification pops open and gizmo stores the notifications but the message is the same. If they did look different user would need to figure out that is this the same message I just saw or not.

I would suggest to keep using pop-up notifications with restraint. Only notify things that are important to note at that moment. The less important messages can be in the gizmo panel and indicated with badge.

I agree that the toggle switch should have a disabled style if not available and turned off.
