### ISSUE TITLE
Runtime configuration of @PWA()

### ISSUE THREAD

**Issue by TordJoranger** [vaadin/flow#8311]
Hi. We're looking to use the @PWA() annotation in our application  However we only want  the app starter popup  turned on for some customers. So the "enableInstallPrompt" is what we need, but we want to turn in on and off on demand. 

So we are looking for a way to override the configurations runtime, reading values from config file or env variables. 

something like this or equivalent would be ideal

`@PWA(name = "My Name ",shortName = "My ShortName",enableInstallPrompt = "${popupEnabled}" )`

Talked with Martin in the vaadin expert chat, that redirected me here. 

 Versions:
    - Vaadin / Flow version: 14.1
    - Java version: 11

**Comment by Artur-** [comment]
You should not rely on the install prompt. Browser vendors decided not to implement the feature and it is being removed from Vaadin 17+. See #8038 for more details

**Comment by pleku** [comment]
Hello. Artur beat me to it, but as he said the install prompt feature is actually going away - it will still be available in Vaadin 14 but as the browser feature for it didn't make it to the HTML standard, it will not be available in other browsers than Chrome. The reason is mostly that majority of the vendors don't think another prompt that every page implements itself is the way to go for this - the installing experience is something that the browser will provide instead and thus it will be the same for every PWA application. So this means that the user has to install through the browser UI.

To customize the install prompt experience for Chrome ONLY could be possible at least as long as Chrome supports it, but we're not going to make that happen in the framework. Thus any such feature should be done as an add-on, if you still need it you should contact your Vaadin account manager.

Closing the issue as won'tfix.
