### ISSUE TITLE
MPR add-on nightly build fails

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8388]
- MPR 2.0 Validation https://bender.vaadin.com/viewLog.html?buildId=150455&buildTypeId=Flow_Flow23_AddOns_Mpr20

**Comment by denis-anisimov** [comment]
Any specific reason to combine those failures together ?
Is the reason of the failure the same ?
Is it already known ?

Generally this is extremely bad idea to report build failure in one ticket for many various reasons.
One of such reason: the build failure needs to be fixed ASAP and making one ticket limits the number of people working on this.
It's much easier to work on different tickets for several people without any coordination instead of one ticket.

**Comment by joheriks** [comment]
Many tests were failing because the live reload gizmo caused a client-side error in compatibility mode. #8396 fixes this. Once merged I will update this ticket to mention only the remainign failing tests (or close it if all tests pass, though that seems unlikely since at least [MPR validation](https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow23_AddOns_Mpr20) has been always failing until now).

**Comment by mshabarov** [comment]
> Any specific reason to combine those failures together ?
> Is the reason of the failure the same ?
> Is it already known ?

These build failures were combined into one ticket because they happened to fail simultaneously. It seemed to me that creating a single ticket for each particular build would bring a mess into the ready to go board. The reason was not known for the moment of ticket creation, but there was a correlation between merging to 2.3 branch yesterday and these nightly failures. Generally speaking, I agree with you, that many specific tickets are better that one for all.

> that seems unlikely since at least MPR validation has been always failing until now

Yes, but the last MPR validation build errors summary was the different than for few previous builds.
