### ISSUE TITLE
PushHandler is not cleaning CurrentInstances in the connectionLost method when the UI is reloaded in a Chromium based browser and push transport is WEBSOCKET(+XHR)

### ISSUE THREAD

**Issue by lmorocz** [vaadin/flow#8548]
### Description of the bug
The `com.vaadin.flow.server.communication.PushHandler.connectionLost` executes `service.findVaadinSession(vaadinRequest)` and `service.findUI(vaadinRequest)` and this populates the `com.vaadin.flow.internal.CurrentInstance.instances` ThreadLocal. This Session/UI context holder is not cleared properly when the caller is `PushAtmosphereHandler` (no one calls `com.vaadin.flow.internal.CurrentInstance.clearAll`). This leads to leftover Vaadin CurrentInstance state on Tomcat managed (pooled) execution threads.

Details of the use-case and the problem is here: https://github.com/lmorocz/vaadin14.push.connectionlost-demo/blob/master/README.md

### Minimal reproducible example
See: https://github.com/lmorocz/vaadin14.push.connectionlost-demo
### Expected behavior
The PushHandler#connectionLost cleans all CurrentInstance ThreadLocal after execution regardless of the caller (VaadinService#handleRequest or JSR356Endpoint+PushAtmosphereHandler).
### Actual behavior
PushHandler#connectionLost called from JSR356Endpoint+PushAtmosphereHandler does not clean CurrentInstance ThreadLocals. 
### Versions:
    - Vaadin / Flow version: 14 (14.0.x, 14.1.x, 14.2.x - not tested with 15+ versions)
    - Java version: 11 LTS Hotspot Adopt OpenJDK 
    - OS version: Win10 Pro (64-bit) 1909, but also on RHEL 7 and CentOS 7
    - Browser version (if applicable): Chrome v83.0.4103.97 (64 bit)
    - Application Server (if applicable): Tomcat 9.0.35
    - IDE (if applicable): IDEA Community 2020.1

**Comment by denis-anisimov** [comment]
The PR https://github.com/vaadin/flow/pull/8567 doesn't fix the issue since it's no-op.
`CurrentInstance.clearAll` unexpectedly doesn't do anything being called as a command via `VaadinSession::access`.

Some other way needs to be done to fix the issue.

**Comment by denis-anisimov** [comment]
**Important note:** the original PR is bad because `CurrentInstance.clearAll`  can't be postponed via `access` .
But the suggestion do not postpone `CurrentInstance.clearAll`  is bad: there are two ways of calling `connectionLost`:
one from `AtmosphereResourceListener` (e.g. happens with FF) another from `PushAtmosphereHandler:: onStateChange`.

See details here: https://github.com/lmorocz/vaadin14.push.connectionlost-demo/blob/master/README.md.

In one case it's safe to call `CurrentInstance.clearAll` right away. In another case the call happens from 
`VaadinService:: handleRequest` , `PushRequestHandler:: handleRequest `.
And `CurrentInstance` can't be cleaned up before `VaadinService:: handleRequest` exited because `PushRequestHandler` is just one of the number of request handlers and other handlers may need `CurrentInstance`  values.

It might be that `CurrentInstance.clearAll`   can be called in the end of request conditionally.
