### ISSUE TITLE
Flow client is too restrictive about content-type on application bootstrap

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#8589]
This condition is too restrictive:

https://github.com/vaadin/flow/blob/0fa1788c83776fe5b2e21750c8d3566729703a74/flow-client/src/main/resources/META-INF/resources/frontend/Flow.ts#L313-L317

It will trigger `onerror` if the Content-Type header contains e.g. the charset: `application/json;charset=ISO-8859-1` (common on many web servers).

**Comment by javier-godoy** [comment]
RFC8259 - https://www.iana.org/assignments/media-types/application/json 
> No "charset" parameter is defined for this registration.
>  Adding one really has no effect on compliant recipients.

**Comment by knoobie** [comment]
Because of some browsers, web server vendors and frameworks had to implement something with encoding. 
See the comment in spring framework about it:

https://github.com/spring-projects/spring-framework/blob/fe3b36af68d9659c7fddeb358061d33d554d849d/spring-web/src/main/java/org/springframework/http/MediaType.java#L122-L130

**Comment by heruan** [comment]
Any update on this?
