### ISSUE TITLE
Exclude HasDataView interface

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8618]
There are three getters for `DataView` object to be obtained from the component:
- `HasDataView` for common data view API, like a `getItems`, `getSize`, etc.
- `HasListDataView` for in-memory related API
- `HasLazyDataView` for lazy loading related API

Im-memory `DataView` DX tests shows the developers chooses `getDataView()` instead of `getListDataView` almost each time when they want to get the data view object from the component. Then they wonder why they are not able to see and use in-memory specific methods. It usually takes some time to realise to use another method, and they do that if they really know which method they want to use, but which is absent in returning interface. More-other, if the developer does not closely familiar with DataView concept, he may call `getDataView()` and use a generic `XXXDataView` interface and even not know about `XXXListDataView`. 

This ticket aims to consider the removal of `HasDataView` and its component-side implementation, at least until the developers claims it with a real use case examples.

**Comment by pleku** [comment]
Using the wrong getter from the component also came along with DX tests for `LazyDataView`.

The original idea why it was added was the existing users who are using a data provider with type like `DataProvider` instead of `ListDataProvider` or `BackendDataProvider` (or extending types). One alternative could be to just remove the `DataView getDataView()` but keep the `setDataSource` methods that return `DataView`.
Then again we have a lot of `setDataSource` overrides already now, and being able to remove two of them completely would help against the API bloat.

**Comment by mshabarov** [comment]
It looks like a trade-off between `Data View` API usability and coverage of the all cases. Could we figure out in advance how mush are the use cases for custom data providers not inherited from `ListDataProvider` or `InMemoryDataProvider`? And would they really use the `DataView` interface for their needs? Unfortunately I haven't got mush information to confidently choose the option either to remove it or keep. For me it would be safer to remove and then add if needed, than to keep and then remove, because in the second case it would be a breaking change for the developers who already have been using this API.

**Comment by pleku** [comment]
One comment from the DX test was that "if someone is using `DataProvider`, they will be able to cast it to the correct type". I also now think that we can make it more difficult for this not-so-common case in order to make is easier for majority of the cases.

I'd say we just remove the `HasDataView` and data views that are not either list or lazy in the components.

**Comment by Legioth** [comment]
If I understand correctly, the generic `getDataView()` method is very useful for generic logic (e.g. an add-on that produces a CSV export) that doesn't know what kind of data source a component is used. Removing it would mean that such generic functionality would instead have to `try` invoking `getListDataView()` and then fall back to `getLazyDataView()` if the first one throws. That doesn't seem like a good alternative.

I think we should encourage "regular" usage to capture whatever is returned when they call `setDataSource`. Using `getDataView()` should thus be necessary only in special cases where it might be fine to require that the user understands that they might want to (try to) cast the value to a desired specific type.

**Comment by pleku** [comment]
>I think we should encourage "regular" usage to capture whatever is returned when they call setDataSource. Using getDataView() should thus be necessary only in special cases where it might be fine to require that the user understands that they might want to (try to) cast the value to a desired specific type.

This is more difficult than one would expect. Even showing this approach in the examples and mentioning the returned object in the javadocs did not get users to store it. My observation is that it is related to the mindset that "setting a data source" is not expected to return anything. In a discussion yesterday with @mstahv he brought alternatives to setter like `bindItems` where it might be then more obvious that something is returned. Currently we are thinking about renaming it to `setData` because then it will be shown before the deprecated `setDataProvider` in Eclipse auto-complete.

I'm not sure if I like the idea that we make using data views more inconvenient for majority of users to make it easier for a couple of addon developers - I suspect the usage of the generic API is less than 2% of combined list+lazy. But if we don't want to remove it, we could rename it to `getGenericDataView()` or `getBaseDataView()` so maybe people would be able to choose the one they want better, but then again it is still less convenient than they just have one or two alternatives (list-always, lazy for couple components).

**Comment by mstahv** [comment]
We are talking about data binding often. Both for components and to forms. Maybe the method name could be *bindData* 🤔 Then Data would be somehow connected to the returned DataView object. Just throwing random ideas.

But in general, let's optimise for the most common cases and make compromises for cases we expect are being used by "experts only".

**Comment by Legioth** [comment]
Something like `getGenericDataView()` might make sense. My main point was to avoid a situation that requires using [exceptions for control flow](https://wiki.c2.com/?DontUseExceptionsForFlowControl).

**Comment by pleku** [comment]
Agreed on api review session that we keep the interface, but rename it

### Acceptance Criteria
- rename the generic data view getter to `getGenericDataView()`

**Comment by mshabarov** [comment]
Does it make sense to rename `HasDataView` to `HasGenericDataView` either?

**Comment by pleku** [comment]
>Does it make sense to rename HasDataView to HasGenericDataView either?

IMO that would also mean that the interface name is changed from `DataView` to `GenericDataView` and I don't see what benefits would this bring. Yes it would match the getter naming, but then again the getter name is IMO enough of the exception that "you most likely don't want to use this but either getListDataView() or getLazyDataView() instead"
