### ISSUE TITLE
Redirect on session close not working correctly

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#8623]
In Vaadin 14.2.0, the following code closes the session and redirects the browser to `/logout`.
```
add(new Button("logout", ev->{
	UI.getCurrent().getPage().setLocation("/logout");
	UI.getCurrent().getSession().close();
}));
```

In Vaadin 14.2.2 it closes the session and displays the message "_Tried to move from states TERMINATED to TERMINATED which is not allowed_" before redirecting the browser to `/logout`

This is a regression introduced in Vaadin 14.2.1, likely because of https://github.com/vaadin/flow/issues/8177

**Comment by denis-anisimov** [comment]
Reproduced.
Thanks for good description which allows to reproduce the issue.

**Comment by denis-anisimov** [comment]
There are two unrelated issues here:
- one is introduced by the fix for #8177 indeed: this is the message `Tried to move from states TERMINATED to TERMINATED which is not allowed`. But this message doesn't do anything and can be easily fixed.
- the redirect doesn't happen.

As I said: the error message doesn't relate to the absence of redirect. So this is not a regression because of fix for #8177:
if I remove this fix the behavior is the same except the message.

On the other hand it's indeed a regression introduced in `2.2.1`: the code works fine in `2.2.0`.

**Comment by denis-anisimov** [comment]
Alright....
I'm mixing behavior in two branches: `master` and `2.2`.
In `2.2` branch everything works as it should except this red client side message.
I will fix here only this message.

In the master branch there is this red message but in addition to that: redirect doesn't happen.
This is a separate ticket , I will create it. It's apparently also a regression but caused by something else.

**Comment by denis-anisimov** [comment]
Ticket for the `master`  branch: https://github.com/vaadin/flow/issues/8627
