### ISSUE TITLE
RouterLink click issue after programmatic navigation

### ISSUE THREAD

**Issue by heruan** [vaadin/flow#8689]
If from `/users` I navigate to `/users/123` with

```java
UI.getCurrent().navigate(Users.class, id);
```

then if I click on a `RouterLink` to `/users` nothing happens.

**Comment by jmycka** [comment]
I reproduced the same problem with version 16.0.0 after building an application in production mode. There is no issue on Dev mode.

**Comment by mshabarov** [comment]
Thank you, @heruan and @jmycka for the ticket. We are looking into this issue.

**Comment by joheriks** [comment]
I am unable to reproduce this problem on Vaadin 16 and 17 (in neither development nor production mode) with a simple project containing the following view:
```java
@Route("users")
public class UsersView extends VerticalLayout implements HasUrlParameter<Integer> {
    public UsersView() {
        add(new RouterLink("Routerlink to users",  UsersView.class));
        add(new Button("Programmatically to users/123", e -> UI.getCurrent().navigate(UsersView.class, 123)));
    }

    @Override
    public void setParameter(BeforeEvent event, @OptionalParameter Integer parameter) {
        System.out.println("Got parameter " + parameter);
    }
}
```

Please provide code context and ideally a small project that exposes the problem.

**Comment by igormilina** [comment]
This is duplicate of [8575](https://github.com/vaadin/flow/issues/8575), and it is reproducible in Vaadin 16, haven't tried in V17. It is important to note that the problem happens when navigating **back** to the original route.

**Comment by joheriks** [comment]
@igormilina Thanks for the ticket and description, this is now clear and reproducible with Vaadin 16. It should be fixed with `@vaadin/router` version 1.7.2 (see [8071](https://github.com/vaadin/flow/issues/8071)). To confirm this, you can try a Vaadin 17 prerelease (which includes the updated `@vaadin/router`)

**Comment by heruan** [comment]
Will this be available in V16? Unfortunately V17 brings breaking changes on the data-provider API which prevent us to update right now.

**Comment by joheriks** [comment]
@heruan Yes, the next maintenance release of Vaadin 16 will included the updated `@vaadin/router` dependency. As a workaround, you can until then use [npm mode](https://vaadin.com/docs/v16/flow/advanced/tutorial-switch-npm-pnpm.html) (instead of pnpm) or pin the version of `@vaadin/router` in `pnpmfile.js`.

**Comment by heruan** [comment]
@joheriks Not sure why, but I already see `"@vaadin/router": "1.7.2"` in my `packages.json` with V16 🤔

**Comment by haijian-vaadin** [comment]
Hi @heruan, I think it's because in v16, `pnpm` is used by default, and it's reading the version from [versions.json](https://github.com/vaadin/platform/blob/16.0/versions.json) file. I've made a fix yesterday, now waiting for another maintenance release.

I think the pnpmfile.js is overridden automatically every time you start the application.

So I think you can try to delete the `node_modules` and `target` folder, and then run the application with [npm mode](https://vaadin.com/docs/v16/flow/advanced/tutorial-switch-npm-pnpm.html), in this way, you should be able to get the 1.7.2 version of `@vaadin/router`.

**Comment by heruan** [comment]
Thanks, not sure what I'm missing but I've tried both Spring's `vaadin.pnpm.enable = false` and POM's plugin configuration `<pnpmEnable>false</pnpmEnable>` but I still get PNPM 😕

**Comment by joheriks** [comment]
Either of these should work for switching to npm. If you use `pnpmEnable` to set in the mode in the `configuration` section of ´vaadin-maven-plugin` (in the profile for development mode), can you verify that `target/classes/META-INF/VAADIN/config/flow-build-info.json´ contains a line `"pnpm.enable": false`?

**Comment by heruan** [comment]
I'd probably missed a `clean`, now I'm on NPM and 1.7.2 showed up.

**Comment by haijian-vaadin** [comment]
Does it work with `npm`, can we close the ticket? @heruan

**Comment by heruan** [comment]
It didn't happen yet with Router 1.7.2, I'll close this for now. Thanks!
