### ISSUE TITLE
Exception in StreamResourceWriter or InputStreamFactory will set Internal Server Error after Response has been written

### ISSUE THREAD

**Issue by roeltje25** [vaadin/flow#8740]
### Description of the bug
In our application we generate reports which can be downloaded. We have use a StreamResource with a StreamResourceWriter (we also tried an InputStreamFactory with the same results) which will generate the output for the client. When the generation of the data generates an exception Vaadin sets the response status code to 500 Internal Server Error in StreamResourceHandler.java line 80 to 85 (vaadin 14.3.1). However in the try-with-resource block the OutputStream is closed BEFORE the catch block is entered. Closing the OutputStream causes the response to write to the client (at least in our WildFly server using undertow). The status code is then not picked up anymore by the browser resulting in a download popup which has an empty file.
### Minimal reproducible example
A minimal example can be found here: https://github.com/roeltje25/streamresourcehandlerissue
### Expected behavior
When the link in the minimal example is clicked the download should not start, and in the browser network log the request should return with status code 500.
### Actual behavior
When the link in the minimal example is clicked the download starts (with a popup in chrome e.g.), the status code in the network log is 200 and the downloaded file is empty.
### Versions:
    - Vaadin / Flow version: 14.3.1
    - Java version: 
      openjdk version "13" 2019-09-17
      OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
      OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)
    - OS version:
    - Browser version (if applicable): Firefox 78.0.2
    - Application Server (if applicable): Jetty built into maven (jetty-9.4.28.v20200408; built: 2020-04-08T17:49:39.557Z; git: ab228fde9e55e9164c738d7fa121f8ac5acd51c9; jvm 13+33)

**Comment by roeltje25** [comment]
As an additional remark. It is not possible to easily add a global streamresource failure handler. For example to show a notification or things like that

**Comment by denis-anisimov** [comment]
Confirmed.

I disagree with the expected behavior though a bit.
>When the link in the minimal example is clicked the download should not start

The download should start. The mentioned example is very specific: it throws an exception immediately but that doesn't have to happen generally. The exception may be thrown at any point: some part of file may be read and downloaded and an exception may be thrown somewhere in the middle.
We may not prevent downloading : it should always start.
But we should return a server error status in case there is an error in the stream.

**Comment by roeltje25** [comment]
Dear Denis,

The problem with your perspective is that you cannot set the http Status
Code If the download started already, as the headers have been sent to the
client already at that point.

I agree that nothing can be done when an error occurs in the stream after
part of the resource itself has been written, the download indeed has been
started already. In the provided example, however, not even a single byte
has been transferred as the inputstream of the resource itself was not
created because of the IllegalStateException

An error during reading an existing stream can only be noticed client side
If content-length header, or transfer-encoding chunked or something like
that is used I guess. However, the issue in the example is with an
inputstream which is not even created in the first place.

With kind regards

Roel

Op wo 29 jul. 2020 14:24 schreef Denis <notifications@github.com>:

**Comment by denis-anisimov** [comment]
Dear Roel,
I would like to ask you :
- do not mix several issues together in one ticket
- keep ticket description short short 

I treat this ticket in as only one issue: the status code is `200` but it should be `500`.
I made a PR which fixes this issue. This is definitely a bug and doesn't require any other 
discussion.

If you have other issues with the current behavior then please create another ticket.

Download is started by the browser so we may not prevent downloading even though there is no any single byte to read.
In the extremely corner case when the exception is thrown on `StreamResource` creation  we may add a dedicated logic which I don't really know what should do.
This is a corner case for sure and this is totally different issue. It requires a discussion what should be done in this case generally and that's why it cannot be a part of this ticket about status code.

**Comment by roeltje25** [comment]
> Dear Roel,
> I would like to ask you :
> 
> * do not mix several issues together in one ticket
> * keep ticket description short

I agree, Consider my additional remark about a StreamResource errorhandler as an afterthought that I could have put elsewhere. I will do this in the future. Thanks. 

> I treat this ticket in as only one issue: the status code is `200` but it should be `500`.
> I made a PR which fixes this issue. This is definitely a bug and doesn't require any other
> discussion.
Absolutely. I agree.
> 
> If you have other issues with the current behavior then please create another ticket.
> 
> Download is started by the browser so we may not prevent downloading even though there is no any single byte to read.
> In the extremely corner case when the exception is thrown on `StreamResource` creation we may add a dedicated logic which I don't really know what should do.
> This is a corner case for sure and this is totally different issue. It requires a discussion what should be done in this case generally and that's why it cannot be a part of this ticket about status code.

My last comment was not meant to add anything to the ticket, I was trying to disagree with your opinion that the expected result was wrong. In case the InputStream is created, indeed the download should have started, in case the InputStream did not even get created, the download should not have started at all. Indeed, a download request that has status Internal Server Error 500 does not popup a download in Firefox or Google Chrome.

Anyway, thanks again for the fix and the pointers

**Comment by denis-anisimov** [comment]
It's very good that we are on the same page now.
Thanks.

My point about download is:
- the download is initiated by the browser.
- the `StreamResource` is created only when the request is coming from the browser.
- at this point the download is _already_ started: we can't do anything here anymore.
- the only thing we can do is: set the status code (which is done in the fix).

The reason why I don't see a difference between 0 bytes read from stream (or not even created stream) and some bytes : it doesn't matter because browser _already_ initiated download.
This is a runtime check.
This is not possible to do statically.

The simplest way to prevent this could be : create a stream in advance and check whether this is possible.
But this is wrong. Since this happens at runtime.
The stream creation may fail when it's called in advance and it may be fine when it's called on download initiation.
Only developer may know the static code essence: if it's known that the stream won't be created at all then the link should not be added/created at all. And we may not do this instead of developer.
So I just don't even see how we may prevent a download generally here : the "in advance" strategy is wrong.
