### ISSUE TITLE
Investigate latest front-end build tools to achieve better development time performance and modularisation 

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow#8757]
There are potential new tools that could make our front-end build monster disappear, at least for the development mode builds. Those should be investigated and prototyped to see if they can make the front-end build faster and more stable. Also if modular front-end modules could be achieved for example OSGi and Portal users. 

Ideas/technologies that should be investigated:

* WebPack 5 and module federation (preliminary investigations already started a year ago: https://github.com/vaadin/flow/issues/6773, Implement chunk: https://github.com/vaadin/flow/issues/5537 )
* Snowpack 2
* "default widgetset" https://github.com/vaadin/flow/issues/6248

Bonus part to keep in mind when experimenting with these is to get also front-end resources to behave as well as java changes now do: https://github.com/vaadin/flow/issues/8001

**Comment by knoobie** [comment]
I can't stress enough that the current process is sh**. We currently have some trainees with us that are "forced" to develope on older pcs (3-4 years) and the starting of an application is insane. We are talking about 10min until a simple vaadin spring boot tutorial app starts. 

Running maven with -X resulting in multiple minutes waiting at this line alone:

```
[DEBUG] Configuring mojo com.vaadin:vaadin-maven-plugin:14.3.1:prepare-frontend from plugin realm ClassRealm[plugin>com.vaadin:vaadin-maven-plugin:14.3.1, parent: sun.misc.Launcher$AppClassLoader@70dea4
e]
[DEBUG] Configuring mojo 'com.vaadin:vaadin-maven-plugin:14.3.1:prepare-frontend' with basic configurator -->
[DEBUG]   (f) frontendDirectory = XXX\test\vaadin-crm\frontend
[DEBUG]   (f) generatedFolder = XXX\test\vaadin-crm\target\frontend
[DEBUG]   (f) nodeDownloadRoot = https://nodejs.org/dist/
[DEBUG]   (f) nodeVersion = v12.16.0
[DEBUG]   (f) npmFolder = XXX\test\vaadin-crm
[DEBUG]   (f) pnpmEnable = false
[DEBUG]   (f) project = MavenProject: com.vaadin.tutorial.crm:vaadin-crm:1.0-SNAPSHOT @ XXX\test\vaadin-crm\pom.xml
[DEBUG]   (f) requireHomeNodeExec = false
[DEBUG]   (f) webpackGeneratedTemplate = webpack.generated.js
[DEBUG]   (f) webpackOutputDirectory = XXX\test\vaadin-crm\target\classes\META-INF\VAADIN
[DEBUG]   (f) webpackTemplate = webpack.config.js
[DEBUG] -- end configuration --
[DEBUG]
>>> Running prepare-frontend in Vaadin CRM project
System.properties:
productionMode: null
bowerMode: null
compatibilityMode: null
webpackPort: null
project.basedir: null
Goal parameters:
productionMode: false
compatibilityMode: null
compatibility: false
npmFolder: XXX\test\vaadin-crm
Token file: XXX\test\vaadin-crm\target\classes\META-INF\VAADIN\config\flow-build-info.json
Token content: {"compatibilityMode":false,"productionMode":false,"npmFolder":"XXX\\test\\vaadin-crm","generatedFolder":"XXX\\test\\vaadin-crm\\target\\frontend","fr
ontendFolder":"XXX\\test\\vaadin-crm\\frontend","pnpm.enable":false,"require.home.node":false}
```

Environment:
- Tutorial: https://vaadin.com/learn/tutorials/modern-web-apps-with-spring-boot-and-vaadin
- Windows 7 
- Lenovo 460T

**Comment by denis-anisimov** [comment]
We still cannot use webpack 5. Details are here: https://github.com/vaadin/flow/issues/6773#issuecomment-663474834

**Comment by denis-anisimov** [comment]
`Snowpack 2`: may be I'm missing something but I don't see how it may help dramatically.
As I understood it's just a replacement for webpack dev server.
It works quite similarly : it runs a dev server which checks the files changes and provides a way to include the result of its work into the page.
The difference between webpack and snowpack is : webpack makes a single bundle which is included as one file into the page.
`snowpack` makes several files.  I didn't get how exactly it includes the result into the page. It produces the result somewhere into the `node_modules`: the second run of `snowpack` uses cashed result and it does rebuilding only if `node_modules`  is removed.
The  initial "fresh" start time for webpack and snowpack is quite similar.
So the only difference is the produced result : one bundle file (webpack) vs several files (snowpack) (as it's stated in the docs at least). This is only valid for dev mode since for production mode it's still recommended to use one bundle.

As a result : I don't see the benefit of using snowpack. May be I'm missing something but having several files instead of one bundle file is not something we can use for improvement. As I understood the configuration is very similar : you have to make a page which includes all the imported modules ( `generated-flow-imports.js` is generated currenty). Then snowpack produces the result based on the imported modules. Same thing webpack does (the only difference is a number of files).

As I understand (not sure) webpack will regenerate the bundle file in case of changes in `
generated-flow-imports.js`.
And snowpack will also regenerate it resulr in case of changes. 
Again the difference is only in the number of files. Theoretically regeneration of one file chunk file (snowpack) is faster than regeneration the whole bundle.
But in fact I don't think it affects the performance so much.
Our main issue currently the long initial "transpilation" which is the same in both cases.

So overall (if I didn't miss anything important) I don't see serious reasons to switch to snowpack especially considering we will need to rewrite a lot f code (Java support side for snpwpack).

The last item "default widgetset" is just a separate ticket: I think it needs to be just done, not sure what to investigate there.

I'm closing this ticket. Please reopen if you think there are missed things.

**Comment by Artur-** [comment]
Snowpack benefits should be:
1. It copies and transpiles and rewrites files from `node_modules` to `web_modules` once and not on every startup. This surely speeds up all startups after the first one as there is no "webpack compile" phase at all
2. It should be possible to ship the `web_modules` folder with a starter project, eliminating the need to even transpile once
3. Every change in a file requires recompiling only that file (should be on the level ~50ms) whereas a webpack compile can take 10-20s today. 

Anything you performance test on a new Mac is worthless. Try on a 5 year old Windows machine without an SSD.

**Comment by denis-anisimov** [comment]
Alright, thanks @Artur- a lot for clarification!

**Comment by denis-anisimov** [comment]
>It copies and transpiles and rewrites files from node_modules to web_modules once and not on every startup.

Yes, I confirm that.

>It should be possible to ship the web_modules folder with a starter project, eliminating the need to even transpile once

Right, that's a good point.

>Anything you performance test on a new Mac is worthless. Try on a 5 year old Windows machine without an SSD.

:( That's why I don't see any performance improvement .

**Comment by Artur-** [comment]
We should ignore production build performance here because that is not what developers see daily. That is something that happens in the background on some build server.

If development mode and production mode work in different ways, we need to make sure that build customizations are still possible to do, static files work as expected etc.

**Comment by denis-anisimov** [comment]
I expect that prototyping for Snowpack will take quite much time and I would suggest to make a decision and just do it.
Investigation of performance difference between Snowpack and Webpack can't be done by me because of Artur's comment: https://github.com/vaadin/flow/issues/8757#issuecomment-664184514

I think investigation should be redone by someone else on slow machine.

**Comment by pleku** [comment]
Trying to clarify the investigation targets a bit:

#### Webpack 5 for development mode:
- Check that we can actually now use Webpack 5 for this, there should be a new webpack-cli version available soon or at least the fix has been included now so a custom patch version should be used https://github.com/vaadin/flow/issues/6773#issuecomment-663474834
- Check how much Webpack 5 itself is faster than 4 as it has been claimed it will be. #6773 can be closed after such benchmark
  - Are incremental builds faster when changing frontend files (than with Webpack 4) ?
  - Are incremental builds faster when starting server again (than with Webpack 4) ?
  - Is initial startup and first build faster (than with Webpack 4) ?
- Investigate how we could "split out the default widgetset" by using the module federalization feature:
  - Probably (?) could be good to get separate modules for core and commercial components.
  - Could these (component modules) be built with platform release and shipped as static resources that are used to speed up development build ?
  - Should we build & ship a module of Flow introduced dependencies like vaadin-router ? 

#### Webpack 5 for production mode:
- Get it to work (first)
- Can we start splitting bundles now with it, without building any support for `@Chunk` or such for Java ?
- We should try to get the micro frontend project setup running with module federalization instead of custom plugin https://github.com/Artur-/iothttps://github.com/Artur-/iot
  - Target is to be able to update vaadin / app module easily
  - This will be needed for handling OSGi later on

#### Snowpack for development mode
- Get it to work
- Are incremental builds faster when changing frontend files (than Webpack 4 / 5) ?
- Are incremental builds faster when starting server again (than Webpack 4 / 5) ?
- Is initial startup and first build faster than with Webpack ?
- Can we ship prebuilt parts (with e.g. starters) to speedup initial startup, if yes then how much faster ?

**Comment by caalador** [comment]
Production build is blocked for WP5 at the moment due to https://github.com/webpack/webpack/issues/10831 when using commercial add-ons

**Comment by knoobie** [comment]
FYI: The problem of my college could be fixed thanks to the comments in https://vaadin.com/forum/thread/17779813/build-hangs-on-vaadin-maven-plugin-execution - the combination of Windows 7, npm and proxy was the culprit.

**Comment by mstahv** [comment]
@caalador @pleku Would it make sense to use the `SET NO_UPDATE_NOTIFIER=1` setting mentioned in the blog always for npm if a version installed automatically by Vaadin is in use 🤔

**Comment by knoobie** [comment]
@mstahv I was wondering why the pr https://github.com/vaadin/flow/pull/6860 did not fix the problem above, because that PR sets the command line argument for npm(?).

**Comment by pleku** [comment]
Looking at #6860 and then the code we have, it would seem to me that `--no-update-notifier` used when checking the version of npm.

But however, if the user is using a `.npmrc` file then it might not be applied, based on this https://github.com/npm/npm/issues/20698 ?

I wonder if then we should just simply run `npm set update-notifier=false` after we've automatically installed node&npm.

Second but - this probably should be its own ticket.

**Comment by joheriks** [comment]
The result of the Snowpack investigation is that there is significant performance improvement opportunity in repeated startups (*hot start*) when using the `snowpack` dev server. The speedup comes from not having to create a bundle and Snowpack's local cache (in `node_modules/.cache` directory). On one test project (start.vaadin.com with a single "Card list" view), the hot startup time was almost instantenous (less than 2 s, compared to 8 s with Webpack 4).

The main issue is that cold starts are slower compared to Webpack 4. Snowpack processing of all Vaadin components' frontend assets took about 20 seconds (against 8 second with Webpack 4). In principle, all Vaadin components would not need to be processed but finding out which ones are needed via class scanning has its own performance issues (particularly with Spring Boot projects). While the slower cold start is quickly amortized away by the faster hot start, adding 10+ seconds to the initial build is not great DX.

Another possibility explored was running Snowpack in `build --watch` mode. In this mode, Snowpack monitors frontend files for changes, and automatically rebuilds the site into a local directory (`build`, to be served by DevModeHandler) containing the processed `.js`. However, in this mode Snowpack does not use the `build` directory as a cache, meaning that it is rebuilt during both hot and cold restarts. In the particular example tested, the build took about 20 seconds.

Minor limitations and issues encountered.
- Dev server logging assumes output is TTY, sends "clear screen" escapes and emitting the same log messages multiple times. This makes the server log ugly and means that messages from Snowpack cannot be used for monitoring its state as we currently do for Webpack.
- Need to provide custom plugin for converting CSS into JS modules that export the CSS content as a string (not built in).
- Compared to webpack, the number of requests is significantly larger as there is one for each .js. This was not perceived to have a negative impact on localhost development at least.

**Comment by Legioth** [comment]
I wonder whether an alternative approach could help deal with the initial startup time. I'm thinking of leaving `flow-generated-imports.js` empty and instead dynamically inject the actually used imports based on the same lookup of attached components that is currently used to detect whether to load the fallback bundle.

I'm not 100% sure what would be the best way of dynamically injecting those imports. If we can construct a URL to use with dynamic `import()`, then that might be the best alternative. Otherwise, we could also generate a big `flow-generated-imports` where each regular static `import` is instead replaced with an exported function that does a dynamic `import()` of that particular dependency.

**Comment by Artur-** [comment]
> Snowpack processing of all Vaadin components' frontend assets took about 20 seconds (against 8 second with Webpack 4).

Is this processing related to the project in any way or can processed files be shipped with the project (larger download, faster startup)

**Comment by pleku** [comment]
>Is this processing related to the project in any way or can processed files be shipped with the project (larger download, faster startup)

I understood that it is not possible at the moment at least with what was suggested before here with the `web_modules` folder. The cache is inside `node_modules/.cache` and at least this far `node_modules` has been part of `.gitignore` instead. Trying to ship anything inside there seems flaky, but maybe it can be something that is "prepopulated" in online environments like Gitpod ?

In the issue about "dev persistent cache" it is said that "the first ever run will still be slow" so I think that means that it is not possible https://github.com/pikapkg/snowpack/pull/305#issuecomment-626208841

**Comment by joheriks** [comment]
Got from the Snowpack dev chat that while having the dev server cache stored elsewhere than `node_modules` (suitable for version control) is not a supported feature at the moment (as there has not been a use case for that), technically it may be feasible to add.

**Comment by pleku** [comment]
Vite is the way to go for now and it has been shipped in V22 behind a feature flag.
