### ISSUE TITLE
ListDataView: use ArrayList as the default option

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8761]
When calling `grid.setItem(personA, personB)`, it's using `Array.asList()` as the default option. As a result, many of the API provided by the `ListDataView` won't work, since they are index-based. such as `ListDataView.addItemAfter()`.

**Comment by mstahv** [comment]
Getters should work fine, but mutators don't work if the underlaying collection is immutable. Also when assigning a collection instead of an array/vararg. This is mentioned in the javadocs and documentation, but I agree it may appear as a bug. In-fact, I reported this same issue to the team as well, but it "works as coded". 

A potential way to improve the experience would be to create an ArrayList instead of using Array.asList when using varargs, but I guess we don't want to replace the collection.

Could you @haijian-vaadin verify if you had an issue with getNextItem?

**Comment by haijian-vaadin** [comment]
oh, yes, actually `getNextItem` works.

**Comment by mstahv** [comment]
Let's keep this open and see if more people expect this to work this way. An easy and safe enhancement if seen necessary, but I'd guess quite obsolete for real world use cases. But I might be wrong...

**Comment by pleku** [comment]
To be honest, this feels to me like an existing bug that we have been carrying out since Vaadin 8. It has been introduced there as an accident and I don't know why we would not fix this.
