### ISSUE TITLE
Error appearing in Chrome DevTools

### ISSUE THREAD

**Issue by MatsG23** [vaadin/flow#8800]
![a](https://user-images.githubusercontent.com/60609373/88950905-95003400-d295-11ea-857d-21480241ec54.png)
I saw this 501 Error in Chrome DevTools.

**Comment by mshabarov** [comment]
Hello, @MatsG23. Please provide a minimum reproduce example, steps to reproduce and the environment description: OS, Java, Vaadin, Chrome versions. Thanks.

**Comment by mshabarov** [comment]
Sorry, but until you can provide the code that reproduces the issue, there is nothing that we can do. Until that we consider this an issue specific to your application. Please reopen the issue if you discover a root cause not dependent on your application and can provide the code to reproduce the issue.
