### ISSUE TITLE
Embedded applicaiton : Link created by StreamResource doesn't lead to requested document 

### ISSUE THREAD

**Issue by tagtraeumer** [vaadin/flow#8813]
### Description of the bug

When including a Vaadin View into an existing Spring JSP application using WebComponentExporter and JSP i cannot offer a File Download using Anchor and StreamResource. The URI from the StreamResource and the resulting link in the Anchor lead to a non existing site:

Could not navigate to 'v/main/VAADIN/dynamic/resource/1/2e0165b5-02a1-4d8b-9dfe-0cc4f31c3a63/label.pdf'
Reason: Couldn't find route for 'v/main/VAADIN/dynamic/resource/1/2e0165b5-02a1-4d8b-9dfe-0cc4f31c3a63/label.pdf'

### Minimal reproducible example

I created a running example project:
https://github.com/tagtraeumer/vaadin-issue-streamresource

I used a clean starter using spring-boot. All source code files are in the same package, additionally to that i added some dependencies to the POM, changed the application.properties (changed it to yaml) and added a jsp as well as a template file for creating the PDF

### Expected behavior

StreamResource in combination with WebComponentExporter (Spring & JSP) creates an URI that leads to the requested PDF like the following:
http://localhost:8080/VAADIN/dynamic/resource/1/2e0165b5-02a1-4d8b-9dfe-0cc4f31c3a63/label.pdf

### Actual behavior

The resulting link created by StreamResource includes the servlet path: e.g.

http://localhost:8080/v/main/VAADIN/dynamic/resource/1/2e0165b5-02a1-4d8b-9dfe-0cc4f31c3a63/label.pdf

### Versions:
    - Vaadin / Flow version: 14
    - Java version: 1.8
    - OS version: Windows 10
    - Browser version (if applicable): Tested in Chromiom Edge & Firefox
    - Application Server (if applicable): Spring boot (dependencies see linked github project)
    - IDE (if applicable): STS 4

**Comment by denis-anisimov** [comment]
Confirmed.
The link in the embedded application refers to the URL which is based on the enclosing app URL and not on the embedded app link

**Comment by denis-anisimov** [comment]
The reason is quite simple:
the method `Anchor::setHref`  generates a `URI` which is relative to the app base URL.
Then this generated string is set as an `href` attribute value.
The problem is that the generated URI is correct relatively for the embedded app but not for the embedding app.
That's why it doesn't work.

The workaround is call `href` attribute one more time to the corrected value (get it via getHref() and prefix with  "../../") but that should be done in the end of request and when the element is already attached.
So something like 
```
getElement().getNode().runWhenAttached(ui -> ui.getInternals().getStateTree()
                .beforeClientResponse(....
```

should be used to correct the `href` value.

The real issue we need somehow to fix: not sure how since we just set the string for `href` without providing any semantic for this string for the client side. And only the client side knows that this URI should be prefixed with the embedded app base URI.

**Comment by denis-anisimov** [comment]
That could be a solution : https://github.com/w3c/webcomponents/issues/581
But it doesn't exist...

**Comment by denis-anisimov** [comment]
> 
> The workaround is call `href` attribute one more time to the corrected value (get it via getHref() and prefix with "../../") but that should be done in the end of request and when the element is already attached.
> So something like
> 
> ```
> getElement().getNode().runWhenAttached(ui -> ui.getInternals().getStateTree()
>                 .beforeClientResponse(....
> ```
> 
> should be used to correct the `href` value.
> 

Sorry, the workaround won't work since setting the attribute to another value will unregister the resource so the URL won't work after that.

**Comment by denis-anisimov** [comment]
There is still a workaround but instead of using `setAttribute("href"` on the server side ( or `Anchor::setHref` ) one should set it on the client side directly via JS: `getElement().executeJs("this.href=$0;",updatedHref);`.
It will desync the client side and server side but then the resource will be still registered on the server side and the client side will have the correct value.

Or just wait for the fix.
