### ISSUE TITLE
Keep V18 compatible with the `offlinePath` property of `@PWA`

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#8856]
When upgrading a Vaadin 12+ app that uses the `@PWA` annotation to Vaadin 18, I want the `offlinePath` property of the `@PWA` annotation to remain working as before, so that my migration is easier. 

The `offlinePath` property in V12+ is a path to a static 'offline page' HTML file that's served by the service worker instead of the bootstrap page when the app is offline. In V18 doing exactly the same does not make sense because the same app shell remains active also when offline. The expectation is that the 'offline page' HTML is displayed in place of the server-side views, not in place of the entire application shell.

One solution to this would be creating a 'compatibility offline view' web component that renders the contents of the custom offline page inside an iframe.

DoD:
 - Having a V17 app with a `@PWA` annotation and a custom `offlinePath`, after an upgrade to V18, when the app goes offline I want to see the content of the custom `offline.html` rendered instead the app shell (i.e. the behavior in V18 remains exactly the same as it is in V17 and no new offline features are available to the app until the developer removes the `offlinePath` property from the `@PWA` annotation).
 - same as above, but instead of using a custom `offlinePath` property, the app has customized content in the default `offline.html` file path -> the presence of the `offline.html` resource is detected and when the app is offline, the content of `offline.html` is rendered instead the app shell
 - when the `offlinePath` property of the `@PWA` annotation is not set, when offline the app renders the app shell. See https://github.com/vaadin/flow/issues/9132.

**Comment by Haprog** [comment]
The issue description should be updated (see https://github.com/vaadin/flow/issues/8855#issuecomment-677572873) but I think the main point is keeping backwards compatibility so that `offlinePath` still keeps working even after implementing #8854.

**Comment by joheriks** [comment]
Will `default-offline-page.html` served from `flow-server` still have a role after this is implemented? In essence: shall the V18 user be able to write `@PWA(offlinePath="offline.html")` _without providing a custom_ `offline.html` and then expect to get the default V17 offline page replacing the whole appshell?

**Comment by vlukashov** [comment]
> Will `default-offline-page.html` served from `flow-server` still have a role after this is implemented? In essence: shall the V18 user be able to write `@PWA(offlinePath="offline.html")` _without providing a custom_ `offline.html` file in their project and then expect to get the default V17 offline page replacing the whole appshell?

That would be a reasonable expectation. The intent here is to keep the app working in the same way as before the V18 upgrade, if it uses the `offlinePath` property at all. Any use of the `offlinePath` property (other than `offlinePath = null`) would effectively disable the offline app shell caching introduced in V18.

**Comment by joheriks** [comment]
Followup: do we have a conclusion what to do when this V17 "PWA compatibility mode" is enabled (i.e., `offlinePath` is defined), and the the following happens:  user is on a client-side view, goes offline, then navigates to a server-side view (the same scenario described in #9132). The two sensible alternatives seem to be:

1. Display the stub introduced as per ticket #9132
2. Display the offline page instead of the appshell

Noting that V17 does not do 2, but rather shows an loading indicator and a blank page. Only when reloading the page do you get the offline page.

**Comment by Haprog** [comment]
Since this issue is about compatibility. I'd say the minimum is that the behaviour/UX should not be worse than it was in V17. So in this context it would be ok to keep the behaviour the same in this case (blank page + loading indicator if that is how it used to work).

But if we can make it better with low effort (or create a ticket about making it better if it's not trivial) then I think both options 1. and 2. as described above are ok. I think 1. makes a bit more sense as you can still navigate with menus (to client side views for example).
