### ISSUE TITLE
Investigate changes needed for fading away polymer template

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#8861]
Since there are classes in `com.vaadin.flow.component.polymertemplate` that are not related only to polymer template after introducing lit support, we should investigate how much breaking changes it would cause for the applications if we move the shared classes to another package. Or another option is to duplicate those classes and support both, but this might be a bit confusing.

If the breaking changes are considered to be too severe, we can then just keep the wrong package name to annoy and remind us about this obsolete technology.

The target is anyway to by minimum deprecate classes that are only related to `PolymerTemplate` and not shared features with `LitTemplate`, like the `TemplateModel` (and anything that is tied to it). The plan is to remove those after the next LTS but keep them until that as deprecated.

**Comment by denis-anisimov** [comment]
The  shared classes at the moment are only:
- `IdMapper`
- `ParserData`
- `IdCollector`

All those classes are not public API in fact but rather just internal utility classes which are not supposed to be used externally anyhow.
So we can do whatever we want with them:
- keep them in the current package and use from lit package
- duplicate them in another package
- move them into another `internal` package. Technically this decision is not backward compatible but as I already noted: those classes were not designed as a part of public API. We can deprecate them and move copies into another `internal` package and just delegate every call to the those moved classes.

Current Lit template support is implemented so that `LitTemplate extends Component` and not any `AbstractTemplate`  or 
`PolymerTemplate`.
`AbstractTemplate`  is not needed since it's based on which we want to get rid of.

`EventHandler` is a tricky annotation.
Technically it's not used for Lit template. And it's not used directly in polymer template support.
It's rather a generic functionality which we perhaps also want to keep for Lit templates in the future: call server side (annotated) methods from the client side.
I don't know what to do with this annotation: we may not extend annotations. Moving it to another package will break compatibility. Keeping it as is will be confusing.

The same situation with `Id` annotation.  Currently it's not used. But if we want to support this feature for Lit templates then it's not clear what to do...


`RepeatIndex` is the annotation which is shorthand for `@EventData("event.model.index")`   and I don't know whether it's applicable or not for Lit. May be not. So it may be safely ignored I suppose.

All other classes are Polymer template impl related only and can be ignored.
