### ISSUE TITLE
Vaadin TypeScript: Offline form submitter

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#8893]
As a developer, I want my TypeScript form to be able to work offline so that I can save the form data locally when offline and automatically send the data to endpoints when getting back online.

DoD:
1. Have an `OfflineFormSubmitter` in `@vaadin/form` package
2. The `OfflineFormSubmitter` takes the following constructor parameters:
- `endpointMethod: (value: T) => Promise<T|void>`, the endpoint method that the form data should be submitted to
- `onDataSavedLocally?: () => void`, the callback when data is saved locally
- `onDataSyncSucess?: () => void`, the callback when data sync succeeded
- `onDataSyncFail?: () => void`, the callback when data sync failed
3. When the user is online, the form data is submitted to the endpoint directly.
4. When the user is offline:
4.1. The form data is saved locally(local storage or indexDB). 
4.2. Server-side Validation is skipped. Client-side validations are kept. 
4.3. It also registers an online event listener to the window, so that when the user is back online, the locally saved data is submitted to the `endpointMethod`. The locally saved data is removed.
5. `OfflineFormSubmitter` has a public `submit()` method.

Limitation:
When user saved a form offline, then he refreshes the page, the window online listeners are lost, local data cannot be submitted.
Possible solution:
After page load, we can 
- check what are the locally saved forms and submit them, which requires an additional parameter in the local data to describe how the form could be submitted.
- Or simply remove all the legacy local data.

A quick prototype is available at https://github.com/vaadin/flow/tree/haijian/offline-form-prototype

**Comment by Legioth** [comment]
That's quite many constructor parameters. Would it make sense to instead use a configuration object of instance fields for the optional ones?

What's the purpose of those callbacks - in which cases would an application use them?

Is `onDataSyncSucess` called also if submitting while online?

If implemented to submit again after page load (or if returning online again after doing a page refresh while offline), then how would that logic actually be triggered? Would we inject a check for it so that it's always run, or application logic explicitly trigger the submission?

What if server-side validation fails when going online?

**Comment by haijian-vaadin** [comment]
> What's the purpose of those callbacks - in which cases would an application use them?
For example, show a notification to the end-user about the status.

> Is onDataSyncSucess called also if submitting while online?
No, only offline

We came up with a new design in the grooming session. Closing these tickets for now, will make new ones tomorrow morning.
