### ISSUE TITLE
Parse initial disabled attribute value from templates

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#8973]
Follow up on #8957, given a template with
```html
<div id="foo" disabled></div>
``` 
The initial attribute value should reflect the `enabled` state on server side for an `@Id` mapped component, like
```java
@Id("foo") Div fooDiv;

fooDiv.isEnabled(); // returns false initially
```
Toggling the disabled state initially for a component in a template can be considered a reasonably common thing to do via designer. The component is then later on enabled via server side Java logic.

**Comment by pleku** [comment]
Not done yet. The users will expect that 
```html
<vaadin-button id="button" disabled>My button</vaadin-button>
```
and
```java
@Id("button") Button button;
button.isEnabled(); // returns false
button.setEnabled(true); // -> button will not be disabled anymore, no attribute in dom
```
The whole purpose of this feature is to make sure that the state in template maps correctly to the component APIs and allows coding the UI logic in Java. If the user can't enable the button anymore, then this is broken. This is a very special case, but this is how it should go.

**Comment by denis-anisimov** [comment]
This issue has nothing to do with templates.
It's a generic issue and should be reported separately.
But I don't want to start one more useless discussion.

**Comment by pleku** [comment]
Agreed that we would make this work only for Lit templates as the risk for regression is nonexistent for those.

We should document the limitation of `isEnabled()` and `setEnabled(boolean enabled)` not cascading to children like they do with "normal" Java component API, because the template hierarchy is not parsed. It should be clearly shown that for the given template
```html
<vaadin-vertical-layout id="layout">
    <vaadin-text-field id="textfield"></vaadin-text-field>
    <vaadin-button id="button"></vaadin-button>
</vaadin-vertical-layout>
```
```java
@Id("layout)
VerticalLayout layout;
@Id("textfield")
TextField textField;
@Id("button")
Button button;

layout.setEnabled(false);
textfield.isEnabled(); // would return true !
button.isEnabled(); // would return true !
```
The limitation should be added to https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/polymer-templates/tutorial-template-intro.asciidoc#known-limitations-of-templates
Also the limitation on what lit template syntax is supported (and what is not) should be added to the limitations list.

**Comment by denis-anisimov** [comment]
The question is about polymer templates: how `setEnabled`  should behave ?
Should it be set based on `disabled`  attribute at all (and then there will be no way to set it enabled back as it's now) or 
it should not be set at all for polymer elements (so basically revert the current behavior for polymer templates) ?

**Comment by denis-anisimov** [comment]
This bug is caused by the requested design of `setEnabled` on the server side and has no any relation to the client side (as I though initially).
The problem is in the desync between Element API and Component API.
`Element::setEnabled` makes the Element disabled on the server side without any additional action accept disallowing to accept RPC.

_IF_ there is a component mapped to the `Element` then  in addition to that `Component::onEnabledStateChanged`  is called which sets `disabled` attribute and calls this method for any child.

So the behavior is dramatically different depending whether the Element mapped to Component or not.
From my point of view this design is fundamentally broken: `Element` should not know anything about `Component` . And this is the cause why we have such weird bugs: it's totally unexpected.

What happens with `@Id`  mapped Element: `setEnabled`  is called for the `Element` and you expect that everything will just happen out of the box.
Nothing works because `Element` is not mapped _YET_ to the `Component` . So the code which should set the attribute is never invoked.

We may not call the code which sets the `disabled`  attribute _after_ mapping to the `Component`  : `Component`  CTOR may want to call `setEnabled`  with a different value and it's absolutely expected that it will set in the end to the value which user requested in the CTOR.

So to be able to fix this one more ugly workaround is required which will call `setEnabled`  in absolutely unexpected place which should not care about `setEnabled` at all.

The code becomes less and less maintainable with such design decisions.
