### ISSUE TITLE
Two webpack-dev-servers started if the application is restarted during webpack startup

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8981]
### Minimal reproducible example
```
vaadin init double-webpack --latest
cd double-webpack
mvn install # Only to generate webpack.config.js
```

Add the snippet to the start of webpack.config.js
```
const fs = require("fs");
if (!fs.existsSync("target/classes/foo.txt")) {
  fs.writeFileSync("target/classes/foo.txt","Hello");
}
```

Run 
```
mvn
```

### Expected behavior
One `webpack-dev-server` process is running

### Actual behavior
Two `webpack-dev-server` processes are running

### Versions:
    - Vaadin version: 17
    - Java version: 11
    - OS version: macOS

**Comment by caalador** [comment]
It would seem that the problem is that when the first dev-server is starting we touch files that the server sees as a change and reloads trying to start a new dev-server which will start as the first has not at this point in time written the port information to the DevServerPortFile. 

We would probably need a temporary file while starting dev-server that can be checked and waited upon if exists when startting a dev-server.

**Comment by denis-anisimov** [comment]
Temporary file has one disadvantage: if it's not removed at the correct point (e.g. because of JVM crash) then webpack won't ever start after that.

The suggestion is to use some Java private flag instead (may be `static` ).
That flag won't survive during server restart but temporary file has the same issue (the file itself will survive of corse but it's name has to be somehow travel from one server instance to another and that's the same issue with Java flag or global property).

We need this flag only for very short period of time: before initiating webpack server start up until the server port file is written.
It's quite unlikely that server will be restarted within this interval.

So the suggestion is to use some Java flag which prevents another server start once the first start is initiated up until the server port is written. Once the port file is written the flag should be cleared out.

This needs to be tested at least with :
- Spring dev tools
- Jetty scan interval.

**Comment by denis-anisimov** [comment]
@Artur- , I was able to reproduce this using totally different steps based on guess of back engineering of the original steps.
The reason is : 
`vaadin`  command doesn't exist in my environment.
Could you please provide steps to reproduce (in future) which can be used on any environment ?

**Comment by denis-anisimov** [comment]
My initial understanding of the issue was wrong: the issue is caused exactly by the fact that Java reload happens because of
writing into `target/classes`  which is done by webpack on its start.

And two absolutely different cases to consider:
- partial Java hot reload (which is done by Spring dev tools and JRebel e.g.)
- complete web server restart which is done by Jetty plugin e.g.

The cases are absolutely different and both has issues.
The first case don't need anything to store but properly written Java code which is not the case with `DevModeHandler` : the initial code is one big very initial draft and it horribly designed.
The second case can't be solved with storing anything in Java classes since web server is completely restarted which means that the app is loaded (at least) by other classloaders and nothing is reused from previous app (initially partially started).
The problem is: the first webpack hadn't completed yet it's startup but the web app has been restarted and "another" `DevModeHandler` instance is trying to check a webpack server port and start a new one if there is no-one.
It has no sense to have boolean flag: whether the server is already started or not. To be able to avoid the second webpack 
startup one needs the port of the webpack server which (may be) is starting up. 
Otherwise there are two options:
- stop everything and fail
- or proceed with a new webpack instance.

So to be able to avoid this issue with total web app restart we should write the port file right away before even starting the webpack process (right now it's written in the very end).
And there are a lot of changes required to support this scenario.

Currently the app is failing with an exception if there is a provided port but it doesn't respond.
Instead we should consider two cases:
- port is provided explicitly by the user 
- port is read from the port file ( so it's written by us).

In the first case fail strategy should be taken if port doesn't respond.
In the second case we should just try to start another instance with a random port in the same path as port is being not provided.

**Comment by Artur-** [comment]
> `vaadin` command doesn't exist in my environment.
This is the same as `npx @vaadin/cli`

**Comment by denis-anisimov** [comment]
The issue is technically the race condition. Depending on who is faster : reload functionality or a `DevModeHandler` whose purpose to write the port file.
If port file is written fast enough then it will be read by the next instance of the `DevModeHandler` class.
If it's not written fast enough then the next instance will run a new webpack process bound to a new port.

In Spring boot dev tools case there should not be any new instance of `DevModeHandler` at all: it should reuse an existing one. In fact it reuses but before reusing it create another instance ( a bug in the code) which produces a new webpack process.

So the issue can be reproduced reliably if one add a timeout (sleep) before writing the port file (in the code).

I've restructured the code so that the port file is written immediately when port number is known and change the strategy to fail when the port is provided (as mentioned in the previous comment: it's either user defined or read from the file).
Now there can't be any timeout because port is available even before webpack is started. 
So the way described above with a timeout won't work anymore.
