### ISSUE TITLE
Initial value of the value attribute is not handled properly from templates

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9012]
Considering template with contents
```html
<vaadin-text-field id="textField" value="foobar"></vaadin-text-field>
<input id="inputField" value="foobar"></input>
```
and the corresponding Java template
```java
@Id("textField")
TextField textField;

@Id("inputField")
Input inputField;

inputField.getValue(); // returns ""
textField.getValue(); // returns ""
```
Probably related to how setting the `value` property directly is not taken into account in `AbstractFieldSupport` or `AbstractSinglePropertyField` . Whatever it is, we need to handle this properly even though giving a "default value for value" in the template seems like something that is not commonly done... it was discovered quickly when testing though.

**Comment by denis-anisimov** [comment]
This is  the bug:

```
Element element = new Element("vaadin-text-field");
        element.setProperty("value", "foo");
        UI ui = new UI();
        UI.setCurrent(ui);
        VaadinSession session = Mockito.mock(VaadinSession.class);
        ui.getInternals().setSession(session);
        VaadinService service = Mockito.mock(VaadinService.class);
        Mockito.when(session.getService()).thenReturn(service);

        Instantiator instantiator = Mockito.mock(Instantiator.class);

        Mockito.when(service.getInstantiator()).thenReturn(instantiator);

        Mockito.when(instantiator.createComponent(TextField.class))
                .thenAnswer(a -> new TextField());
        TextField field = Component.from(element, TextField.class);
        Assert.assertEquals("foo", field.getValue());
```

**Comment by denis-anisimov** [comment]
`AbstractSinglePropertyField` uses the default value (via `AbstractFieldSupport` ) as a value for the field in its CTOR
disregarding a fact that the underlying `Element`  already may have a value for the property
(there can be an `Element`  which is not a new but already existing one for which component is created).

So first of all `AbstractSinglePropertyField` CTOR should set the `value` based on underlying `Element`  property value if it exists overriding the default value.

This should be done in Flow.

But this is far away from the end of the story.
`TextField`  uses `GeneratedVaadinTextField` CTOR with an empty string as initial value.
And here is the code in the generated CTOR:
```
if (initialValue != null) {
            setModelValue(initialValue, false);
            setPresentationValue(initialValue);
        }
```

So text field is initially designed so that it doesn't care about any value in underlying Element and always sets the empty string as an initial value.
And it does it twice! : `setPresentationValue`  is not needed since there is only one value and it has been already set via `setModelValue`: only one method should be called to update the value.

**Comment by denis-anisimov** [comment]
This is fixed in Flow and in every `AbstractSinglePropertyField` component .
