### ISSUE TITLE
Navigation from a TypeScript view to a Java view is broken

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9134]
With Vaadin 17.0.6 / Flow 5.0-SNAPSHOT navigation from a TypeScript view to a Java view is broken. This looks like a regression in Flow 5.0 because with Vaadin 17.0.6 / Flow 4.0.2 navigation works as expected.

![Screen Recording 2020-10-07 at 11 28 PM](https://user-images.githubusercontent.com/22416150/95384177-e7447d80-08f4-11eb-9fe9-370be0b27354.gif)

**Steps to reproduce**
 1. create a project on start.vaadin.com
     - general settings
        ![image](https://user-images.githubusercontent.com/22416150/95383423-d47d7900-08f3-11eb-8520-9f720407e8f7.png)
     - views (all but the "Hello World" view are TypeScript + HTML (default), the "Hello World" view is Java)
        ![image](https://user-images.githubusercontent.com/22416150/95383066-43a69d80-08f3-11eb-9d45-1d3a5727bdbc.png)
 2. download the project and override the version of Flow to 5.0-SNAPSHOT
 3. run the project with `mvn`
 4. open http://localhost:8080/about
 5. click at the "Hello World" link in the navigation menu
 6. see that the hello world view is NOT rendered

**Comment by caalador** [comment]
I couldn't replicate the problem, can you check that the issue 9125 is in the 5.0-SNAPSHOT that you are using. The fix was merged yesterday and should have been in the SNAPSHOT around 15:40

I tested by going through the steps and setting `<vaadin.version>18.0-SNAPSHOT</vaadin.version>` which brings in `5.0-SNAPSHOT`
