### ISSUE TITLE
HierarchicalDataCommunicator does not provide a way to sync expanded state with client side.

### ISSUE THREAD

**Issue by tulioag** [vaadin/flow#9175]
### Description
The is no way for a TreeGrid to access the data in `HierarchyMapper` regarding expanded items. 

Take a look at this issue: [(BFP) Treegrid doesn't maintain states when using Tabs (vaadin-grid#1820)](https://github.com/vaadin/vaadin-grid/issues/1820)

When detaching and reattaching a TreeGrid, the expanded items state is not synchronized with the client side, so all columns show as not expanded. The same happens when using `@PreserveOnRefresh`.

This pull request fixes the issue, by using reflection to access the data in `KeyMapper` and `HierarchyMapper`. https://github.com/vaadin/vaadin-flow-components/pull/228

I would like to have a way to achieve the same result without using reflection.

### Minimal reproducible example
See https://github.com/vaadin/vaadin-grid/issues/1820

### Expected behavior
There is a way to trigger a call to `"$connector.expandItems"` passing the keys for the expanded items on attach.

### Actual behavior
That can only be achieved through reflection.

### Versions:
See https://github.com/vaadin/vaadin-grid/issues/1820
    - Vaadin / Flow version: latest snapshot

**Comment by pleku** [comment]
While this might require exposing new API, I would still treat it as an "design bug" that should be fixed and can be shipped in a maintenance release, but it should of course be backwards compatible.

**Comment by pleku** [comment]
> I would like to have a way to achieve the same result without using reflection.

Yes, after doing a bit of initial investigation, it seems that the `HierarchicalDataCommunicator` should not probably expose any new API but instead it should be made to work when the component is reattached without calling `reset()`:
- the server side state should be retained, including hierarchy state (expanded/collapsed) and probably active items range
- the client side state is reset so everything should be resend to the client from server
It is a good question whether or not we should _now_ change HierarchicalDataCommunicator to eagerly send "enough expanded items' children to the client side" on the initial render, instead of sending them one-by-one per each node+level. But this is optional.

**Comment by TatuLund** [comment]
@pleku 

> It is a good question whether or not we should now change HierarchicalDataCommunicator to eagerly send "enough expanded items' children to the client side" on the initial render, instead of sending them one-by-one per each node+level. But this is optional.

Yes, I think I am talking about roughly the same thing here: https://github.com/vaadin/vaadin-grid/issues/1914#issuecomment-683806711

**Comment by pleku** [comment]
@TatuLund yes lets use that issue (?) for continuing on that enhancement. This issue can be fixed without changing the expanding behavior.

**Comment by jcgueriaud1** [comment]
The PR has a tag +0.1.0. The current "LTS" version of flow is 2.4.x for 14.4.x.

Does this mean this issue will be fixed in flow 2.5.x = Vaadin 14.5.x?

**Comment by mshabarov** [comment]
@jcgueriaud1 this fix will be back-ported to Flow `2.4` with some modifications in order to have no breaking changes (tag +0.0.1).
