### ISSUE TITLE
Fusion: live reload is 1 step behind of the change due to InjectManifest

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9182]
To reproduce:
1. checkout [CRM TS tutorial](https://github.com/vaadin-learning-center/crm-tutorial-typescript)
2. run `mvn`
3. Make some changes, e.g. in the `contact-form.ts`, modify the label of the first name field
4. Live reload is triggered, but the updated content is not shown on the page. And the following error can be found from the log
```
WARNING in InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
Child InjectManifest:
     1 asset
    Entrypoint InjectManifest = sw.js
       55 modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
ℹ ｢wdm｣: Compiled with warnings.
```

Per discussion, a solution could be to update the service worker in the gizmo.

**Comment by joheriks** [comment]
I'm now not able to reproduce this with the above steps. I do get the warning about InjectManifest being called multiple times, Any change to the frontend files are reflected though after reloading (e.g. if I make a change to `contact-form.ts` I see the change after the automatic reload). I'm testing with the `master` branch of CRM and `5.0.offline-SNAPSHOT`. (the `offline` branch currently throws some webpack errors).

Some follow-up questions to be able to reproduce:
- The instructions to reproduce are to be carried out while online, right?
- Since this looks to be a timing issue / race condition,  browser and IDE could be of importance (I am using Chrome + IntelliJ).

**Comment by haijian-vaadin** [comment]
> The instructions to reproduce are to be carried out while online, right?

Yes
> Should I be testing with the offline branch of CRM?

Yes, I think I was using the offline branch, sorry, I forgot to mention this in the description.
> Since this looks to be a timing issue / race condition, browser and IDE could be of importance (I am using Chrome + IntelliJ).

I was using VSCode + Chrome.

**Comment by joheriks** [comment]
It seems that the reversal of the order of the statements `registerRoute(navigationFallback)` and `precacheAndRoute(manifestEntries)` in `sw.ts` introduced by [this commit](https://github.com/vaadin/flow/commit/ffc0326710f8c704746546c85394b409f162b26f#diff-a2826f74296a89c82153e6331d729b0142d875e9934e0e730a074397713b45dc) fixes the core issue. I will implement a test in the `test-live-reload` module to verify this and protect against future regressions.

**Comment by joheriks** [comment]
The warning quoted above is due to the `workbox-webpack-plugin` not being able to guarantee that the manifest reflects the assets after dev-server reload because removals cannot accurately be tracked (see https://github.com/GoogleChrome/workbox/issues/1790 for details). I do not think we should mute or otherwise hide this warning. At the same time, having the warning echoed on every reload for non-PWA applications as is now occurring looks unnecessarily alarming. I suggest we disable the plugin in `webpack.generated.js` for non-PWA applications.

**Comment by haijian-vaadin** [comment]
> I suggest we disable the plugin in webpack.generated.js for non-PWA applications.

sounds good, let's do it.
