### ISSUE TITLE
UidlRequestHandler#getRpcHandler implements non-thread-safe lazy initialization

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#9323]
Method `UidlRequestHandler.getRpcHandler(VaadinSession)` initializes `rpcHandler` field in an unsafe manner:

https://github.com/vaadin/flow/blob/e63f4e0a16df96b84fe5b68bccdb378aca3ba91c/flow-server/src/main/java/com/vaadin/flow/server/communication/UidlRequestHandler.java#L186-L192

Check that `VaadinSession` is locked is not sufficient, because `UidlRequestHandler` is a singleton.

**Comment by denis-anisimov** [comment]
`UidlRequestHandler` is not a singleton, it's 1:1 `VaadinService` and `VaadinService` is not really a singleton.
But the point is still valid: lazy init is done in unsafe way.

Also there is some logic issue: `session`  is given as a parameter and it's kind of supposed that the resulting RPC handler will be returned per session. But in fact it doesn't belong to the session.

It's OK of course to return something which is not belong to the provided argument but then it should be done in a safe way.

So either the result should be inside session and then the session lock will be enough here or it doesn't depend on the session and then initialization should be thread safe.

The easiest way to fix this would be make `rpcHandler` `final` and remove lazy init.
The problem is: `createRpcHandler` is a part of contract and this method may not be called in the CTOR (or initialization) because it's possible to override it.

**Comment by denis-anisimov** [comment]
I would say this is quite serious bug even though everything somehow works (apparently just because there is lock even though the lock is wrong).
