### ISSUE TITLE
Adding `flow-dev-deps` module to platform cause error running tests

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#9345]
Adding the mentioned module into platform causes platform validation failed with following errors:

```
[INFO] --- vaadin-maven-plugin:18.0-SNAPSHOT:build-frontend (default) @ vaadin-platform-test ---
<something more in the thread>
TypeError: Cannot read property 'then' of undefined
    at C:\WorkFolder\platform\vaadin-platform-test\node_modules\.pnpm\registry.npmjs.org\cacache\15.0.5\node_modules\cacache\lib\util\fix-owner.js:113:7
    at enqueue (C:\WorkFolder\platform\vaadin-platform-test\node_modules\.pnpm\registry.npmjs.org\compression-webpack-plugin\4.0.1_webpack@4.42.0\node_modules\compression-webpack-plugin\dist\index.js:208:11)
    at async Promise.all (index 0)
    at C:\WorkFolder\platform\vaadin-platform-test\node_modules\.pnpm\registry.npmjs.org\compression-webpack-plugin\4.0.1_webpack@4.42.0\node_modules\compression-webpack-plugin\dist\index.js:270:7
```

step to reproduce:

- you can simply use this branch for testing https://github.com/vaadin/platform/pull/1638
- generate the pom `./scripts/generateBoms.sh` (use all snapshot versions)
- run platform tests under production mode `mvn clean install -Pproduction`

**Comment by pleku** [comment]
It seems that the `flow-dev-deps` module is not used by any of our IT modules so there is nothing that makes sure that the dependencies even work.

It is another question what does cause `cacache` failure there, mayhaps the `compression-webpack-plugin` is not working with that particular `cacache` version or something else not working with `cacache`.

**Comment by denis-anisimov** [comment]
> It seems that the `flow-dev-deps` module is not used by any of our IT modules so there is nothing that makes sure that the dependencies even work.
> 
> It is another question what does cause `cacache` failure there, mayhaps the `compression-webpack-plugin` is not working with that particular `cacache` version or something else not working with `cacache`.

yes and no.

yes: there are no test which confirms that deps are working
no: deps are calculated based on built test. Once one of our IT is built the command is executed which outputs all used dev dependencies. Those dependencies are collected then into the resource file which is packaged into `flow-dev-deps`.

I may assume that the problem is unsolvable in fact: the dependencies which are used are not in flat list.
There is a dependency tree. Different dependencies may use different transitive dependency versions.
That has been seen during impl. I hoped that the chosen way of detecting dependency version is good enough but probably it's not.
As a result locking dep versions via `pnpmfile.js` becomes quite nontrivial task: it's not designed to work with dependency tree.
