### ISSUE TITLE
Support "Full" Html in Html component

### ISSUE THREAD

**Issue by Springrbua** [vaadin/flow#9352]
### Description of the bug
I have an external html-File I would like to render in Vaadin. I tried to use the [Html](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/Html.java) component but it seems that it expects to get only the `body` instead of the full html.
This behavior was introduced with #7466.

### Minimal reproducible example
Set the following Html as the content of the `Html` component:
```
<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    <head>
        <title>Test</title>
        <style>
            div {
                background: red;
            }		
        </style>
    </head>
    <body>
        <div>
            Test
        </div>
    </body>
</html>
```

### Expected behavior
The Html should be rendered.

### Actual behavior
An `IllegalArgumentException` with the message `HTML must contain exactly one top level element (ignoring text nodes). Found 4 elements with the tag names meta, title, style, div` is thrown.

### Versions:
    - Vaadin / Flow version: 17.0.7 / 4.0.3
    - Java version: 11.0.9
    - OS version: Windows 10

**Comment by taefi** [comment]
After looking into the [Html](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/component/Html.java) documentation and also the #7466 it is obvious that changes in #7466 intentionally changed to the current behavior described in the bug description. So it is being closed because it works as it's coded.

**Comment by Legioth** [comment]
Supporting a full HTML document would lead to some additional complexity and ambiguity that would probably be quite confusing in most cases. The key question is what to do with the `<head>` contents when loading that HTML. Those tags should typically be placed inside the actual head of the document rather than at the same place in the DOM where the `Html` component itself is placed.

Here are just some examples of what kind of questions that would lead to:
* Should those tags then also be removed from the head when the `Html` component is detached?
* How to deal with tags that only make sense when the page is being loaded, such as  `<meta charset="utf-8">` from the example above?
* What to do with tags that are supposed to only be defined once, such as `<title>`? Should we then remove the original title?

Implementing special handling for those special cases would then also be a quite big effort.

Answering those questions probably depends on the requirements of the application in question and the semantics of the HTML documents that the application uses.

**Comment by Springrbua** [comment]
I solved my usecase by using `IFrame`, which is probably the better option, as the Html includes styles, which should only apply to this html and not the whole page.
