### ISSUE TITLE
Add clarifying information to the error message about moving nodes to another state tree

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#9376]
The "Can’t move a node from one state tree to another" exception is quite often triggered by accidentally using an inappropriate DI scope for some specific component class, thus causing an instance of that component to become accidentally reused.

It would be much easier to debug that kind of problem to trace down which class has inappropriate scope if the error message would better identify the component in question. To achieve that, I would propose that the logic that throws the exception would have a special logic to check if the state node is an element node and that element has a component associated. In that case, the class name of the component would also be included in the error message.

**Comment by knoobie** [comment]
@pleku I would like to sponsor this feature with our prime hours. This is driving our new developers nuts and it's impossible to check hundreds of classes which has the wrong annotation.. If you are interested, just hit me up, that I can create a request in vaadin.com.

**Comment by pleku** [comment]
I'll see what we can do.

**Comment by knoobie** [comment]
@pleku Created VS-3873 for it :)

**Comment by johannest** [comment]
Other rather common case when this happen is having (especially) a VaadinIcon with static modifier.. This happens easily especially if you have used V8 FontIcons as with static keyword. In V14+ VaadinIcons are components thus using static keyword causes easily this error.

**Comment by mvysny** [comment]
Very easy to reproduce, also with Vaadin 24.2.2:
```java
@Route("")
public class MainView extends VerticalLayout {

    // obviously wrong, only used to reproduce the issue
    private static Button button = new Button("Say hello",
            e -> Notification.show(Services.getGreetService().greet("foo")));

    public MainView() {
        add(button);
    }
}
```
Navigate to the route, then reload the page with `F5`.

The exception message gives no pointers as to what's wrong. Either:
* the component should automatically remove itself from the old UI (as happens automatically when adding a component into another layout from within the same UI) - probably not a good idea since this could cause the intended component caching to misbehave silently
* or the exception message should include more precise instructions,
* or the components should have additional code to prevent this kind of exception being thrown - e.g. additional checks & throwing an exception directly from the Component layer, explaining the situation.

**Comment by mvysny** [comment]
This kind of code improves the situation a lot:
```java
@Route("")
public class MainView extends VerticalLayout {

    private static Button button = new Button("Say hello",
            e -> Notification.show(Services.getGreetService().greet("foo")));

    public MainView() {
        add(button);
    }

    @Override
    public void add(Collection<Component> components) {
        for (Component component : components) {
            final UI componentUI = component.getUI().orElse(null);
            if (componentUI != null && !UI.getCurrent().equals(componentUI)) {
                throw new IllegalArgumentException("Vaadin doesn't support moving component from one UI to another, because there is no way to preserve state blah blah. Offending component: " + component + ", moving from UI " + componentUI + " to " + UI.getCurrent());
            }
        }
        super.add(components);
    }
}
```
1. I know that moving component from one UI to another is forbidden because of "insert valid reason here"
2. I can place a breakpoint and investigate the offending component
3. Since I know which component is the offending one, I can validate its annotations or scoping.

**Comment by mvysny** [comment]
Moving a component from one UI to another is fundamentally possible, and it's an internal optimization that leaks and throws the "can't move state" exception. However, moving a component from one UI to another will cause the component to disappear from the original UI for no apparent reasons, and therefore this is definitely not a good practice. In conclusion, we don't want to allow moving components from one UI to another, to "protect the programmer from shooting himself into the foot".

That means that the inability to move a component from one UI to another is a good thing, and we want to preserve that.

What remains is to improve the exception. Luckily, if you can attach a debugger to your code, it is possible to figure out the offending component: it is referenced from the `ComponentMapping` feature, stored in `StateNode.features`:

![Screenshot from 2023-11-13 09-47-08](https://github.com/vaadin/flow/assets/254091/a79de2e0-f83b-4e51-b4e1-55d9955524cc)

**Comment by mcollovati** [comment]
In development mode you can also evaluate this expression to get more information

```
ComponentTracker.findCreate(Element.get(this).getComponent().get())
```

![image](https://github.com/vaadin/flow/assets/4648894/5783a983-94c5-41f0-af79-84891dddc59e)


There's also the `ComponentTracker.findAttach` method

![image](https://github.com/vaadin/flow/assets/4648894/5b2b15e2-f2cf-49a0-a68f-7be7ca964983)

**Comment by mcollovati** [comment]
This can probably be used in dev mode to improve the exception message. Something like
`
java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree.
Component 'com.vaadin.flow.component.button.Button' created at 'MainView.java' (org.vaadin.example.MainView.<clinit> LINE 16), attached at 'MainView.java' (org.vaadin.example.MainView.<init> LINE 20)
`

**Comment by mvysny** [comment]
I'd also add as much information as possible in production as well, since that's how those kind of issues are usually discovered. I assume that the ComponentTracker is disabled in the production, but we can at least learn the Component via Element.get(this).getComponent() ?

**Comment by mcollovati** [comment]
Yes, ComponentTracker is disabled in production mode

**Comment by mvysny** [comment]
Acceptance criteria: the error message now reads:
```
Can't move a node from one state tree to another. If this is 
intentional, first remove the node from its current 
state tree by calling removeFromTree. This usually 
happens when a component is moved from one UI to another, 
which is not a good idea. This may be caused by 
assigning components to static members or spring 
singleton scoped beans and referencing them from 
multiple UIs. Offending component: com.vaadin.flow.
component.ComponentTest$TestButton@
```
