### ISSUE TITLE
Rerouting should not require the target component to have a route path

### ISSUE THREAD

**Issue by Frettman** [vaadin/flow#9386]
Rerouting does not change the browser location. Yet, target components are currently required to have a route even if it should never be possible to navigate to these components directly.

An example of this can be seen in the official documentation of the [Navigation Lifecycle](https://vaadin.com/docs/v17/flow/routing/tutorial-routing-lifecycle.html): The `NoItemsView` has a route even though it makes no sense to navigate to it directly. One can use a path that is very unlikely to cause naming conflicts, but that feels like unnecessarily polluting the "route space". Especially since that route will show up in the list created by `RouteNotFoundError`.

**Comment by pleku** [comment]
> Rerouting does not change the browser location

Yes, and this is intentional, like it is said in the javadocs:
```java
     * This function doesn't change the browser URL as opposed to <code>forwardTo()</code>.
```
The `BeforeEvent::forwardTo` methods do that instead.

>The NoItemsView has a route even though it makes no sense to navigate to it directly

The example is just maybe a bit bad one - in case you want to have a component shown in certain scenario but not be possible to navigate to the URL directly, then I think you should just handle it directly in that view by showing a different component instead of another. In case the URL should be changed, you could use `getUI().getPage().getHistory().replaceState(null, "some-location")`. But I don't know why you would want to have a URL shown that cannot be navigated into directly since then the users history back/forward navigation would lead into errors.

**Comment by Frettman** [comment]
Sorry for the misunderstanding. I wasn't questioning the general behavior of rerouting. But considering that the location does not change - as expected and desired - , it seems unnecessary that the target component is required to have a registered route. In a way I was expecting it to work similar to HasErrorParameter views (that also don't need or have a fixed route), just without the added implication of an error.

My use case is that I am controlling access via an BeforeEnterListener. When authentication is required I need to redirect to an external URL (web-based SSO). I can use Page#setLocation(...) but that won't stop the original target from being shown before navigating to the new URL. So I have to reroute to what is essentially a dummy view.
While my use case specifically would also be satisfied by #4606, it just seemed like a reasonal expectation to me that a reroute target wouldn't need to have a registered route, as its path is never shown.

**Comment by pleku** [comment]
> While my use case specifically would also be satisfied by #4606, it just seemed like a reasonal expectation to me that a reroute target wouldn't need to have a registered route, as its path is never shown.

Ok, thanks for the details. But I think for that case we should go with #4606. Closing this one.
