### ISSUE TITLE
Can change npm to cnpm

### ISSUE THREAD

**Issue by jackila** [vaadin/flow#9398]
For some reason , my jenkins server can not use npm. we use cnpm as a replacement
Does flow can change to cnpm?
And how to config?

**Comment by pleku** [comment]
Hello. cnpm as in https://github.com/cnpm/cnpm I guess ?

Sorry I have not heard of this before.  So would it be enough if instead of executing goals with `npm` it would be using `cnpm` instead ?

> my jenkins server can not use npm

Have you tried configuring proxy for npm ? 
https://vaadin.com/docs/v14/flow/installing/installing-overview.html#proxy-settings-for-downloading-frontend-toolchain

**Comment by jackila** [comment]
thanks
