### ISSUE TITLE
Development mode log message is misleading

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9411]
When run in development mode, Vaadin prints:

```
[http-nio-8080-exec-1] INFO com.vaadin.flow.server.DefaultDeploymentConfiguration - 
Vaadin is running in DEBUG MODE.
When deploying application for production, remember to disable debug features. See more from https://vaadin.com/docs/
```

There is no such thing as a "debug mode" - there's development mode: https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html

### Versions:
    - Vaadin / Flow version: 14.4.2
    - Java version: 11
    - OS version: Linux
    - Browser version (if applicable):
    - Application Server (if applicable): Tomcat
    - IDE (if applicable):

**Comment by pleku** [comment]
Actually the `DEBUG MODE` is the alternative for production mode. This has been since earlier Vaadin versions.
And _development mode_ means that the webpack devserver is running / webjars are used as an alternative for the frontend resources being bundled.

You can have an app either in debug/production mode and run it in either development mode (webpack dev server running) or with bundled frontend resources (webpack has build & bundled the frontend resources). IMO the latter is a the confusing part in terms of naming, but your mileage can vary.

Probably it has been misunderstood even internally and thus the documentation is not clear on this. I'm not sure if we should try to rename anything at this point, but at least the documentation should fixed. @magi42 do you have any thoughts on the naming so it would be unambiguous ?

**Comment by mvysny** [comment]
The "debug" is unequivocally perceived as JVM debug; adding any other meaning to this is immediately confusing. Something like "client hot redeploy" mode would be much more accurate, even though longer. However, it sounds as if we have two separate things: "client development mode" (aka debug mode) and "server development mode". It's confusing. Is there any merit in running client in production mode but server in development and vice versa?

**Comment by pleku** [comment]
>  perceived as JVM debug

I would think this is the intention and it has been like this since at least since Vaadin 7 if not even earlier (cannot remember).

Probably over 90 % of the time the combinations are: frontend-development & debug mode and production-build-frontend & production mode.
But sometimes it is necessary to run production-build-frontend but in debug mode (we've learned this and had to make it possible earlier on), when running the app as a .jar or when for some reason the frontend build / webpack devserver is to be avoided. I don't recall hearing about running frontend-development but in production mode.

**Comment by mshabarov** [comment]
@tarekoraby yes, let's close this ticket.
