### ISSUE TITLE
Offline service worker is broken in production mode by webpack compression plugin working first

### ISSUE THREAD

**Issue by platosha** [vaadin/flow#9457]
In production mode, generated webpack config has `CompressionPlugin` added to plugins. This produces two copies of bundle files in the output directory, one raw `.js` and one compressed with `.js.gz` filename extension.

While `InjectManifest` manifest is always adding manifest to the raw `.js` output file, the compressed `.js.gz` output could be missing the injected manifest if compression plugin works first.

Currently in the generated webpack config, `CompressionPlugin` is defined first, well before `InjectManifest`. If compressed assets are then served to the browser, this results in a broken service worker, as the manifest is entirely missing there.

Solution idea: make sure `InjectManifest` is defined before `CompressionPlugin` in the webpack config.

**Comment by haijian-vaadin** [comment]
- Add offline IT tests in production mode.
- Find why it works with the offline branch, and explain it here as a comment.

**Comment by joheriks** [comment]
Regarding why it was still working in the offline branch, even though the compressed and uncompressed `sw.js` had different contents: It seems to be because serving of compressed content is broken in `offline`branch (e.g. [this line is never](https://github.com/vaadin/flow/blob/feature/offline/flow-server/src/main/java/com/vaadin/flow/internal/ResponseWriter.java#L134) reached, not for service worker or the bundles), so the erroneous service worker was never exposed. I will create another ticket for this.
