### ISSUE TITLE
VaadinSession.close should mention invalidate and/or redirect

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9645]
The `VaadinSession.close()` javadoc is great but can be improved. Two things should be mentioned:

1. That you should also call `vaadinSession.getSession().invalidate()` if you have been storing values outside of `VaadinSession` itself, since `VaadinSession.close()` won't call `invalidate()`.
2. That in order to avoid getting Session Expired, a navigation to the login view should be performed.

Also see:

* https://vaadin.com/docs/v8/framework/articles/HandlingLogout.html
* The new javadoc should provide a clear answer to https://vaadin.com/forum/thread/3229986/logoff-cleanup-is-closing-vaadinsession-sufficient

### Versions:
    - Vaadin / Flow version: 14.4.4 / 2.4.3

**Comment by denis-anisimov** [comment]
I agree that `close` method is a bit confusing since `VaadinSession` is confusing itslef.
There is no clear explanation that `VaadinSession` is not 1:1 to HTTP session (and you may be expect that).
In fact there can be many `VaadinSession` per one HTTP session. That's why closing one `VaadinSession`  doesn't affect anyhow the big HTTP session.
This needs to be clarified.
