### ISSUE TITLE
SPIKE: figure out what is the best way to detect changes in the active theme folder when webpack is running

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9666]
Related to #9594, #9596 and #9622.

We need to be able to pick adding new/renaming css files, resources and deleting the files without failing the build. This should be done for only the currently active theme folder (in the project).
The problem is at the moment that 
- webpack is only rebuilding when referenced files are touched
- we are not copying resources that are not also used from css

**Comment by mshabarov** [comment]
Update regards file delete errors:

Have no idea how to workaround the issue with deleting theme resource file error. 
I tried to use of `import()/require`  with `try-catch` in `theme-generator.js` to safely recognise the files delete cases, but it either throws the error anyway, or return a promise, which is not appropriate for code in `theme-generator.js`.

Another attempt was in to using a `RemovePlugin` to delete `my-theme.generated.js` and play with plugins ordering, but it also failed because no matter how I order the plugins, `index.ts` is always being called within webpack recompilation -> code `my-theme.generated.js` throws.

My question now is that who calls `index.ts`. Is it a webpack? This is not clear from stack-trace.

**Comment by mshabarov** [comment]
No good solution found on how to workaround the file/folders delete errors so far.
It's proposed to mention this limitation in docs, stating:

_Files/folders inside `frontend/themes/my-theme` folder might be deleted during application development/theming. Please notice that you may get webpack errors in the application logs, as follows:
`Error: ENOENT: no such file or directory, open 'your-project-root-path/frontend/themes/my-theme/global.css'`
or even see a webpack error pop up on your application page.
This is a known limitation and you need to refresh the browser page manually, if you see webpack error pop up, and merely ignore  this error in logs._

**Comment by mshabarov** [comment]
Closed, as the live reload upon new files done, file delete issue has been documented, and https://github.com/vaadin/flow/issues/9622 is a separate ticket.
