### ISSUE TITLE
offline logout

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#9789]
As a user I expect that after I logged out of the app offline, I would not be able to make authenticated requests to the backend when coming back online, so that I can trust the "Logout" button. With Vaadin 19 offline logout reliably works for browser tab where it was triggered, but--as described in https://github.com/vaadin/flow/issues/9537#issuecomment-757963675--a newly opened tab could still reuse the HTTP session.

**Comment by Legioth** [comment]
The only reasonable way I see for implementing offline logout would be to change authentication to use JWT instead of session cookies since then we can effectively log out by discarding the JWT. With anything based on sessions cookies (assuming HttpOnly is used according to best practices), we have no way of impacting the login state without reaching the server.

While Fusion could store a flag that indicates that the user has logged in, we still cannot ensure that 3rd party clients would honor that flag. The result is thus that the user would be given the impression that they have logged out while an attacker with familiarity of how the system works could still trivially circumvent the fake logout.

From that point of view, I'm wondering whether it would actually be better to not even give the impression that a logout was successful?

**Comment by joheriks** [comment]
Could [requiring two cookies](https://medium.com/@thbrown/logging-out-with-http-only-session-ad09898876ba), one which is HttpOnly and the other deletable in JS, be a potential alternative? Note that this is not an assessment of whether this is more implementable than using JWT.

**Comment by Legioth** [comment]
A second cookie is indeed also an alternative. It would probably be the best option if we'd plan to stick to session cookies in the long run. The benefit is less clear in this situation when we're most likely also going the JWT route within the foreseeable future for other reasons.

**Comment by haijian-vaadin** [comment]
Related https://medium.com/android-news/solving-offline-logout-problem-f3b50da49e7e

**Comment by Haprog** [comment]
Related https://github.com/vaadin/fusion/issues/49 but I'm not sure if this issue should still be kept open. Is there maybe some additional case of offline logout we would like to support besides using the client side `logout()` helper that should work now in main branch?

**Comment by haijian-vaadin** [comment]
I think it's the same issue, we can close it, as it's fixed in https://github.com/vaadin/fusion/pull/129
