### ISSUE TITLE
Server-side security security context / state is delayed (title updated)

### ISSUE THREAD

**Issue by markhm** [vaadin/flow#9826]
This issue appears when trying to configure Spring Security to use a Fusion and Flow side by side in one application, authenticating against Okta based on the [Okta Vaadin Fusion article](https://developer.okta.com/blog/2020/11/09/vaadin-spring-boot).

As an introduction to this issue, please see the following:
- By default, Flow views do nót work when using the SecurityConfiguration from the Okta article. This is confusing, so I kindly suggest an update to the Okta article.
- By applying both a Fusion and a Flow style `SecurityConfiguration.configure(HttpSecurity http)` consecutively, I was able to get Flow views working, see line 55 of the [SecurityConfiguration](https://github.com/markhm/vaadin-fusion-playground/blob/main/src/main/java/fusion/playground/security/SecurityConfiguration.java).
- Login and logout works correctly on Fusion side. After selecting logout, the client-local `okta-token-storage` is removed from the browser's `localStorage`, so the user is no longer logged in.
- Flow side login against the `inMemoryAuthentication` also works, although it does not forward to the correct view after success yet.

On the server side, I see some strange behaviour however, when trying to look into details using a [`SecurityInfoView`](https://github.com/markhm/vaadin-fusion-playground/blob/main/src/main/java/fusion/playground/views/security/SecurityInfoView.java):

1) The server-side view of the authentication state seems delayed. Only visible after clicking a few other views I am able to see the correct `Principal` details from `org.springframework.security.oauth2.jwt.Jwt`;
2) Even after client logout, the `authentication.getPrincipal()` in the server-side Flow view still shows the Jwt Principal.

Both seems strange, but in 2) is the reason for this issue. Is it a bug? Is related to caching? E.g. Should the client-side logout make an extra call to the server to clear a server-side context?

My project [Vaadin Fusion Playground](https://github.com/markhm/vaadin-fusion-playground) will help you to reproduce. Credentials for Fusion/Okta authentication are username: `testuser@vfp.nl`, password:`72DyZRJn`. Credentials for server-side authentication are username: `admin@test.dk`, password:`321`.

My goal is to use Okta authentication also for the Flow side of the application, so a user only needs to login once and still the Flow views and additional non-Fusion REST endpoints can be `@Secured` in the normal way. I do realise that for this to work, some other configuration is still needed (e.g. server-side Okta `authenticationManager` in the `SecurityConfiguration`). 

PS: From recent v19 release notes, I understand work is ongoing in the security area. Perhaps the issues I am experiencing are expected during your work in progress, and this issue will be fixed by current development work and/or an explanation of how to configure security for an integrated Fusion/Flow security approach.

Please don't hesitate if you have any questions or need additional information. 

**Desktop:**
 - OS: macOS latest
 - Browser:  Brave Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)
 - Vaadin platform version 18.0.5

**Comment by tanbt** [comment]
Hi @markhm, I tried to run the project but can't find `application.mac.properties` file.
Tried with `application.dev_unused.properties` but got 
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'okta.oauth2' to com.okta.spring.boot.oauth.config.OktaOAuth2Properties failed:

    Property: okta.oauth2.issuer
    Value: @okta.oauth2.issuer@
    Origin: class path resource [application.properties] - 31:20
    Reason: null


Action:

Update your application's configuration
```
I'm on Windows.

**Comment by markhm** [comment]
Thanks @tanbt. 

Could I send you the necessary file via mail, so I don't have to share the credentials out in the open...?

**Comment by vlukashov** [comment]
> Thanks @tanbt.
> 
> Could I send you the necessary file via mail, so I don't have to share the credentials out in the open...?

Thanks Mark, this is not necessary now. I was able to reproduce the issue. For other Vaadin folks, I've posted the API keys and tokens needed to run this app locally to Vaadin Slack ([link](https://vaadin.slack.com/archives/C6RAXJATF/p1611305858013900?thread_ts=1611305683.013300&cid=C6RAXJATF)).

A couple of observations so far:
 - In the end, once all the issues are figured, I guess there should not be two login views in the app. Was there a particular reason to add the "Login Flow", apart from trouble shooting?
 - the way how this example integrates with Okta and uses OpenID Connect / JWTs looks very reasonable, and I think Vaadin will want to support it better, i.e. update the docs / blog post and provide helpers if necessary

The issue with a lag in client -> server auth credentials propagation is there, and I am able to reproduce it locally. I'll continue the investigation.

**Comment by markhm** [comment]
Thank you for your feedback, @vlukashov. 

Correct, only the client-side login should be sufficient. I added the server-side login when I did not yet know that the security context is synchronized with the server. 

I will check on the (npm component) state of this project myself, as I am been seeing connection refusal problems in the browser console from the VaadinDevmodeGizmo.js's WebSocket connection to port 35729. I did not have these problems when I started a new project via start.vaadin.com recently, so perhaps it is time for an update of this project's npm underpinnings. Might not be related, but I wanted to mention it.

**Comment by vlukashov** [comment]
### Access to Security Principal from JWT on the server-side
As of Vaadin 19, server-side access checks rely on the security credentials stored in the HTTP-session. When using the Spring Security setup for JWT-based auth as outlined in the [Quick Guide to Security with Vaadin Fusion and Spring Boot](https://developer.okta.com/blog/2020/11/09/vaadin-spring-boot) blog post, these security credentials are written to the HTTP session by a custom JWT-aware request filter (as long as the request contains the `Authorization: Bearer [token]` HTTP header), and erased by the default Spring Security logout filter.

All requests to Fusion endpoints do include the auth header (through a [custom Fusion client middleware](https://github.com/oktadeveloper/okta-vaadin-fusion-spring-boot-example/blob/b0ba0518886e7e24ddd330781e68f41eab082926/frontend/connect-client.ts#L11-L22)). However, this middleware does not apply to requests to server-side (Flow) views, and therefore these requests do not include the auth header. This leads to a situation when server-side views do not get the security credentials from the JWT details until the first request to a Fusion endpoint.

**Steps to reproduce**:
 1. clone https://github.com/vaadin-learning-center/crm-tutorial-typescript (the `jwt-login` branch)
 1. start the app with `mvn`
 1. clear the browser cache / local storage / etc and open http://localhost:8080/auth-info-flow
 1. see a login prompt
 1. login and see that for client-side code the login is successful, so you are redirected to `/auth-info-flow`
 1. see that for the server-side code you are still "anonymous"
 1. open the Dashboard view (to trigger a call to a Fusion endpoint)
 1. open the `/auth-info-flow` view and see that now for the server-side code you are logged in

**Workaround**:
 1. add a `Jwt4FlowEndpoint` class
    ```java
    @Endpoint
    public class Jwt4FlowEndpoint
    {
        public void sync() {
            // intentionally empty
        }
    }
    ```
 2. in the client-side code explicitly call `Jwt4FlowEndpoint.sync()` after a successful login.

**Suggeted fix**:
Add a `loginWithJwt()` method to the `@vaadin/flow-frontend` package so that it can be used to make auth info available to server-side views and without having to resort to work-arounds as suggested in https://github.com/vaadin/flow/issues/9826#issuecomment-761845719:

```ts
import { loginWithJwt } from '@vaadin/flow-frontend';
...
[ get a JWT somehow ]
...
await loginWithJwt(accessToken);
```

**Comment by vlukashov** [comment]
### WebSocket connection problems
A brief investigation shows that the WebSocket connection issues are caused by the Vaadin DevMode "gizmo" not being able to connect to the LiveReload server started by Spring Boot development tools. The cause of this issue seems to be specific to the [Vaadin Fusion Playground](https://github.com/markhm/vaadin-fusion-playground) project and to how it is configured to work over HTTPS.

Turning off HTTPS during development fixes the issue.

**Comment by vlukashov** [comment]
### Helpers to configure Spring Security in a Vaadin app
This is tracked as a separate enhancement here: https://github.com/vaadin/spring/issues/678
