### ISSUE TITLE
Node.js auto-installed to .vaadin should be auto-upgraded

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#9864]
The Node.js version automatically downloaded and installed into `~/.vaadin` has recently been updated to latest LTS 14 (from 12). However, if version 12 was previously installed into `~/.vaadin` it will continue to take precedence until the dev deletes it from their `~/.vaadin` folder. ~Upgrading the global Node.js installation does not help either (because of #9863).~ Flow could automatically upgrade the Node.js version whenever it resorts to it (no global `npm` or forced via `require.home.node`).

**Comment by pleku** [comment]
@mstahv @gilberto-torrezan this would be needed for Vaadin 21 / flow-fusion 8.0 if we want to drop support for end-of-life Node version(s).

**Comment by mshabarov** [comment]
### Acceptance criteria:
1. Once no globally installed `Node` is found or `require.home.node` config parameter is set, the Flow should check the node version installed into `~/.vaadin`.
2. If `~/.vaadin` already contains the node, then flow checks its version to be at least `FrontendTools::DEFAULT_NODE_VERSION = "v16.7.0"`. Once the version is older, it is removed by flow.
3. Flow installs a new version `FrontendTools::DEFAULT_NODE_VERSION` to `~/.vaadin`.
4. Automatic node update should be mention in docs https://vaadin.com/docs/latest/flow/guide/install/#node-js.

**Comment by Artur-** [comment]
Doesn't sound like a feasible solution
1. That would potentially break my Vaadin 14 application when I test Vaadin 22 if Vaadin 22 just deletes my Node version that is working with 14 and replaces it with something else
2. What would happen if V14 requires Node 12 and V22 requires Node 16. Do you imaging that everytime I start an app of the other version, it would download and reinstall Node?

**Comment by mshabarov** [comment]
> Doesn't sound like a feasible solution
> 
> 1. That would potentially break my Vaadin 14 application when I test Vaadin 22 if Vaadin 22 just deletes my Node version that is working with 14 and replaces it with something else
> 2. What would happen if V14 requires Node 12 and V22 requires Node 16. Do you imaging that everytime I start an app of the other version, it would download and reinstall Node?

Good point! Then the flow shall not remove anything, but:
1. Compare the node version discovered in `~/.vaadin/node` (hardcoded path to the installed node) with `FrontendTools::DEFAULT_NODE_VERSION`
2. Check the node version in `~/.vaadin/nodes/{FrontendTools::DEFAULT_NODE_VERSION}` (the path can be changed to something more clever) if the `~/.vaadin/node` is too old. Create the path and install `DEFAULT_NODE_VERSION` unless it doesn't exist. Double check of the version inside `~/.vaadin/nodes/{FrontendTools::DEFAULT_NODE_VERSION}` is probably needed, because the developer can erroneously replace it with something else or remove its content. 
3. If `~/.vaadin/node` is new enough for the current Vaadin version used, then just use it.

Seems like we need to have different node executables in Vaadin home for different Vaadin versions anyway, e.g. `~/.vaadin/nodes/v16.7.0`,  `~/.vaadin/nodes/v14.17.6` etc.

**Comment by mshabarov** [comment]
By the way, 
```
That would potentially break my Vaadin 14 application when I test Vaadin 22 if Vaadin 22 just deletes my Node version that is working with 14 and replaces it with something else
```
would need the "upper" supported version of node.
Currently flow does only check the minimal supported versions.
