### ISSUE TITLE
[BUG] Offline line feature is broken in 19.0.0.alpha5

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#9977]
To reproduce: 
1. Download a fusion project from start.vaadin.com (V19, Java 11 LTS, TS+HTML ).
2. Deploy the application
3. Set offline in the browser tab
4. Refresh the page

Expected:
Get the cached page
Actual:
A "This site can’t be reached" page
![Screenshot 2021-02-05 at 13 58 30](https://user-images.githubusercontent.com/30408303/107039856-1990b980-67c7-11eb-88d1-30a7eacc39b0.png)

Observations:
1. It works in 19.0.0.alpha4
2. It breaks in 19.0.0.alpha5 and 19.0-SNAPSHOT

**Comment by Artur-** [comment]
Just noting that 
1. It works in production mode `mvn -Pproduction`
2. In dev mode, `self.__WB_MANIFEST` in sw.ts is apparently supposed to be replaced with the manifest produced by the webpack plugin but it is missing the entry for `'.'`

**Comment by Artur-** [comment]
I had a quick additional look and it seems the problem is exactly what the logged warning talks about:
```
WARNING in InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
```

With the old configuration, the `index.html` asset was generated on each webpack run and everything works as it is mapped into `appShellUrl` in the webpack configuration.

With the new configuration, after https://github.com/vaadin/flow/commit/61df7f739ae85dc4b6c6e262c4da7554973dd250, the `index.html` asset is only emitted on the first compilation.

Now for some reason the webpack compilation is run twice when you start the application. If you log the manifest entries, you can see that in the first (full) compilation, an `'.'` asset is included in the manifest. On the second (incremental) compilation, no `'.'` asset is included in the manifest. As the workbox webpack plugin does not track old assets, as mentioned in the link issue, it will output a manifest without the `.` entry and that will not be precached in the service worker.

A way to get this to work would be to store the app shell entry and ensure it is always included in the manifest, e.g.
```
  if (indexEntryIdx !== -1) {
    manifest[indexEntryIdx].url = appShellUrl;
  }
```
->
```
  if (indexEntryIdx !== -1) {
    manifest[indexEntryIdx].url = appShellUrl;
    appShellEntry = manifest[indexEntryIdx];
  } else {
    // Add previously created entry point
    manifest.push(appShellEntry);
  }

```
