### ISSUE TITLE
UidlRequestHandler performance optimization

### ISSUE THREAD

**Issue by huuskart** [vaadin/flow#9987]
### Description of the bug / feature
flow-server UidlRequestHandler does avoidable memory allocation and memory copy when generating the response.
### Minimal reproducible example
Code inspection
### Expected behavior
See attached patch (apologies for not using pull request).
Patch depends on gwt-elemental patch in vaadin/gwt issue 10.
Code could be improved even more because the stringbuilder->string is also useless, but unfortunately StringBuilder does not have getBytes().
[flow-server.patch.txt](https://github.com/vaadin/flow/files/5943597/flow-server.patch.txt)

### Actual behavior
See above
### Versions:
    - Vaadin / Flow version: 2.2.1
    - Java version: 1.8
    - OS version: linux

**Comment by Legioth** [comment]
Do you have any measurements for the real-world impact of this optimization?

**Comment by pleku** [comment]
Hello @huuskart and thanks for contributing. I've understood that this issue originates from https://github.com/vaadin/framework/issues/5987 where your investigation @Legioth has brought up the in issue in the elemental library being slower in certain cases than the previously used org.json.

The code required for the patch mentioned in https://github.com/vaadin/gwt/issues/10 and needed by the patch in here would have go to https://github.com/gwtproject/gwt/blob/master/elemental/src/elemental/json/impl/JsonUtil.java which is deprecated and I don't know if there will be any new releases of it or if there would be a release that we would adopt to. There is an elemental2 library which is probably not something that we're looking into using in the near future.

So, in order to contribute improvements regarding this, the first question to answer would be: **what is the impact** so we might know if the gains could be worth doing something or not. In case the improvement is substantial, I think we could even c/p our own version of the necessary JsonUtil methods to the project.

**Comment by pleku** [comment]
This has been waiting for feedback from the author but due to inactivity, closing the issue.
