### ISSUE TITLE
Filtering and identifierGetter in Grid setItems Method

### ISSUE THREAD

**Issue by simasch** [vaadin/flow#9989]
From Vaadin 18 it's possible to call setItems() with a FetchCallback which is great because in some circumstances it's not possible to provied a CountCallback.
 
But this setItems method misses two features:

1. The filter type of the fetchCallback is always Void so it's not possible to filter via the Query
2. In some situations a identifierGetter must be set but there is no way to pass a ValueProvider

Either add filtering and identitfierGetter in a setItems method that returns ConfigurableFilterDataProvider or provide a CallbackDataProvider without the need of passing a CountCallback.

**Comment by pleku** [comment]
Hi Simon. 
> The filter type of the fetchCallback is always Void so it's not possible to filter via the Query

The filter type is indeed `Void` for everything else except `ComboBox` since that is the only component that provides a filter itself inside the component. For everything else, you should just do a `refreshAll()` when the filter changes (eg. like `textField.addValueChangeListener(event -> grid.getDataView().refreshAll());`) and then directly get the filter(s) in the query callback method and pass it to your backend.

There could be some overloads for `setItems` which make it possible to provide the filter (and its type) to the query, but we thought that this would actually complicate things than help as you can just pass the filter directly. So you take the offset & limit from the query and the filter somewhere else.

(For in-memory data the API is different as things are easy https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java#L1152)

> In some situations a identifierGetter must be set but there is no way to pass a ValueProvider

Sorry, can you please elaborate a bit more what you mean by this ?

**Comment by simasch** [comment]
Let's make an example:

        dataProvider = new CallbackDataProvider<Dns, Dns>(
                query -> dnsService.findByExample(query.getFilter(), query.getSortOrders()).stream(),
                query -> dnsService.count(query.getFilter()),
                Dns::getId)
                .withConfigurableFilter();

        grid.setItems(dataProvider);

As Vaadin 18 no longer seems require a CountCallback I want to remove the CountCallback. But how?

1. I use a filter 
2. I use an identitfierGetter

If you need more information please let me know.
Thank you

**Comment by mshabarov** [comment]
Hi @simasch ,

Here is an example on how you can set the filter and identifier getter by using data view API:

```java
        Grid<Dns> grid = new Grid<>();

        // grid set-up code goes here
 
        TextField filterField = new TextField("Search Dns");
        filterField.addValueChangeListener(
                event -> {
                    // Reset the items as shown below:
                    grid.setItems(query ->
                        Dns filter = getDnsFilter(event.getValue());    
                        dnsService.findByExample(filter, query.getSortOrders()).stream();
                    );
                });



        // Or use text field value directly and refresh all, like this:
        filterField.addValueChangeListener(
                event -> grid.getLazyDataView().refreshAll());
        grid.setItems(query -> {
            Dns filter = getDnsFilter(filterField.getValue());
            return dnsService.findByExample(filter, query.getSortOrders()).stream();
        });
        
        // Set identifier getter via data view API:
        grid.getLazyDataView().setIdentifierProvider(dns -> dns.getFoo());
```

Hope this helps.

**Comment by simasch** [comment]
That helps! Thank you very much.

**Comment by pleku** [comment]
As there is a way to set the identifier provider and how to react to filtering change, closing the issue. 

https://github.com/vaadin/flow/issues/11246 has been opened for further improve the use case with filtering.
